### PR TITLE
Add option to prevent Play from creating bound caches

### LINKED ISSUE #5443: NamedEhCacheProvider doesn't allow explicitly configured cache attributes
https://www.playframework.com/documentation/2.4.x/ScalaCache states that additional caches can be configured by creating a custom ehcache.xml.  It also indicates that you should list these caches in play.cache.bindCaches and use the NamedCache qualifier to access these caches.  This doesn't appear to work as documented (tested with Play 2.4.6).

I've defined a custom ehcache.xml:

```
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ehcache.org/ehcache.xsd" updateCheck="false">

  <defaultCache
    maxEntriesLocalHeap="10000"
    eternal="false"
    timeToIdleSeconds="120"
    timeToLiveSeconds="120"
    overflowToDisk="false"
    maxElementsOnDisk="10000000"
    diskPersistent="false"
    diskExpiryThreadIntervalSeconds="120"
    memoryStoreEvictionPolicy="LRU" />

  <cache name="my-cache"
    maxEntriesLocalHeap="10000" />

</ehcache>
```

In application.conf, I've listed this cache:

```
play.cache.bindCaches = ["my-cache"]
```

And from my code I've wired the cache up:

```
class Test @Inject()(@NamedCache("my-cache") cache: CacheApi)
```

If I try to start the application with this configuration, it blows up:

```
Caused by: net.sf.ehcache.ObjectExistsException: Cache my-cache already exists
  at net.sf.ehcache.CacheManager.addCache(CacheManager.java:1171)
  at play.api.cache.NamedEhCacheProvider.get$lzycompute(Cache.scala:208)
```

If I remove the custom cache definitions from ehcache.xml, things work, but this means I cannot set custom attributes on individual caches.

At first glance it seems like the code should be changed to something more like this:

```
diff --git a/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala b/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala
index d55bb23..970a40a 100644
--- a/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala
+++ b/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala
@@ -205,8 +205,10 @@ class CacheManagerProvider @Inject() (env: Environment, config: Configuration, l
 private[play] class NamedEhCacheProvider(name: String) extends Provider[Ehcache] {
   @Inject private var manager: CacheManager = _
   lazy val get: Ehcache = {
-    manager.addCache(name)
-    manager.getEhcache(name)
+    Option(manager.getEhcache(name)).getOrElse {
+      manager.addCache(name)
+      manager.getEhcache(name)
+    }
   }
 }

```

### PR DESCRIPTION
**Pull request by gmethvin**
Fixes #5443 

This can be backported to 2.5.x and 2.4.x.

### CODE REVIEW

**Comment by gmethvin** [comment]
Note that I also have the same fix in #5923 but I decided this should be a separate PR so we can backport it.

**Comment by marcospereira** [comment]
Is it possible to have a test here? We can test exactly what was reported at #5443 and try to have an ehcache.xml defining cache regions and it should work when `createBoundCaches` is false.

**Comment by gmethvin** [comment]
@marcospereira Sure. It actually doesn't look like we have tests for the EhCacheApi right now at all.

For that test I could probably don't even need the ehcache.xml file. I can just manually create the caches using the `CacheManager` and try to bind them.

**Comment by gmethvin** [comment]
updated

**Pull request merged**
