### PR TITLE
Remove Java deprecations

### PR DESCRIPTION
**Pull request by marcospereira**
## Purpose

Remove Java APIs deprecations.

Later we can do another PR to remove Scala deprecated APIs. I'm not mixing them to avoid extreme large pull requests.

### CODE REVIEW

**Comment by mkurz** [comment]
@marcospereira You can also remove the `callLegacyValidateMethod` [here](https://github.com/playframework/playframework/blob/2.6.1/framework/src/play-java-forms/src/main/java/play/data/Form.java#L477-L499) and the code that uses it [here](https://github.com/playframework/playframework/blob/2.6.1/framework/src/play-java-forms/src/main/java/play/data/Form.java#L530-L541) (like I did in #7608).

**Comment by ekosutopo** [comment]
Bergabung untuk memperbaiki

**Comment by mkurz** [comment]
Care must be taken to not remove [`TypedKey.underlying()`](https://github.com/playframework/playframework/pull/8036/files#diff-07f44d2fa7dfcad9be538857e30e76e5R24) and [`TypedMap.underlying()`](https://github.com/playframework/playframework/pull/8036/files#diff-5c7e00c9d16d422a6cbce04919c948ceR35). Even though it says these methods are deprecated since `2.6.8` they shouldn't be removed in the Play 2.7 release yet because that deprecation warning were not backported to 2.6.x actually.

**Comment by mkurz** [comment]
@marcospereira Is there something still missing you want to include in this pull request?

**Comment by marcospereira** [comment]
@mkurz, nops. Rebased to solve conflicts and let's see if we get a green build. :-)

**Comment by mkurz** [comment]
@marcospereira there is a new conflict now :wink:

**Comment by marcospereira** [comment]
Thanks, @mkurz. I expect some other minor conflicts if we merge other breaking changes first. I've also adjusted to some other changes there were made since this PR was opened.

**Comment by mkurz** [comment]
@marcospereira Alright. I will review your pull request and if it's green I will just merge.

**Comment by mkurz** [comment]
@marcospereira Please see #8289 - it's similiar to this pr.

**Pull request merged**
