### PR TITLE
reorder splitWhen code due to pekko 1.1 test failures

### PR DESCRIPTION
**Pull request by pjfanning**
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

relates to #12662 and #12793 

#12793 did not fix the broken tests in #12662 

reordering the code fixes most of the broken tests (in my local testing and most recent 12793 build)

### CODE REVIEW

**Comment by gwak** [comment]
@pjfanning I tried your ordering and I can confirm its works for me as well!

**Comment by pjfanning** [comment]
there appears to be an issue with one of the sbt scripted tests:

**Comment by pjfanning** [comment]
Failed tests:
[error] 	play-sbt-plugin/dev-mode

**Comment by mkurz** [comment]
> there appears to be an issue with one of the sbt scripted tests:
> 
> Failed tests: [error] play-sbt-plugin/dev-mode

hmm.. usually these tests sbt tests are reliable, however I restarted to see if this was just a temporary problem.

**Comment by mkurz** [comment]
worked now.

**Comment by gwak** [comment]
Hey @mkurz, what's the timeline for a 3.0.5 release, because we're using pekko 1.1.0-M1 (using pekko-persistence-jdbc compatible with Scala 3) ?

**Comment by mkurz** [comment]
I just wait for the netty 4.1.112 release, which, based on previous releases, should happen in the next days: https://netty.io/news/

However, all the PRs regarding pekko the last days where merged into main, we would need to backport them to the 3.0.x branch, can you open a PR for that? Thanks!

**Comment by gwak** [comment]
https://github.com/playframework/playframework/pull/12796

**Comment by mkurz** [comment]
> Hey @mkurz, what's the timeline for a 3.0.5 release, because we're using pekko 1.1.0-M1 (using pekko-persistence-jdbc compatible with Scala 3) ?

@gwak Play 3.0.5 was just released, I hope if works for you :wink:

**Comment by gwak** [comment]
@mkurz Hey, we've updated to it today and it works just fine ! 

Thanks a lot to you, @pjfanning and the Pekko team!

**Pull request merged**
