### PR TITLE
Update netty-reactive-streams

### LINKED ISSUE #5835: [play-scala 2.5.0] ERR_CONTENT_LENGTH_MISMATCH error occurs  on Heroku when the response is greater than 85kb
The demo project source code is here [https://github.com/joymufeng/play250](https://github.com/joymufeng/play250). And the demo application on Heroku is:
```
http://play250.herokuapp.com/getResponse?len=99000 
```
You can change the len parameter to control the response length. If the response length is lower than 85kb, it works well, otherwise ERR_CONTENT_LENGTH_MISMATCH  error occurs in the browser.

### PR DESCRIPTION
**Pull request by jroper**
Fixes #5835

### CODE REVIEW

**Comment by jroper** [comment]
This is failing due to a legitimate bug - I'm not waiting for the last chunk to be sent before closing.

**Comment by marcospereira** [comment]
I believe this should be backported to 2.5.x, right?

**Comment by mkurz** [comment]
@marcospereira I think this should be backported.

**Comment by mkurz** [comment]
Backport PR: #5932

**Pull request merged**
