### PR TITLE
Small typo

### PR DESCRIPTION
**Pull request by ndeverge**
`your Scala actions to to be classes` -> `your Scala actions not to be classes`

### CODE REVIEW

**Comment by gmethvin** [comment]
Well, it should be `your Scala controllers to be classes` (as opposed to objects).

**Comment by ndeverge** [comment]
Ah yeah, sorry ! I added a patch on my patch.

Feel free to delete this PR and do the update yourself :-)

**Comment by cchantep** [comment]
Could you please squash the commits to a single one?

**Comment by ndeverge** [comment]
@cchantep squashed !

**Pull request merged**
