### PR TITLE
Fix the usage of Messages.get().

### PR DESCRIPTION
**Pull request by mshibanami**
See also #4886.

### CODE REVIEW

**Comment by gmethvin** [comment]
As mentioned in #4886, it'd be great if you could move this to a compiled code file so it can be automatically compiled and tested.

**Comment by mshibanami** [comment]
I'm sorry.
I really didn't understand what richdougherty said.
I'm so embarrassing...

I'll change this PR soon.

**Comment by marcospereira** [comment]
@mshibanami thank you very much for the PR. Could you please submit it to `master` branch instead? We can then backport it to branch `2.4.x` later.

Again, thank you.

**Comment by richdougherty** [comment]
Hi @mshibanami, I can see that you've changed your code so it can be compiled and tested. Thanks a lot! Sorry I didn't explain myself very well before. :)

When you move this change to the _master_ branch, could you also [squash the two commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) so there is just one commit? Thanks!

**Comment by mshibanami** [comment]
@marcospereira
I also didn't understand that. I'm sorry. I'll recreate the PR.


@richdougherty
>Sorry I didn't explain myself very well before. :)
No. It's my fault. I'm sorry...
>could you also squash the two commits so there is just one commit?
Sure. I didn't know that way well. Thank you for your advice!

**Pull request closed without merging**
