### PR TITLE
Flexible cookie handling for play.mvc.Http.Response #5015 implemented…

### PR DESCRIPTION
**Pull request by darioalessandro**
… builder pattern for Cookie using Cookie.Builder, and created Http.Response setCookie that takes a Cookie instance

1 commit :) thanks Marcos & James

### CODE REVIEW

**Comment by marcospereira** [comment]
@darioalessandro I think that something get lost when you open this new PR since `Http.Response.setCookie(Cookie cookie)` is missing.

Also, maybe we should deprecated those old `setCookie` methods in favor of using the builder. What do you think?

**Comment by darioalessandro** [comment]
I agree, since we have the builder, new dev should be using it.



2015-09-08 0:43 GMT-04:00 Marcos Pereira <notifications@github.com>:

**Comment by darioalessandro** [comment]
@marcospereira I added the @Deprecated statements and squashed the two, let me know if this would work.

**Comment by marcospereira** [comment]
@darioalessandro thank you so much for your time and patience.

**Comment by darioalessandro** [comment]
Thank you @marcospereira for your patience, next time I'll be more careful XD.

**Comment by kyouz** [comment]
Hi,
Look what I've just found for you, you'll be surprised, more info here <http://advantage.timothypike.com/e3vqeurb>

Hugs, amsdta_09@yahoo.com

**Pull request merged**
