### PR TITLE
Update header plugin and change year to 2018

### PR DESCRIPTION
**Pull request by raboof**
Rebased version of #8241

### CODE REVIEW

**Comment by marcospereira** [comment]
Thank you, @raboof.

Made two commits to fix the build (basically, add missing headers).

**Comment by mkurz** [comment]
So #8241 can be closeD?

**Comment by raboof** [comment]
Ah, I don't think I realized the build was not green yet ;) thanks for getting this over the finish line!

**Comment by richdougherty** [comment]
Do we really need to backport this? The number of files changed + the sbt plugin changes make this a little tricky to backport.

**Comment by richdougherty** [comment]
I'm wondering if we can skip backporting this. The number of files changed + the sbt plugin changes make this a little tricky to backport.

**Comment by richdougherty** [comment]
This PR could not be backported so I have created a 2.6.x version that we can use: #8435.

**Pull request merged**
