### PR TITLE
Remove global state from Assets

### PR DESCRIPTION
**Pull request by gmethvin**
Moves around a bunch of the assets stuff so everything is injected.

### CODE REVIEW

**Comment by gmethvin** [comment]
(The only exception currently is for the PathBindable)

**Comment by gmethvin** [comment]
I also pulled out all the `isDev` and `isProd` checks into separate settings.

**Comment by wsargent** [comment]
I see that there's an AssetsModule and an AssetsComponents -- do we need to add anything to BuiltInComponentsFromContext or to the documentation?

**Comment by gmethvin** [comment]
@wsargent Perhaps to the documentation. I'll check where we discuss assets there. It's not a big deal with runtime DI since the bindings should be set up automatically.

Since the `router` in `BuiltInComponentsFromContext` is still abstract, it doesn't need to worry about creating controllers. We could mix in `AssetsComponents` but it might not make sense for all apps, like ones that only provide an API and no static assets.

**Pull request merged**
