### PR TITLE
updated WebSocket Documentation page

### PR DESCRIPTION
**Pull request by akhilvijayan05**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Updated WebSocket page for both java and scala

## Purpose

To provide clear documentation to the readers.

## Background Context

For getting a good documentation

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @akhilvijayan05,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by akhilvijayan05** [comment]
I have signed in to CLA

**Comment by marcospereira** [comment]
Thank you, @akhilvijayan05.

**Comment by marcospereira** [comment]
Backport to 2.6.x here: 249f83ef1

**Pull request merged**
