### PR TITLE
sbt-plugin: Try to fix ~run when using sbt 1.3+

### PR DESCRIPTION
**Pull request by dwijnand**
Requires allowing playStop to run, despite playInteractionMode.

This still needs finessing, but after hours and hundreds of lines of
code, this is the closest I got to solving this.  It's almost there, but
I think there are still easy failure modes that need addressing.

### CODE REVIEW

**Comment by dwijnand** [comment]
* TODO: keep native file watching when running non-blocking?

**Comment by dwijnand** [comment]
Notes from presenting and asking questions at the sbt meeting, in addition to the finessing mentioned above:

1. `watchOnTermination` might be possible to be used so that ending `~run` stops the server
2. it would be good to use something other than `StaticPlayNonBlockingInteractionMode`
3. using keys like `watchOnTermination` can only go in a Play version that is sbt 1.3+ only (another alternative is those keys are ported back to 1.2.x and we can Play, for example, sbt 1.2.8+).

**Comment by dwijnand** [comment]
Parked for now.

**Comment by SoerenSilkjaer** [comment]
Is `~run` still buggy on sbt 1.3+? For me it is still not working.

**Comment by mkurz** [comment]
@SoerenSilkjaer Still not working, open issue here: #9983

**Pull request closed without merging**
