### PR TITLE
Remove deprecated FakeKeyStore

### PR DESCRIPTION
**Pull request by ignasi35**
Has been deprecated since 2.7.0 and was only meant to be used internally.

### CODE REVIEW

**Comment by raboof** [comment]
refs #10478

**Review by raboof — APPROVED** [review]

**Comment by ignasi35** [comment]
@raboof we had the `Dismiss stale pull request approvals when new commits are pushed` flag enabled so when I fixed Mima and scalafmt you approval was dismissed.

**Comment by ignasi35** [comment]
I think we should backport this to `2.8.x`. It improves support for JDK 15 and it _just_ removes deprecated code anyway.

**Comment by ignasi35** [comment]
@mergifyio backport 2.8.x

**Comment by SethTisue** [comment]
https://github.com/scala/community-build/pull/1289 :+1:

**Pull request merged**
