### PR TITLE
Update OpenID for 2.5

### PR DESCRIPTION
**Pull request by gmethvin**
Switch to `CompletionStage` and deprecate static methods in favor of `OpenIdClient`.

### CODE REVIEW

**Comment by wsargent** [comment]
Why no CI test running here?

**Comment by gmethvin** [comment]
Not sure. I tried pushing the branch again to see if CI would start.

**Comment by gmethvin** [comment]
@wsargent Okay I got it to show up by closing and reopening the PR...

**Comment by wsargent** [comment]
https://travis-ci.org/playframework/playframework/jobs/109691625#L2311

**Comment by gmethvin** [comment]
@wsargent looks like a spurious build failure. It's ok now.

**Pull request merged**
