### PR TITLE
fix typo (authorisation -> authorization)

### PR DESCRIPTION
**Pull request by hshiozawa**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes typo. (authorisation -> authorization)

### CODE REVIEW

**Comment by gmethvin** [comment]
This isn't a typographical error. Both spellings are correct depending on which dialect of English you're using. In Australia and New Zealand *-ise* and *-isation* are typically used, whereas in the US and Canada *-ize* and *-ization* are more common. As I understand it both forms are common in the UK.

I'm not opposed to changing the spellings, but we should do so across the documentation for consistency. You could search for the occurrences using a regular expression. Is that something you'd be interested in doing @hshiozawa? Also as usual we should make the change to master and backport it from there.

**Comment by hshiozawa** [comment]
Hi,

THank you for the reply.

I've searched the both spelling.

''authorization''
```
$ grep -ri "authorization" ./
.//manual/releases/release25/migration25/Migration25.md:There's a new config option to bypass the new CSRF protection for requests with certain headers. This config option is turned on by default for the Cookie and Authorization headers, so that REST clients, which typically don't use session authentication, will still work without having to send a CSRF token.
.//manual/tutorial/Tutorials.md:* [Play Multidomain Auth](https://github.com/adrianhurt/play-multidomain-auth) by Adrianhurt: this is a second part of play-multidomain-seed project. This project tries to be an example of how to implement an Authentication and Authorization layer using the Silhouette authentication library. It also uses [Play-Bootstrap](https://adrianhurt.github.io/play-bootstrap/) for easy template scaffolding.
.//manual/working/scalaGuide/main/forms/ScalaCsrf.md:* The request has one or more `Cookie` or `Authorization` headers.
.//manual/working/scalaGuide/main/application/ScalaHttpFilters.md:In contrast, [[action composition|ScalaActionsComposition]] is intended for route specific concerns, such as authentication and authorization, caching and so on.  If your filter is not one that you want applied to every route, consider using action composition instead, it is far more powerful.  And don't forget that you can create your own action builders that compose your own custom defined sets of actions to each route, to minimise boilerplate.
.//manual/working/scalaGuide/main/ws/ScalaOpenID.md:3. The user confirms the authorization on his OpenID provider, and gets redirected back to your server.
.//manual/working/javaGuide/main/forms/JavaCsrf.md:* The request has one or more `Cookie` or `Authorization` headers.
.//manual/working/javaGuide/main/ws/JavaOpenID.md:3. The user confirms the authorization on his OpenID provider, and gets redirected back to your server.
.//manual/ModuleDirectory.md:## Authentication (Login & Registration) and Authorization (Restricted Access)
.//manual/ModuleDirectory.md:### Authentication and Authorization module (Scala)
.//manual/ModuleDirectory.md:* **Short description** This module provides an authentication and authorization way
```

''authorisation''
```
$ grep -ri "authorisation" ./
.//manual/working/javaGuide/main/application/JavaHttpFilters.md:In contrast, [[action composition|JavaActionsComposition]] is intended for route specific concerns, such as authentication and authorisation, caching and so on.  If your filter is not one that you want applied to every route, consider using action composition instead, it is far more powerful.  And don't forget that you can create your own action builders that compose your own custom defined sets of actions to each route, to minimise boilerplate.
.//manual/ModuleDirectory.md:* **Short description:** Deadbolt is an authorisation mechanism for defining access rights to certain controller methods or parts of a view using a simple AND/OR/NOT syntax
```

So I will change the spelling 'authorisation' to 'authorization'.

**Comment by gmethvin** [comment]
I would suggest searching for all words ending in *-ise* or *-isation* and changing the spellings.

**Comment by hshiozawa** [comment]
I've searched all words and fixed them.

Could you review #8818?

**Pull request closed without merging**
