### PR TITLE
Updated to latest sbt-rc (0.3.1) and sbt-core-next (0.1.1)

### PR DESCRIPTION
**Pull request by corruptmemory**
Replaces #3914

### CODE REVIEW

**Comment by pvlugter** [comment]
@corruptmemory, can you clean up the commits? Squash the version bumps. Remove the merge commit. Thanks.

**Comment by pvlugter** [comment]
Or let me know and I can do it.

**Comment by corruptmemory** [comment]
Sure

**Comment by corruptmemory** [comment]
Better?

**Comment by pvlugter** [comment]
Yep, completely squashed is good too. Thanks.

**Pull request merged**
