### PR TITLE
Update ScalaTestingWithScalaTest.md

### PR DESCRIPTION
**Pull request by massimo32**
Removed import of scalatest, in accordance with the text.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @massimo32,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by marcospereira** [comment]
@massimo32 could please sign the Typesafe Contributors License Agreement:

http://www.typesafe.com/contribute/cla

We can merge this PR after that. :+1:

**Comment by marcospereira** [comment]
@massimo32 just passing to let you know we will be ready to merge this PR when you sign the Typesafe Contributors License Agreement:

http://www.typesafe.com/contribute/cla

Thanks.

**Comment by massimo32** [comment]
Hi @marcospereira,
I just wanted to signal a problem, I'm not interested in signing.

Thanks.

**Pull request closed without merging**
