### PR TITLE
Documentation for ws streaming request/response body for both Scala and Java

### PR DESCRIPTION
**Pull request by dotta**
* Added `sendEntity` to the Java Results API
* Improvements in Scala WS documentation
* Documentation for streaming request's bodies for Scala/Java
* Java documentation for streaming response bodies

### CODE REVIEW

**Comment by dotta** [comment]
I believe it's a spurious failure, closing and re-opening PR to trigger another build.

**Comment by dotta** [comment]
and re-trying again...

**Comment by jroper** [comment]
@dotta, I think you should have permission to restart builds, and individual sub jobs of builds, from the Travis UI, using the restart button on the far right:

job__281_1_-_playframework_playframework_-_travis_ci

**Comment by dotta** [comment]
@jroper Oh, good to know. I've rebased this PR and the commits history is now clean.

**Pull request merged**
