### PR TITLE
Upgrade to Akka 2.4.1

### PR DESCRIPTION
**Pull request by wsargent**
Addresses #5378, #3795, https://github.com/playframework/playframework/issues/5120

### CODE REVIEW

**Comment by benmccann** [comment]
@wsargent it seems like the suggestions in https://github.com/playframework/playframework/issues/3795 should also be part of this PR?

I.e. from [the akka docs](http://doc.akka.io/docs/akka/snapshot/java/logging.html), we should also add: 

    akka {
      loggers = ["akka.event.slf4j.Slf4jLogger"]
      loglevel = "DEBUG"
      logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
    }

**Comment by wsargent** [comment]
@benmccann I see some of #3795 in master already:


```
  # Tell akka to use Slf4jLogger and filter
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
```

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/resources/play/reference-overrides.conf#L39

Is it just setting the loglevel to DEBUG then?

**Comment by benmccann** [comment]
Looks like it. I don't know much about this. @richdougherty seems like the better person to ask here

**Comment by hepin1989** [comment]
I have to refs https://github.com/playframework/playframework/issues/5120 :)

**Comment by richdougherty** [comment]
Yeah, I think you just need to set debug.

**Comment by wsargent** [comment]
Okay, done.

**Comment by richdougherty** [comment]
LGTM

**Comment by richdougherty** [comment]
Not sure about that build failure, retrying.
```
[error] (SBT-Fork-Run-Plugin/*:scripted) Failed tests:
[error] 	fork-run / dev-mode
[error] Total time: 1499 s, completed Dec 14, 2015 10:06:04 PM
The command "framework/bin/$SCRIPT "set concurrentRestrictions in Global += Tags.limitAll(1)"" exited with 1.
```

**Pull request merged**
