### PR TITLE
Remove workaround for bug fixed in https://github.com/sbt/sbt/pull/1450

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by richdougherty** [comment]
@play-pull-request-validator, there were bind failures, please try again.

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by richdougherty** [comment]
Bind failures. Let's wait until #3783 is merged before running CI again.

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Pull request merged**
