### PR TITLE
added jaxb-api so that jdk 9+ classpath works without configuration

### PR DESCRIPTION
**Pull request by schmitch**
currently this adds the jaxb-api jar (122kb) so that play will work without any flag under jdk 9+.
An alternative would be to either fork jjwt and fix the outstanding issue or use a different JWT implementation.
We could also wait for a fix directly in jjwt however I guess it's fine to add jaxb-api.jar for known since it is only 122kb and than we could run play under jdk 9+ without any flags/problems.

After we merge that Play will still print:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

However this is probably not easy to fix, but can be ignored until we add support for JPMS (which can't work without the help of the Scala Compiler anyway).

(We could also add tests for JDK 10 if scala [2.12.6](https://github.com/scala/scala-dev/issues/480) hits

### CODE REVIEW

**Comment by schmitch** [comment]
wierd mima issue:
```
java.lang.RuntimeException: bad constant pool tag 19 at byte 54
	at com.typesafe.tools.mima.core.ClassfileParser$ConstantPool.errorBadTag(ClassfileParser.scala:192)
```

**Comment by schmitch** [comment]
Blocked by https://github.com/lightbend/migration-manager/issues/206

**Comment by schmitch** [comment]
and in production it would not be possible.
I guess using a 122kb jar is good enough. in the future it can probably also be removed, but play is already really big, so adding 122kb is not a big deal.

or we fork jjwt under the playframework banner and remove jaxb from that library (the library does not need jaxb since it only uses the Base64 decoder which exists under Java8+ (java.base module) anyway)

**Comment by wsargent** [comment]
We don't need to use jjwt at all -- it's not exposed as a public API.  We use JWT but we could easily switch to a different library.

**Comment by schmitch** [comment]
Actually jjwt has PRs for the matter: 
* https://github.com/jwtk/jjwt/pull/318
* https://github.com/jwtk/jjwt/pull/283

**Comment by schmitch** [comment]
updates mima, so this can be looked at (merge ready)

**Comment by schmitch** [comment]
I merged it, it's easy to revert and I also added a follow up issue on #8446 to discuss what we could do.

**Comment by marcospereira** [comment]
@schmitch I think we should probably backport this to 2.6.x. See https://github.com/playframework/play-scala-starter-example/pull/86.

**Comment by schmitch** [comment]
yeah I guess we could, I mean it just adds a dependency, which should not break any builds.

**Comment by schmitch** [comment]
Backport is here: #8451

**Comment by PromanSEW** [comment]
https://github.com/jwtk/jjwt/pull/341

**Pull request merged**
