### PR TITLE
fix for UnEncoded key on key-value serialisation #9403.

### LINKED ISSUE #9403: UnEncoded key on key-value serialisation
Searching for `URLEncoder.encode` we find a few places converting `Map[String,String]` into `key1=val1&key2=val2` for queryString representation of body as forlUrlEncoded.

Some of these serialisers fail to use `URLEncoder.encode` for the key. E.g. https://github.com/playframework/playframework/blob/282cb7905f3b4a1b4dc97b2fbc8e8eca9224158b/core/play/src/main/scala/play/api/http/Writeable.scala#L99

Related: https://github.com/playframework/playframework/pull/9389 and https://github.com/playframework/playframework/pull/9401

### PR DESCRIPTION
**Pull request by brbrown25**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #9403

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by brbrown25** [comment]
@ignasi35 I ran compile and test with no errors. would you like me to add some unit tests showing that this is fixed in all of these classes?

**Comment by brbrown25** [comment]
- [ ] fix build errors

**Comment by brbrown25** [comment]
@ignasi35 is there anything you'd like me to tweak on this?

**Comment by gmethvin** [comment]
@ignasi35 assuming we want a backport for this to 2.7 and possibly 2.6?

**Pull request merged**
