### PR TITLE
disable flaky `play-sbt-plugin/shutdown-downing` test

### PR DESCRIPTION
**Pull request by xuwei-k**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

### CODE REVIEW

**Comment by octonato** [comment]
Ok to disable, but maybe better to have an issue first if more information about it. 

If we disable like that, we will be forever gone. We need an issue to track it and remind us that we need to bring it back. 
Of course, we can also decide that this test doesn't add enough value and in that case we can also remove it. 

Also good to add some stacktrace to the issue to help us understand where it is failing.

**Comment by BillyAutrey** [comment]
I've seen it fail most often in Java 8.  Might be worth looking through the PR GHAs, to see which versions are failing and which are not.  Might be as easy as a timeout bump, too.

**Comment by BillyAutrey** [comment]
Looks like the failure in question is a connection refusal after 30 tries, in an attempt to make the "downing" call:

```
[info] Attempt 1 at /simulate-downing
[info] Got exception: java.net.ConnectException: Connection refused (Connection refused). Cause was null
[info] Attempt 2 at /simulate-downing
[info] Got exception: java.net.ConnectException: Connection refused (Connection refused). Cause was null
[info] Attempt 3 at /simulate-downing
[info] Got exception: java.net.ConnectException: Connection refused (Connection refused). Cause was null
[info] Attempt 4 at /simulate-downing
[info] Got exception: java.net.ConnectException: Connection refused (Connection refused). Cause was null
[info] Attempt 5 at /simulate-downing
[info] Got exception: java.net.ConnectException: Connection refused (Connection refused). Cause was null
[info] Attempt 6 at /simulate-downing
[info] Got exception: java.net.ConnectException: Connection refused (Connection refused). Cause was null
```

**Comment by mkurz** [comment]
I prefer to fix the test instead of just disabling it. Even if it's just increasing the timeout...

**Comment by mkurz** [comment]
Let's see if increasing the timout works: #11361

**Comment by mkurz** [comment]
Hopefully fixed now.

**Pull request closed without merging**
