### PR TITLE
add play conditional form mapping tutorial

### PR DESCRIPTION
**Pull request by NTCoding**
# Pull Request Checklist

* Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* Have you added copyright headers to new files?
* Have you checked that both Scala and Java APIs are updated?
* Have you updated the documentation?
* Have you added tests?

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by gmethvin** [comment]
@NTCoding It looks like you put this at the bottom with the 2.2.x tutorials. Do you know which version of Play this was intended for? We should put it in the section for the latest version this applies to.

**Comment by NTCoding** [comment]
Im sorry for the mistake. it should work with 2.3.

**Comment by NTCoding** [comment]
PR updated

**Comment by gmethvin** [comment]
Great. Can you squash your commits?

**Comment by NTCoding** [comment]
Yes. My apologies for not doing that in the first place and repeatedly wasting your time.

**Comment by gmethvin** [comment]
No problem. Thanks.

**Pull request merged**
