### PR TITLE
re #4282, add a direct download link

### PR DESCRIPTION
**Pull request by lazaridis-com**
please see #4282 for further simplification steps

### CODE REVIEW

**Comment by marcospereira** [comment]
As discussed there, @jroper suggest that we use the following url instead:

https://playframework.com/download 

Could you please update this PR to use it?

**Comment by lazaridis-com** [comment]
No, because the suggestion was logically wrong.

**Comment by lazaridis-com** [comment]
(INSTALL.md is an autonomous doc, and should not relay to another doc)

**Comment by nafg** [comment]
On Fri, Apr 24, 2015, 9:36 AM Lazaridis <notifications@github.com> wrote:

No, because the suggestion was logically wrong.

 Can you prove that with the scala type system?

You seem to believe that whatever seems right to you is an indisputable
objective truth.


 --
Reply to this email directly or view it on GitHub
<https://github.com/playframework/playframework/pull/4286#issuecomment-95934246>.

**Comment by cchantep** [comment]
For the same reason as init #4282, this ticket is now closed and locked.

**Pull request closed without merging**
