### PR TITLE
Consistency update for JavaFileUpload.md

### PR DESCRIPTION
**Pull request by thiagoarrais**
This makes the first example in [JavaFileUpload.md](https://www.playframework.com/documentation/2.6.x/JavaFileUpload) consistent with the second one (the test) regarding the usage of MultipartFormData.

I've also been trying to follow these docs to learn Play. At some point somewhere, I've come to start using this for my controller boilerplate:

    package controllers;

    import play.mvc.*;

    import views.html.*;

    public class MyController extends Controller {

        public Result myAction() {
            return ok("change me");
        }

    }

(I think this comes from `play-java-starter-example`, but I'm not really sure)

By using Http explicitly (in `Http.MultipartFormData<File> body`), I am able to continue using this boilerplate combined with a simple text editor. I don't need to resort to some fancy IDE or anything.

### CODE REVIEW

**Comment by mkurz** [comment]
@thiagoarrais Travis complains: https://travis-ci.org/playframework/playframework/jobs/272140626#L2924
If you could fix this that would be great, thanks!

**Comment by mkurz** [comment]
Oh, I just saw this pull request was made against the`2.6.x` branch.

@thiagoarrais could you please rebase this against the `master` branch, thanks?

**Comment by thiagoarrais** [comment]
Will do it, but can't do it right now.

Sorry. I've used the link in the website and just didn't think about the
branch Github was sending the pr to.

**Comment by gmethvin** [comment]
@thiagoarrais: @mkurz is right but I will just merge this and cherry-pick to master since it's only a small documentation change.

**Comment by thiagoarrais** [comment]
Sorry for the inconvenience, folks. I will try to remember filing my future PRs against master.

**Pull request merged**
