### PR TITLE
Scripted tests use snapshot repositories on cron jobs

### LINKED ISSUE #9713: [master/2.7.x] CRON builds fail on scripted tests
For about 3 weeks now, the `CRON` builds for the `2.7.x` branch fail the `scripted` tests jobs (both `0.13` and `1.x`).

The failure is caused by a [failure to resolve](https://travis-ci.com/playframework/playframework/jobs/237766102#L1575) Akka (and Akka-HTTP) snapshots from the builds on the `scripted` tests.

~This doesn't seem to happen in either `master` not `2.6.x` `CRON` builds.~

**UDPDATE**: This also happens in `master` (see [this build](https://travis-ci.com/playframework/playframework/jobs/239682764#L4323)) but it is often masked by jobs failing in earlier stages of the build.

### PR DESCRIPTION
**Pull request by ignasi35**
Fixes #9713

### CODE REVIEW

**Comment by ignasi35** [comment]
Hmmm, so mergify removed the label `needs-backport` but didn't create the backport PR.

**Comment by ignasi35** [comment]
Anyway, this worked on jobs for `scripted` tests run on `sbt 1.x` but fails when running on `sbt 0.13`:

```
...
[info] Getting Scala 2.10.7 (for sbt)...

[info] downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ...

[info] 	[SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar (58ms)

[info] :: retrieving :: org.scala-sbt#boot-scala

[info] 	confs: [default]

[info] 	5 artifacts copied, 0 already retrieved (24560kB/47ms)

[info] Error during sbt execution: java.lang.NoClassDefFoundError: sbt/AttributeMap$

[error] java.lang.NoClassDefFoundError: sbt/AttributeMap$

[error] 	at sbt.Command$.make(Command.scala:34)

[error] 	at sbt.Command$.command(Command.scala:30)

[error] 	at sbt.BuiltinCommands$.defaults(Main.scala:223)

[error] 	at sbt.xMain.run(Main.scala:33)

[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)

[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)

[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)

[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)

[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)

[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)

[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)

[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)

[error] 	at xsbt.boot.Boot.main(Boot.scala)

[error] Caused by: java.lang.ClassNotFoundException: sbt.AttributeMap$

[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[error] 	... 13 more

[error] x play-sbt-plugin / akka-fork-join-pool

[error]    {line 1}  Command failed: Remote sbt initialization failed

Running play-sbt-plugin / basic-service

[error] java.lang.NoClassDefFoundError: sbt/AttributeMap$

[error] 	at sbt.Command$.make(Command.scala:34)

[error] 	at sbt.Command$.command(Command.scala:30)

[error] 	at sbt.BuiltinCommands$.defaults(Main.scala:223)

[error] 	at sbt.xMain.run(Main.scala:33)

[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)

[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)

[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)

[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)

[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)

[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)

[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)

[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)

[error] 	at xsbt.boot.Boot.main(Boot.scala)

[error] Caused by: java.lang.ClassNotFoundException: sbt.AttributeMap$

[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[error] 	... 13 more

[info] Error during sbt execution: java.lang.NoClassDefFoundError: sbt/AttributeMap$

[error] x play-sbt-plugin / basic-service

[error]    {line 2}  Command failed: Remote sbt initialization failed

Running play-sbt-plugin / basic-service-with-routes-file

[error] java.lang.NoClassDefFoundError: sbt/AttributeMap$

[error] 	at sbt.Command$.make(Command.scala:34)

[error] 	at sbt.Command$.command(Command.scala:30)

[error] 	at sbt.BuiltinCommands$.defaults(Main.scala:223)

[error] 	at sbt.xMain.run(Main.scala:33)

[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)

[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)

[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)

[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
...
```

**Comment by ignasi35** [comment]
https://travis-ci.com/playframework/playframework/jobs/244428341#L322

**Comment by ignasi35** [comment]
`CRON` `master` is [looking good](https://travis-ci.com/playframework/playframework/builds/131727074).

The errors commented above seem to be temporary issues in travis.

**Comment by ignasi35** [comment]
This doesn't backport cleanly because there's no `sbt-scripted-tools` in `2.7.x`.

**Comment by dwijnand** [comment]
Manually backported in #9821.

**Pull request merged**
