### PR TITLE
Docs: change "an error" to "a message"

### PR DESCRIPTION
**Pull request by thiagoarrais**
This is just a minor update to the docs.

I found it weird to display "an error" after a successful save.

### CODE REVIEW

**Comment by schmitch** [comment]
Could you please rebase your PR against `master`? We normally only backport changes onto the 2.5.x branch.

**Comment by thiagoarrais** [comment]
CLA signed!

**Comment by thiagoarrais** [comment]
Oh, sorry, @schmitch. I didn't notice I was sending the PR to the branch. I simply clicked the link to the source code [on the live page][1] and edited.

 [1]: https://www.playframework.com/documentation/2.5.x/JavaSessionFlash

**Comment by thiagoarrais** [comment]
@schmitch: rebasing is done.

**Comment by mkurz** [comment]
2.5.x: ef0539a9860f96a00516465ead39073157326850

**Pull request merged**
