### PR TITLE
Ensure Java Global.onRequest gets invoked

### LINKED ISSUE #4462: [2.4.0-RC3] Bug: Global.onRequest(request, actionMethod) not called anymore
For a quick a test:
```java
public class Global extends GlobalSettings {

    @Override
    public Action onRequest(Request request, Method actionMethod) {
        System.out.println("Global.onRequest"); // Does not get called 
        return new Action.Simple() {
            public F.Promise<Result> call(Context ctx) throws Throwable {
                return delegate.call(ctx);
            }
        };
    }
}
```
It seems the `onRequest` never gets called (It does not matter if you use `InjectedRoutesGenerator` or not).

### PR DESCRIPTION
**Pull request by jroper**
Fixes #4462

### CODE REVIEW

**Comment by richdougherty** [comment]
LGTM

**Comment by jroper** [comment]
Question is whether this warrants an RC4 or not.

**Comment by richdougherty** [comment]
I'd say that a few people will run into this one. Maybe let's see how many other bugs we get for RC3.

**Comment by jroper** [comment]
Oh it definitely needs to be in 2.4.0, the question is whether this change is risky enough to warrant another RC when we merge it.

**Comment by richdougherty** [comment]
OK, I see. Hmmm.

**Pull request merged**
