### PR TITLE
Revert "Updated dependencies" (conflicts found)

### PR DESCRIPTION
**Pull request by wsargent**
Reverts playframework/playframework#6376

### CODE REVIEW

**Comment by marcospereira** [comment]
Which conflicts? I'm asking mainly because the build is green for #6376.

**Comment by wsargent** [comment]
If you look at https://github.com/playframework/playframework/commit/a91fdc4c4f0b4b8eec34b4961532c48d77c2cab6

then there's a message saying 

```
Conflicts:

	framework/project/Dependencies.scala
```

**Comment by wsargent** [comment]
It looks like it might be a false positive -- the master build failed from a ConnectException

https://travis-ci.org/playframework/playframework/jobs/149543623#L1171

So we may be good...

**Comment by mkurz** [comment]
The commit message ("Conflicts...") is wrong. I actually cherry-picked #6375 into master on my machine and yes, there were some conflicts. But I resolved them. Looks like I didn't clean up the commit message.
The PR should be good.

**Comment by mkurz** [comment]
I think we can close this revert-PR

**Pull request closed without merging**
