### PR TITLE
New versions

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by mkurz** [comment]
@dwijnand To make Travis like this pull request you need to remove this line:
https://github.com/playframework/playframework/blob/39efe18ff4e3e31c53e0535f6d6281ac4c89d360/project/BuildSettings.scala#L93
because interplay dropped support for Scala 2.11: https://github.com/playframework/interplay/pull/58

**Comment by mkurz** [comment]
:cry: 
```
sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-stream_2.13.0-RC1;2.6.0-M1: not found
```

**Comment by dwijnand** [comment]
I'm confused about how my PR caused that.

**Comment by dwijnand** [comment]
Oh, it's the interplay update: it updates from M5 to RC1.

**Pull request merged**
