### PR TITLE
Split cron build extra opts

### PR DESCRIPTION
**Pull request by renatocaval**
Strange enough, sbt wasn't reading the second -D option, but it was using the whole string "2.5-20190325-231121 -Dakka.http.version=10.1.7" as the akka version.
I guess this was broken since day one.

### CODE REVIEW

**Comment by dwijnand** [comment]
No I broke it by mistake in https://github.com/playframework/playframework/pull/9023/commits/c3b34e704fc4302650563f9ed023e01e78d60133#diff-bfba0e56309921d498e9f567d7475fdbR36

The way to safely do an array of strings is:

```bash
declare -a EXTRA_OPTS

EXTRA_OPTS+=("-Dakka.version=${AKKA_VERSION}")
EXTRA_OPTS+=("-Dakka.http.version=${AKKA_HTTP_VERSION}")

sbt "${EXTRA_OPTS[@]}"
```

**Comment by marcospereira** [comment]
@dwijnand so should we instead just revert the change you made before (+ using /snapshots/ instead of /maven/)?

**Comment by marcospereira** [comment]
> ```shell
> sbt "${EXTRA_OPTS[@]}"
> ```

Another point, do we need the double quotes here? I have the impression they were the culprit of this problem (making everything look like a single parameter).

**Comment by dwijnand** [comment]
The `@` in there makes the array expand correctly, which each variable being double quoted, so spaces are preserved as intended.  It's how bash variable expansion works.

**Comment by renatocaval** [comment]
This is already merged without using `${EXTRA_OPTS[@]}`. 
The reason why I didn't choose that path is to have things more explicitly.

**Comment by renatocaval** [comment]
Backported to 2.7.x (c2f292dd6ebf3febd0ddb0b7917192902b6317ec)

**Pull request merged**
