### PR TITLE
Allow backticks quoted parameters in routes

### LINKED ISSUE #4693: Allow backticks quoted parameters in routes
Was trying this in my routes:
```
GET    /search        controllers.PeopleController.list(`tags[]`: Seq[String] ?= Seq.empty)
```

I'm getting a routes compilation error on the next line `Compilation error[Identifier expected]`
The controller itself has no issue with a `tags[]` argument

By default it seems that jQuery puts array parameters as `?tags[]=foo&tags[]=bar` but I can't get this to work properly in the routes file.
On the jQuery side this can be configured using the `traditional` setting but I have no control over the client.
http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings
http://api.jquery.com/jQuery.param/

My current workaround looks like this:
```scala
def list(tags:Seq[String]) = Action.async{ implicit request =>
  // since we can not define this in the routes file
  // https://github.com/playframework/playframework/issues/4693
  val arrayTags = request.queryString.get("tags[]")
  val actualTags = arrayTags.getOrElse(tags)
  // continuing with this actualTags
  ...
```

### PR DESCRIPTION
**Pull request by mtrovo**
fix #4693

Parameter identifiers are being checked against Java identifiers policy,
this adds support for valid backticked Scala identifiers.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @mtrovo,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by jroper** [comment]
I think it's also important to test this in a scripted test - to ensure that the code we're generating compiles, and to ensure that we're correctly extracting properties out.  Another important thing to check is that the JavaScript reverse router correctly runs.  The place to add tests is here:

https://github.com/playframework/playframework/tree/master/framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation

And here's the JavaScript router tests:

https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/assets/JavaScriptRouterSpec.js

That router is generated here:

https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/utils/JavaScriptRouterGenerator.scala

**Comment by mtrovo** [comment]
I made some needed changes on the forward and on the reverse router but I'm not sure how this should be accomplished on the javascript router.

Below is the block of code being generated right now, any Ideas on how could we change the function argument name to valid javascript on this context without hitting some name collision issues?

```
// route
GET    /foo     controllers.FooController.foo(`bar[]`: List[String])
```
``` scala
    // @LINE:1
    def foo: JavaScriptReverseRoute = JavaScriptReverseRoute(
      "controllers.FooController.foo",
      """
        function(`bar[]`) {
          return _wA({method:"GET", url:"""" + _prefix + { _defaultPrefix } + """" + "foo" + _qS([(""" + implicitly[QueryStringBindable[List[String]]].javascriptUnbind + """)("`bar[]`", `bar[]`)])})
        }
      """
    )
```

**Comment by jroper** [comment]
Something along the lines of this to generate unique safe parameter names for the JavaScript (of course it will be more complex since there's a number of places where you need to refer to the name):

```scala
params.zipWithIndex.map {
  case (param, idx) => param.replaceAll("[^a-zA-Z0-9]", "_") + idx
}
```

**Comment by mtrovo** [comment]
This is weird, this play-sbt-plugin / distribution is failing sporadically also on my machine but it seems to not be related to this PR as the master branch also fails on this task some times.

It seems some of the `testProd` tasks return without really binding to the :9000 port on the `distrubution/test` file.

**Comment by jroper** [comment]
Hmm... it doesn't affect us very often, but I did find one build several days ago that had the same failure.

**Comment by jroper** [comment]
I've restarted the sbt plugins build.  Once it passes, we can merge, thanks for implementing this!

**Comment by francisdb** [comment]
thanks @mtrovo

**Comment by mkurz** [comment]
@mtrovo @jroper @francisdb
This pull request introduces a bug!

Using Play 2.5.0-M1 following javascript reverse route functions will now be generated:
```javascript
_nS('controllers.Application'); _root['controllers']['Application']['scalaIntRoute'] = 
        function(id0) {
        
          if (id == 12345) {
            return _wA({method:"GET", url:"/" + "IntValue"})
          }
        
          if (true) {
            return _wA({method:"GET", url:"/" + "Int/" + (function(k,v) {return v})("id", id0)})
          }
        
        }
      ;
````
As you can see `id0` is passed to the function but then only `id` (without the trailing zero) is used as variable which obviously does not exist (Chrome throws a exception like "undefined variable").

@mtrovo Can you fix this please?

**Comment by mkurz** [comment]
You can reproduce the bug with [this simple project](https://github.com/mkurz/playRoutesTest). Just run it via `activator run` and have a look at `/assets/routes.js` in your browser.

**Pull request merged**
