### PR TITLE
Add withThreshold to GzipFilterConfig

### PR DESCRIPTION
**Pull request by slisaasquatch**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes https://github.com/playframework/playframework/issues/10040

## Purpose
Adds `withThreshold` to `GzipFilterConfig` to make it accessible in Java.

## Background Context
N/A

## References
N/A

### CODE REVIEW

**Comment by mkurz** [comment]
Thanks! Can you also add `withCompressionLevel`? It's the only method missing now. Thanks!

**Comment by mkurz** [comment]
Can you do one more thing? Rebase your branch against the 2.8.x branch and then change the pull request base to 2.8.x as well so this will be merged into 2.8.x.

**Comment by slisaasquatch** [comment]
I kind of messed up in the rebase process. I'll create a new pull request.

**Comment by mkurz** [comment]
Just open it against the 2.8.x branch.

**Pull request closed without merging**
