### PR TITLE
sbt-java-formatter 0.8.0

### PR DESCRIPTION
**Pull request by mkurz**
Now sorts imports: https://github.com/sbt/sbt-java-formatter/releases/tag/v0.8.0

### CODE REVIEW

**Comment by ihostage** [comment]
Ah, great! 👍 
I'll be very happy if we have the same for Scala sources 🤞  
Because frequently new contributors format code and reorder imports by their IDE settings. This clutter up the git history and uselessly increases the size of pull requests 🤪 

Maybe also needs to write manual about IDE settings of sorting imports in our unified (thank you Matthias 🫶) **CONTRIBUTING** guide 🤔

**Comment by mkurz** [comment]
I think we should just add a `formatCode` task to all repos like we have for `validateCode` already and put that in the contributor guidlines: https://github.com/playframework/playframework/issues/11467

**Comment by ihostage** [comment]
The problem is `scalafmt` can't sort imports 🤷‍♂️ We'll need something another tools for that.

**Comment by felipebonezi** [comment]
> The problem is `scalafmt` can't sort imports 🤷‍♂️ We'll need something another tools for that.

We could use `Scalafix` to do it.
https://github.com/scalacenter/scalafix

**Comment by adrianlyjak** [comment]
scalafmt can sort imports 
https://scalameta.org/scalafmt/docs/configuration.html#imports

**Comment by mkurz** [comment]
However has time feel free to provide a pull request with the scalafmt rule.

**Pull request merged**
