### PR TITLE
sbt 0.13.18

### PR DESCRIPTION
**Pull request by sullis**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

latest version of SBT

## Purpose

latest version of SBT

## Background Context

latest version of SBT

## References

latest version of SBT

### CODE REVIEW

**Comment by mkurz** [comment]
@marcospereira Backport needed.

**Comment by dwijnand** [comment]
Why?

**Comment by mkurz** [comment]
For the 2.7 branch? Why not?

**Comment by marcospereira** [comment]
Backported in #8871.

**Pull request merged**
