### PR TITLE
separated Configuration class from core as a sbt sub-project

### LINKED ISSUE #9745: Feature request: split Configuration into standalone library
Play's `Configuration` class (scala) is a nice wrapper around typesafe config. Would it be possible to split it out into a standalone library so that scala projects that don't need all of Play can use it? Similar to how play-json was split out into a separate library.

### PR DESCRIPTION
**Pull request by gurkankaymak**
closes #9745 

also created the `Play-Utils` sub project for the dependencies of Configuration class

### CODE REVIEW

**Comment by renatocaval** [comment]
Thanks @gurkankaymak. 

We are right now cutting many releases. We will come back to this as soon we ship all the planned releases.

**Comment by tarmath** [comment]
could this perhaps be resurrected?

**Comment by aaabramov** [comment]
Hi @gurkankaymak! Do you plan to actualize this PR? I've been waiting to see Confifuration wrapper for years!

**Comment by gurkankaymak** [comment]
Hi @aaabramov

It's not up to me, I submitted this pr almost a year ago and It hasn't been reviewed, there is no point for me to spend time to update it with master, if they are not interested in merging it.

**Comment by octonato** [comment]
@gurkankaymak, my excuses for that. Unfortunately, what happened in this case is not uncommon. We receive more than 200 GitHub notifications per day coming from the many OSS we manage. And it happens that things get lost between the many messages we have to deal with.

The fact that this PR didn't get proper review is not due to lack of interest in merging it. It's because it fall through the cracks. 

I understand the frustration when contributing something that doesn't get enough attention from the maintainers. On the other hand, this is also an indication of the community interest around the issue. Nobody in the community seemed to have found the motivation to move it forward and as a result we lose it from sight.

If someone wants to move this forward, I suggest to either fix the merge conflicts on this PR or to open a new one based on the work already done here. If picked by another contributor, that person must ensure that @gurkankaymak's work is not lost and the authorship is preserved.

**Comment by gurkankaymak** [comment]
@octonato thanks for the reply, then I can resolve the conflicts to move the pr forward, probably I will have time in the weekend, until then if anyone wants to take over, feel free to do so.

**Comment by octonato** [comment]
@gurkankaymak, thanks for your understanding. 

When ready, don't hesitate to ping the maintainers directly to draw attention to this PR. And if nothing happens after a while, insist. 😉

**Comment by tmccombs** [comment]
@gurkankaymak are you still working on this? Or should I make a new PR that resolves the conflicts?

**Comment by gurkankaymak** [comment]
@tmccombs actually I forgot about this and currently have no time to work on this, feel free to do what suits best to you to move the work forward

**Comment by tmccombs** [comment]
ok, thanks. I went ahead and created a new pull request (#11573)

**Comment by mkurz** [comment]
Outdated, see #11573

**Pull request closed without merging**
