### PR TITLE
configure logback with custom application loader

### PR DESCRIPTION
**Pull request by yanns**
same as https://github.com/playframework/playframework/pull/4532, but against master

### CODE REVIEW

**Comment by yanns** [comment]
@richdougherty what do you think of this?

**Comment by richdougherty** [comment]
Error was:
```
[info] NettyDefaultFiltersSpec
[info] 
[info] filters should
[info]   handle errors
[info]     + ErrorHandlingFilter has no effect on a GET that returns a 200 OK
[info]     + ErrorHandlingFilter has no effect on a POST that returns a 200 OK
[info]     + ErrorHandlingFilter recovers from a GET that throws a synchronous exception
[info]     + ErrorHandlingFilter recovers from a GET that throws an asynchronous exception
[info]     + ErrorHandlingFilter recovers from a POST that throws a synchronous exception
[info]     + ErrorHandlingFilter recovers from a POST that throws an asynchronous exception
[error]   x Filters are not applied when the request is outside the application.context
[error]    '500' is not equal to '200' (FiltersSpec.scala:114)
```
@play-pull-request-validator can you try again in case it was a transient error?

**Comment by richdougherty** [comment]
@yanns, that looks good to me. :+1:

**Comment by marcospereira** [comment]
Build failed again:

```
[info] AkkaDefaultHttpFiltersSpec
[info] 
[info] filters should
[info]   handle errors
[info]     + ErrorHandlingFilter has no effect on a GET that returns a 200 OK
[info]     + ErrorHandlingFilter has no effect on a POST that returns a 200 OK
[info]     + ErrorHandlingFilter recovers from a GET that throws a synchronous exception
[info]     + ErrorHandlingFilter recovers from a GET that throws an asynchronous exception
[info]     + ErrorHandlingFilter recovers from a POST that throws a synchronous exception
[info]     + ErrorHandlingFilter recovers from a POST that throws an asynchronous exception
[error]   x Filters are not applied when the request is outside the application.context
[error]    '500' is not equal to '200' (FiltersSpec.scala:114)
[info] 
[info]   + Filters are applied on the root of the application context
[info]   + Filters work even if one of them does not call next
[info]   + ErrorHandlingFilter can recover from an exception throw by another filter in the filter chain, even if that Filter does not call next
[info]   + ErrorHandlingFilter can recover from an exception throw by another filter in the filter chain when that filter calls next and asynchronously throws an exception
[info]   + requests not matching a route should receive a RequestHeader modified by upstream filters
[info] 
[info] Total for specification AkkaDefaultHttpFiltersSpec
```

run @play-pull-request-validator, run!

**Comment by marcospereira** [comment]
@play-pull-request-validator please!

**Comment by jroper** [comment]
Does the failure happen when you run the integration tests locally?  I guess the test has a problem.

**Comment by yanns** [comment]
I also have errors when runnings the tests locally:
```
[error] Failed: Total 425, Failed 6, Errors 0, Passed 418, Skipped 1, Pending 26
[error] Failed tests:
[error] 	play.it.mvc.AkkaDefaultHttpFiltersSpec
[error] 	play.it.http.AkkaHttpHttpPipeliningSpec
[error] 	play.it.http.NettyHttpPipeliningSpec
[error] 	play.it.mvc.NettyDefaultFiltersSpec
[error] (Play-Integration-Test/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 224 s, completed Jun 4, 2015 10:55:00 AM
```

**Comment by yanns** [comment]
on master, "only" 2 tests are failing:
```
[error] 	play.it.http.AkkaHttpHttpPipeliningSpec
[error] 	play.it.http.NettyHttpPipeliningSpec
```
I guess my changes broke something. I'll check that.

**Comment by yanns** [comment]
I tried to fix the error, but the tests are now running locally without any change... Strange...

**Comment by richdougherty** [comment]
Maybe it works on master now. @play-pull-request-validator, please try again.

**Comment by richdougherty** [comment]
@yanns Do you want to try rebasing against master and try again? It looks like #4869 might be related.

**Comment by yanns** [comment]
no luck..
This PR is doomed... ;)

**Comment by richdougherty** [comment]
It doesn't seem to be CI stability because other PRs passing CI.

Maybe it's a genuine bug, since failing the `*FiltersSpec` test uses compile-time DI and has custom `initialSettings`, so it could interact with your change. The setting that is changed, `play.http.context`, is quite deeply embedded in Play. It's used by both the router and `HttpRequestHandler`. There are some lazy vals in `*FiltersSpec` so maybe there are some initialisation ordering or timing issues? Just a guess.

The tricky thing is that the test is failing in CI but it isn't failing in your environment. Could the bug be JRE, OS or timing related?

**Comment by yanns** [comment]
The problem comes from:
```
  lazy val configuration = context.initialConfiguration ++ Configuration.load(environment)
```
If I revert it back to 
```
  lazy val configuration = context.initialConfiguration
```
the tests are not failing.

I'll remove this change, because `ApplicationLoader.createContext` already uses the environment to create the `initialConfiguration`:
```
val configuration = Configuration.load(environment, initialSettings)
```
but also gives the possibility to provide the `initialSettings`

**Comment by yanns** [comment]
Can somebody triggers the CI?

**Pull request merged**
