### PR TITLE
play.filters.gzip.Gzip.gunzip throws java.util.zip.DataFormatException: invalid stored block lengths

### PR DESCRIPTION
**Pull request by jroper**
Gzip.gunzip enumeratee throws "java.util.zip.DataFormatException: invalid stored block lengths" when I'm trying to decompress any content created by gzip command line tool. It works perfect with content produced by Gzip.gzip enumeratee but fails for any file created by gunzip.

Exception in thread "main" java.util.zip.DataFormatException: invalid stored block lengths
at java.util.zip.Inflater.inflateBytes(Native Method)
at java.util.zip.Inflater.inflate(Inflater.java:259)
at play.filters.gzip.Gzip$$anon$5.play$filters$gzip$Gzip$$anon$$inflateUntilNeedsInput(Gzip.scala:235)
at play.filters.gzip.Gzip$$anon$5$$anonfun$play$filters$gzip$Gzip$$anon$$step$2.apply(Gzip.scala:218)
at play.filters.gzip.Gzip$$anon$5$$anonfun$play$filters$gzip$Gzip$$anon$$step$2.apply(Gzip.scala:211)

You can produce two zip files by gzip tool: first without file name in header using -n option and second with file name in header. Gunzip throws exception when header contains original file name.

### CODE REVIEW

**Comment by jroper** [comment]
I attached a PR, when I looked into it I saw that `dropWhile` was actually completely messed up anyway.  Now there are tests included.

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by benmccann** [comment]
Perhaps this should be backported to 2.3.x?

**Comment by jroper** [comment]
I don't think it's necessary, this is only a bug in the gunzip code, not in the gzip code.  Play actually doesn't use this enumeratee anywhere - request body decompression is handled by Netty.  Play does gzip responses itself if you use the gzip filter, but that doesn't do gunzip.

**Pull request merged**
