### PR TITLE
Flexible cookie handling for play.mvc.Http.Response #5015 implemented…

### PR DESCRIPTION
**Pull request by darioalessandro**
… builder pattern for Cookie, and created Http.Response setCookie that takes a Cookie instance

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @darioalessandro,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by jroper** [comment]
Hi @darioalessandro, thanks for implementing this!

The approach you've implemented is not quite what we were looking for.  We'd like `Cookie` to stay immutable, with a new `Cookie.Builder` class to build it.  Using it might look something like this:

```java
Cookie.builder("name", "value").setMaxAge(123).build()
```

**Comment by darioalessandro** [comment]
Ok, I'll create a CookieBuilder which is mutable and rollback Cookie to be immutable.

**Comment by dotta** [comment]
@darioalessandro I'm closing this PR. Please, do reopen it when it's ready for review.

**Pull request closed without merging**
