### PR TITLE
[master] Update dependencies

### PR DESCRIPTION
**Pull request by mkurz**
#8838 was only merged in `2.7.x` branch.

### CODE REVIEW

**Comment by dwijnand** [comment]
Rather than this can't we just merge the 2.7.0 branch into master?

**Comment by mkurz** [comment]
We could, however that's the way we did it in the past, probably to keep nice git history and avoid merge commits. I don't care too much actually. @marcospereira?

**Comment by marcospereira** [comment]
It is okay to cherry-pick and push when the change is not substantial, like this one. Although I like that by using a new PR we can count on Travis to avoid silly mistakes.

Anyway, since we have a PR here now, let's get a green build and integrate it.

Thanks for noticing this wasn't forwarded ported, @mkurz.

**Comment by dwijnand** [comment]
Cherry picking duplicates SHAs, merging also makes sure the branches don't stay diverging (which they shouldn't, seeing as every change in 2.7.x should be also present in the version that follows.)

**Pull request merged**
