### PR TITLE
Connection was not closed when there is an exception fom checkEvoluti…

### PR DESCRIPTION
**Pull request by rajendrag**
# Pull Request Checklist

* [Yes ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [Yes ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ Yes] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ Yes] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [No new files] Have you added copyright headers to new files?
* [Scala] Have you checked that both Scala and Java APIs are updated?
* [Minor change ] Have you updated the documentation for both Scala and Java sections?
* [Moving the line into try block] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

Releases the db connection if there is an exception while checking the evolutions status

If the db is inconsistent state, `play.api.db.evolutions.InconsistentDatabase` exception thrown and it is going out of the databaseEvolutions method, hence the connection is still there.

### CODE REVIEW

**Comment by marcospereira** [comment]
Hi @rajendrag, 

Build is broken:

https://travis-ci.org/playframework/playframework/jobs/149922567#L344

Besides that, this PR looks good to me.

**Comment by mkurz** [comment]
I think you need to remove the spaces in the empty lines.

**Comment by gmethvin** [comment]
@rajendrag What happened to this PR?

**Comment by schmitch** [comment]
I guess this is not needed anymore since the stop hooks will now clean it up anyway?

**Comment by rajendrag** [comment]
I had to submit another PR as I could not update this one. This is merged as part of https://github.com/playframework/playframework/pull/6391

**Comment by gmethvin** [comment]
Thanks. I was just checking to see that everything in the 2.5.5 milestone was backported.

**Pull request closed without merging**
