### PR TITLE
Java 17

### PR DESCRIPTION
**Pull request by mkurz**
### :point_right: If you are looking for a way run Play 2.8.x with Java 17... Yes, that is possible since Play 2.8.15: https://github.com/playframework/playframework/releases/tag/2.8.15

<hr>

Let's see how well Play plays with Java ~16~ 17.
The goal here is to make Play work with upcoming [Java 17 (release date: 2021/09/14)](https://openjdk.java.net/projects/jdk/17/) as early as possible, because just like Java 11, Java 17 will be a LTS version.

- [x] validate (see below)
- [x] compile
- [x] publishLocal
- [x] tests
- [x] integration tests (see below)
- [x] scripted tests

<hr>

**WIP: ---add-exports**

scripted tests:
https://travis-ci.com/github/playframework/playframework/jobs/498243543#L5170-L5174

<hr>

**Microbenchmark and integration tests with akka's http2 endpoint fail**

Failed Integration tests: https://travis-ci.com/github/playframework/playframework/jobs/498389129
See all the `java.net.SocketTimeoutException`s, http2 does not start. Also see the bottom of the logs, you will see the `InaccessibleObjectException`s.

Failed microbenchmarks: https://travis-ci.com/github/playframework/playframework/jobs/498367902#L1934-L1942
<details>
  <summary>Error log</summary>

```
...
[info] # JMH version: 1.25
[info] # VM version: JDK 16, OpenJDK 64-Bit Server VM, 16+36
[info] # VM invoker: /home/travis/.jabba/jdk/1.16.0-custom/bin/java
[info] # VM options: --add-exports=java.base/sun.security.x509=ALL-UNNAMED -XX:MaxMetaspaceSize=384m -Xmx512m -Xms128m
[info] # Warmup: <none>
[info] # Measurement: 1 iterations, 10 s each
[info] # Timeout: 10 min per iteration
[info] # Threads: 1 thread, will synchronize iterations
[info] # Benchmark mode: Throughput, ops/time
[info] # Benchmark: play.microbenchmark.it.HelloWorldBenchmark.helloWorld
[info] # Parameters: (endpoint = ak-20-enc, reqsPerConn = 5)
[info] # Run progress: 88.89% complete, ETA 00:00:13
[info] # Fork: 1 of 1
[info] Picked up JAVA_TOOL_OPTIONS: --add-exports=java.base/sun.security.x509=ALL-UNNAMED
[info] Iteration   1: ERROR a.a.OneForOneStrategy - Unable to make public void sun.security.ssl.SSLEngineImpl.setHandshakeApplicationProtocolSelector(java.util.function.BiFunction) accessible: module java.base does not "opens sun.security.ssl" to unnamed module @5a2e4553
[info] akka.actor.ActorInitializationException: akka://application/system/Materializers/StreamSupervisor-0/TLS-for-flow-1-1: exception during creation
[info] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
[info] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public void sun.security.ssl.SSLEngineImpl.setHandshakeApplicationProtocolSelector(java.util.function.BiFunction) accessible: module java.base does not "opens sun.security.ssl" to unnamed module @5a2e4553
[info] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
...
```
</details>

* ~Will this be fixed when [upgrading to akka-http 10.2.x](https://github.com/playframework/playframework/pull/10411)?~ The problem is okhttp.
* Workaround for now: `--add-opens=java.base/sun.security.ssl=ALL-UNNAMED`

<hr>

**Validate docs fail (but not relevant for now)**
https://travis-ci.com/github/playframework/playframework/jobs/497685525#L4256
<details>
  <summary>Error log</summary>

```
[error] java.lang.RuntimeException: Error creating extended parser class: Could not determine whether class 'play.doc.CodeReferenceParser$$parboiled' has already been loaded
[error] 	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
[error] 	at org.pegdown.plugins.PegDownPlugins$Builder.withPlugin(PegDownPlugins.java:126)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.parseMarkdownFile$1(PlayDocsValidation.scala:125)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.$anonfun$generateMarkdownRefReportTask$3(PlayDocsValidation.scala:209)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.$anonfun$generateMarkdownRefReportTask$1(PlayDocsValidation.scala:209)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:831)
[error] Caused by: java.lang.RuntimeException: Could not determine whether class 'play.doc.CodeReferenceParser$$parboiled' has already been loaded
[error] 	at org.parboiled.transform.AsmUtils.findLoadedClass(AsmUtils.java:213)
[error] 	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
[error] 	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
[error] 	at org.pegdown.plugins.PegDownPlugins$Builder.withPlugin(PegDownPlugins.java:126)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.parseMarkdownFile$1(PlayDocsValidation.scala:125)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.$anonfun$generateMarkdownRefReportTask$3(PlayDocsValidation.scala:209)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.$anonfun$generateMarkdownRefReportTask$1(PlayDocsValidation.scala:209)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:831)
[error] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @79600226
[error] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[error] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[error] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[error] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[error] 	at org.parboiled.transform.AsmUtils.findLoadedClass(AsmUtils.java:206)
[error] 	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
[error] 	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
[error] 	at org.pegdown.plugins.PegDownPlugins$Builder.withPlugin(PegDownPlugins.java:126)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.parseMarkdownFile$1(PlayDocsValidation.scala:125)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.$anonfun$generateMarkdownRefReportTask$3(PlayDocsValidation.scala:209)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at com.typesafe.play.docs.sbtplugin.PlayDocsValidation$.$anonfun$generateMarkdownRefReportTask$1(PlayDocsValidation.scala:209)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:831)
[error] (generateMarkdownRefReport) Error creating extended parser class: Could not determine whether class 'play.doc.CodeReferenceParser$$parboiled' has already been loaded
```
</details>

[Line that causes the exception](https://github.com/playframework/playframework/blob/2.8.8/dev-mode/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala#L125).
Problem: play-docs [depends on unmaintained pegdown 1.6.0](https://github.com/playframework/play-doc/blob/2.1.0/build.sbt#L11) (which is discussed [here](https://github.com/playframework/play-doc/issues/35) already), which [depends on outdated parboiled-java 1.1.7](https://github.com/sirthias/pegdown/blob/1.6.0/build.sbt#L36), which [depends on outdated ASM version 5.0.3](https://github.com/sirthias/parboiled/blob/1.1.7/project/Dependencies.scala#L15) that has no support for newer JDKs. Even current parboiled 1.3.1 (which is the latest versions as time of this writing) only [includes ASM 7.1](https://github.com/sirthias/parboiled/blob/1.3.1/project/Dependencies.scala#L15), which still does not support Java 16. Only parboiled's master branch already [depends on latest ASM 9.1](https://github.com/sirthias/parboiled/blob/35e0524d8261a89be2dfa947d75c318a3b2eeb75/project/Dependencies.scala#L15).
However, this problem is not urgent and does not block Play from supporting Java 17, because this is "just" about "Validate docs (links, sample code, etc.)". We can and will continue running this jobs with Java 8, and even if ditch Java 8, we will probably only move the Java 11 as next step which will still work. So I think we are good for a couple more years (I mean in theory, we can even run this validation jobs with Java 8/11 forever).
We could also try to just override the ASM dependency, maybe that would be enough(?)

### CODE REVIEW

**Comment by aelgn** [comment]
It seems like a big problem is the deeply transitive dependency on `cglib` via `guice`. cglib is a **discontinued** project using a ton of illegal access reflection, which is by default denied in java 16.
`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4f9a18bd
`

Adding VM arg `--illegal-access=warn` is a temporary work around that will be removed in a future JVM release.

The new guice release `5.0.1` removes cglib and fixes various illegal access problems.
https://github.com/google/guice/issues/1133

For this and other reasons I do think it is imperative that play framework migrates to guice 5.
https://github.com/google/guice/wiki/Guice501#guice-core

**Comment by mkurz** [comment]
@aelgn we already upgraded Guice to 5.0.1 in the `master` branch (see #10724 and #10727). Therefore upcoming Play 2.9 will not show that warnings anymore. Also my goal is to fully support Java 17 with Play 2.9, which looks promising already.

**Comment by aelgn** [comment]
@mkurz that is great news! 🥇

**Comment by mkurz** [comment]
Blocked by https://github.com/travis-ci/travis-cookbooks/pull/1092 (and I am too lazy for a workaround right now(

**Comment by mkurz** [comment]
FYI: I switched to JDK nightlies to Eclipse Adoptium:
- https://blog.adoptium.net/2021/03/eclipse-adoptium-announcement/
- https://adoptium.net/nightly.html?variant=openjdk17&jvmVariant=hotspot
- https://github.com/adoptium/temurin17-binaries/releases

**Comment by francisdb** [comment]
JDK 17 LTS was released, what work is remaining here?

**Comment by mkurz** [comment]
> JDK 17 LTS was released, what work is remaining here?

I don't think there is any work left. This PR was just for experimenting. When I find time I can set up a clean PR.

**Comment by teagy** [comment]
We've been waiting a long time for this to get completed. Any ETA?

**Comment by gokhanoner** [comment]
@mkurz does it necessary to wait for 2.9 for Java 17 support? Only PR I see regarding any code change is this one -> https://github.com/playframework/playframework/pull/10731

Is it possible to merge it into 2.8.x also, so we can at least use Java 17 (Or since it's already merged into master, will it be available in the next 2.8 release?)

**Comment by mkurz** [comment]
> does it necessary to wait for 2.9 for Java 17 support?

Yes, I am pretty sure that's necessary. There were other pull requests merged already besides the one you mentioned that were necessary for prober Java 17 support (E.g. I think the Guice version in Play 2.8.x won't work in Java 17 as far as I can remember). I don't think I will spend more time to get Java 17 support into Play 2.8.x, I think time is better invested to finally get 2.9. out. However I can not give you an ETA right now, I will try my best over the next week.

**BTW: If you want to financially support Play, you can do that now via https://opencollective.com/playframework - that would allow contributors like me to spend more time working on it. Thanks!**

**Comment by diversit** [comment]
Any news on Play 2.9? Java 17 already has been out for over 6 months now.

**Comment by gokhanoner** [comment]
As I mentioned in this PR, https://github.com/playframework/playframework/pull/10731, just applying this PR to the next 2.8 release should be more than enough for us to run our apps using Java 17, even if it's not officially supported, yet.

**Comment by teagy** [comment]
> As I mentioned in this PR, #10731, just applying this PR to the next 2.8 release should be more than enough for us to run our apps using Java 17, even if it's not officially supported, yet. I believe we can handle updating dependencies that causes issues with JDK > 11, like guice dependency etc, that's the easy part. AFAIK, the only code change that's needed is in above PR.

I concur. We really need this PR in 2.8 ASAP even if not officially supported. We have been running Play on Java 15 for many years now just fine but we can't upgrade to Java 17 until this PR is merged and we have seriously been considering switching to a different web framework considering how long it's taken you to get these changes merged in. If you don't want to merge it into the release then at least consider building a separate version that is a "beta" version of Java 17 or something so we can pull it into our SBT projects. Thanks.

**Comment by mkurz** [comment]
I can backport #10731 and release a new Play 2.8.x version and you can try if that works for you.

**Comment by mkurz** [comment]
I am not sure however if #10731 is enough, like @gokhanoner said you probably need to upgrade some dependencies yourself to make everything work.

**Comment by justinnichols** [comment]
> I am not sure however if #10731 is enough, like @gokhanoner said you probably need to upgrade some dependencies yourself to make everything work.

I suspect Guice, at minimum, has to have its version updated due to the issues with reflection and certain access deprecation (if it was finally disallowed in Java 17).

**Comment by mkurz** [comment]
Yeah you can do the Guice upgrade yourself in your `build.sbt`, no problem.
I am not sure however if there are other things that would need to be done. In the last year I remember fixing things regarding Java 17, however they might not be relevant for everyone.

**Comment by mkurz** [comment]
OK, here we go: #11206

**Comment by mkurz** [comment]
After merging #11207 I will wait until tomorrow, after Play's daily build is done (which runs additional tests, not just tests triggered by pull requests), and I have enough time, I can probalby release Play 2.8.14

**Comment by gokhanoner** [comment]
@mkurz Thank you very much, much appreciated 👍🏽

**Comment by mkurz** [comment]
You can follow the 2.8.14 release here: https://github.com/playframework/play-meta/issues/217
The 2.8.x cron build should start in like 1 hour: https://app.travis-ci.com/github/playframework/playframework/builds
Note sure if I have time this evening to do the release, if not the probably tomorrow.

**Comment by gokhanoner** [comment]
Thanks @mkurz . Build seems successfully completed. Today or tomorrow, I'm fine & thanks for your quick reply 🙏🏽

**Comment by mkurz** [comment]
Play 2.8.14 is now available :+1: Please give it a try if now Java 17 works for you, but be aware that you have to upgrade some dependencies yourself, see the notes here: #11206
Please let me know if something else makes problems, we might can fix it for 2.8.x, thanks!
I will announce the release early next week, it would be nice if you could give feedback if Java 17 works for you, so I can add it to the release announcements. Thanks!

**Comment by gokhanoner** [comment]
@mkurz thank you very much, I'll do a build & update here.

**Comment by gokhanoner** [comment]
@mkurz I just build my project & run unit + integrations tests with JDK 17. Everything works.
I tested with both `ThisBuild / javacOptions ++= Seq("--release", "11")` and `ThisBuild / javacOptions ++= Seq("--release", "17")`.

Also, I was using guice 5.0.1 & I got some error. Apparetly they have a minor upgrade to support Java 17, https://github.com/google/guice/wiki/Guice510, you might want to update to that version for Play 2.9.

**Comment by mkurz** [comment]
Great! (main [is using Guice 5.1.0 already](https://github.com/playframework/playframework/blob/a048110b14d13ec54e3417800527c76b3b6677df/project/Dependencies.scala#L132))

**Comment by francisdb** [comment]
Just tried upgrading, is below expected? It pops up during our tests. I don't see it mentioned in the notes

```
[info]   java.lang.IllegalAccessError: class com.typesafe.sslconfig.ssl.FakeKeyStore$ (in unnamed module @0x59505b48) cannot access class sun.security.x509.X509CertInfo (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x59505b48
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$.createSelfSignedCertificate(FakeKeyStore.scala:89)
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$.generateKeyStore(FakeKeyStore.scala:79)
[info]   at play.core.server.SelfSigned$.x$1$lzycompute(SelfSigned.scala:24)
[info]   at play.core.server.SelfSigned$.x$1(SelfSigned.scala:23)
[info]   at play.core.server.SelfSigned$.sslContext$lzycompute(SelfSigned.scala:23)
[info]   at play.core.server.SelfSigned$.sslContext(SelfSigned.scala:23)
[info]   at play.core.server.SelfSignedSSLEngineProvider.sslContext(SelfSigned.scala:36)
[info]   at play.core.server.AkkaHttpServer.sslContext$lzycompute(AkkaHttpServer.scala:245)
[info]   at play.core.server.AkkaHttpServer.sslContext(AkkaHttpServer.scala:244)
[info]   at play.core.server.AkkaHttpServer.$anonfun$httpsServerBinding$1(AkkaHttpServer.scala:260)
[info]   ...
```

**Comment by gokhanoner** [comment]
@francisdb it is mentioned. Apparently you're using self signed certificates. Try adding `--add-opens=java.base/sun.security.ssl=ALL-UNNAMED` to your startup.

**Comment by francisdb** [comment]
@gokhanoner mind pointing me to where it is mentioned? We are not doing anything special with certificates, just testing with OneServerPerSuiteWithComponents

```scala
class RedirectFilterSpec extends PlaySpec with OneServerPerSuiteWithComponents with WsTestClient { 

  override lazy val components = new BuiltInComponentsFromContext(context) with RedirectHttpsComponents {
    ...
  }

  ...
}
```

**Comment by gokhanoner** [comment]
@francisdb under `Microbenchmark and integration tests with akka's http2 endpoint fail` in this ticket, check the `Error logs`. It shows a specific error, very similar to yours & I remember reading self-signed certificate related JDK17 issues mentioned by @mkurz. Let me check if I can find more details

**Comment by gokhanoner** [comment]
Found it -> https://github.com/playframework/playframework/issues/10883#issuecomment-851566257

**Comment by sleski** [comment]
Maybe we can adjust this info in command line:

[info] loading settings for project de_idnow_ai from build.sbt ...
[info]   __              __
[info]   \ \     ____   / /____ _ __  __
[info]    \ \   / __ \ / // __ `// / / /
[info]    / /  / /_/ // // /_/ // /_/ /
[info]   /_/  / .___//_/ \__,_/ \__, /
[info]       /_/               /____/
[info]
[info] Version 2.8.14 running Java 17.0.1
[info]
[info] Play is run entirely by the community. Please consider contributing and/or donating:
[info] https://www.playframework.com/sponsors
[info]
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[info]   Java version is 17. Play supports only 8 and 11.
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mkurz** [comment]
@sleski See #11215

**Comment by mkurz** [comment]
https://github.com/playframework/playframework/releases/tag/2.8.15

**Comment by gokhanoner** [comment]
@mkurz also, since I couldn't see any, you might want to upgrade to latest Spring 5.3, since they did a lot of work for JDK 17 support there. Although they'll officially support JDK 17 in Spring 6, according to this, https://github.com/spring-projects/spring-boot/blob/v2.5.5/spring-boot-project/spring-boot-docs/src/docs/asciidoc/getting-started/system-requirements.adoc, its' compatible (This is the only document mentions JDK 17 compatibility), and it uses Spring 5.3.X

**Comment by gokhanoner** [comment]
@mkurz you might want to upgrade to latest 5.3 (5.3.18 as of now) in master, which contains a fix for Spring vulnerability.

**Comment by mkurz** [comment]
@gokhanoner scala-steward will do the upgrade for us :wink:

**Comment by hedecai** [comment]
Hi,
We use play-ebean, the version 6.2.0-RC4 doesn't support java 17 since the Ebean version is 12.8.1.

**Comment by PromanSEW** [comment]
@hedecai see https://github.com/playframework/play-ebean/pull/281

**Comment by hedecai** [comment]
> @hedecai see [playframework/play-ebean#281](https://github.com/playframework/play-ebean/pull/281)

Thanks. Waiting for the new release of play-ebean.

**Comment by PromanSEW** [comment]
@hedecai please check `6.2.0-RC6`
Also see
https://github.com/playframework/play-ebean/issues/278#issuecomment-1123982804
Do you have this `IllegalStateException` on start after update?

**Comment by hedecai** [comment]
> 

@PromanSEW We upgrade from 6.2.0-RC4 to 6.2.0-RC6 has this exception "javax.persistence.PersistenceException: models.xx is NOT and Entity Bean registered with this server " in production (using sbt clean; sbt dist).
In our development machine run our project using sbt run every thing is OK.
This project is using java 8 and play 2.8.15

**Comment by PromanSEW** [comment]
@hedecai also see https://github.com/playframework/play-ebean/issues/290

**Comment by hedecai** [comment]
> @hedecai also see [playframework/play-ebean#290](https://github.com/playframework/play-ebean/issues/290)

We don't has the IllegalStateException, our app use Ebean 12.16.1 as play-ebean version.
We change the application.conf Ebean.default = ["models.*"] to ebean.default = ["models.A", "model.B", "models.C", ...] not when compile but after package with sbt dist, so the Ebean enhance is OK.  There something wrong when running the app, the app didn't register Entity to Ebean correct.

**Comment by ruyconolly** [comment]
> playframework/play-ebean#290

I'm facing the same problem but my project has more than 100 entities! 😢

**Comment by mkurz** [comment]
@hedecai @ruyconolly Please try the latest, just released play-ebean version: https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC7

**Comment by mkurz** [comment]
Done in #11448, main branch in now Java 17 compatible out of the box (except the certifcate stuff from ssl-config, but that shouldn't really be a problem)

**Pull request closed without merging**
