### PR TITLE
Include how to parse JSON, and where the val json comes from. Fixes #…

### LINKED ISSUE #6540: Scala JsonTransformers do not work as documented
### Play Version (2.5.x / etc)
2.4.x / 2.5.x

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux kvell 4.4.0-9136-generic #55-Ubuntu SMP Fri Aug 26 05:58:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-2-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

### Expected Behavior
```scala
scala> import play.api.libs.json._
import play.api.libs.json._

scala> val json = Json.toJson("""{
     |   "key1" : "value1",
     |   "key2" : {
     |     "key21" : 123,
     |     "key22" : true,
     |     "key23" : [ "alpha", "beta", "gamma"],
     |     "key24" : {
     |       "key241" : 234.123,
     |       "key242" : "value242"
     |     }
     |   },
     |   "key3" : 234
     | }""")
json: play.api.libs.json.JsValue = "{\n  \"key1\" : \"value1\",\n  \"key2\" : {\n    \"key21\" : 123,\n    \"key22\" : true,\n    \"key23\" : [ \"alpha\", \"beta\", \"gamma\"],\n    \"key24\" : {\n      \"key241\" : 234.123,\n      \"key242\" : \"value242\"\n    }\n  },\n  \"key3\" : 234\n}"

scala> val jsonTransformer = (__ \ 'key2 \ 'key23).json.pick
jsonTransformer: play.api.libs.json.Reads[play.api.libs.json.JsValue] = play.api.libs.json.Reads$$anon$8@10bbae3f

scala> json.transform(jsonTransformer)
res9: play.api.libs.json.JsResult[play.api.libs.json.JsValue] = 
  JsSuccess(
    ["alpha","beta","gamma"],
    /key2/key23
  )
```

### Actual Behavior

```scala
scala> import play.api.libs.json._
import play.api.libs.json._

scala> val json = Json.toJson("""{
     |   "key1" : "value1",
     |   "key2" : {
     |     "key21" : 123,
     |     "key22" : true,
     |     "key23" : [ "alpha", "beta", "gamma"],
     |     "key24" : {
     |       "key241" : 234.123,
     |       "key242" : "value242"
     |     }
     |   },
     |   "key3" : 234
     | }""")
json: play.api.libs.json.JsValue = "{\n  \"key1\" : \"value1\",\n  \"key2\" : {\n    \"key21\" : 123,\n    \"key22\" : true,\n    \"key23\" : [ \"alpha\", \"beta\", \"gamma\"],\n    \"key24\" : {\n      \"key241\" : 234.123,\n      \"key242\" : \"value242\"\n    }\n  },\n  \"key3\" : 234\n}"

scala> val jsonTransformer = (__ \ 'key2 \ 'key23).json.pick
jsonTransformer: play.api.libs.json.Reads[play.api.libs.json.JsValue] = play.api.libs.json.Reads$$anon$8@10bbae3f

scala> json.transform(jsonTransformer)
res23: play.api.libs.json.JsResult[play.api.libs.json.JsValue] = JsError(List((/key2/key23,List(ValidationError(List(error.path.missing),WrappedArray())))))
```

### Reproducible Test Case

Please provide a PR with a failing test.  Will try...

If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

### PR DESCRIPTION
**Pull request by graingert**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #6540

## Purpose

Include how to parse JSON, and where the val json comes from, in the JsonTransformer docs

…6540

### CODE REVIEW

**Comment by schmitch** [comment]
I'm not sure about the change. I would keep the Json as is and a note below in a second snippet on how to get the raw json to a JsValue.

**Comment by graingert** [comment]
Not sure about that. The JSON seems to stand on its own and unrelated to the rest of the documentation

**Comment by schmitch** [comment]
Actually it's just the example Json (and not any parsed value) which will be used in the examples. The Json Transfomers is actually a more advacned use case and if you are at that page you should've probably understood the previous pages and now how to get a parsed JsValue from Json. Also the text clearly says what it is "in the samples below we use that json"

**Comment by graingert** [comment]
Sure, but it's unclear. I got confused. It would be much better to refer to ’that json’ by an actual `val`.

Ideally I'd like to be able to paste the examples into my Scala repl and have them 'just work'

**Comment by cchantep** [comment]
@grainbert as indicated previously, the way to parse a `String` as `JsValue` is explained in the first example of the JSON documentation, which is recommanded to get started (for this reason and others) before going on with more advanced usages. So before submitting such PR, please discuss it on the MailingList to figure out if/how a change could be useful. Best regards.

**Comment by AkashicSeer** [comment]
too bad they didn't listen to this guy and people like him. This seems to be the mentality too often. I'm over it.

**Pull request closed without merging**
