### PR TITLE
Fixed date constraint on the form input 

### LINKED ISSUE #9495: Form input constraint truncates dates to the minute
The date constraint on form inputs ( https://www.playframework.com/documentation/2.7.x/api/scala/play/api/data/Forms$.html#date(pattern:String,timeZone:java.util.TimeZone):play.api.data.Mapping[java.util.Date] ) truncates values such as '2019-07-22T07:00:57+00:00' to the minute (i.e. '2019-07-22T07:00:00+00:00')
Indeed, the conversion in https://github.com/playframework/playframework/blob/master/core/play/src/main/scala/play/api/data/format/PlayDate.scala is only performed down to minutes : seconds and nano of seconds are ignored.

### Play Version
2.6.x / 2.7.x, still present on master branch.

### API
Scala

### Operating System
Ubuntu 19.04

### JDK
OpenJDK 1.8.0_212

### Expected Behavior

1. Build a form with a date input and a pattern such as 'yyyy-MM-dd'T'HH:mm:ss.SSSXXX'
2. Submit the form with a serialized date value such as '2019-07-22T07:00:57+00:00'
3. The resulting java.util.Date instance, initialized with the correct value up to the millisecond precision (the java.util.Date precision limit)

### Actual Behavior

1. Build a form with a date input and a pattern such as 'yyyy-MM-dd'T'HH:mm:ss.SSSXXX'
2. Submit the form with a serialized date value such as '2019-07-22T07:00:57+00:00'
3. The resulting java.util.Date instance, initialized with the correct value up to the minute precision. Seconds and milliseconds are lost.

### PR DESCRIPTION
**Pull request by emmanuelGuiton**
Fixed date constraint on the form input so that seconds and nanoseconds are taken into account. Fixes #9495 .

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by emmanuelGuiton** [comment]
I did sign the CLA.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by renatocaval** [comment]
@emmanuelGuiton, thanks for your contribution. 

It seems that we are having a problem with the CLA check. I can see indeed that you have signed it and that GitHub identifies you as the committer. For some reason, the CLA check is failing. I will check it internally to understand why this is happening. 

The tests failed because of some flakiness. I reboot them.

**Comment by TimMoore** [comment]
@emmanuelGuiton to pass the CLA check, you'll need to add the email address you used in the Git commit to your GitHub account. Alternatively, you could rewrite the commits with the email address that you have configured in GitHub.

**Comment by emmanuelGuiton** [comment]
Sorry, I had not noticed that I used a wrong e-mail address in my commits. That is now fixed (and I see the CLA validator is now very happy).

**Comment by emmanuelGuiton** [comment]
@renatocaval I added test cases. It was really worth it since it made me notice that time zones were not handled. I fixed that too.

**Pull request merged**
