### PR TITLE
Mentioned play-slick in migration doc

### PR DESCRIPTION
**Pull request by dotta**
The addition is motivated by feedback received in the play-framework ML.

**To backport**

### CODE REVIEW

**Comment by jroper** [comment]
Add `PlaySlickMigrationGuide` to `PlayDocsKeys.playDocsValidationConfig` external wiki pages in `documentation/project/Build.scala` to fix the build failure.

**Comment by marcospereira** [comment]
@dotta could you please rebase from master to resolve the conflicts?

**Comment by dotta** [comment]
@marcospereira rebased done.

**Comment by gmethvin** [comment]
2.4.x: 51ae0a4

**Comment by dotta** [comment]
@gmethvin Thanks!

**Pull request merged**
