### PR TITLE
Merge pull request #9981 from geetikagupta16/patch-1

### PR DESCRIPTION
**Pull request by geetikagupta16**
Added information to send data to web sockets

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @geetikagupta16,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by geetikagupta16** [comment]
@lightbend-cla-validator I have signed the CLA

**Comment by renatocaval** [comment]
Hmm, I just realised that you probably sent this PR using the browser and that you won't have a local checkout to amend commits. Was that the case? Are you familiar with sending PR in GitHub? If not, we can merge like this and I take care of applying the change on the Java page. 

Otherwise, if you want to do it yourself, or learn how to amend to this PR we can assist you. 

Please, let us know.

**Comment by geetikagupta16** [comment]
@renatocaval Thanks for the review. I'll update the related Java docs as well.

**Comment by geetikagupta16** [comment]
@renatocaval I have made the required changes. Please review.

**Comment by renatocaval** [comment]
Thanks @geetikagupta16.

**Comment by renatocaval** [comment]
I accidentally closed. I need more coffee. 

I reopened and merged! ;-)

**Comment by geetikagupta16** [comment]
Thanks @renatocaval :)

**Pull request merged**
