### PR TITLE
Removes duplicate links

### PR DESCRIPTION
**Pull request by naferx**
Removes duplicate link pointing to Debugging SSL section

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @nafers4n,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by richdougherty** [comment]
@naferx, thanks for the fix. Are you able to sign the CLA? I notice that your username is `naferx` but the CLA validator thinks that you are `nafers4n`. That could cause a problem with the CLA validator, so let me know if you've signed the CLA but the validator is still failing.

**Comment by naferx** [comment]
Hi @richdougherty!, 
I have signed the CLA.

**Comment by richdougherty** [comment]
Thanks!

**Pull request merged**
