### PR TITLE
Add head/headOption & tail/tailOption on JsArray

### PR DESCRIPTION
**Pull request by gmethvin**
*See #4248*

### CODE REVIEW

**Comment by gmethvin** [comment]
Attached a PR.

To be consistent with `apply`, I think we should just have `head` and `tail` on `JsLookup`. I could also add `headOption` and `tailOption` but that would basically mean mapping any `JsUndefined` to `None`, which I think might be confusing. Of course, you can still do that explicitly with `.head.toOption`

**Comment by cchantep** [comment]
Thanks @gmethvin

**Comment by jroper** [comment]
I think the original issue they wanted `last`.

**Comment by gmethvin** [comment]
Yeah just noticed that. I'll add it.

**Pull request merged**
