### PR TITLE
Add full name of WS abbreviation to docs

### PR DESCRIPTION
**Pull request by YourPsychiatrist**
I added "WebService" as an explanation for the abbreviation WS (in "play-**ws**") to both the java and the scala documentation.
Issue: https://github.com/playframework/play-ws/issues/382

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @YourPsychiatrist,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by YourPsychiatrist** [comment]
I signed the CLA after opening the pull request!

**Comment by ignasi35** [comment]
I'm merging this even though the TravisCI build is not fully green. The failure is unrelated to this change (which is trivial). The failure is a side effect of https://github.com/playframework/playframework/pull/9576 refactoring some travis-related scripts.

**Comment by ignasi35** [comment]
thanks @YourPsychiatrist

**Pull request merged**
