### PR TITLE
[WS] Add info and warnings to sunset SHA1 signatures

### PR DESCRIPTION
**Pull request by wsargent**
Fixes https://github.com/playframework/playframework/issues/4241

The algorithm to note SHA-1 certificates is based on the expiration date -- a certificate expiring from 6/2016 to 12/2016 gets an info, but expiration after that gets a warning, based on http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html

### CODE REVIEW

**Comment by marcospereira** [comment]
@wsargent scalariform error here:

```
[warn] Scalariform parser error for /scratch/jenkins/workspace/play-master-PRs/framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala: Expected token RBRACKET but got Token(XML_START_OPEN,<,664,<)
[warn] Scalariform parser error for /scratch/jenkins/workspace/play-master-PRs/framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala: expected start of definition, but was Token(DEF,def,12168,def)
[info] Reformatted 1 Scala source {file:/scratch/jenkins/workspace/play-master-PRs/framework/}Play-WS(test).
[warn] Scalariform parser error for /scratch/jenkins/workspace/play-master-PRs/framework/src/play/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala: Expected token RBRACKET but got Token(XML_START_OPEN,<,2055,<)
[success] Total time: 1 s, completed May 15, 2015 7:51:15 PM
diff --git a/framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/AlgorithmCheckerSpec.scala b/framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/AlgorithmCheckerSpec.scala
index 3a0fcda..75efda5 100644
--- a/framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/AlgorithmCheckerSpec.scala
+++ b/framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/AlgorithmCheckerSpec.scala
@@ -5,10 +5,10 @@
  */
 package play.api.libs.ws.ssl
 
-import java.security.cert.{CertPathValidatorException, Certificate, X509Certificate}
+import java.security.cert.{ CertPathValidatorException, Certificate, X509Certificate }
 import java.util.Collections._
 
-import org.joda.time.{DateTime, Days, Instant}
+import org.joda.time.{ DateTime, Days, Instant }
 import org.specs2.mutable._
 import play.api.libs.ws.ssl.AlgorithmConstraintsParser._
 
ERROR: Scalariform check failed, see differences above.
```

**Comment by wsargent** [comment]
@marcospereira *shakes fist at scalariform*

**Comment by wsargent** [comment]
@play-pull-request-validator again

**Comment by wsargent** [comment]
```
[ERROR] [05/18/2015 20:17:28.694] [application-akka.actor.default-dispatcher-11] [ActorSystem(application)] Outgoing response stream error
akka.http.scaladsl.model.InvalidContentLengthException: HTTP message had declared Content-Length 100000 but entity data stream amounts to 99985 bytes less
	at akka.http.scaladsl.model.InvalidContentLengthException$.apply(ErrorInfo.scala:50)
	at akka.http.impl.engine.rendering.RenderSupport$CheckContentLengthTransformer.onUpstreamFinish(RenderSupport.scala:92)
	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$4.run(Interpreter.scala:442)
	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:216)
	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$4.progress(Interpreter.scala:433)
	at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:533)
	at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$unsafeFork(Interpreter.scala:597)
	at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$fork(Interpreter.scala:585)
	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.finish(Interpreter.scala:293)
	at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.finish(Interpreter.scala:608)
	at akka.stream.stage.AbstractStage.enterAndFinish(Stage.scala:80)
	at akka.stream.impl.fusing.BatchingActorInputBoundary.akka$stream$impl$fusing$BatchingActorInputBoundary$$onComplete(ActorInterpreter.scala:113)
	at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:150)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:339)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

@play-pull-request-validator again please

**Pull request merged**
