### PR TITLE
Update Deploying.md

### PR DESCRIPTION
**Pull request by Dinduks**
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

### CODE REVIEW

**Comment by marcospereira** [comment]
Hello @Dinduks,

Thanks for contributing to Play. What is the purpose of this change?

**Comment by Dinduks** [comment]
Hi @marcospereira. 

Java properties should be passed before the `-jar jarname.jar` part. 
The syntax currently in the documentation is incorrect.

**Comment by marcospereira** [comment]
Thanks @Dinduks.

**Comment by marcospereira** [comment]
Backport here: 42ce9d9fa74973dd29f39da6b6c5883c04c34a1a

**Pull request merged**
