### PR TITLE
Fixed threadpools documentation default examples

### PR DESCRIPTION
**Pull request by gstraymond**
I had some difficulties configuring the default dispatcher and discovered that documentation about configuration was not totally accurate.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @gstraymond,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by wsargent** [comment]
Hi @gstraymond -- can you review https://github.com/playframework/playframework/pull/5595 as well and we'll merge them?

**Comment by mkurz** [comment]
Is this fixed by #5595 now?

**Comment by wsargent** [comment]
Yes, this is fixed:

https://github.com/wsargent/playframework/commit/5ee0ff4709c3d44c9678bf00b2649609568fd7ad#diff-9dd456a7b09f0c61b2863b571b575cebR33

**Pull request closed without merging**
