### PR TITLE
Upgrade to Netty 4.1.10

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by marcospereira** [comment]
This fixes part of #7307. See also playframework/netty-reactive-streams#31.

**Comment by benmccann** [comment]
I closed #7307 because 4.1.10 will evict the version pulled in by netty-reactive-streams

**Comment by marcospereira** [comment]
@benmccann actually, it only evicts the same artifacts added. For example, if `netty-transport-native-epoll` was added transitively by netty-reactive-streams, then it will be evicted by the newer version added by Play. But netty-reactive-streams also adds `netty-codec-http` which is not added transitively so we end up with version 4.1.7.Final instead.

In fact, running `sbt "whatDependsOn io.netty netty-codec-http 4.1.7.Final"`* shows:

```
[info] io.netty:netty-codec-http:4.1.7.Final
[info]   +-com.typesafe.netty:netty-reactive-streams-http:2.0.0-M1
[info]     +-com.typesafe.play:play-netty-server_2.12:2.6.0-SNAPSHOT [S]
[info]       +-com.typesafe.play:play-microbenchmark_2.12:2.6.0-SNAPSHOT [S]
```

*see https://github.com/jrudolph/sbt-dependency-graph.

**Comment by benmccann** [comment]
Ah, I didn't realize they were different artifacts. The artifact doesn't show up in the diff. I reopen the issue to track

**Comment by mkurz** [comment]
New release: https://github.com/netty/netty/releases/tag/netty-4.1.11.Final

**Comment by benmccann** [comment]
I don't see 4.1.11. Maybe they unreleased it? It doesn't resolve

**Comment by mkurz** [comment]
@benmccann Yeah, looks like the tag is gone...

**Pull request merged**
