### PR TITLE
Split generated reverse routes

### LINKED ISSUE #4340: Play 2.4 breaks compatibility with ScalaIDE
Even though my project compiles and runs fine, I get following error for reverse routes in the (latest) ScalaIDE - which also causes that autocompletion doesn't work (Also a weird thing is that the error is not showing up in the "Problems" tab of the IDE):

scala-ide-error

I created a [simple test project](https://github.com/mkurz/play-java-eclipse) based on the latest [play-java template](https://github.com/playframework/playframework/tree/master/templates/play-java) with only a [few modification](https://github.com/mkurz/play-java-eclipse/commits/master) to reproduce the issue.

Going further I tried making it a Java-only project (without the Scala Nature) as described [here](https://github.com/playframework/playframework/blob/master/documentation/manual/gettingStarted/IDE.md#setup-sbteclipse) by adding:
```sbt
EclipseKeys.projectFlavor := EclipseProjectFlavor.Java           // Java project. Don't expect Scala IDE
EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)  // Use .class files instead of generated .scala files for views and routes 
EclipseKeys.preTasks := Seq(compile in Compile)                  // Compile the project before generating Eclipse files, so that .class files for views and routes are present
```

This makes it even worse as ScalaIDE now shows following 2 errors (in the "Problems" tab now):
```
controllers.routes cannot be resolved
views.html.index cannot be resolved to a type
```

The same happens when using pure Eclipse as well.

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #4340

The file `target/scala-2.11/routes/main/router/routes_reverseRouting.scala` gets split into `target/scala-2.11/routes/main/<package>/routes_reverseRouting.scala` and `target/scala-2.11/routes/main/<package>/javascript/routes_reverseRouting.scala`.

Let me know what you think, I would love to see ScalaIDE fixed before the next 2.4.0-RC.
Thanks!

### CODE REVIEW

**Comment by mkurz** [comment]
@play-pull-request-validator

**Comment by benmccann** [comment]
@mkurz looks like jenkins is failing on this

>[error] /scratch/jenkins/workspace/play-master-PRs/documentation/manual/working/javaGuide/main/forms/code/javaguide.forms.routes: not found: type javaguide
[error] /scratch/jenkins/workspace/play-master-PRs/documentation/manual/working/scalaGuide/main/forms/code/scalaguide.forms.scalaforms.routes: not found: type scalaguide
[error] /scratch/jenkins/workspace/play-master-PRs/documentation/manual/working/scalaGuide/main/http/code/scalaguide.http.routing.reverse.routes: not found: type scalaguide

**Comment by mkurz** [comment]
Build is green :sunny: 
Review(s) would be welcome, thanks!

**Comment by jroper** [comment]
Actually, I probably shouldn't have merged then, the incremental compilation scripted test needs to be updated.  For example, here's the first set of assertions:

```
> playRoutes

$ exists target/routes/main/a/routes_routing.scala
$ exists target/routes/main/a/routes_reverseRouting.scala
$ exists target/routes/main/controllers/a/routes.java
$ exists target/routes/main/b/routes_routing.scala
$ exists target/routes/main/b/routes_reverseRouting.scala
$ exists target/routes/main/controllers/b/routes.java
```

It should be asserting the existence of all the new reverseRouting files.

Also, there's a bug.  If I have a router, `a.routes`, and a controller, `a.MyController`, the file the reverse router for that controller will be put in will be called `a/routes_reverseRouting.scala`, while the routes prefix will be also put in `a/routes_reverseRouting.scala`, so these two files will overwrite each other.  The routes prefix file needs to be renamed to something like `routes_routesPrefix.scala`.  In fact, the current naming is stupid (it uses that naming due to the way incremental compilation/hashing used to work and because it generated these files into directories shared with other tasks).

Lets call the files:

* forwards router -> `Routes.scala`
* reverse routers -> `ReverseRouters.scala`
* javascript reverse routers -> `JavaScriptReverseRouters.scala`
* routes prefix files -> `RoutesPrefix.scala`

**Comment by jroper** [comment]
I'm doing these changes now (they're quite simple).

**Comment by jroper** [comment]
Done in #4490

**Pull request merged**
