### PR TITLE
Upgrade Scala 2.12.1

### PR DESCRIPTION
**Pull request by wsargent**
Upgrades master to Scala 2.12.1

### CODE REVIEW

**Comment by schmitch** [comment]
Shouldn't we also upgrade interplay?

**Comment by wsargent** [comment]
I don't think we need to upgrade Interplay for point releases -- it should be binary compatible.

**Comment by schmitch** [comment]
well yeah normally we shouldn't however wouldn't our build server still run into the issues of 2.12.0 when we don't upgrade it?

**Comment by wsargent** [comment]
@schmitch I'm going to fix the build server shortly -- probably yet another PR I'm afraid

**Pull request merged**
