### PR TITLE
Fix IOException when using sbt thin client

### LINKED ISSUE #10864: sbt --client causes "java.io.IOException: Stream Closed" error
This was originally reported as https://github.com/sbt/sbt/issues/6515 by @dkovalenko

### Play Version

sbt version: 1.5.2
Play framework version: 2.7.9

### Expected Behavior

1. Take a play project
2. Have sbt server running
3. Try to `run` in `--client` mode: `sbt --client app/run`
4. The app should run

### Actual Behavior

```
sbt --client app/run                                          
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
> app/run
[warn] javaOptions will be ignored, fork is set to false

--- (Running the application, auto-reloading is enabled) ---
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)
[error] java.io.IOException: Stream Closed
[error]         at java.base/java.io.FileInputStream.available0(Native Method)
[error]         at java.base/java.io.FileInputStream.available(FileInputStream.java:330)
[error]         at play.sbt.PlayConsoleInteractionMode$InputStreamWrapper.read(PlayInteractionMode.scala:64)
[error]         at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:245)
[error]         at jline.internal.InputStreamReader.read(InputStreamReader.java:258)
[error]         at jline.internal.InputStreamReader.read(InputStreamReader.java:195)
[error]         at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2180)
[error]         at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2170)
[error]         at play.sbt.PlayConsoleInteractionMode$.waitEOF$1(PlayInteractionMode.scala:99)
[error]         at play.sbt.PlayConsoleInteractionMode$.$anonfun$waitForKey$2(PlayInteractionMode.scala:110)
[error]         at play.sbt.PlayConsoleInteractionMode$.$anonfun$doWithoutEcho$1(PlayInteractionMode.scala:117)
[error]         at play.sbt.PlayConsoleInteractionMode$.$anonfun$doWithoutEcho$1$adapted(PlayInteractionMode.scala:114)
[error]         at play.sbt.PlayConsoleInteractionMode$.withConsoleReader(PlayInteractionMode.scala:93)
[error]         at play.sbt.PlayConsoleInteractionMode$.doWithoutEcho(PlayInteractionMode.scala:114)
[error]         at play.sbt.PlayConsoleInteractionMode$.$anonfun$waitForKey$1(PlayInteractionMode.scala:110)
[error]         at play.sbt.PlayConsoleInteractionMode$.$anonfun$waitForKey$1$adapted(PlayInteractionMode.scala:97)
[error]         at play.sbt.PlayConsoleInteractionMode$.withConsoleReader(PlayInteractionMode.scala:93)
[error]         at play.sbt.PlayConsoleInteractionMode$.waitForKey(PlayInteractionMode.scala:97)
[error]         at play.sbt.PlayConsoleInteractionMode$.waitForCancel(PlayInteractionMode.scala:121)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:121)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last app / Compile / run for the full output
[error] (app / Compile / run) java.io.IOException: Stream Closed
[error] Total time: 4 s, completed 18 May 2021, 12:29:13
```

### Notes

Instead of stdin (`System.in`) that can be reassigned, JLine 2 code hardcodes to `FileDescriptor.in`, and likely Play copied the code from it since it does similar thing here - https://github.com/playframework/playframework/blob/53e55f017f508f0dcdf2a70327bd73153fe87e5e/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala#L84-L87

For sbt 1.4.0 and above, I think the better thing to do is something like https://github.com/sbt/jline2/pull/1/commits/6821546aaeea30df2615fb5d3b4a34b78812da65 where `System.in`, which I think would be forwarded from the sbtn inputs.

### PR DESCRIPTION
**Pull request by gmethvin**
## Fixes

Fixes #10864

## Purpose

Use `System.in` in the interaction mode input stream wrapper rather than `FileDescriptor.in`.

## Background Context

As @eed3si9n suggested on the ticket, we essentially want to do what jline already does in [this commit](https://github.com/sbt/jline2/commit/6821546aaeea30df2615fb5d3b4a34b78812da65), for similar reasons.

## References

Also fixes https://github.com/sbt/sbt/issues/6515.

### CODE REVIEW

**Comment by mkurz** [comment]
@gmethvin You added the `status:needs-backport-2.7` label, however 2.7 is EOL and it's _very_ unlikely there will be further 2.7 releases.

**Comment by gmethvin** [comment]
The bug was originally discovered (recently) on Play 2.7.9, and I work with apps that use 2.7, so I think it would benefit the community to have this fix for 2.7. It's a fairly straightforward fix that doesn't require additional changes to backport to 2.7.

My understanding is that EOL means it's not supported by Lightbend, but the community should still be able to maintain it. I got the impression the Lightbend team wanted to allow community maintainers to handle releases for older versions, but the release tooling just isn't set up. It even looks like we have commits on 2.7.x, so I think we want to release those eventually?

**Comment by dkovalenko** [comment]
Can we merge this?

**Comment by gmethvin** [comment]
@mkurz or another committer has to approve. It seems the only concern was with backporting to 2.7. I do think we should backport it to 2.7.x and eventually release a new version with all the new commits on 2.7.x, but it shouldn't have any bearing on whether this gets merged to master and backported to 2.8.x.

**Review by mkurz — APPROVED** [review]
LGLTM

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Comment by mkurz** [comment]
Another 2.7.x release is not my top priority but if you want to do that, I am happy to help to get it done :wink:

**Comment by gmethvin** [comment]
@Mergifyio backport 2.7.x

**Comment by octonato** [comment]
I would like to share some information regarding releases. 

We don't have the Vegemite machine anymore and we will have to fix the release process. Right now, I'm preparing for releasing Play 2.8.9 from my local machine.

@gmethvin, if you want to release 2.7.x, I think you will have to release it from your machine as well. 

We have a new sonatype profile, `com.typesafe.play`. We will need to associate your sonatype user to this new profile.
See also #11024

**Comment by mkurz** [comment]
@gmethvin I am pretty sure this is causing #11032

**Pull request merged**
