### PR TITLE
Fixes #5772 : Reinstate play.mvc.Results.noContent()

### LINKED ISSUE #5772: Reinstate play.mvc.Results.noContent()
Play 2.5 is missing `play.mvc.Results.noContent()` - this was my mistake, I wrote a script to generate all those methods, but since `noContent()` doesn't need any of the overload for providing a body, when I replaced all the methods with the generated versions, I missed the `noContent` method.  This method should be reinstated - not in the generated part of the file though otherwise it will be accidentally deleted again.

### PR DESCRIPTION
**Pull request by itsbrnrd**

### CODE REVIEW

**Comment by gmethvin** [comment]
@itsbrnrd Can you please add this above the section that's generated?

**Comment by gmethvin** [comment]
@itsbrnrd the code's not compiling since you added the method twice. If you remove the second one and squash your commits this'll be good to merge.

**Comment by gmethvin** [comment]
@itsbrnrd please squash your commits

**Comment by itsbrnrd** [comment]
My bad. It should be good now

**Pull request merged**
