### PR TITLE
Add support for Guice's Scopes.NO_SCOPE

### LINKED ISSUE #10893: Add support for Guice's Scopes.NO_SCOPE
Besides the singleton Scope (which of course is not Guice specific) Guice also offers a [`NO_SCOPE` scope](https://google.github.io/guice/api-docs/5.0.1/javadoc/com/google/inject/Scopes.html#NO_SCOPE):
> This exists only in case a class has been annotated with a scope annotation such as `@Singleton`, and you need to override this to "no scope" in your binding.

So if you have an annotated class like

```java
@Singleton
public class FooImpl implements FooApi { }
```
and you want to remove the singleton scope from it, in Guice you can `bind(...)...in(Scopes.NO_SCOPE)`. That probably makes most sense if you are working with a 3rd party library and are not able to just remove the annotation.

Play's DI agnostic API however does not support that, because it requires the scope to be an annotation:

https://github.com/playframework/playframework/blob/4b60f86ccb45e17814d256853c50fdb803178a15/core/play/src/main/scala/play/api/inject/Binding.scala#L44-L53

So my current idea is to add a `@NoScope` annotation to the `play[.api].inject.guice` namespace and detect if it is used and then just pass `Scopes.NO_SCOPE` to Guice instead here:
https://github.com/playframework/playframework/blob/4b60f86ccb45e17814d256853c50fdb803178a15/core/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala#L383-L389
If possible the annotation shouldn't be allowed to actually be applied on classes since its only usage would be when declaring a module.

### PR DESCRIPTION
**Pull request by arpitbhardwaj**
# Pull Request Checklist

* [X] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [X] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [X] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [X] Have you added copyright headers to new files?
* [X] Have you checked that both Scala and Java APIs are updated?
* [X] Have you updated the documentation for both Scala and Java sections?
* [X] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #10893

## Purpose

What does this PR do?

Add support for Guice's Scopes.NO_SCOPE

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by mkurz** [comment]
@arpitbhardwaj Please run `scalafmtAll` within sbt to fix the formatting, thanks!

**Comment by arpitbhardwaj** [comment]
@mkurz Formatted!

**Comment by mkurz** [comment]
You did revert your commit now. You can try to rebase on top of the main branch.
Assuming you have the `no_scope` branch checked out you can run: `git rebase -i main`, You can then delete the line which reverts your commit.

**Comment by arpitbhardwaj** [comment]
@mkurz Fixed !

**Comment by arpitbhardwaj** [comment]
@mkurz Just a suggestion we can add a short shell script to run all these formatting commands along with test in root level say "precheck.sh". It would be easy for developer to run that script locally before pushing commits.

We can document this as well in contribution guidelines.

Let me know if create an issue to address this suggestion.

**Comment by mkurz** [comment]
@arpitbhardwaj Actually you can run `sbt validateCode` which does check everything for you, see 
https://github.com/playframework/playframework/blob/682f1093693cdddc89bd9bf87ebe929a423b4dc2/build.sbt#L478-L486

**Comment by mkurz** [comment]
Actually yes we could add something like
```sbt
 addCommandAlias( 
   "formatCode", 
   List( 
     "headerCreateAll", 
     "scalafmtSbt", 
     "scalafmtAll", 
     "javafmtAll", 
   ).mkString(";") 
```
to make life easier

**Comment by mkurz** [comment]
@arpitbhardwaj Can you please resolve the conflicts of this pull request? Afterwards I will review, thanks!

**Comment by mkurz** [comment]
@arpitbhardwaj Did you close this PR on purpose?

**Pull request closed without merging**
