### PR TITLE
Introduce sbt-pekko-version-check plugin

### LINKED ISSUE #11986: sbt-pekko-version-check sbt plugin?
Until Play 2.9 we use the [sbt-akka-version-check](https://github.com/johanandren/sbt-akka-version-check) plugin to validate the akka versions [here](https://github.com/playframework/playframework/blob/8395f65a37bd2f66905193378d6a69871e7bd0ea/build.sbt#L517). . Might make sense to fork it for Pekko; the Pekko org itself will not do the fork, see

* https://github.com/apache/incubator-pekko/discussions/671

Not that important currently, but if with more major/minor Pekko versions we might want to introduce such a `sbt-pekko-version-check` plugin.

### PR DESCRIPTION
**Pull request by Philippus**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?

# Helpful things

## Fixes

Fixes #11986

## Purpose

Introduce sbt-pekko-version-check plugin, to make sure versions across Pekko modules are the same in the project.

## Background Context

We had the akka-equivalent of this plugin before.

### CODE REVIEW

**Comment by pjfanning** [comment]
I have a BOM that might be useful. https://github.com/pjfanning/pekko-libraries-bom

**Review by mkurz — APPROVED** [review]
LGTM, thanks for doing this!

**Comment by mkurz** [comment]
@Mergifyio backport 2.9.x

**Comment by mkurz** [comment]
@Mergifyio backport 3.0.x

**Pull request merged**
