### PR TITLE
Clarified the allowedhost blacklist usage in documentation

### PR DESCRIPTION
**Pull request by FuriousTurtle**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?

# Helpful things

## Purpose

I used this feature in a project and I through that the doc had a mistake that needed to be fixed since it was extremely confusing to me

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @FuriousTurtle,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
@Mergifyio backport master

**Comment by mkurz** [comment]
@Mergifyio backport master

**Pull request merged**
