### PR TITLE
Upgrade scala to 2.12.2/2.11.11

### PR DESCRIPTION
**Pull request by mkurz**
Please double check:
```
grep -r '2\.11' .
grep -r '2\.12' .
```

### CODE REVIEW

**Comment by PromanSEW** [comment]
If I update
```scala
scalaVersion := "2.11.11"
```
in my Play 2.5.14 project, it will work perfectly without any changes?

**Comment by mkurz** [comment]
@PromanSEW Yes, that should be the case.

**Comment by mkurz** [comment]
@PromanSEW See https://github.com/scala/scala/releases/tag/v2.11.11:
> As usual for minor releases, Scala 2.11.11 is binary compatible with the whole Scala 2.11 series

**Comment by mkurz** [comment]
@marcospereira I think this will not turn green, see https://github.com/playframework/playframework/issues/6690#issuecomment-295191015
We either have to fix #6690 or set the compiler flag.
Also see the release notes:
https://github.com/scala/scala/releases/tag/v2.12.2
and the PR which causes our build to fail now:
https://github.com/scala/scala/pull/5402

**Comment by mkurz** [comment]
Related #6302

**Comment by marcospereira** [comment]
@mkurz please see #7259.

**Comment by mkurz** [comment]
Thanks Marcos!

**Pull request closed without merging**
