### PR TITLE
Upgrade Guice

### PR DESCRIPTION
**Pull request by mkurz**
Release notes:
https://github.com/google/guice/wiki/Guice42
Adds Java 9 support:
https://github.com/google/guice/issues/1085#event-1497746031

I think we want to backport this?

### CODE REVIEW

**Comment by richdougherty** [comment]
> I think we want to backport this?

How stable do you think the change is?

**Comment by mkurz** [comment]
@richdougherty Seems like we can't backport... There are some compatibility issues like `override` is needed now or Java's Function is used now instead of a Guice buil in one...

**Comment by marcospereira** [comment]
@mkurz it already looks good to me, but maybe we could add a highlight for this update.

**Comment by eximius313** [comment]
So in order to use JDK9, we need to wait for Play 2.7?

**Comment by mkurz** [comment]
@eximius313 No, you can use Guice 4.2 now already. Just put in your `build.sbt`:
```sbt
val guiceVersion = "4.2.0"
val guiceDeps = Seq(
	"com.google.inject" % "guice" % guiceVersion,
	"com.google.inject.extensions" % "guice-assistedinject" % guiceVersion
)

libraryDependencies ++= Seq(
	guice,
	//...
) ++ guiceDeps
```

**Comment by eximius313** [comment]
Thanks @mkurz :)

**Comment by mkurz** [comment]
@marcospereira Done. Added highlights and migration notes.

**Comment by benmccann** [comment]
@mkurz this one needs a rebase now

**Comment by mkurz** [comment]
I will rebase after #8281 has been merged, because there will be another conflict again.

**Comment by mkurz** [comment]
@marcospereira @richdougherty Rebased, green, highlights & migration notes added - ready to merge :stuck_out_tongue_winking_eye:

**Comment by marcospereira** [comment]
Amazing work. Thank you, @mkurz.

**Comment by mkurz** [comment]
Thanks for merging @marcospereira !

**Pull request merged**
