### PR TITLE
Remove 3rd Party Tools

### LINKED ISSUE #11246: Remove 3rd Party Tools page
https://www.playframework.com/documentation/2.8.x/ThirdPartyTools
`documentation/manual/hacking/ThirdPartyTools.md`

After removing travis #11142
We don't use any third party tools AFAIK.

### PR DESCRIPTION
**Pull request by felipebonezi**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #11246 

## Purpose

Remove 3rd party tools because it's obsolete.

### CODE REVIEW

**Review by mkurz — APPROVED** [review]

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Comment by mkurz** [comment]
@felipebonezi Can you provide a backport for the 2.8.x branch? Thanks!

**Comment by felipebonezi** [comment]
> @felipebonezi Can you provide a backport for the 2.8.x branch? Thanks!

Sure but what do I need to do?

Do I just need to remove my merge commits? 
Open another PR from another branch?

I don't know how to do a backport.

**Comment by ihostage** [comment]
If Mergify could't do that automatically, needs to create another PR with the same changes for `2.8.x` branch 😉

**Pull request merged**
