### PR TITLE
Update SettingsLogger.md

### PR DESCRIPTION
**Pull request by falconepl**
Specify path for `logback.xml` file.

### CODE REVIEW

**Comment by cchantep** [comment]
@play-pull-request-validator

**Comment by falconepl** [comment]
I think that there might be some issue with pull request validator again. I've signed CLA... twice.

**Comment by cchantep** [comment]
There is an issue elsewhere:

```
[info] Play-Java-JPA: found 0 potential binary incompatibilities
java.lang.RuntimeException: Play-Test: Binary compatibility check failed!
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.tools.mima.plugin.SbtMima$.reportErrors(SbtMima.scala:64)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$3.apply(MimaPlugin.scala:26)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$3.apply(MimaPlugin.scala:26)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
```

**Comment by marcospereira** [comment]
@cchantep and @falconepl, the build problem is being discussed in #4902.

**Comment by marcospereira** [comment]
@play-pull-request-validator try again.

**Comment by jroper** [comment]
Forward ported to master: 7565bc6

**Pull request merged**
