### PR TITLE
Upgrade javassist

### PR DESCRIPTION
**Pull request by mkurz**
Changes: https://github.com/jboss-javassist/javassist/compare/rel_3_19_0_ga...rel_3_20_0_ga
JIRA: https://issues.jboss.org/browse/JASSIST/fixforversion/12326488/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

### CODE REVIEW

**Comment by jroper** [comment]
Any idea if there are any issues that might impact Play that this release fixes? If there are it may be a good idea to backport.

**Comment by mkurz** [comment]
Could someone then please add the `needs-backport` label?

**Comment by marcospereira** [comment]
@jroper It is unlikely that this will cause an impact on Play since this is a very small releases with just three bug fixes. If there is some impact it will probably be on play-enhancer.

@mkurz I've added the `needs-backport` label and will do a backport as soon as I can.

**Comment by jroper** [comment]
It's not so much whether it will impact Play that I'm worried about, it's more whether Play needs it.

**Comment by marcospereira** [comment]
@jroper I don't think so.

**Pull request merged**
