### PR TITLE
Using Files.size(...) should be safer than file.length()

### PR DESCRIPTION
**Pull request by mkurz**
Have a look at the answers here: https://stackoverflow.com/q/7226588/810109
I think it's better and safer to rely on `Files.size(...)`.

### CODE REVIEW

**Comment by dwijnand** [comment]
Hi @mkurz.  We discussed this ticket today (you might have noticed it's the last one in the 2.7.0 milestone!).

We all agreed that it would be better to use Files.size (for the reasons mentioned in that stackoverflow link) but doing so would require reviewing each usage of File#length to understand how it should behave when using Files.size.  Doing so on a case-by-case basis would be time-consuming and there still would be an element of risk, and while the change is good it isn't resolving any immediate or pressing need; it doesn't resolve any performance or security concerns, nor does it unblock any other issues.  We don't want to delay 2.7.0 any further with an RC10, and putting this straight into 2.7.0 would risk having to hot-fix it with a 2.7.1.

As such we're going to retarget this for 2.8.0.

**Comment by mkurz** [comment]
:+1: It's not important for me at all to get this into 2.7. I was just bumping into this stackoverflow question the other day and thought that it would be good to switch to `Files.size(...)`.
However there is no urgency, this can of course wait until 2.8.

**Comment by dwijnand** [comment]
@mkurz want to rebase (or restart) this change?

**Comment by mkurz** [comment]
@dwijnand Yes, I will asap.

**Comment by mkurz** [comment]
@dwijnand Done, ready for review.

**Pull request merged**
