### PR TITLE
=pfh #7256 fix illegal double push in CSRF handler rewrite

### LINKED ISSUE #7256: Illegal double push in CSRF BodyHandler
Reported by @kryton

```
@ktoso - code is here - https://github.com/kryton/people upload error is in http://localhost/people/admin/import / PersonController.scala
@ktoso full stack trace - https://gist.github.com/kryton/e303f7e504512dcc2cbcdc4105d2e185
```

```

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalArgumentException: requirement failed: Cannot push port (BodyHandler.out(1192987429)) twice]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:257)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:285)
	at ErrorHandler.onServerError(ErrorHandler.scala:43)
	at play.core.server.AkkaHttpServer$$anonfun$11$$anonfun$apply$1.applyOrElse(AkkaHttpServer.scala:198)
	at play.core.server.AkkaHttpServer$$anonfun$11$$anonfun$apply$1.applyOrElse(AkkaHttpServer.scala:197)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
Caused by: java.lang.IllegalArgumentException: requirement failed: Cannot push port (BodyHandler.out(1192987429)) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:508)
	at play.filters.csrf.BodyHandler$$anon$1$$anon$2.onPush(CSRFActions.scala:302)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:401)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
	at akka.stream.impl.
```

### PR DESCRIPTION
**Pull request by ktoso**
Resolves #7256, I have verified on the reporters reproducer however would be good to add a test covering this too I guess

### CODE REVIEW

**Comment by marcospereira** [comment]
@ktoso is it possible to have a test for this fix too?

**Comment by ktoso** [comment]
Yes, I absolutely want to add a test - sorry, I'm having a very chaotic week with moving and things kept distracting me :(

I hope to add a test here today or tomorrow

**Comment by gmethvin** [comment]
I'm going to merge this so we can include in M5, since this is already broken in M4. @ktoso you can submit a PR later to add tests.

**Comment by ktoso** [comment]
Ok will do, thanks

-- 
Konrad Malawski

**Pull request merged**
