### PR TITLE
Improve the getting started documentation

### PR DESCRIPTION
**Pull request by megazord**
Does the following changes to improve the first hour experience of how to use play:

1. Reorder the sections to focus on how to get an app running and how to setup an IDE
2. Explain the difference between full and minimal activator packages
3. Update links to IDE plugins and integrations

This is related to #4179.

### CODE REVIEW

**Comment by megazord** [comment]
This will probably generate a conflict with PR #4226. If you choose to integrate that PR first, just let me know and I will rebase the master to solve the conflict.

**Comment by megazord** [comment]
Looks like that there is also an overlap with PR #4204.

**Comment by megazord** [comment]
I've just rebased this PR with master and solve the conflicts. It is good to be merged.

**Comment by jroper** [comment]
I didn't notice you haven't actioned some of the comments - feel free to submit another PR when you're done.

**Pull request merged**
