### PR TITLE
Update dependencies (minor versions only)

### PR DESCRIPTION
**Pull request by mkurz**
Actually I just wanted to upgrade HikariCP so it gets backported in the `2.6.x` branch but then updated some other dependencies as well :smile: 

Please backport, thanks!

### CODE REVIEW

**Comment by mkurz** [comment]
Fails because twirl isn't published.

**Comment by marcospereira** [comment]
Hey @mkurz,

The problem is not with Twirl itself, but with the fact that you are also updating interplay to 1.3.12 which adds support for sbt 1.0, but there are other changes we need to make in order to update it. Remove the interplay update and the build will probably pass.

**Comment by marcospereira** [comment]
@mkurz green build, but there are some conflicts now.

**Comment by mkurz** [comment]
@marcospereira Updated

**Comment by mkurz** [comment]
@marcospereira I think this can be backported because it's just minor versions upgrades.

**Comment by mkurz** [comment]
Were there any concerns why this wasn't backported before 2.6.6 was tagged?

**Pull request merged**
