### PR TITLE
Update typesafe description in templates

### PR DESCRIPTION
**Pull request by Warry**

### CODE REVIEW

**Comment by pvlugter** [comment]
Do we also want this update in the currently published templates?

**Comment by pvlugter** [comment]
Backported to 2.3.x: bf6465b1fbcb817769062ae1e35ca9d8a4106a13

**Comment by pvlugter** [comment]
@Warry I can't publish the templates as the image doesn't exist currently.

**Comment by Warry** [comment]
The PR has been merged, but the website has been re-build since. I'll make it right.

**Comment by Warry** [comment]
@pvlugter It's live http://typesafe.com/assets/images/activator/logo-typesafe-activator.png

Sorry for the false start.

**Comment by pvlugter** [comment]
Thanks. Templates have been republished.

**Pull request merged**
