### PR TITLE
Update key to generate a new secret

### PR DESCRIPTION
**Pull request by Wlanez**
Updating doc to avoid:

[SystemPlay] $ play-update-secret
[error] Not a valid command: play-update-secret
[error] Not a valid project ID: play-update-secret
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: play-update-secret (similar: playUpdateSecret, playGenerateSecret)
[error] play-update-secret

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @Wlanez,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by jroper** [comment]
Hi @Wlanez, are you not interested in signing the CLA?

**Comment by Wlanez** [comment]
@jroper Yes, it said "Your submission was processed."

**Comment by jroper** [comment]
Oh, I see you've signed it.  I just don't understand why you closed this pull request?  Do you not want us to merge it?

**Comment by Wlanez** [comment]
I wonder how did it get close. 

Yes I would like to merge it, thank you @jroper

**Comment by jroper** [comment]
Forward ported to master: 5e56ea6

**Comment by jroper** [comment]
Thanks!

**Pull request merged**
