### PR TITLE
Mergify: close backport PRs that fail

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Note I'm using `#assignee=0` as the opt-out; in English: if you want to stop Mergify from closing the issue, assign it to yourself (or someone).

**Comment by dwijnand** [comment]
> On each failed backport PR we need to evaluate if it's something that we can ignore or fix.

From my memory, this contradicts what we had agreed which was: "only backport bugfixes and doc fixes, and if the PR fails we just close it".

**Comment by dwijnand** [comment]
Obviously there's going to be exceptions to the rule (for example security fixes) but I'm codifying the general rule here.

**Comment by renatocaval** [comment]
> "only backport bugfixes and doc fixes, and if the PR fails we just close it"

Maybe the wording here is wrong. I understand it as: we don't add extra effort if we judge not necessary.

> Obviously there's going to be exceptions to the rule (for example security fixes) but I'm codifying the general rule here.

How many of the recent failed backports have we just close it? To my memory, we had to fix most, if not all, of them. So, that's not the general rule. The general rule is that those backports must be applied and we have fixed them. If we close them automatically we will add more work on our plate. 

We had recently an important forward porting that was closed and we almost missed it. So we do need to scrutinize it and not simply click the close button or let mergify do it for us.

**Comment by dwijnand** [comment]
> The general rule is that those backports must be applied and we have fixed them.

I believe this isn't what we said originally.

Let's chat about it, but I'm happy to end up accepting your interpretation (and closing this PR).

**Comment by dwijnand** [comment]
> We had recently an important forward porting that was closed and we almost missed it.

Before I forget to mention: I am concerned about forward ports and we should find away to avoid impacting them (in the shortish time I spent on this I couldn't find an easy way).

**Pull request closed without merging**
