### PR TITLE
Split unit tests from integration tests.

### LINKED ISSUE #8703: Split test into test VS IT in travis jobs
Currently the test-scala-* jobs take about 25min:

* test-scala-211 (24 min 37 sec)
* test-scala-212 (24 min 5 sec)
* test-scala-213 (24 min 1 sec)

(example times taken from https://travis-ci.org/playframework/playframework/builds/440507343?utm_source=github_status&utm_medium=notification)

About 800sec of that time is spent on `Play-Integration-tests/test:executeTests`. We could split the `test-scala-` jobs in two: 

1. compile + test
2. compile + it:test

NOTE: currently `Play-Integration-tests` doesn't use `src/it/{scala,java}` but it'd be a reasonable task to refactor (rename folder, setup `It` on the `build.sbt`).

### PR DESCRIPTION
**Pull request by dwijnand**
# Helpful things

## Fixes

Fixes #8703

### CODE REVIEW

**Comment by mkurz** [comment]
Would it make sense to group the integration tests into their own stage and only run that stage after the "normal" test stage passes?

**Comment by dwijnand** [comment]
I'm not sure.  I thought about it, but I thought it might be better to get started on running the integration tests asap rather than serially after the unit tests.

**Comment by dwijnand** [comment]
Rebased due to the merge conflict (changed file in one of the integration tests, that I'm moving here).

The fix I went with is by restricting the bash scripts.

Also, I tweaked the Travis CI cache so we don't keep downloading the launcher.

**Comment by marcospereira** [comment]
Hum, the test failure is probably related to the alpn not being added to `IntegrationTest` scope:

https://github.com/sbt/sbt-javaagent/blob/04371d4abf2c11db3c649c63ad71d7e6cb53fa2f/src/main/scala/com/lightbend/sbt/javaagent/JavaAgent.scala#L66-L67

Not sure about it though since I didn't have time do to a proper investigation/testing.

**Comment by dwijnand** [comment]
Sounds very plausible.  Will fix, probably tomorrow.

**Comment by dwijnand** [comment]
How did this break `EndpointIntegrationSpecificationSpec`??

```
[error]     x with Akka HTTP HTTP/2 (encrypted) (343 ms)
[error]      http/1.1 != h2 (EndpointIntegrationSpecificationSpec.scala:23)
```

**Comment by dwijnand** [comment]
Oh, that's related to jetty-alpn-agent #8829.  So I must not be doing something right.

**Comment by marcospereira** [comment]
Are you sure the agent is being added correctly for the integration tests when forking? At least this is my suspicion.

**Comment by dwijnand** [comment]
Nope, just kind of tried to throw it together.  I'll have to come back and figure it out.

**Comment by dwijnand** [comment]
Finally!

**Comment by ignasi35** [comment]
Should we backport to `2.7.x`?

**Comment by dwijnand** [comment]
Feel free to.

**Comment by renatocaval** [comment]
Backported to 2.7.x (b60c5f6a19c711f4f82472183718a7a4d92b55bf)

**Pull request merged**
