### PR TITLE
Typo in localhost address in ForwardedHeaderHandler

### PR DESCRIPTION
**Pull request by cezary-draus**

### CODE REVIEW

**Comment by richdougherty** [comment]
Weird build failure, rebuilding now…

```
[error] (Play-Netty-Utils/*:mimaFindBinaryIssues) java.lang.ArrayIndexOutOfBoundsException: 1561
```

**Comment by richdougherty** [comment]
Thanks! I'm going to add a test to make sure this works in the PR I'm working on (#5306).

**Comment by richdougherty** [comment]
@cezary-draus - would you mind signing the contributor agreement?

http://www.typesafe.com/contribute/cla

**Comment by cezary-draus** [comment]
Of course but during the weekend

2015-11-26 23:02 GMT+01:00 Rich Dougherty <notifications@github.com>:

> @cezary-draus <https://github.com/cezary-draus> - would you mind signing
> the contributor agreement?
>
> http://www.typesafe.com/contribute/cla
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playframework/playframework/pull/5308#issuecomment-159998210>
> .
>



-- 
Pozdrawiam,
Cezary Draus

**Comment by richdougherty** [comment]
No problem!

**Pull request merged**
