### PR TITLE
Update ScalaRouting.md sird to be uppercase

### PR DESCRIPTION
**Pull request by valentinvstoyanov**
Fix ScalaRouting.md by making SIRD(String Interpolating Routing DSL) uppercase.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @valentinvstoyanov,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by valentinvstoyanov** [comment]
I signed the CLA.

**Comment by renatocaval** [comment]
needs forward port to master as this was done on branch 2.6.x

**Comment by marcospereira** [comment]
Forward port to 2.7.x: 0b4090b56186fc9a7ecf196363742f4b93cabb74

Forward port to master: d6c1408af5ed3bd179e858bceecd7dc3cdccdd67

**Pull request merged**
