### PR TITLE
[2.5.x] Fix url encoded query parameter in WSRequest

### PR DESCRIPTION
**Pull request by wsargent**
Fixes https://github.com/playframework/playframework/issues/7444

### CODE REVIEW

**Comment by mkurz** [comment]
The `codeChecks` test just won't turn green, it recurrently fails with an `OutOfMemoryError` exception. I restarted the job like 5 times.
On my machine the test passes, so maybe we can merge?

**Comment by marcospereira** [comment]
@mkurz I think we are good to merge this.

On the bright side, it is good to have separated jobs like the build for 2.5.x, so we can view better exactly what breaks and retry just that. Maybe we should go back to this for 2.6.x too.

WDYT?

**Comment by mkurz** [comment]
If it easily possible why not? We just have to make sure that we continue to test for Scala 2.11 and 2.12.

**Comment by marcospereira** [comment]
@mkurz good point. Let me give it a try then. :-)

**Comment by wsargent** [comment]
@marcospereira do look at the git history -- there's been a bunch of tweaking on the build scripts.

**Comment by jefffangji** [comment]
This fix makes query string in url string be encoded, which is different from the previous behavior.
It worked before that I encoded the query string by myself, and pass it into ws.url(). But after the fix, I find my query string is double encoded.
Such as:
http://example.org?bar=%7b%7d is doubled encoded to http://example.org?bar=%257b%257d 

Is it expected?

**Pull request merged**
