### PR TITLE
Upgrade Netty

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by hepin1989** [comment]
not right,you need to rewrite the netty-server implement and the netty-http-pipelining to using netty 4:P

**Comment by benmccann** [comment]
I don't understand why this compiles correctly on my machine, but not on Jenkins. Do you know how I can reproduce the error locally?

**Comment by hepin1989** [comment]
that maybe cause the netty-http-pipeline dependes on netty.
that can't be current,maybe we need change the netty in netty-http-pipeline as provided

**Comment by benmccann** [comment]
Going back to the first PR. Hopefully we can get that one working first and then maybe I'll come back to this one

**Pull request closed without merging**
