### PR TITLE
Upgrade to AHC 2.0.0-RC16

### PR DESCRIPTION
**Pull request by gmethvin**

### CODE REVIEW

**Comment by marcospereira** [comment]
@gmethvin could you please also update the documentation (JavaWS and ScalaWS pages) links?

**Comment by wsargent** [comment]
fixes https://github.com/playframework/playframework/issues/5922

**Comment by wsargent** [comment]
:+1:

**Comment by marcospereira** [comment]
Backport to 2.5.x: 64776c6c5a033c8882b59ae99d5cc8ae498158e9

**Pull request merged**
