### PR TITLE
Update deployment documentation

### PR DESCRIPTION
**Pull request by jehrhardt**
I accidentally deleted this pull request. So here is it again.

It took me some time figure out how to make my Play application work well in my environment, since not everything has been documented. So I added the parts I was missing.

### CODE REVIEW

**Comment by marcospereira** [comment]
@jehrhardt,

Could you please squash the two commits? We do this to make it easier to backport or track the changes.

**Comment by jehrhardt** [comment]
✓

**Comment by jehrhardt** [comment]
Why did the Travis build fail?

**Comment by cchantep** [comment]
Please rebase against updated master, which includes the required Travis config.

**Comment by cchantep** [comment]
Sorry the config is still pending

**Comment by jehrhardt** [comment]
@cchantep This branch is already rebased against master.

**Comment by jroper** [comment]
@jehrhardt our cloudbees CI server vanished a few days ago, rather than fixing that, we've decided to switch to travis, but the process is taking a while.

**Comment by jehrhardt** [comment]
Is there anything, I can do? Or do we just have to wait until the non-working Travis build allows you to merge theses changes on the documentation?

**Comment by marcospereira** [comment]
@jehrhardt thanks for your patience.

**Pull request merged**
