### PR TITLE
Scala 2.13.4

### PR DESCRIPTION
**Pull request by mkurz**
https://github.com/scala/scala/releases/tag/v2.13.4

### CODE REVIEW

**Review by ignasi35 — APPROVED** [review]

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Comment by jtjeferreira** [comment]
@mkurz dont we need to upgrade the versions in https://github.com/playframework/interplay/blob/master/src/main/scala/interplay/Versions.scala instead?

**Comment by mkurz** [comment]
Yes they need to be updated as well.

**Comment by mkurz** [comment]
@jtjeferreira See 
https://github.com/playframework/interplay/pull/146
and
https://github.com/playframework/interplay/pull/147
and #10718

**Pull request merged**
