### PR TITLE
JDNI renamed to correct abbreviation JNDI (Java Naming and Directory Interface)

### PR DESCRIPTION
**Pull request by tumakha**
JDNI renamed to correct abbreviation JNDI (Java Naming and Directory Interface)

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

### CODE REVIEW

**Review by mkurz — APPROVED** [review]
Thank you very much!

**Comment by tumakha** [comment]
Small text change isn't reason of build failure:
```
$ jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version
Error: could not open `/home/travis/.jabba/jdk/adopt@1.11.0-11/lib/jvm.cfg'
```
https://app.travis-ci.com/github/playframework/playframework/jobs/558550956

**Comment by mkurz** [comment]
Yes it isn't. We are about to move to GitHub actions anyway, also away from jabba which sometimes fails unexpected.

**Comment by mkurz** [comment]
It's just a type in the docs, we can still merge without Travis agreeing.

**Pull request merged**
