### PR TITLE
Update dependencies before Release Candidate 4

### PR DESCRIPTION
**Pull request by marcospereira**
## Purpose

The main purpose is to update:

- twirl to version 1.4.0-RC4
- play-ws to version 2.0.0-RC2
- play-json 2.7.0-RC2

Other libraries updated too.

### CODE REVIEW

**Comment by marcospereira** [comment]
Blocked by https://github.com/playframework/twirl/pull/196.

**Comment by mkurz** [comment]
Hey Marcos I am working on one last pull request right now (which fixes a bug in query parsing IMHO). In case you want to release RC-4 today - would it be ok to postpone until tomorrow? I should be finished by then.

**Comment by marcospereira** [comment]
Hey @mkurz the release is happening today, in a couple of hours. Is there anything you want me to take a look before doing it?

**Comment by mkurz** [comment]
Probably yes... Working on it. How many hours? Can you give me a deadline in UTC (7:06 PM right now) so I can estimate if I will make it?

**Comment by marcospereira** [comment]
Well, I was going to start the release right now. But I can wait for a couple of hours if that is what you need.

**Comment by mkurz** [comment]
That would be nice, I will try my best to come up with a pull request within the next 2-3 hours? Thanks a lot!

**Comment by mkurz** [comment]
BTW: This should then really be my last PR for 2.7

**Comment by mkurz** [comment]
@marcospereira This PR needs to be applied on master as well.

**Pull request merged**
