### PR TITLE
[2.6.x]: Make it clear where to add sbt-eclipse settings

### PR DESCRIPTION
**Pull request by ManognaMutyala**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things
More comprehensible

## Purpose
Beginners cannot understand in which files the commands has to be inserted.

What does this PR do?
Clear understanding of setting up  ide in eclipse with the certain changes that has to be made in the plugin and build files.

### CODE REVIEW

**Comment by marcospereira** [comment]
Hi @ManognaMutyala.

Is this somehow related to #7919? Asking because this is a different change and also you are targeting `2.6.x` branch again. If these PRs aren't related to each other, could you please rewrite your commit message to better explain the change?

Thanks!

**Comment by ManognaMutyala** [comment]
Actually they are not related but I felt those are similar changes which are supposed to be made in order to execute in eclipse ide.Thanks for your feedback @marcospereira .I would definitely remove the reference of PR.

**Comment by marcospereira** [comment]
Thank you for explaining, @ManognaMutyala.

The reference between the PRs is not a problem, but we should try to have more descriptive commit message so that it would be easier to navigate the commit history later. :-)

**Comment by marcospereira** [comment]
Hi @ManognaMutyala, are you still interested in this PR?

I think the only thing to improve here is to have a more descriptive commit message. Besides that, it looks good to me.

Thanks for contributing.

**Comment by marcospereira** [comment]
I understand now that this was created using Github interface, so the less descriptive commit message. :-)

So I decide to edit the commit message when merging.

@ManognaMutyala although Github is nice enough to automatically create a commit message, you can edit it if you want/need.

Thank you for contributing. Hope to see you around again.

**Pull request merged**
