### PR TITLE
Make 429 header plural; add more Java headers

### PR DESCRIPTION
**Pull request by richdougherty**

### CODE REVIEW

**Comment by jroper** [comment]
Do you want this backported to 2.4?

**Comment by mkurz** [comment]
+1 for backporting

**Comment by marcospereira** [comment]
If we decide to backport, should the deprecated message/version be changed to 2.4?

**Comment by richdougherty** [comment]
Yes, the deprecation message should be changed. I used deprecation version of 3.0 because I wasn't sure about backporting.

**Comment by richdougherty** [comment]
@marcospereira, I talked to @jroper and we think this fix isn't important enough to backport to 2.4. We want to cut a 2.4.0 release soon so we want to restrict the 2.4 changes to bug fixes and documentation changes.

**Pull request merged**
