### PR TITLE
Add support for Java 8 datatypes in JSON serialization/deserialization

### PR DESCRIPTION
**Pull request by benmccann**
Already added the jar in another commit, but forgot to register the module

### CODE REVIEW

**Comment by jroper** [comment]
Perhaps you should add a test to ensure it works.

**Comment by benmccann** [comment]
Looks like @cchantep added some tests for Java 8 support for the Scala stuff https://github.com/playframework/playframework/commit/5a2bf4937014d033de7aeb16f6a124548fa0e4d9

I don't see any Java tests though, so I'm not quite sure where I'd add the test?

**Comment by cchantep** [comment]
https://github.com/playframework/playframework/tree/master/framework/src/play-json/src/test/scala/play/libs ?

**Comment by benmccann** [comment]
Glad I added a test because I misread the docs and had accidentally only added support for Java 8 `Optional` originally. Now it actually works with Java 8 date types as well as `Optional`

**Comment by benmccann** [comment]
Thanks for the pointer to the test @cchantep

**Pull request merged**
