### PR TITLE
Upgrade netty

### PR DESCRIPTION
**Pull request by mkurz**
Changes: https://github.com/netty/netty/compare/netty-3.10.3.Final...netty-3.10.4.Final
Also contains a fix from @jroper

### CODE REVIEW

**Comment by marcospereira** [comment]
Nice! It will fix #4432.

**Comment by mkurz** [comment]
@play-pull-request-validator

**Comment by marcospereira** [comment]
Backport here: 53ec18e

**Comment by jroper** [comment]
Actually, #4432 is already fixed in Play 2.4 since we don't use Netty's cookie decoder, but our own copy of it, it's 2.3.9 that is impacted by #4432.

**Comment by OlegYch** [comment]
i tried to use 3.4.10.Final with 2.3.9 and got this:
```
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.getHeader(Ljava/lang/String;)Ljava/lang/String;
        at play.core.server.websocket.WebSocketHandshake$.getWebSocketLocation(WebSocketHandshake.scala:33)
        at play.core.server.websocket.WebSocketHandshake$.shake(WebSocketHandshake.scala:36)
```

**Comment by OlegYch** [comment]
3.10.4 that is

**Pull request merged**
