### PR TITLE
Prefer sonatypeBundleRelease

### PR DESCRIPTION
**Pull request by ignasi35**
See https://github.com/lagom/lagom/pull/2261

> Following recommendations on https://github.com/xerial/sbt-sonatype/issues/89#issuecomment-529203859, this PR opts into using `sonatypeBundleRelease`.

### CODE REVIEW

**Comment by ignasi35** [comment]
This is blocked on https://github.com/playframework/interplay/pull/89.

We'll need a release of `interplay` to unblock this.

**Comment by dwijnand** [comment]
Or you could just update the version of sbt-sonatype here without having to do the interplay release merry-go-round.

**Comment by marcospereira** [comment]
> Or you could just update the version of sbt-sonatype here without having to do the interplay release merry-go-round.

Better to update it on interplay since scala-steward will then update it on all the other projects (twirl, play-ws, play-json, etc). So every one of them may use `sonatypeBundleRelease` as well.

**Comment by ignasi35** [comment]
> Better to update it on interplay since scala-steward...

GO @scala-steward !!! 🥇

**Pull request merged**
