### PR TITLE
Fix grammar error

### PR DESCRIPTION
**Pull request by dmcquillan314**
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @dmcquillan314,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by gmethvin** [comment]
@dmcquillan314 This is actually subjective. If you pronounce it "sequel" it should be "a" whereas if you pronounce it "ess cue ell" it should be "an". I'm not sure if we have a standard in Play...

**Comment by dmcquillan314** [comment]
@gmethvin I hadn't thought about it from a pronunciation perspective, you bring up a good point.  I think it does look a little weird when it comes to looking at the text.  I guess the question is it more weird to read it as "a SQL" or "an SQL" even though I pronounce it "ess cue ell", but yet after reading this: http://blog.apastyle.org/apastyle/2012/04/using-a-or-an-with-acronyms-and-abbreviations.html I think "an SQL" does actually make more since if the majority of people read is as "ess cue ell"

**Comment by gmethvin** [comment]
I've heard both pronunciations about equally, but my experience is heavily biased toward native English-speaking developers. I suspect pronouncing the letters individually is more common amongst non-native speakers.

In general, I think we should favor assuming an initialism if there is not one pronunciation that's significantly more popular than the others.

**Pull request closed without merging**
