### PR TITLE
Docs Improvement : Forms, nested values #9976

### PR DESCRIPTION
**Pull request by gavinbaumanis**
# Pull Request Checklist
I have previously signed the CLA.
(I am not a Java developer so have just created this PR for the Scala guide ONLY.)

## Fixes
Add an extra nested element to the documentation to clearly show how multiple nested values are defined, specifically for how to correctly use apply() / unapply().

## Purpose
Add Clarity for multiple nested form elements.

## References
Issue #9976

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by renatocaval** [comment]
@gavinbaumanis, build is broken due to a format issue. Please, check build logs to see how to fix it. 

The CLA needs signing as well.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by mkurz** [comment]
CLA is signed by user `gavinbaumanis`:
https://www.lightbend.com/contribute/cla/check/gavinbaumanis
However, it looks like the author of the commits (the email address) is not the same as the author of the pull request? Having a quick look at [the patch](https://patch-diff.githubusercontent.com/raw/playframework/playframework/pull/10006.patch) reveals a ecpr.com.au email address is used. On the [public profile](https://github.com/gavinbaumanis) there is a gmail adress. Maybe that's because CLA validator doesn't turn green here?

**Comment by gavinbaumanis** [comment]
I have updated my git email address for my Playframework fork/ repository : gavinbaumanis@gmail.com
(Not sure how I can fix it it : after the fact, so the build works?)

Also I have emailed my scanned signed CLA. (I hadn't previously done this)

Lastly the build says it failed because the page I edited was not formatted correctly.
I have run `sbt scalafmtAll scalafmtSbt` : but no files were changed - so I am unsure about what is still needed to allow the build to be successful.

**Comment by renatocaval** [comment]
Closing and reopening to trigger CLA

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by renatocaval** [comment]
@gavinbaumanis, you can do run it insdide the documentation folder

```shell
cd documentation
sbt scalafmtAll scalafmtSbt
```

**Comment by renatocaval** [comment]
@gavinbaumanis, the commits are associated with the domain ecpr.com.au. That's why GitHub is not 'recognising' you. Either you add your ecpr.com.au email to GitHub or you re-send the commits using your gmail account. 

You have to edit your ` ~/.gitconfig` file and add your gmail. Then you have to change the commits.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by gavinbaumanis** [comment]
Is there a way that I can run the tests on Travis, locally?

**Pull request merged**
