### PR TITLE
Migrate CSRFActions, WebSocketClient & RangeResults to GraphStage

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by marcospereira** [comment]
Hi @naferx, 

Build is broken: https://travis-ci.org/playframework/playframework/jobs/145365388#L6554

**Comment by naferx** [comment]
Thanks! @marcospereira 

I'm looking for some free time to fix it.

**Comment by wsargent** [comment]
Hi @naferx are you still interested in this?

**Comment by naferx** [comment]
Sorry, I have to leave it. Currently, I have a lot of work this week

**Comment by naferx** [comment]
I had forgotten this PR

**Comment by wsargent** [comment]
Closing for rebased version https://github.com/playframework/playframework/pull/7094

**Pull request closed without merging**
