### PR TITLE
Always send Content-Disposition with filename in sendFile

### LINKED ISSUE #4936: Inline file attachments using sendFile() have no way of specifying file names
See [this line](https://github.com/playframework/playframework/blob/5d7adcbc246323310f6c9a9ef26555902e0ba3dc/framework/src/play/src/main/scala/play/api/mvc/Results.scala#L415) of code. Currently it is:
```scala
if (inline) Map.empty else Map(CONTENT_DISPOSITION -> ("attachment; filename=\"" + name + "\""))
```

I think it should be:
```scala
Map(CONTENT_DISPOSITION -> s"""${if (inline) "inline" else "attachment"};filename="$name"""")
```

Otherwise there is no way to specify `inline=true` and still have an appropriate name for the file if the browser fails to render the file inline and treats it as an attachment.

Reference: http://stackoverflow.com/questions/1395151/content-dispositionwhat-are-the-differences-between-inline-and-attachment

### PR DESCRIPTION
**Pull request by gmethvin**
Fixes #4936

### CODE REVIEW

**Comment by jroper** [comment]
Build failure due to master broken.

**Comment by jroper** [comment]
@play-pull-request-validator master is fixed now.

**Comment by jroper** [comment]
Hmm... I've never seen that test fail before.... @play-pull-request-validator

**Comment by marcospereira** [comment]
@gmethvin could you please rebase with master and solve the conflicts?

**Comment by gmethvin** [comment]
@marcospereira updated

**Pull request merged**
