### PR TITLE
Changed two references of SecurityHeaders

### PR DESCRIPTION
**Pull request by Guisanpea**
This is a documentation minor edit focusing on providing fresh and relevant references to documentation topics. 

The referenced information on X-XSS-Protection and X-Content-Type-Options were two blog post of Microsoft with a very particular explanation on the client part of Internet Explorer, the XSS Filter post also explained other topics which for me was disorienting.

IMHO Refering to the Mozilla documentation, like it is being done on X-Frame-Options, is a better option because it is more concise and also because Mozilla Docs is a very good reference on web topics.

# Pull Request Checklist

* [X] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [X] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [X] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [X] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [X] Have you added copyright headers to new files?
* [X] Have you checked that both Scala and Java APIs are updated?
* [X] Have you updated the documentation for both Scala and Java sections?
* [X] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Not a fix but changed a blog post reference for a documentation reference.

## Purpose

Helping future readers of the play documentation on understanding underlying topics of it.

## Background Context

I was reading the documentation and I found that the resources linked were not really clarifying, so I thought of replacing it with Mozilla Documentation on the topic

## References

None

# From the editor

I will be pleased if I have feedback about this pull request because this is my first contribution to this project and one of the first to open source :smile:

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Guisanpea,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by Guisanpea** [comment]
@marcospereira I think combining both is good, didn't think it as an option so yes, combining both is good, a reference content if you just want a quick view and a blog post for detailed information.

Should I change the pull request?

**Comment by marcospereira** [comment]
> Should I change the pull request?

Hi @Guisanpea, sorry for the long time to give feedback. Yeah, I think that you should update the pull request to keep both. :-)

**Comment by marcospereira** [comment]
Hey @Guisanpea,

Do you still have time to look at this PR? Let me know if you need some help here.

Best.

**Comment by lightbend-cla-validator** [comment]
Hi @mergify[bot],

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Pull request merged**
