### PR TITLE
Providing a test to show POST request is fired with an empty body

### PR DESCRIPTION
**Pull request by fg-devs**
Issue #8632

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

The issue that was reported in the issue is actually fixed already. It just seems that there was a test missing, which is now included in this PR.

## References

#8632

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by mkurz** [comment]
CLA signed: https://www.lightbend.com/contribute/cla/check/fg-devs

**Comment by scyhhe** [comment]
Also signed by me (committer): https://www.lightbend.com/contribute/cla/check/scyhhe

**Comment by mkurz** [comment]
Actually your test also runs without problems when using Play 2.6.13... So your test does not prove that #8632 got fixed.
Actually I can not even reproduce #8632 even with Play 2.6.13 (which is the Play version used in the original discussion)

**Comment by mkurz** [comment]
Actually you are writing a PlayJava test. The bug report is about PlayScala though.
Anyway, I can not even reproduce the issue in PlayScala with Play 2.6.13... using following code:
```scala
      val request = FakeRequest(POST, "/uri").withHeaders("<myheader>" -> "headervalue")
      val result = Helpers.route(fakeApplication, request)
```
The original code of the bug report does not even work...

**Comment by mkurz** [comment]
Whatever, I guess we can still merge this one, its just another test - and keep #8632 open meanwhile.

**Comment by scyhhe** [comment]
Yes, it’s a PlayJava test, I also couldn’t reproduce it in Scala with the same code. I could also write a Scala test for the sake of semantics.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by mkurz** [comment]
@scyhhe You did not push your commit in this pull with your `scyhhe` GitHu account, that's why `typesafe-cla-validator` is complaining.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by scyhhe** [comment]
> @scyhhe You did not push your commit in this pull with your `scyhhe` GitHub account, that's why `typesafe-cla-validator` is complaining.

Correct, I forgot to switch my local git config... anyway to undo this? GitHub won't let me link the commit to myself.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
Hi @scyhhe,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://localhost:9000/contribute/cla](http://localhost:9000/contribute/cla)

**Pull request merged**
