### PR TITLE
Removed file Tag in logger configuration

### PR DESCRIPTION
**Pull request by ToBeHH**
# Pull Request Checklist
- [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
- [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
- [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
- [x] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
- [x] Have you added copyright headers to new files?
- [x] Have you checked that both Scala and Java APIs are updated?
- [x] Have you updated the documentation for both Scala and Java sections?
- [x] Have you added tests for any changed functionality?
# Helpful things
## Fixes

Fixes #xxxx
## Purpose

What does this PR do?
## Background Context

Why did you take this approach?
## References

Are there any relevant issues / PRs / mailing lists discussions?

If a rollingPolicy is given, a <file> tag must not be given. Otherwise only the file tag is used and the rollingPolicy is ignored

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @ToBeHH,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by wsargent** [comment]
Hi @ToBeHH -- can you provide a reference for this?

**Comment by marcospereira** [comment]
@wsargent it is actually optional, according to [logback docs](http://logback.qos.ch/manual/appenders.html#tbrpFileNamePattern):

> Note that the file property in RollingFileAppender (the parent of TimeBasedRollingPolicy) can be either set or omitted. By setting the file property of the containing FileAppender, you can decouple the location of the active log file and the location of the archived log files. The current logs will be always targeted at the file specified by the file property. It follows that the name of the currently active log file will not change over time. However, if you choose to omit the file property, then the active file will be computed anew for each period based on the value of fileNamePattern. The examples below should clarify this point.

I don't see the need to remove the `file` tag and maybe we can just add a reference to logback docs.

**Comment by ToBeHH** [comment]
The reference is my actual server configuration. I tried with the file tag, but having the file tag present, the rolling just does not happen. There are some stackoverflow post with exactly that solution, e.g. http://stackoverflow.com/questions/18791154/logback-rollingfileappender-not-working

If the logback docs say, the file property is optional, they might refer to a different version.

**Comment by marcospereira** [comment]
This was linked at Stackoverflow:

http://logback.qos.ch/codes.html#renamingError

Basically, it says:

> File rename operations during rollover can be avoided altogether by omitting the file property in RollingFileAppender.

I think that is ok to remove this line and add references to logback docs.

**Comment by marcospereira** [comment]
Closed in favor of #6983.

@ToBeHH keep in mind that #6983 is targeting master branch, which uses an updated version of Logback.

**Pull request closed without merging**
