### PR TITLE
Update specs2

### PR DESCRIPTION
**Pull request by gmethvin**

### CODE REVIEW

**Comment by mkurz** [comment]
It would be interesting what is wrong with this update.... Any clues so far @marcospereira @gmethvin ?

**Comment by gmethvin** [comment]
I suspect something changed in specs2 that's triggering a deadlock in our tests.

**Comment by cchantep** [comment]
Update to 3.9.4 by other PR

**Comment by marcospereira** [comment]
Closed in favor of #7639.

**Pull request closed without merging**
