### PR TITLE
Upgrade templates to SBT 0.13.7

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by jroper** [comment]
Any particular reason for this?  Note that the version of sbt that users use is completely up to them (specified in `build.properties`), and Play's sbt should (and in my experience does) work with 0.13.6 and 0.13.7.

**Comment by benmccann** [comment]
I wanted to remove a workaround for a bug that was present in SBT versions before SBT 0.13.6. See https://github.com/playframework/playframework/issues/1889  I figured we should use SBT 0.13.6 internally if we're recommending folks to use it. I've had lots of problems running tests all around with SBT 0.13.5

**Comment by jroper** [comment]
I'd still prefer that we build against 0.13.5 and run our scripted tests against 0.13.5, we want to ensure that we are compatible with 0.13.5, if we build against 0.13.6, then we may accidentally use APIs that are new.

**Comment by benmccann** [comment]
Hmm, okay. How do we set the cutoff for which versions of SBT we want to be compatible with?

**Comment by jroper** [comment]
I'd say we should set it as low as possible, unless there's a pressing need to upgrade.

**Comment by benmccann** [comment]
The reason I was suggesting this is that I've seen numerous hard-to-track-down test errors being reported for the past couple of years that were fixed in 0.13.6. See https://github.com/sbt/sbt/pull/1450

I'll let you decide if that warrants the 0.13.6 upgrade or not. If not, then feel free to close this

**Comment by nateww** [comment]
Due to JUnit issues, we've been hard-coding the use of SBT 13.6 for all our Play 2.3 apps, so I'd prefer if this was the default.

**Comment by jroper** [comment]
Since users explicitly select the version of sbt that they use (by setting it in the `project/build.properties` file, the version of sbt that we compile against and test with is not that relevant.  Us upgrading here actually has no impact on users.  I think we should update the templates to use SBT 0.13.7, giving users the latest there when they create new projects, but I think we can stay on 0.13.5 in our tests, to ensure compatibility.

**Comment by jroper** [comment]
The sbt version that the templates use by the way is set in https://github.com/playframework/playframework/blob/master/templates/build.sbt.

**Comment by benmccann** [comment]
@jroper thanks, that sounds reasonable. i didn't know where that was coming from. i've updated it now

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Pull request merged**
