### PR TITLE
Update code on tutorial pages

### LINKED ISSUE #9942: Hello World page does not work
### Play Version

2.8.x

### API

nop

### Operating System

linux

### JDK

java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

### Library Dependencies

nop 

### Expected Behavior

1. copy and paste examples in https://www.playframework.com/documentation/2.8.x/ImplementingHelloWorld should work

### Actual Behavior

comes out the error:
```
Compilation error
not enough arguments for method apply: (title: String, assetsFinder: controllers.AssetsFinder)(content: play.twirl.api.Html)play.twirl.api.HtmlFormat.Appendable in object main.
Unspecified value parameter assetsFinder.

In /users/a/play-samples-play-scala-starter-example/app/views/hello.scala.html:1
1@main("hello") { 
2    <section id="top">
3        <div class="wrapper">
4            <h1>Hello</h1>
5        </div>
```

### PR DESCRIPTION
**Pull request by ignasi35**
Implements `option 2.` from https://github.com/playframework/playframework/issues/9942#issuecomment-572522407

The Java and the Scala starter samples are out of sync so the tutorial only made sense for the Java implementation.

Fixes #9942 

Related to https://github.com/playframework/play-samples/pull/83

### CODE REVIEW

**Comment by renatocaval** [comment]
@ignasi35, this one needs formatting

**Comment by ignasi35** [comment]
I've blocked the merge. it doesn't make sense to merge or even review this until https://github.com/playframework/play-samples/pull/83 is merged.

**Comment by ignasi35** [comment]
(formatted code, and squashed commits)

**Comment by ignasi35** [comment]
https://github.com/playframework/play-samples/pull/83 was finally merged.

**Comment by mkurz** [comment]
@Mergifyio backport main

**Pull request merged**
