### PR TITLE
Improve Java app loader/provider

### PR DESCRIPTION
**Pull request by marcospereira**
## Purpose

While this API is internal and wouldn’t be used by users creating application, it could be useful to people integrating with Play.

It will helps us to move from this code:

```java
public class Foo {
    public static void main(String[] args) {
        play.Environment env = play.Environment.simple();
        play.ApplicationLoader.Context context = play.ApplicationLoader.create(env);

        play.api.ApplicationLoader loader = play.api.ApplicationLoader$.MODULE$.apply(context.underlying());

        play.api.Application application = loader.load(context.underlying());
        play.core.ApplicationProvider applicationProvider = play.core.ApplicationProvider$.MODULE$.apply(application);

        scala.Option<play.api.mvc.Result> resultOption = applicationProvider.handleWebCommand(someKindOfRequestTranslation());
        
        if (resultOption.isDefined()) {
            // application was able to handle the result
            play.api.mvc.Result result = resultOption.get();
        } else {
            // no handler was found
            play.api.mvc.Result result = play.api.mvc.Results$.MODULE$.NotFound();
        }
    }

    private static play.api.mvc.RequestHeader someKindOfRequestTranslation() {
        return ...;
    }
}
```

To this new version using only Java APIs:

```java
public class Foo {
    public static void main(String[] args) {
        play.Environment env = play.Environment.simple();
        play.ApplicationLoader.Context context = play.ApplicationLoader.create(env);

        play.ApplicationLoader loader = play.ApplicationLoader.apply(context);

        play.Application application = loader.load(context);
        play.server.ApplicationProvider applicationProvider = new play.server.ApplicationProvider(application);

        play.mvc.Result result = applicationProvider
                .handleWebCommand(someKindOfRequestTranslation())
                .orElse(play.mvc.Results.notFound());
    }

    // This would translate from AWS Lambda request to a Play request.
    private static play.mvc.Http.RequestHeader someKindOfRequestTranslation() {
        return ...;
    }
}
```

## References

See discussion here: https://twitter.com/sapessi/status/859450726551924736

### CODE REVIEW

**Comment by mkurz** [comment]
+1 Anything still missing here @marcospereira @wsargent ?

**Comment by marcospereira** [comment]
@mkurz we just have this package inconsistency highlighted by @wsargent.

Not sure if move these classes to the correct packages is something we still can do, considering that we are very close to release 2.6.0 and APIs are freezing.

But I think that the changes here are ok.


@wsargent WDYT?

**Comment by wsargent** [comment]
@marcospereira agreed, too late in the game now.  We should add an issue for 2.7.x though.

**Comment by marcospereira** [comment]
@wsargent see #7446.

**Pull request merged**
