### PR TITLE
[Backport 2.5.x] Disallow users to send a message-body and Content-Length header field for 1xx, 204 and 304 responses (#6261)

### PR DESCRIPTION
**Pull request by monkey-mas**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Purpose

Backport of https://github.com/playframework/playframework/pull/6261

## References
Please have a look at https://github.com/playframework/playframework/pull/6261

### CODE REVIEW

**Comment by schmitch** [comment]
Fails with:

[error]  * method SwitchingProtocols()play.api.mvc.Result in trait play.api.mvc.Results does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("play.api.mvc.Results.SwitchingProtocols")
[error]  * synthetic method play$api$mvc$Results$_setter_$SwitchingProtocols_=(play.api.mvc.Result)Unit in trait play.api.mvc.Results does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("play.api.mvc.Results.play$api$mvc$Results$_setter_$SwitchingProtocols_=")
[error]  * synthetic method play$api$mvc$Results$_setter_$Continue_=(play.api.mvc.Result)Unit in trait play.api.mvc.Results does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("play.api.mvc.Results.play$api$mvc$Results$_setter_$Continue_=")
[error]  * method Continue()play.api.mvc.Result in trait play.api.mvc.Results does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("play.api.mvc.Results.Continue")

**Comment by gmethvin** [comment]
We might just want to remove the extra methods in Results to avoid the binary compatibility issue.

**Comment by monkey-mas** [comment]
Thanks for your feedback and review! :)

P.S.
> adding methods to a trait makes it bin incompatible. But I guess that's fine for that?

Actually mima is correct. We can't add a `val` to trait when maintaining binary-compatibility (but can add it to an abstract class. a little bit confusing Scala code translation to JVM code. ;) )

**Comment by schmitch** [comment]
Actually I found it not that hard after watching https://www.youtube.com/watch?v=K3sHQrhpvUM&index=15&list=PLX8CzqL3ArzUY6rQAQTwI_jKvqJxrRrP_ retronym has a great talk explaining it (and why it probably won't be "way" better in 2.12)

**Comment by monkey-mas** [comment]
Haha, glad to hear you've already self-solved it! :) Thanks for the link, will watch it from now :D

**Pull request merged**
