### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
I don't understand why it's saying Travis failed. If I click through then it looks like it passed

**Comment by mkurz** [comment]
Its green now here on GitHub.

**Comment by mkurz** [comment]
Should we update (some of) the dependencies in the 2.6.x branch as well?

**Comment by marcospereira** [comment]
@mkurz yes, some. We should avoid Jackson since it is a more large upgrade.

**Comment by mkurz** [comment]
There is also a new minor release of jackson, `2.8.10`.

**Pull request merged**
