### PR TITLE
Do not include sbteclipse by default

### PR DESCRIPTION
**Pull request by benmccann**
This matches what we do with IDEA and allows sbteclipse to be upgraded independently of Play

The instructions I added here will only work after sbteclipse 4.0.0 is released, which should happen in the next few days. The code for sbteclipse 4.0.0 is ready and I just need someone to cut the release, which I filed an issue to track: https://github.com/typesafehub/sbteclipse/issues/258

### CODE REVIEW

**Comment by jroper** [comment]
I think this is the right approach, however I'd like to confirm with @havocp as to whether this may cause problems for Activator.

One reason why we removed the IntelliJ support is that IntelliJ now natively allows importing sbt projects, no sbt plugin required, so the experience for end users is essentially unaffected (in fact, it's improved, since there's no `gen-idea` step).  This isn't the case for Eclipse.  We should consider whether we should include `sbteclipse` in the default Play templates.

**Comment by havocp** [comment]
Pretty sure Activator still adds a .sbt file itself with the eclipse plugin, so it can eclipsify any project. Ben if you want to test it's on the Code tab in a drop down menu. We could also upgrade the plugin activator adds, may run into issues with the fat zip due to changed transitive deps, but we can try it.

**Comment by benmccann** [comment]
Looks like Activator is using three different versions of Eclipse right now. Hopefully it can standardize on a newer one

./project/Dependencies.scala:  val eclipseVersion = "2.5.0"
./project/Dependencies.scala:  val eclipseSbt13Plugin     =  Defaults.sbtPluginExtra("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.2.0", "0.13", "2.10")
./project/project/eclipse.sbt:addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")
./project/eclipse.sbt:addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")

**Comment by benmccann** [comment]
FYI, sbteclipse 4.0.0-RC0 is out now. The auto-imports seem messed up though. Hopefully someone can help me with that. https://github.com/typesafehub/sbteclipse/issues/262

**Pull request merged**
