### PR TITLE
fill  the original tempty template

### PR DESCRIPTION
**Pull request by trydofor**
new template compiled with https://github.com/playframework/playframework/blob/2.4.x/documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala

and tested by browser at https://github.com/moilioncircle/playframework-2.4.x-scala/blob/master/app/controllers/c4/S1ScalaForms.scala

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @trydofor,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by cchantep** [comment]
Thanks @trydofor . Please squash the commits in a single one.

**Comment by trydofor** [comment]
@cchantep  when i pass the ` jenkins-pr-validator — Merged build finished.`, i will push new request in single one

**Comment by cchantep** [comment]
Not a new request, please squash the commits of *this* PR.

**Comment by marcospereira** [comment]
LGTM. @trydofor could you please rebase against our master and squash the two commits here?

Thanks. :-)

**Comment by trydofor** [comment]
@marcospereira  sorry, i get something bad, there are 2 commits  2522284 & c4c0491. 
I do some research, but i'm not sure that i can do it right, please help me out .

**Comment by marcospereira** [comment]
Looks like there were some problem with your rebase, since it generated new hashes to commits that are already in our master. Here is what I usually do:

```bash
# Add playframework repository as a remote
git remote add upstream git@github.com:playframework/playframework.git

# Pull changes from playframework remote into my local master
git checkout master
git pull --rebase upstream master

# Just to keep your remote master updated
git push origin master 

# Create a branch to my changes 
git checkout -b improve-scala-guide

# change the code...

#  Commit and publish changes to my remote branch
git commit -am 'Improve examples in scala guide'
git push origin improve-scala-guide --force
```

After that, I just go to https://github.com/playframework/playframework/ and Github does its magic and asks me if I want to submit a pull request to my new pushed branch. :-)

**Comment by trydofor** [comment]
@marcospereira thank you , i learned so much :)  after the following step, the PR waw closed, can i make a new PR? or what should i do?

``` bash
# to get a fresh copy of my repository, since my local is mad
git clone https://github.com/trydofor/playframework.git

# rebase as you help
git remote add upstream git@github.com:playframework/playframework.git
git checkout master
git pull --rebase upstream master

# still had something i can not manange
git status
  On branch master
  Your branch and 'origin/master' have diverged,
   and have 39 and 19 different commits each, respectively.
    (use "git pull" to merge the remote branch into yours)

# then, i reset my repository and want to make new commit
git reset --hard 1a0c328a3afece6a460842dcc357cfe46f0ef529
git pull --rebase upstream master
git push origin master --force

# copy my files to this reset-repository 
git commit -a -m "fill the original empty template with nested-repeat element"
git push origin master
```
i refresh this page, and the PR is closed by me :(

though i read the whole `git-scm.com/book` and search `stackoverflow`,
there are more things to learn.

**Comment by marcospereira** [comment]
@trydofor thanks!

**Comment by trydofor** [comment]
@ALL it's happy to work with you, thanks you.

**Pull request merged**
