### PR TITLE
Upgrade to Akka HTTP 1.0-M4

### PR DESCRIPTION
**Pull request by richdougherty**
A few code changes were needed because of Akka API changes.

### CODE REVIEW

**Comment by benmccann** [comment]
@play-pull-request-validator try again to get past flakiness

>[error] p.c.s.n.NettyResultStreamer$ - Error while sending response.
java.lang.Exception: null
	at play.it.libs.WSSpec$$anonfun$3$$anonfun$apply$82$$anonfun$apply$83$$anonfun$apply$84.apply(WSSpec.scala:159) ~[test-classes/:na]
	at play.it.libs.WSSpec$$anonfun$3$$anonfun$apply$82$$anonfun$apply$83$$anonfun$apply$84.apply(WSSpec.scala:157) ~[test-classes/:na]
	at play.api.libs.iteratee.Enumerator$$anon$12$$anonfun$apply$24.apply(Enumerator.scala:396) ~[classes/:na]
	at play.api.libs.iteratee.Enumerator$$anon$12$$anonfun$apply$24.apply(Enumerator.scala:396) ~[classes/:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]

**Comment by benmccann** [comment]
@play-pull-request-validator try again

>[error] p.c.s.n.NettyResultStreamer$ - Error while sending response.
java.lang.Exception: null
	at play.it.libs.WSSpec$$anonfun$3$$anonfun$apply$82$$anonfun$apply$83$$anonfun$apply$84.apply(WSSpec.scala:159) ~[test-classes/:na]
	at play.it.libs.WSSpec$$anonfun$3$$anonfun$apply$82$$anonfun$apply$83$$anonfun$apply$84.apply(WSSpec.scala:157) ~[test-classes/:na]
	at play.api.libs.iteratee.Enumerator$$anon$12$$anonfun$apply$24.apply(Enumerator.scala:396) ~[classes/:na]
	at play.api.libs.iteratee.Enumerator$$anon$12$$anonfun$apply$24.apply(Enumerator.scala:396) ~[classes/:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]

**Comment by benmccann** [comment]
@richdougherty maybe this really is broken? it seemed unrelated but keeps failing in the same manner?

**Comment by richdougherty** [comment]
@benmccann, I think those errors are OK. They're logged during a test that checks error handling. It would be nicer if we didn't display the errors at all. Anyway, in this case I'm pretty sure the build failed due to a timeout in the scripted tests. I'll investigate further and see if I can get it working.

```
[info] ---- AKKA HTTP SERVER SCRIPTED TESTS
[info]
[info] Loading project definition from /scratch/jenkins/workspace/play-master-PRs/framework/project/project
[info] Loading project definition from /scratch/jenkins/workspace/play-master-PRs/framework/project
[info] Set current project to Root (in build file:/scratch/jenkins/workspace/play-master-PRs/framework/)
[info] Packaging /scratch/jenkins/workspace/play-master-PRs/framework/src/play-akka-http-server/target/scala-2.10/play-akka-http-server-experimental_2.10-2.4-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Wrote /scratch/jenkins/workspace/play-master-PRs/framework/src/play-akka-http-server/target/scala-2.10/play-akka-http-server-experimental_2.10-2.4-SNAPSHOT.pom
[info] :: delivering :: com.typesafe.play#play-akka-http-server-experimental_2.10;2.4-SNAPSHOT :: 2.4-SNAPSHOT :: integration :: Sun Mar 01 22:22:39 EST 2015
[info] 	delivering ivy file to /scratch/jenkins/workspace/play-master-PRs/framework/src/play-akka-http-server/target/scala-2.10/ivy-2.4-SNAPSHOT.xml
[info] Packaging /scratch/jenkins/workspace/play-master-PRs/framework/src/play-akka-http-server/target/scala-2.10/play-akka-http-server-experimental_2.10-2.4-SNAPSHOT.jar ...
[info] Done packaging.
[info] 	published play-akka-http-server-experimental_2.10 to /home/jenkins/.ivy2/local/com.typesafe.play/play-akka-http-server-experimental_2.10/2.4-SNAPSHOT/poms/play-akka-http-server-experimental_2.10.pom
[info] 	published play-akka-http-server-experimental_2.10 to /home/jenkins/.ivy2/local/com.typesafe.play/play-akka-http-server-experimental_2.10/2.4-SNAPSHOT/jars/play-akka-http-server-experimental_2.10.jar
[info] 	published play-akka-http-server-experimental_2.10 to /home/jenkins/.ivy2/local/com.typesafe.play/play-akka-http-server-experimental_2.10/2.4-SNAPSHOT/srcs/play-akka-http-server-experimental_2.10-sources.jar
[info] 	published ivy to /home/jenkins/.ivy2/local/com.typesafe.play/play-akka-http-server-experimental_2.10/2.4-SNAPSHOT/ivys/ivy.xml
Running akka-http / play-akka-http-plugin
Build timed out (after 76 minutes). Marking the build as aborted.
```

**Comment by richdougherty** [comment]
Sorry, that code was seriously broken!

I wasn't even running Akka HTTP tests properly. The Akka HTTP tests were running using Netty; they'd broken during the DI test changes. So the Akka HTTP upgrade wasn't tested and didn't work at all. Luckily the scripted tests picked up the problem. (BTW I've fixed up the scripted tests so they shouldn't hang any more if they don't get a response from the server.)

**Comment by richdougherty** [comment]
The Play-WS subproject is [failing with security algorithm errors](https://playframework2.ci.cloudbees.com/job/play-master-PRs/3946/consoleFull). These tests work locally for me. I wonder what's going on? @wsargent, do you have any suggestions?
```
[error]    NoSuchAlgorithmException: : unrecognized algorithm name: SHA256WithRSA  (AlgorithmId.java:407)
[error] sun.security.x509.AlgorithmId.get(AlgorithmId.java:407)
[error] sun.security.x509.X509CertImpl.sign(X509CertImpl.java:564)
[error] sun.security.x509.X509CertImpl.sign(X509CertImpl.java:528)
[error] play.api.libs.ws.ssl.CertificateGenerator$.generateCertificate(CertificateGenerator.scala:84)
[error] play.api.libs.ws.ssl.CertificateGenerator$.generateRSAWithSHA256(CertificateGenerator.scala:35)
[error] play.api.libs.ws.ssl.AlgorithmCheckerSpec$$anonfun$1$$anonfun$apply$4.apply(AlgorithmCheckerSpec.scala:32)
[error] play.api.libs.ws.ssl.AlgorithmCheckerSpec$$anonfun$1$$anonfun$apply$4.apply(AlgorithmCheckerSpec.scala:27)
```

**Comment by jroper** [comment]
That's the second time I've seen that. @play-pull-request-validator try again.

**Comment by benmccann** [comment]
The tests passed now

**Comment by richdougherty** [comment]
Great. I'm OK for this PR to be merged now.

**Pull request merged**
