### PR TITLE
Upgrade sbt-rjs in templates

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by mkurz** [comment]
@benmccann Tests fail (I did restart them twice already)

**Comment by marcospereira** [comment]
Was version 1.0.8 released to some public repository?

**Comment by benmccann** [comment]
@huntc said he published it https://github.com/sbt/sbt-rjs/issues/64

looks like others have reported it missing too though https://github.com/sbt/sbt-rjs/issues/65

**Comment by huntc** [comment]
1.0.8 appears to be published: https://bintray.com/sbt-web/sbt-plugin-releases/sbt-rjs/1.0.8/view#files/com.typesafe.sbt/sbt-rjs/scala_2.10/sbt_0.13/1.0.8/jars

**Comment by huntc** [comment]
It is here: https://bintray.com/sbt-web/sbt-plugin-releases/sbt-jshint/1.0.4/view

However it looks as though it requires linking to the main sbt plugins repo. I shall do that.

**Comment by huntc** [comment]
The 1.0.8 problem should now be addressed. Apologies for any inconvenience caused.

**Pull request merged**
