### PR TITLE
Update framework/src/play/src/main/java/play/mvc/Controller.java

### PR DESCRIPTION
**Pull request by kentcdodds**
Just a spelling update (fix) for the javadoc of public static String session(String key) :)

### CODE REVIEW

**Comment by Niler851** [comment]
Great things started here :)

**Comment by kentcdodds** [comment]
:smile: they certainly did @Niler851 :D

**Comment by richdougherty** [comment]
@kentcdodds: have some :cake:.

**Comment by VikasHanumegowda** [comment]
Wow...a thank you note after almost 3 years........NICE:-D

**Comment by Adimvicky** [comment]
Wow. I'm heavily inspired by this PR and it's comment thread.

**Comment by TheCoderFish** [comment]
I got my first PR accepted today as well !!!

**Comment by rohitkrishna094** [comment]
Kentcdodds must thank the person who actually made that spelling mistake without which he wouldn't be making so many open source contributions these days. :)

**Comment by junibrosas** [comment]
Hi @kentcdodds, your blog got me here. Inspiring.

**Comment by sara1si** [comment]
> Hi @kentcdodds, your blog got me here. Inspiring.

same here

**Comment by gim224** [comment]
awesome!

**Comment by jannomeister** [comment]
hi @kentcdodds , thank you for writing that blog <3

**Comment by geeqib23** [comment]
This gives me a good feeling!

**Comment by ad99526** [comment]
Would be a nostalgic feeling, your blog got me here

**Comment by Poonam-raj** [comment]
Your blog and this PR makes me feel like contributing to Open Source isn't actually as impossible to get into as it feels at first, thank you!

**Comment by Henry409** [comment]
Thanks Kent, landed here from your blogpost. For some reason I thought contributing to Open Source was something waaaay different and have penciled in a plan to be ready in 6 months. LOL. After only a little research, I'm sure even I could have figured out "value" was spelled wrong. Haha. What a great spring board, yet again you start a ripple that effects change in others. Inspiring.

**Comment by giri-madhan** [comment]
Can someone please link the blog post from Kent that everyone is talking about here? Thank you!

**Comment by kentcdodds** [comment]
Here's the blog post: https://kentcdodds.com/blog/2010s-decade-in-review

**Comment by jirawat97224** [comment]
J

**Comment by sajwan05** [comment]
Wow so here things started for Kent. Very Inspiring.

**Pull request merged**
