### PR TITLE
Java forms bind `multipart/form-data` file uploads

### PR DESCRIPTION
**Pull request by mkurz**
Just have a look at the notes I added to the 2.7 release highlights.
Now a Java form also mimics an html multipart-form :wink: 

We could now add validators for uploaded files (like `@MinFileSize`, `@AllowedContenttypes`, etc.). Nice, I like that. No more validation of file uploads in the controller...

BTW: I uncovered a spring-beans bug which also effects previous Play versions. However it doesn't hold back this pull request (this pull request didn't cause the bug, it exists since a long time). (I will fix the bug in spring).

This pull request is/should be backwards compatible and no problem to include in the next Play 2.7 RC.

### CODE REVIEW

**Comment by mkurz** [comment]
Build will turn green when finished (only Java 11 tests currently left) :+1: 
@marcospereira Looking forward to your feedback so we get this shipped with the next RC, thanks!

**Comment by mkurz** [comment]
Closed/re-opened because there were problems getting the build status from Travis...

**Comment by mkurz** [comment]
Thanks for reviewing @marcospereira. Added the docs, please have a look again, thank you very much!

**Comment by eximius313** [comment]
@mkurz could you link to the bug in Spring here?

**Comment by mkurz** [comment]
@eximius313 I don't think there is an open bug report in the Spring project yet. I will open one and provide a fix for it to Spring as soon as I have more time (maybe this week...)

**Comment by renatocaval** [comment]
Backported to 2.7.x (e81c6652cda8f72e42cad5fd30d1e708f45611c6)

**Comment by eximius313** [comment]
@mkurz If you just open this bug report, we will see what people from Spring say about it. Maybe it's already known, maybe it's "feature not a bug" - who knows ;)

**Comment by mkurz** [comment]
@eximius313 If you are still interested: Here is the fix for Play: #9692 and here is the upstream fix for spring: https://github.com/spring-projects/spring-framework/pull/21855

**Pull request merged**
