### PR TITLE
sbt 1.4.0-RC2

### PR DESCRIPTION
**Pull request by mkurz**
Just testing: http://eed3si9n.com/sbt-1.4.0-beta

### CODE REVIEW

**Comment by mkurz** [comment]
The build breaks, however I don't have time to look into it...

**Comment by mkurz** [comment]
Maybe @eed3si9n can have a look?

**Comment by eed3si9n** [comment]
It looks like `project/Docs.scala` needs to be updated (https://api.travis-ci.com/v3/job/375339364/log.txt):

```
[0J[error] ${BASE}/project/Docs.scala:186:37: overloaded method value create with alternatives:
[0J[error]   (x$1: xsbti.compile.ClassFileManager,x$2: Boolean)xsbti.compile.IncToolOptions <and>
[0J[error]   (x$1: java.util.Optional[xsbti.compile.ClassFileManager],x$2: Boolean)xsbti.compile.IncToolOptions
[0J[error]  cannot be applied to (java.util.Optional[Nothing], Boolean)
[0J[error]     val incToolOpt = IncToolOptions.create(Optional.empty(), false)
[0J[error]                                     ^
[0J[error] ${BASE}/project/Docs.scala:190:16: not enough arguments for method run: (sources: List[xsbti.VirtualFile], classpath: List[xsbti.VirtualFile], converter: xsbti.FileConverter, outputDirectory: java.nio.file.Path, options: List[String], incToolOptions: xsbti.compile.IncToolOptions, log: sbt.util.Logger, reporter: xsbti.Reporter)Unit.
[0J[error] Unspecified value parameter reporter.
[0J[error]     javadoc.run(sources, classpath, outputDir, options, incToolOpt, log, reporter)
[0J[error]                ^
[0J[error] two errors found
```

**Comment by mkurz** [comment]
See here: https://github.com/sbt/zinc/issues/927

**Pull request closed without merging**
