### PR TITLE
[2.6.x]: Add support to sbt 1.0 (#7830)

### PR DESCRIPTION
**Pull request by marcospereira**
Backports #7830 to 2.6.x branch.

### CODE REVIEW

**Comment by djx314** [comment]
It seems that play 2.6.6 can't use sbt 1.0.0 due to some sbt dependencies still not found. Are there any package not pushing? Or play 2.6.6 still not support sbt 1.0.0?

**Comment by marcospereira** [comment]
@djx314 maybe it is some other plugin?

Which dependencies are not resolving? Could you post the error message here?

Thanks.

**Comment by djx314** [comment]
```
[info] Updating {file:/E:/pro/workspace/kunlun/project/}kunlun-build...
[warn]  module not found: com.typesafe.play#sbt-plugin;2.6.6
[warn] ==== local: tried
[warn]   C:\Users\Administrator\.ivy2\local\com.typesafe.play\sbt-plugin\scala_2
.12\sbt_1.0\\2.6.6\ivys\ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Administrator\.sbt\preloaded\com.typesafe.play\sbt-plugin\2.6.
6\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Administrator/.sbt/preloaded/com/typesafe/play/sbt-plugi
n_2.12_1.0/2.6.6/sbt-plugin-2.6.6.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/sbt-plugin_2.12_1.0/2.
6.6/sbt-plugin-2.6.6.pom
[warn] ==== sbt-maven-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/play/sb
t-plugin_2.12_1.0/2.6.6/sbt-plugin-2.6.6.pom
[warn] ==== sbt-maven-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/play/s
bt-plugin_2.12_1.0/2.6.6/sbt-plugin-2.6.6.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-p
lugin/2.6.6/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.play/sbt
-plugin/2.6.6/ivys/ivy.xml
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.play#sbt-plugin;2.6.6: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that th
ese dependencies exist with the requested attributes.
[warn]          com.typesafe.play:sbt-plugin:2.6.6 (scalaVersion=2.12, sbtVersio
n=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.play:sbt-plugin:2.6.6 (scalaVersion=2.12, sbtVersio
n=1.0) (E:\pro\workspace\kunlun\project\plugins.sbt#L2-3)
[warn]            +- default:kunlun-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVe
rsion=1.0)
```
@marcospereira It's the output by windows8 x64

**Comment by ekosutopo** [comment]
Commit

**Comment by ekosutopo** [comment]
Memilihnya

**Comment by djx314** [comment]
@marcospereira Now it's fine, Perhaps I didn't clean all the repox proxy config in sbt.

**Pull request merged**
