### PR TITLE
Change to Actor system usage

### PR DESCRIPTION
**Pull request by NoriakiHoriuchi**
"Akka" is no longer needed, so use ActorSystem

https://www.playframework.com/documentation/2.4.x/Migration24#Scala

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @NoriakiHoriuchi,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by jroper** [comment]
Hi @NoriakiHoriuchi, the build failed because your change broke the tests - and the reason that is is that you've created a new Actor system just to instantiate the dispatcher, which is bad, it leaks threads.  You should use Play's actor system to instantiate the dispatcher - and the simplest way to get to Play's actor system statically as is required in this context is using `Akka.system`.

What probably would be best to do is to show how to bind an execution context to a particular name in Guice, and then inject that named actor system as an implicit parameter into components.

**Comment by NoriakiHoriuchi** [comment]
Oh, I see.  I will try it.  Thanks!

**Comment by NoriakiHoriuchi** [comment]
I tried it, but still got errors below...

When I remove "implicit" modifier of the myExecutionContext, it seems to work correctly.

```
play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class utils.Contexts$]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at Global$.onError(Global.scala:11) [anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.6.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.6.jar:na]
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class utils.Contexts$
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:498) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at scala.Option.map(Option.scala:146) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        ... 6 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Could not initialize class utils.Contexts$
        at services.aws.S3Service$$anonfun$upload$1.apply(S3Service.scala:130) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at services.aws.S3Service$$anonfun$upload$1.apply(S3Service.scala:121) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at services.aws.S3Service.upload(S3Service.scala:121) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at services.aws.S3Service.uploadItemImage(S3Service.scala:98) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at controllers.api.client.ItemImagesController$$anonfun$upload$1$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8$$anonfun$apply$9.apply(ItemImagesController.scala:61) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at controllers.api.client.ItemImagesController$$anonfun$upload$1$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8$$anonfun$apply$9.apply(ItemImagesController.scala:58) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at scala.Option.map(Option.scala:146) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at controllers.api.client.ItemImagesController$$anonfun$upload$1$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(ItemImagesController.scala:58) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at controllers.api.client.ItemImagesController$$anonfun$upload$1$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(ItemImagesController.scala:57) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at scala.Option.map(Option.scala:146) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at controllers.api.client.ItemImagesController$$anonfun$upload$1$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7.apply(ItemImagesController.scala:57) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at controllers.api.client.ItemImagesController$$anonfun$upload$1$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7.apply(ItemImagesController.scala:56) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at helpers.ApplicationActions$$anonfun$AuthAction$1$$anonfun$apply$2$$anonfun$apply$3.apply(ApplicationActions.scala:101) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at helpers.ApplicationActions$$anonfun$AuthAction$1$$anonfun$apply$2$$anonfun$apply$3.apply(ApplicationActions.scala:90) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at helpers.ApplicationActions$$anonfun$ApplicationAction$1$$anonfun$apply$1.apply(ApplicationActions.scala:68) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at helpers.ApplicationActions$$anonfun$ApplicationAction$1$$anonfun$apply$1.apply(ApplicationActions.scala:45) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at helpers.ApplicationActions$$anonfun$DispatchAction$1$$anonfun$apply$9.apply(ApplicationActions.scala:168) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at helpers.ApplicationActions$$anonfun$DispatchAction$1$$anonfun$apply$9.apply(ApplicationActions.scala:167) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at scala.Option.fold(Option.scala:158) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at helpers.ApplicationActions$$anonfun$DispatchAction$1.apply(ApplicationActions.scala:172) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at helpers.ApplicationActions$$anonfun$DispatchAction$1.apply(ApplicationActions.scala:140) ~[anonproject.anonproject-1.0-SNAPSHOT-sans-externalized.jar:na]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        ... 22 common frames omitted
```

```scala Contexts.scala
package utils

import play.api.Play.current
import play.api.libs.concurrent.Akka
import scala.concurrent.ExecutionContext

object Contexts {
  implicit val myExecutionContext: ExecutionContext = Akka.system.dispatchers.lookup("akka.actor.s3_service_dispatcher")
}
```

**Comment by benmccann** [comment]
I'm going to close this PR to help clean out the queue since it isn't mergable. Please feel free to ask questions on the mailing list and submit a new PR if you have something working

**Pull request closed without merging**
