### PR TITLE
413 responses now call HttpErrorHandler.onClientError

### PR DESCRIPTION
**Pull request by mkurz**
Fix for #4704

### CODE REVIEW

**Comment by richdougherty** [comment]
LGTM :+1:

**Comment by mkurz** [comment]
@richdougherty No, this won't compile yet, wait for Jenkins, you will see.

**Comment by mkurz** [comment]
@richdougherty Can you help me out how to ideally fix this:

```
[error] /scratch/jenkins/workspace/play-master-PRs/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala:319: type mismatch;
[error]  found   : scala.concurrent.Future[play.api.mvc.Result]
[error]  required: play.api.mvc.Result
[error]         .flatMap(Iteratee.eofOrElse(LazyHttpErrorHandler.onClientError(request, REQUEST_ENTITY_TOO_LARGE)))
[error]                                                                       ^
[error] /scratch/jenkins/workspace/play-master-PRs/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala:359: type mismatch;
[error]  found   : scala.concurrent.Future[play.api.mvc.Result]
[error]  required: play.api.mvc.Result
[error]         ).flatMap(Iteratee.eofOrElse(LazyHttpErrorHandler.onClientError(request, REQUEST_ENTITY_TOO_LARGE)))
[error]                                                                        ^
[error] /scratch/jenkins/workspace/play-master-PRs/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala:675: type mismatch;
[error]  found   : Object
[error]  required: play.api.mvc.Result
[error]           case Left(tooLarge) => Left(tooLarge)
[error]                                       ^
[error] /scratch/jenkins/workspace/play-master-PRs/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala:750: type mismatch;
[error]  found   : scala.concurrent.Future[play.api.mvc.Result]
[error]  required: play.api.mvc.Result
[error]           ).flatMap(Iteratee.eofOrElse(LazyHttpErrorHandler.onClientError(request, REQUEST_ENTITY_TOO_LARGE)))
[error]                                                            
```

**Comment by jroper** [comment]
A bit of code hygiene, there's already a `createBadResult` method in `ContentTypes.scala`, could we use that instead?  And modify that to use the `LazyHttpErrorHandler`?

As for the compile errors, `onClientError` returns a future, and you've replaced the non future `Results.RequestEntityTooLarge` with that.  You need to create a flattened iteratee with this future.  To avoid code duplication, you could do this:

```
private def createBadResultIteratee(msg: String, statusCode: Int = BAD_REQUEST): RequestHeader => Iteratee[Array[Byte], Result] = { request =>
  Iteratee.flatten(createBadResult(msg, statusCode)(request).map(r => Done(r)))
}
```

**Comment by mkurz** [comment]
Still fails, @jroper @richdougherty...

**Comment by richdougherty** [comment]
Here's how to get it working:

https://github.com/playframework/playframework/compare/playframework:master...richdougherty:iteratee-eof-demo

Basically I specialised `Iteratee.eofOrElse` into a method called `checkForEof`. `checkForEof` uses an `Array[Byte]` and a `Future[Result]` instead of an `E` and a `B`. Unfortunately we couldn't use `Iteratee.eofOrElse` because it expects a `B` value, not a `Future[B]` value.

I also fixed an existing bug in `createBadResult` where the status wasn't used if the application wasn't available. See the `new Results.Status(statusCode)(msg)` change in my example.

**Comment by mkurz** [comment]
@richdougherty Thanks. However in your demo shouldn't the `createBadResult` method use `LazyHttpErrorHandler`?

**Comment by richdougherty** [comment]
You're right. Ignore my version of `createBadResult`!

**Comment by mkurz** [comment]
Is the `createBadResult` ok that way?

**Comment by richdougherty** [comment]
Your version using `LazyHttpErrorHandler.onClientError(request, statusCode, msg)` is the correct implementation.

**Comment by mkurz** [comment]
The tests are failing - I looked into the CI logs but I don't really now why my changes cause these errors. Any idea?

**Comment by richdougherty** [comment]
Those failures don't seem related.
```
[error]   x return 404 for files that don't exist
[error]    '500' is not equal to '404' (AssetsSpec.scala:186)
[info] 
[info]   + serve a versioned asset
[info]   return not found when the path is a directory
[error]     x if the directory is on the file system
[error]      '500' is not equal to '404' (AssetsSpec.scala:205)
[info] 
[error]     x if the directory is a jar entry
[error]      '500' is not equal to '404' (AssetsSpec.scala:212)
```
@play-pull-request-validator

**Comment by richdougherty** [comment]
Do these tests work for you on your machine?

**Comment by mkurz** [comment]
No, I get the same errors.

**Comment by richdougherty** [comment]
A couple of ideas for debugging:
* Investigate the cause of the 500 error. It's probably an exception being thrown somewhere.
* Try reverting your changes and check it's not a problem with _master_.

**Comment by mkurz** [comment]
I will look into it later today.

**Comment by mkurz** [comment]
@richdougherty The problem is:
```
InstantiationException: play.api.http.HttpErrorHandler
```

**Comment by mkurz** [comment]
The tests fail because of the change from
```scala
object LazyHttpErrorHandler extends HttpErrorHandler {
  private def ErrorHandler = Play.maybeApplication.fold[HttpErrorHandler](DefaultHttpErrorHandler)(_.errorHandler)
```
to
```scala
object LazyHttpErrorHandler extends HttpErrorHandler {
  private val errorHandlerCache = Application.instanceCache[HttpErrorHandler]
  private def ErrorHandler = Play.maybeApplication.fold[HttpErrorHandler](DefaultHttpErrorHandler)(errorHandlerCache)
```
in `HttpErrorHandler.scala`.

@richdougherty I am going to revert this change for now. If you know what's the problem and how to fix it, I suggest you provide another PR for it.

**Comment by richdougherty** [comment]
I'm not sure what the reason is. Is there a longer stack trace?

**Comment by mkurz** [comment]
That's all I could find out. I don't really know how to get the stacktrace when the Play server runs the integration tests and fails. What I did was starting [the server](https://github.com/playframework/playframework/blob/2.4.x/framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala#L29) in Dev mode and then printed out [`result.body`](https://github.com/playframework/playframework/blob/2.4.x/framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala#L184) via logger or sysout, which displayed me the `InstantiationException` inside the default Play HTML error page markup... There are probably much better ways for debugging this...

**Comment by mkurz** [comment]
This and #4725 are ready to merge. Hopefully this makes it into 2.4.1 :smile:

**Comment by jroper** [comment]
The errors are most likely due to there being no started application in those tests.  The old `LazyHttpErrorHandler` folds the current application onto a default singleton instance of the error handler, so it works without any started application.  The new one would throw an error if there was no current application.  Anyway, this is fine as is, if we want to change `LazyHttpErrorHandler` we can do it in another PR.

**Comment by jroper** [comment]
Backported to 2.4.x: ab33282

**Pull request merged**
