### PR TITLE
Run scripted tests on Java 11

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
yep!

**Comment by marcospereira** [comment]
Close/open since Travis was overloaded and we are still waiting for a _final_ status here.

**Comment by marcospereira** [comment]
__

**Comment by dwijnand** [comment]
Merging seeing as running anything on Java 11 is allowed to fail CI anyways.

**Comment by renatocaval** [comment]
Backported to 2.7.x (ea2e6dae640c2dc1a7e8585244c4fe8094409a8d)

**Pull request merged**
