### PR TITLE
Fix typo in docs: should be onLoadConfig

### PR DESCRIPTION
**Pull request by dragisak**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @dragisak,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by dragisak** [comment]
Why is this failing validation ?!

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator these tests are way too flaky

**Comment by jroper** [comment]
@dragisak because our CI has become incredibly flaky - we're investigating.

**Pull request merged**
