### PR TITLE
Add sql log statements feature to feature hightlights

### PR DESCRIPTION
**Pull request by marcospereira**
As suggested by @richdougherty here: 

https://github.com/playframework/playframework/pull/4713#issuecomment-121767094

### CODE REVIEW

**Comment by marcospereira** [comment]
@play-pull-request-validator try again.

**Comment by dotta** [comment]
@marcospereira Almost there :-)

```
[error] Page /scratch/jenkins/workspace/play-master-PRs/documentation/manual/releases/Highlights25.md is not referenced by the index
[info] [fail] Orphan pages test (1 errors)
java.lang.RuntimeException: Documentation validation failed
```

**Comment by marcospereira** [comment]
@dotta fixed.

**Comment by richdougherty** [comment]
Our first highlighted feature for Play 2.5!

**Comment by marcospereira** [comment]
ftw

**Pull request merged**
