### PR TITLE
Optimize DoneAccumulator to bypass dispatcher in the happy strict case

### PR DESCRIPTION
**Pull request by jrudolph**
On top of the `hasBody` change this removes unncessary scheduling of
future combinator code. It should bring an additional 5-10% increase of
throughput in the request-without-body case.

### CODE REVIEW

**Comment by marcospereira** [comment]
@jrudolph build is failing for scala 2.11:

https://travis-ci.org/playframework/playframework/jobs/215869698#L631

**Comment by jrudolph** [comment]
Ah, I see. Will fix.

**Comment by jrudolph** [comment]
Not sure what's now going on, lot's of tests fail with NPEs in logging.

**Comment by marcospereira** [comment]
@jrudolph we were just talking about this. We think the problem is related to some logback initialization which is static and then is being accessed by more than one test at time. 

For now, to help you progress faster, I think we can make these tests run sequentially. I will take a look right away.

**Comment by marcospereira** [comment]
By the way, see https://github.com/playframework/playframework/pull/7150.

**Comment by jrudolph** [comment]
Cool, could the failed run otherwise just be restarted?

**Comment by schmitch** [comment]
I restarted it and now it's green.
It would be great if we could target prune against certain PR's sometimes, before merging.

**Comment by jrudolph** [comment]
Thanks, @schmitch. Yeah targetting prune at PRs would be nice but at least we still get results after it was merged.

**Pull request merged**
