### PR TITLE
Upgrade to AHC 1.9.14

### PR DESCRIPTION
**Pull request by wsargent**
Upgrading to 1.9.14 as latest version, per @slandelle

### CODE REVIEW

**Comment by megazord** [comment]
@wsargent 

We already have a [1.9.15 version](http://mvnrepository.com/artifact/com.ning/async-http-client/1.9.15).

**Comment by slandelle** [comment]
Yep, there was a [bug with ssl handshake failures](https://github.com/AsyncHttpClient/async-http-client/issues/841). I was in a rush and forgot to advertise the release, sorry.

**Comment by wsargent** [comment]
:cry:

**Comment by benmccann** [comment]
@wsargent let me know if you have a chance to try updating to 1.9.15. i tried it and it's failing the build, but works just fine on my machine. i'm trying to figure out if the problem is on the build or on my machine

**Comment by wsargent** [comment]
Closing in favor of https://github.com/playframework/playframework/pull/4137

**Comment by megazord** [comment]
@wsargent I don't think that #4137 upgraded AHC. Maybe you can reopen this PR with a new commit with AHC 1.9.15.

**Comment by wsargent** [comment]
@megazord I meant #4140

**Comment by megazord** [comment]
@wsargent sorry! I did not saw that PR. :-)

**Pull request closed without merging**
