### PR TITLE
Update to sbt 1.3.0

### LINKED ISSUE #9504: sbt 1.3.0-RCx manual testing
As part of the acceptance testing for sbt 1.3.0 there are a few areas worth looking into with manual tests (e.g.Play does some classloader magic in dev mode to implement hot reload):

- [ ] use the [`play-java-ebean`](https://github.com/playframework/play-samples/tree/2.7.x/play-java-ebean-example) to try out Play _evolutions_
- [ ] test code changes (with and without errors):
  - [ ] In Java/Scala code
  - [ ] in Twirl templates
  - [ ] In `application.conf` files
- [ ] Dist and then run in production mode
  - [ ] Locally
  - [ ] In a docker container

related https://github.com/lagom/lagom/issues/2112

### PR DESCRIPTION
**Pull request by eed3si9n**
## Fixes

Fixes #9504

### CODE REVIEW

**Comment by marcospereira** [comment]
Build failed, but I think it is something related to Travis cache:

[job-220985473-log.txt](https://github.com/playframework/playframework/files/3448875/job-220985473-log.txt)

I've deleted all the caches and restarted the build to confirm that.

**Comment by eed3si9n** [comment]
For the record, the error was

```
Running play-sbt-plugin / dev-mode
[info] Getting org.scala-sbt sbt 0.13.18  (this may take some time)...
[info] :: retrieving :: org.scala-sbt#boot-app
[info] 	confs: [default]
[info] 	49 artifacts copied, 0 already retrieved (17584kB/69ms)
[info] Getting Scala 2.10.7 (for sbt)...
[info] :: retrieving :: org.scala-sbt#boot-scala
[info] 	confs: [default]
[info] 	5 artifacts copied, 0 already retrieved (21327kB/32ms)
[info] Error: Could not retrieve Scala 2.10.7: missing scala.tools.nsc.Global
[error] x play-sbt-plugin / dev-mode
[error]    {line 21}  Command failed: Remote sbt initialization failed
```

Maybe it's failing to cross-sbt build and/or test?

**Comment by marcospereira** [comment]
> Maybe it's failing to cross-sbt build and/or test?

I saw a similar problem in another PR that isn't touching sbt at all. That is why I think it is a cache issue.

**Comment by eed3si9n** [comment]
@marcospereira You're probably right since https://travis-ci.com/playframework/playframework/jobs/220985473 seems to be cruising through the 0.13 scripted tests.

**Comment by marcospereira** [comment]
By the way, here is the other failure I was referring to: https://github.com/playframework/playframework/pull/9517#issuecomment-516596894

**Comment by marcospereira** [comment]
The job for running scripted tests using sbt 1 and Java 11 is failing. Travis failure is not relevant since this job is flaky, but it is possible to reproduce the error running locally:

```bash
$ sbt +2.12.8 publishLocal
$ sbt "scripted routes-compiler-plugin/no-package-declaration-in-routes-file"
```

**Comment by eed3si9n** [comment]
I get the following error locally using JDK 11 and sbt 1.2.8:

```scala
[info] [info] Compiling 1 Scala source to /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/target/scala-2.12/test-classes ...
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:13:14: object routes is not a member of package router
[info] [error]       router.routes.Application.takeBool(true).url must equalTo("/take-bool?b=true")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:14:14: object routes is not a member of package router
[info] [error]       router.routes.Application.takeBool(false).url must equalTo("/take-bool?b=false")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:17:14: object routes is not a member of package router
[info] [error]       router.routes.Application.takeBool2(true).url must equalTo("/take-bool-2/true")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:18:14: object routes is not a member of package router
[info] [error]       router.routes.Application.takeBool2(false).url must equalTo("/take-bool-2/false")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:24:14: object routes is not a member of package router
[info] [error]       router.routes.Application.queryUser(UserId("foo")).url must equalTo("/query-user?userId=foo")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:25:14: object routes is not a member of package router
[info] [error]       router.routes.Application.queryUser(UserId("foo/bar")).url must equalTo("/query-user?userId=foo%2Fbar")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:26:14: object routes is not a member of package router
[info] [error]       router.routes.Application.queryUser(UserId("foo?bar")).url must equalTo("/query-user?userId=foo%3Fbar")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:27:14: object routes is not a member of package router
[info] [error]       router.routes.Application.queryUser(UserId("foo%bar")).url must equalTo("/query-user?userId=foo%25bar")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:28:14: object routes is not a member of package router
[info] [error]       router.routes.Application.queryUser(UserId("foo&bar")).url must equalTo("/query-user?userId=foo%26bar")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:31:14: object routes is not a member of package router
[info] [error]       router.routes.Application.user(UserId("foo")).url must equalTo("/users/foo")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:32:14: object routes is not a member of package router
[info] [error]       router.routes.Application.user(UserId("foo/bar")).url must equalTo("/users/foo%2Fbar")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:33:14: object routes is not a member of package router
[info] [error]       router.routes.Application.user(UserId("foo?bar")).url must equalTo("/users/foo%3Fbar")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:34:14: object routes is not a member of package router
[info] [error]       router.routes.Application.user(UserId("foo%bar")).url must equalTo("/users/foo%25bar")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:36:14: object routes is not a member of package router
[info] [error]       router.routes.Application.user(UserId("foo&bar")).url must equalTo("/users/foo&bar")
[info] [error]              ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:64:69: object routes is not a member of package router
[info] [error]       val Some(result) = route(implicitApp, FakeRequest(GET, router.routes.Application.takeList(List(1, 2, 3)).url))
[info] [error]                                                                     ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:65:7: overloaded method value contentAsString with alternatives:
[info] [error]   (of: play.api.libs.streams.Accumulator[akka.util.ByteString,play.api.mvc.Result])(implicit timeout: akka.util.Timeout, implicit mat: akka.stream.Materializer)String <and>
[info] [error]   (of: scala.concurrent.Future[play.api.mvc.Result])(implicit timeout: akka.util.Timeout, implicit mat: akka.stream.Materializer)String <and>
[info] [error]   (of: play.twirl.api.Content)(implicit timeout: akka.util.Timeout)String
[info] [error]  cannot be applied to (Any)
[info] [error]       contentAsString(result) must equalTo("1,2,3")
[info] [error]       ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:122:29: object routes is not a member of package router
[info] [error]       val call     = router.routes.Application.urlcoding(dynamicDecoded, staticDecoded, queryDecoded)
[info] [error]                             ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:153:19: object routes is not a member of package router.module
[info] [error]     router.module.routes.ModuleController.index().url must_== "/module/index"
[info] [error]                   ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:170:12: object routes is not a member of package router
[info] [error]     router.routes.Application.takeListTickedParam(List(1, 2, 3)).url must_== "/take-list-tick-param?b[]=1&b[]=2&b[]=3"
[info] [error]            ^
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:174:12: object routes is not a member of package router
[info] [error]     router.routes.Application.hello().url must_== "/hello"
[info] [error]            ^
[info] [error] 20 errors found
[info] [info] Packaging /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/target/scala-2.12/root_2.12-0.1.0-SNAPSHOT.jar ...
[info] [info] Done packaging.
[info] [info] Running utils.JavaScriptRouterGenerator target/web/jsrouter/jsRoutesBadHost.js '}}};alert(1);a={a:{a:{a:'
[info] [info] Running utils.JavaScriptRouterGenerator target/web/jsrouter/jsRoutes.js
[info] [error] (Test / compileIncremental) Compilation failed
[info] [error] Total time: 2 s, completed Aug 7, 2019, 12:39:48 AM
[error] x routes-compiler-plugin / no-package-declaration-in-routes-file
[error]  Cause of test exception: {line 4}  Command failed: test:compile failed
[error] java.lang.RuntimeException: Failed tests:
[error] 	routes-compiler-plugin / no-package-declaration-in-routes-file
```

**Comment by marcospereira** [comment]
@eed3si9n that is weird considering that our build runs sbt 1.2.8 + Java 11 and they are green. For example:

- master: https://travis-ci.com/playframework/playframework/jobs/222501979
- 2.7.x: https://travis-ci.com/playframework/playframework/jobs/222658102

But running locally here with this Java version failed for me with the same error. I've tried with Java version below:

```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

And the version used by Travis:

```
openjdk version "11.0.2" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+7, mixed mode)
```

Interesting.

**Comment by dwijnand** [comment]
Spinning off to https://github.com/playframework/playframework/issues/9546.

**Comment by mkurz** [comment]
@marcospereira @eed3si9n So I guess the tests fail on your machines because you use macOS with a case insensitive filesystem? Travis runs a Linux distribution where obviously the filesystem is case sensitive however...

**Comment by marcospereira** [comment]
@mkurz are you talking about `test` directory vs. `test` script?

**Comment by mkurz** [comment]
I am talking about the specific test `scripted routes-compiler-plugin/no-package-declaration-in-routes-file`. It generates a `routes.class` and a `Routes.class` file (inside `target/scala-2.12/classes/router/`.

**Comment by eed3si9n** [comment]
@mkurz `scripted routes-compiler-plugin/no-package-declaration-in-routes-file` in general is problematic on a non-case-sensitive filesystem (macOS and Windows). See #6702. I'd suggest we disable that particular script to avoid further confusion.

In terms of validating sbt 1.3.0-RCx, do we have any other suspects?

**Comment by marcospereira** [comment]
> In terms of validating sbt 1.3.0-RCx, do we have any other suspects?

I don't think so.

**Comment by mkurz** [comment]
@eed3si9n Please update this pull request to final sbt 1.3.0, thanks!

**Comment by mkurz** [comment]
```
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at Docs$.$anonfun$apiDocsTask$1(Docs.scala:208)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ProjectRef(uri("file:///home/travis/build/playframework/playframework/"), "Play-Docs") / apiDocs) sbt.inc.Doc$JavadocGenerationFailed
```

**Comment by mkurz** [comment]
This error only appears on `master` branch, `2.7.x` is green already: #9417

**Comment by mkurz** [comment]
Still fails

**Comment by eed3si9n** [comment]
```
[warn] /home/travis/build/playframework/playframework/core/play/src/main/java/play/mvc/StatusHeader.java:733: error: type arguments not allowed here
[warn]    * @deprecated Deprecated as of 2.8.0. Use to {@link #sendResource(String, boolean,
[warn]     
```

Javadoc failure?

**Comment by eed3si9n** [comment]
Here's another JDK 11 Javadoc failure:

```
[warn] Loading source file /home/travis/build/playframework/playframework/core/play-streams/src/main/java/play/libs/streams/Accumulator.java...
[warn] Loading source files for package play...
[warn] javadoc: error - No source files for package play
[warn] 1 error.
[warn] javadoc exited with exit code 2
[info] Main Java API documentation to /home/travis/build/playframework/playframework/persistence/play-java-jdbc/target/scala-2.13/api...
[warn] Unexpected javac output: Loading source file /home/travis/build/playframework/playframework/persistence/play-java-jdbc/src/main/java/play/db/DefaultDatabase.java...
[warn] Loading source file /home/travis/build/playframework/playframework/persistence/play-java-jdbc/src/main/java/play/db/package-info.java...
```

**Pull request merged**
