### PR TITLE
Made changes for making PLAY_LANG cookie by default HttpOnly. As per …

### PR DESCRIPTION
**Pull request by geek94**
…OWASP cookies should be HttpOnly to migrate the client side scripting access of cookies.

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by mkurz** [comment]
If we change this it has to be changed here as well:
https://github.com/playframework/playframework/blob/2.6.6/framework/src/play/src/main/resources/reference.conf#L844

**Comment by geek94** [comment]
Thanks, I've updated the same in reference.conf.

**Comment by wsargent** [comment]
I don't see the motivation for changing the PLAY_LANG cookie to be HTTP only.  If the client wants to change the language from Javascript, shouldn't that be allowed behavior?  Where's the security vulnerability?

**Comment by geek94** [comment]
According to the security protocol cookies should be HttpOnly by default as its helps in preventing XSS attacks. I noticed this issue when I was running  a Qualys scan on my website. report was constantly giving threat reports for this cookie and forced us to make it HttpOnly. And  also if we create a cookie in play they are HttpOnly by default as well. So I was under the impression that why not make these cookies also as HttpOnly  by default and if a user wants  he can any time override the default feature.

**Comment by gmethvin** [comment]
> According to the security protocol cookies should be HttpOnly by default as its helps in preventing XSS attacks.

It helps in mitigating XSS attacks since it prevents the attacker from stealing your cookies, but it doesn't prevent an XSS attack from doing other things like making a user click links to malicious sites. If you are concerned about preventing XSS attacks, you should make sure to set the  `Content-Security-Policy` header so you can completely block inline scripts and scripts from untrusted origins. The [security headers filter](https://www.playframework.com/documentation/2.6.x/SecurityHeaders) makes this simple to configure, and the filter is enabled by default in Play 2.6.

I agree HttpOnly is a good idea for session cookies and cookies storing private user data, but the PLAY_LANG cookie is just storing the language used on the page. This isn't like a session cookie, which if stolen could allow an attacker to execute actions on behalf of the user.

> I noticed this issue when I was running a Qualys scan on my website. report was constantly giving threat reports for this cookie and forced us to make it HttpOnly.

It seems like the problem for you is just that the cookie was showing up on the scan and not necessarily that you are worried about an XSS attacker knowing which language is used on the page.

> And also if we create a cookie in play they are HttpOnly by default as well. So I was under the impression that why not make these cookies also as HttpOnly by default and if a user wants he can any time override the default feature.

HttpOnly is a good default in general since we don't know what information the cookie will store. I think for consistency it would be a good default for the lang cookie too, but it's incompatible with the existing behavior. There are legitimate reasons to access the cookie from JavaScript, and changing the default will break that functionality upon upgrade. Since I don't see any real security risk, all we are doing is inconveniencing our existing users.

**Pull request closed without merging**
