### PR TITLE
ScalaTest + Play

### PR DESCRIPTION
**Pull request by cheeseng**
Changed to use ScalaTest as default.

### CODE REVIEW

**Comment by marcospereira** [comment]
Maybe we can have another template (play-scala-scalatest) here, instead of changing from specs2 to scalatest.

**Comment by cchantep** [comment]
At least that's a design change to be discussed before.

**Comment by jroper** [comment]
I'd like to change from specs2 to scalatest, for the following reasons:

* We've now pulled scalatestplus-play into the playframework repo:

https://github.com/playframework/scalatestplus-play

this means we're able to maintain it such that when we break it, we can fix it, so we can release it along with new milestone releases and major releases of Play

* The scalatest documentation is much better than the specs2 documentation in Play.
* scalatest has a much more stable API than specs2 - specs2 tends to frequently breaks things.
* specs2 depends on scalaz, and this has tended to cause problems for people who want to use older or new versions of scalaz, or libraries that depend on older/newer versions of scalaz, due to binary compatibility problems.
* scalatest I think is friendly for newcomers, which is why making it the default selection in the templates I think is a good idea.

**Comment by gmethvin** [comment]
I agree with @jroper about the decision but I also noticed there wasn't much community discussion about this.

**Comment by jroper** [comment]
Yes, I didn't really realise that these discussions had happened in private until now.  In fact, it's been mostly @bvenners pushing me, pointing out the advantages of scalatest etc, he and @cheeseng have done an amazing job at creating an incredibly smooth integration between Play and scalatest.  There has also been some internal discussion at Typesafe about switching to scalatest.  And the uncertain future of scalaz since the community problems from last year has made specs2 less attractive recently too.

**Comment by marcospereira** [comment]
I don't see a problem with migrating from specs2 to Scalatest, but I think it could be a good decision to have templates to both and maybe we can also extract all specs2 related code to its own repository.

**Comment by jroper** [comment]
> extract all specs2 related code to its own repository

This is dependent on first migrating Play's integration tests to not use any of the `play-specs2` helpers.  Personally I'd like to move to ScalaTest for all tests, but that will take a while and I think is best done iteratively.

**Comment by marcospereira** [comment]
> I think is best done iteratively.

Agree. Should we start by migrating code examples/docs? Looks like the most reasonable place to me.

**Comment by schmitch** [comment]
There is one thing that isn't as good as it was on specs2 btw.

When running against a database and you want to have multiple configurations you could use `MixedPlaySpec`, however since that will parallelise your test you will soon run out of database connections.
On Specs2 you coul've easily added `sequential` to your tests so they didn't killed your database, but as far as I know Scalatest has nothing like that to run just a bunch of things in sequence.

**Comment by bvenners** [comment]
@schmitch In ScalaTest sequential execution of tests has always been the default. The reason is that usually running suites (test classes) in parallel, and tests within suites sequentially, is sufficient to get the performance you want out of parallel execution. Because tests in the same test class often use the same fixtures, it is more likely they can interfere with each other if run in parallel. An example is running out of database connection as you describe. If you really want tests run instead of just suites in parallel in ScalaTest, you can mix in [ParallelTestExecution](http://doc.scalatest.org/2.2.6/index.html#org.scalatest.ParallelTestExecution).

**Comment by schmitch** [comment]
@bvenners no I don't want to run my tests in parallel, that's exactly what is wrong on scalatest.
If I use MixedPlaySpec I create a `new Suite` with every `new App` (https://www.playframework.com/documentation/2.4.x/ScalaFunctionalTestingWithScalaTest#When-different-tests-need-different-fixtures). 
and due to the nature of scalatest that **will** run in parallel, however there are no *easy* ways of defining that a `sequential`.

**Comment by bvenners** [comment]
I may be misunderstanding your use case, but if you are using MixedPlaySpec each *test* gets a new App. Each MixedPlaySpec is one Suite. Unless you mix in ParalellTestExecution into a MixedPlaySpec, tests inside that MixedPlaySpec will be run sequentially.

By the way ScalaTest also runs Suites sequentially by default, but sbt does not. Sbt will run suites in stalled unless you turn that off. Are you talking about multiple MixedPlaySpecs running in parallel and interfering with each other?

**Comment by schmitch** [comment]
This one will keep my database connections at a peek of 21:
```
class AppDoubleSpec extends PlaySpec with OneAppPerTest{

  var mutSeq = mutable.ListBuffer[String]()

  "Blabla" should {
    "be only happen once first" in {
      mutSeq.length must be(0)
    }
    "be only happen once second" in {
      mutSeq += "hello world"
      mutSeq.length must be(1)
    }
    "be only happen once third" in {
      mutSeq.length must be(1)
    }
  }

  "Blabla2" should {
    "be only happen once" in {
      mutSeq.length must be(1)
    }
  }

}
```

This one will peek my connections to 84:
```
class AppDoubleSpec extends MixedPlaySpec {

  var mutSeq = mutable.ListBuffer[String]()

  "Blabla" should {
    "be only happen once first" in new App {
      mutSeq.length must be(0)
    }
    "be only happen once second" in new App {
      mutSeq += "hello world"
      mutSeq.length must be(1)
    }
    "be only happen once third" in new App {
      mutSeq.length must be(1)
    }
  }

  "Blabla2" should {
    "be only happen once" in new App {
      mutSeq.length must be(1)
    }
  }

}
```

so either they run concurrently or it doesn't drop the connections correctly as PlaySpec does.

**Comment by bvenners** [comment]
@schmitch I was beginning to suspect the connections weren't being closed. I'll take s look when I get back to my laptop.

**Comment by bvenners** [comment]
@schmitch The one difference I can see is that we are still using FakeApplication in MixedFixtures, but are using GuicrApplicationBuilder on OneSppPerTest. That's unintended anyway because we thought we'd completely switched over to GuiceApplicationBuilder. We'll fix that, but I'd like to try and reproduce your issue. How are you counting your database connections? (Probably we should move this to a ScalaTest+Play issue.)

**Comment by schmitch** [comment]
i'm using GuiceApplicationBuilder, I just let it away to post that here ;)
This is a python script i used to look at it:
```
import psycopg2

conn = psycopg2.connect("dbname=loki user=loki password=loki")
conn.autocommit = True

last = None
with conn:
    with conn.cursor() as cur:
        while True:

            ret = cur.execute("SELECT sum(numbackends) FROM pg_stat_database;")
            current = cur.fetchone()[0] - 1

            if current != last and current - 1 != last:
                print(current)

            last = current

conn.close()
```

I also made a new play application without slick, which I'm using with just jdbc. However same result, my script will put out this for MixedPlaySpec (not sure how many datapoints I get since it just prints the connections ;): 
```0
0
0
0
38
30
23
20
18
10
0
0
0
0```

While something like that will be put out by OneAppPerTest:
```
0
0
0
9
8
7
0
0
0
2
0
0
3
1
0
0
```

**Comment by cheeseng** [comment]
@bvenners @schmitch FYI I created an issue in scalatestplus-play here:

https://github.com/playframework/scalatestplus-play/issues/35

We'll continue to work from there.

Thanks.

**Pull request merged**
