### PR TITLE
Upgrade to newer version of Netty

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by hepin1989** [comment]
+1

**Comment by hepin1989** [comment]
than it's time to upgrade the akka's too :P

**Comment by benmccann** [comment]
I've submitted a new PR for this change

**Comment by benmccann** [comment]
This probably depends on first merging https://github.com/typesafehub/netty-http-pipelining/pull/11

**Comment by hepin1989** [comment]
cause the ws,so need the ws upgrade first.

**Comment by benmccann** [comment]
I can't cause this error on my machine. Do you know how I can reproduce it?

What line for the ws upgrade?

**Comment by hepin1989** [comment]
@benmccann sorry ,currently I am using sbt,you may change to the netty-server project tack a try,or may you need something like reload.

**Comment by benmccann** [comment]
It doesn't cause anything to fail for me:

    $ ./build
    > project Play-Netty-Server
    > compile

Or using SBT directly either:

    $ sbt
    > compile

**Comment by benmccann** [comment]
Reason the tests are failing is that the current master is broken. See https://github.com/playframework/playframework/pull/4141

**Comment by jroper** [comment]
@play-pull-request-validator

**Pull request merged**
