### PR TITLE
Save akka and akka-http version after publish-local

### LINKED ISSUE #10215: Scripted tests fail when akka/akka-http are released concurrently
https://travis-ci.com/github/playframework/playframework/builds/161408298

When a new snapshot of akka or akka-http is released while a nightly build against those snapshots is running, the versions can get inconsistent between jobs in which case the resources won't be found.

I think we should write the play version into a file on the workspace so the scripted tests always pick the exact versions that the original compilation used.

### PR DESCRIPTION
**Pull request by fusuiyi123**
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes  #10215 

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by fusuiyi123** [comment]
I see, but only publish-local will write the file `~/.ivy2/local/AKKA_VERSION`? I can raise another pr if needed! Thanks

**Comment by mkurz** [comment]
Since merging this pull request the build is breaking: https://travis-ci.com/github/playframework/playframework/jobs/331365730#L1047

**Comment by raboof** [comment]
> Since merging this pull request the build is breaking: https://travis-ci.com/github/playframework/playframework/jobs/331365730#L1047

I *suspect* that is unrelated to this PR and instead related to the update from JDK `adopt@1.8.0-242` to `adopt@1.8.0-252`

**Comment by mkurz** [comment]
@raboof I guess we need to wait for akka-http 10.1.12 (https://github.com/akka/akka-http/pull/3125)?

How about this workaround for Play as well: https://github.com/akka/akka-grpc/pull/963?

**Comment by raboof** [comment]
> I guess we need to wait for akka-http 10.1.12 (akka/akka-http#3125)?

I'm not *sure* just updating akka-http would be enough (the failing tests don't seem to be about HTTP/2 at first glance?), but I haven't looked into this closer yet

> How about this workaround for Play as well: akka/akka-grpc#963?

That seems reasonable to me

**Comment by jrudolph** [comment]
Updating jetty-alpn-agent to 2.0.10 might solve this issue also for 8u252.

**Comment by mkurz** [comment]
@jrudolph Thanks, let's give that a try: #10268

**Comment by renatocaval** [comment]
@Mergifyio backport 2.8.x

**Pull request merged**
