### PR TITLE
Stop Akka HTTP processing the request body twice

### PR DESCRIPTION
**Pull request by richdougherty**
A bit of a silly mistake!

### CODE REVIEW

**Comment by richdougherty** [comment]
@play-pull-request-validator, CI was too slow.

```
[info] ! support patch method
[error]    TimeoutException: : Futures timed out after [20 seconds]  (Helpers.scala:171)
[error] play.api.test.FutureAwaits$class.await(Helpers.scala:171)
[error] play.api.libs.ws.ning.NingWSSpec$.await(NingWSSpec.scala:17)
[error] play.api.libs.ws.ning.NingWSSpec$$anonfun$19$$anonfun$apply$35$$anon$17$delayedInit$body.apply(NingWSSpec.scala:173)
[error] play.api.test.WithServer$$anonfun$around$3.apply(Specs.scala:62)
[error] play.api.test.WithServer$$anonfun$around$3.apply(Specs.scala:62)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:56)
[error] play.api.test.Helpers$.running(Helpers.scala:365)
[error] play.api.test.WithServer.around(Specs.scala:62)
[error] play.api.test.WithServer.delayedInit(Specs.scala:51)
[error] play.api.libs.ws.ning.NingWSSpec$$anonfun$19$$anonfun$apply$35$$anon$17.<init>(NingWSSpec.scala:169)
[error] play.api.libs.ws.ning.NingWSSpec$$anonfun$19$$anonfun$apply$35.apply(NingWSSpec.scala:169)
[error] play.api.libs.ws.ning.NingWSSpec$$anonfun$19$$anonfun$apply$35.apply(NingWSSpec.scala:169)
```

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by richdougherty** [comment]
Bind failures. Let's wait until #3783 is merged before running CI again.

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Pull request merged**
