### PR TITLE
Updated Tutorials.md with three new tutorials

### PR DESCRIPTION
**Pull request by pazvanti**
Added three new tutorials done on Play version 2.8

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Purpose

Added three new third-party tutorials and a Play 2.8.x category

## Background Context

I did not see the category for Play 2.8.x and added it. Started to add three tutorials written by me.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @pazvanti,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by ignasi35 — APPROVED** [review]
Nice work! Thanks @pazvanti paz

**Comment by pazvanti** [comment]
> Nice work! Thanks @pazvanti paz

Thank you.

**Comment by mkurz** [comment]
@Mergifyio backport master

**Comment by mkurz** [comment]
This PR is not up-to-date with its target branch, that's why it keeps failing.
I included the change in #10774 instead.

**Pull request closed without merging**
