### PR TITLE
Upgrade logback dependency to fix 5 secs delays in unittests

### PR DESCRIPTION
**Pull request by tarmath**
Fixes Issue #7169

See details/discussion on the issue's page

### CODE REVIEW

**Comment by wsargent** [comment]
That's not the latest logback -- it should be http://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.2.3

**Comment by tarmath** [comment]
looking at the logback page, it seems like 1.1.x and 1.2.x are different "series", as they call it.

I wasn't sure if it was appropriate to upgrade to it in 2.5.x...?

**Comment by tarmath** [comment]
well, I updated to 1.2.3 and ran the tests. Only 2 are failing and they both are/seem unrelated:

    [error] Failed: Total 579, Failed 2, Errors 0, Passed 575, Skipped 2, Pending 4
    [error] Failed tests:
    [error] 	play.it.http.NettyIdleTimeoutSpec
    [error] 	play.it.http.AkkaIdleTimeoutSpec
    [error] (Play-Integration-Test/test:test) sbt.TestsFailedException: Tests unsuccessful
    [error] Total time: 436 s, completed Apr 2, 2017 9:35:29 PM

 Both show:

    Caused by: java.io.FileNotFoundException: ./conf/generated.keystore (No such file or directory)

    [error]   x support a separate timeout for https
    [error]    Expected: java.net.SocketException. Got: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection? instead 

So, I'll update logback as per your suggestion

**Comment by benmccann** [comment]
@wsargent - @marcospereira had said on the bug report:

>I'm not sure Logback 1.2.2 (the latest Logback version) is binary compatible with 1.1.x, but I would be conservative here and update to 1.1.11.

Not sure about your thoughts on this...

**Comment by wsargent** [comment]
@benmccann I think it's worth it in this case.

**Pull request merged**
