### PR TITLE
Updated sbt keys to be camel case

### PR DESCRIPTION
**Pull request by jroper**
sbt 0.13 introduced the convention of making all keys camel case.

### CODE REVIEW

**Comment by benmccann** [comment]
Should probably add something like "and remove scala-compilation-times project" to the description

**Comment by jroper** [comment]
That scripted test has been disabled for well over a year now, and definitely no longer works.  It was just created for Grzegorz to simulate typical Play development loops so he could optimise the Scala incremental compiler.

**Comment by jroper** [comment]
Updated commit message.

**Comment by richdougherty** [comment]
LGTM

**Pull request merged**
