### PR TITLE
Reference to play-redis module in Module directory in the documentation

### PR DESCRIPTION
**Pull request by KarelCemus**
## Purpose

This PR updates the documentation. It adds reference to [play-redis](https://github.com/KarelCemus/play-redis) module implementing a redis based cache. It implements common `CacheAPI` and some additional redis commands including the support of collections. The API is implemented in both blocking and asynchronous manner.

### CODE REVIEW

**Comment by KarelCemus** [comment]
Please backport it also into 2.5.x, if you accept this PR

**Comment by marcospereira** [comment]
Hey @KarelCemus, thank you!

There is a "Datastore" section at this documentation page. It could be a better place to add this module. Nothing serious, but it could be easier to other user to find your plugin.

After that, this PR will be good to be merged and backported.

**Comment by KarelCemus** [comment]
Hi, thanks, I know. I hesitated where to put it. It appended it just after 

```
Memcached Plugin

Website: https://github.com/mumoshu/play2-memcached
Short description: Provides a memcached based cache implementation
```

which seemed appropriate. However, I'll move it among datastores.

**Comment by KarelCemus** [comment]
Done, I fixed that.

**Comment by KarelCemus** [comment]
@marcospereira Today, I checked modules directory for version 2.5.x as there is new release and it seems that this PR has not been backported yet. Could you look at it, please?

**Comment by marcospereira** [comment]
@KarelCemus backport here: ecda95c25

The module will appears next time we publish the docs.

**Comment by KarelCemus** [comment]
Thanks.

**Pull request merged**
