### PR TITLE
Don't try to use minified asset in DEV mode

### LINKED ISSUE #5173: [2.4.2] Assets.versioned enforce usage of .min files
There shouldnt be a default behaviour to enforce the .min file usage (if the file exist in the same directory), this is really inconvenient when developing.
Is there a way to switch this off at the moment?

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #5173, https://groups.google.com/d/topic/play-framework/wAW-HbVPx6I/discussion and https://github.com/playframework/playframework/pull/2973#issuecomment-207121085

### CODE REVIEW

**Comment by gmethvin** [comment]
Shouldn't this be something we allow to be configurable in dev mode as well? One way is to change

```scala
lazy val checkForMinified = config(_.getBoolean("assets.checkForMinified")).getOrElse(!isDev)
```

**Comment by mkurz** [comment]
Good idea. Updated.

**Comment by gmethvin** [comment]
@mkurz Where do we have this documented? If we are going to change the behavior we should probably at least mention in the documentation how it works and how to change it.

**Comment by mkurz** [comment]
This never was documented in [the first place](https://github.com/playframework/playframework/pull/2973/files#r14111952).

I will see if I find some time next week to also add documentation to this pr.

(fyi: I considered the current behaviour in dev mode a bug because I assumed it should work as original intended in the original issue #2973).

**Comment by gmethvin** [comment]
As you said, it was never documented, but it seems like the final decision made in #2973 is in [this comment](https://github.com/playframework/playframework/pull/2973#issuecomment-46610810). By default the option is enabled (regardless of mode). What's not mentioned there is that you have to set `assets.checkForMinified = false` in dev mode to get the old behavior.

Documenting the option was also [discussed in the comments of #2973](https://github.com/playframework/playframework/pull/2973/files#r14111952). But since @huntc complied with @jroper's request for a picture of a kitten, the PR was merged without documentation. Since no one ended up revisiting the documentation later, this feature remained undocumented.

So, if we are going to change the behavior yet again, we should document the `assets.checkForMinified` setting and explain how it is set by default.

**Comment by mkurz** [comment]
Added documentation.

**Comment by mkurz** [comment]
@gmethvin If you don't mind I will backport this to the 2.5.x branch.

**Comment by gmethvin** [comment]
@mkurz Sure. It only affects dev mode so it should be okay to backport. I'll have to remember to note the change in the release notes for 2.5.5.

**Comment by mkurz** [comment]
2.5.x: https://github.com/playframework/playframework/commit/02b8daccfa0d52e5d108d0121561d24d1231723a

**Comment by mkurz** [comment]
@gmethvin I updated the `2.5.5` milestone to include all changes made so far in the `2.5.x` branch.

**Pull request merged**
