### PR TITLE
Replace logging string concatenation

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by richdougherty** [comment]
Restarting tests due to test box flakiness.
```
[error]   x allow timing out a future
[error]    '200' is not equal to '500' (ScalaAsync.scala:27)
```

**Comment by benmccann** [comment]
There's some whitespace cleanup here that's unambiguously good. What do people think about the format string as opposed to concatenation? I have mixed feelings. It looks a little cleaner and more readable. It's also more error prone in that if you pass a different number of parameters than there are `{}` you will get an error. I'm not sure if the tradeoff is worth it or not. Curious what we want the style guide to be on this one...

**Comment by wsargent** [comment]
I think that slf4j parameters are better because they'll only be applied if the log statement is actually at an active log level, so they'll be better arranged.  Other than that, I don't have an opinion.

**Comment by gmethvin** [comment]
I agree with @wsargent here. I think using parameters is a bit more readable as well.

LGTM

**Pull request merged**
