### PR TITLE
Removed reliance on Typesafe repo

### LINKED ISSUE #4223: Remove dependence on repo.typesafe.com/typesafe/releases
We want to remove our reliance on all repositories that aren't included with sbt by default, and the one that we currently rely on that isn't is http://repo.typesafe.com/typesafe/releases. While there should be no application dependencies there, build dependencies (eg sbt plugins and their dependencies) that only live there that I've discovered include:

* `net.contentobjects.jnotify:jnotify:0.94`
* `com.typesafe:jse_2.10:1.0.0`
* `com.typesafe:npm_2.10:1.0.0`
* `com.typesafe:webdriver_2.10:1.0.0`

At the moment we don't want to forgo the jnotify dependency, as it is the only option we have for event based (not polling) notification of filesystem changes.  We could solve this by deploying it to the play sbt bintray repository.  Ideally we'd shade it, but given that it's a jni library, we'd have to shade the binaries too, which is not really practical.

jse, npm and webdriver need to be updated to publish to maven central.

### PR DESCRIPTION
**Pull request by jroper**
Fixes #4223

### CODE REVIEW

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by megazord** [comment]
@play-pull-request-validator do your magic!

**Comment by jroper** [comment]
Urgh... gonna have to update every sbt-web plugin due to binary incompatibility in spray-json.

**Comment by benmccann** [comment]
Dependencies updated here:
https://github.com/typesafehub/webdriver/pull/13
https://github.com/typesafehub/js-engine/pull/37

**Comment by benmccann** [comment]
@play-pull-request-validator try again

>[error] (Play-WS/test:test) sbt.TestsFailedException: Tests unsuccessful

**Comment by benmccann** [comment]
@jroper real error this time:

>[info] [error] (*:mochaExecuteTests) java.lang.NoSuchMethodError: spray.json.StandardFormats$class.optionFormat(Lspray/json/StandardFormats;Lspray/json/JsonFormat;)Lspray/json/StandardFormats$OptionFormat;
[info] [error] Total time: 7 s, completed May 6, 2015 11:57:00 PM
[error] x routes-compiler-plugin / injected-routes-compilation
[error]    {line 5}  Command failed: test failed

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by benmccann** [comment]
Maybe we need to upgrade sbt-mocha? Sent a PR: https://github.com/sbt/sbt-mocha/pull/13

**Comment by jroper** [comment]
I just triggered the rebuild because I was testing a Jenkins webhook :)  Yes, sbt-mocha does need to be fixed. I was hoping I'd fixed all the binary compatibility issues.

**Pull request merged**
