### PR TITLE
Upgrade Akka to version 2.4.3

### LINKED ISSUE #5883: FileIO.fromFile triggers exception java.util.NoSuchElementException: http-handler-body-subscriber
### Play Version (2.5.x / etc)

2.5.x

### API (Scala / Java / Neither / Both)

Both

### JDK

```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

### Expected Behavior

The following code should work without exception.

### Actual Behavior

Exception is thrown.

### Reproducible Test Case

(code from #5866)

```scala
@Singleton
class HomeController @Inject()(db: DBApi, ws: WSClient)(implicit materializer: Materializer) extends Controller {

  // Throws: java.util.NoSuchElementException: http-handler-body-subscriber
  def streaming1 = Action {
    try {
      val fileName = "/Volumes/Share/Book/AkkaScala2.3.14.pdf"
      val file = new File(fileName)
      val fileContent: Source[ByteString, Future[IOResult]] = FileIO.fromFile(file)
      val contentType = play.api.libs.MimeTypes.forFileName(fileName).orElse(Some(play.api.http.ContentTypes.BINARY))
      Result(
        header = ResponseHeader(200, Map(CONTENT_LENGTH -> file.length.toString)),
        body = HttpEntity.Streamed(fileContent, Some(file.length()), contentType)
      )
    } catch {
      case t: Throwable =>
        InternalServerError("Error in server: " + t.getMessage())
    }
  }

  // works
  def streaming2 = Action {
    val file = new File("/Volumes/Share/Book/AkkaScala2.3.14.pdf")
    val in: FileInputStream = new FileInputStream(file)
    val dataContent: Enumerator[Array[Byte]] = Enumerator.fromStream(in, 1024*1024)
    val source: Source[Array[Byte], NotUsed] = Source.fromPublisher(Streams.enumeratorToPublisher(dataContent))
    Ok.chunked(source).as("application/pdf")
  }
}
```

### PR DESCRIPTION
**Pull request by marcospereira**
## Fixes

Fixes #5883.

## Purpose

Upgrade Akka to version 2.4.3. This also reverts some changes made at #5878 since Akka 2.4.3 contains akka/akka#20031.

## References

1. #5883 
2. #5878
3. akka/akka#20031
4. http://akka.io/news/2016/04/01/akka-2.4.3-released.html

### CODE REVIEW

**Comment by benmccann** [comment]
>[error]     ! close when the consumer is done
[error]      java.util.concurrent.TimeoutException: Futures timed out after [5 seconds] (Helpers.scala:191)
[error] play.api.test.FutureAwaits$class.await(Helpers.scala:191)
[error] play.it.http.websocket.NettyWebSocketSpec$.await(WebSocketSpec.scala:29)
[error] play.it.http.websocket.WebSocketSpec$$anonfun$runWebSocket$1.apply(WebSocketSpec.scala:50)
[error] play.it.http.websocket.WebSocketSpec$$anonfun$runWebSocket$1.apply(WebSocketSpec.scala:48)
[error] play.it.http.websocket.WebSocketClient$.apply(WebSocketClient.scala:72)
[error] play.it.http.websocket.WebSocketSpec$class.runWebSocket(WebSocketSpec.scala:48)
[error] play.it.http.websocket.NettyWebSocketSpec$.runWebSocket(WebSocketSpec.scala:29)
[error] play.it.http.websocket.WebSocketSpec$$anonfun$closeWhenTheConsumerIsDone$2.apply(WebSocketSpec.scala:132)
[error] play.it.http.websocket.WebSocketSpec$$anonfun$closeWhenTheConsumerIsDone$2.apply(WebSocketSpec.scala:130)
[error] play.it.http.websocket.WebSocketSpec$$anonfun$withServer$1.apply(WebSocketSpec.scala:44)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:76)
[error] play.it.http.websocket.NettyWebSocketSpec$.running(WebSocketSpec.scala:29)
[error] play.it.http.websocket.WebSocketSpec$class.withServer(WebSocketSpec.scala:44)
[error] play.it.http.websocket.NettyWebSocketSpec$.withServer(WebSocketSpec.scala:29)
[error] play.it.http.websocket.WebSocketSpec$class.closeWhenTheConsumerIsDone(WebSocketSpec.scala:130)
[error] play.it.http.websocket.NettyWebSocketSpec$.closeWhenTheConsumerIsDone(WebSocketSpec.scala:29)
[error] play.it.http.websocket.WebSocketSpec$$anonfun$5$$anonfun$apply$97$$anonfun$apply$110.apply(WebSocketSpec.scala:381)
[error] play.it.http.websocket.WebSocketSpec$$anonfun$5$$anonfun$apply$97$$anonfun$apply$110.apply(WebSocketSpec.scala:381)
[error] play.it.ServerIntegrationSpecification$$anonfun$around$1.apply(ServerIntegrationSpecification.scala:31)
[error] play.it.ServerIntegrationSpecification$class.around(ServerIntegrationSpecification.scala:31)
[error] play.it.http.websocket.NettyWebSocketSpec$.around(WebSocketSpec.scala:29)

**Comment by marcospereira** [comment]
@benmccann it is not a test flake. I was able to reproduce it locally. I will take a look tomorrow. ;-)

**Comment by gmethvin** [comment]
@marcospereira did you find the issue here?

**Comment by marcospereira** [comment]
@gmethvin did had time to invest in this PR the last couple days.

**Comment by marcospereira** [comment]
@gmethvin,

Build is green and everything is working as expected after a rebase to master. Probably the test failure was related to some deprecated code (removed by @jroper). So this is safe to merge for master, but it MUST NOT be backported to 2.5.x as is.

**Comment by mkurz** [comment]
@marcospereira Will you provide a PR for backporting?

**Comment by marcospereira** [comment]
@mkurz probably not until next week. I'm using some spare time just to keep track of my current open PR. If you have time, feel free to backport it. ;-)

**Comment by wjtan** [comment]
The upgrade to akka 2.4.3 is not backport to play 2.5.2. Play 2.5.2 still depends on akka 2.4.2.

**Comment by gmethvin** [comment]
@wjtan Yes, I just noticed this. I thought we had backported this. Anyway, the workaround is very simple: just explicitly add akka 2.4.3 (or 2.4.4) as a dependency in your project.

**Pull request merged**
