### PR TITLE
Header

### PR DESCRIPTION
**Pull request by echosudan**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @echosudan,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by mkurz** [comment]
@echosudan Could you please sign the CLA? It's very easy, just a few clicks. Thanks!

**Comment by mkurz** [comment]
Ping @echosudan

**Comment by mkurz** [comment]
Replace with #5784

**Pull request closed without merging**
