### PR TITLE
Fix #5761: Create interface traits for compile-time DI components

### LINKED ISSUE #5761: There is no CacheComponents trait for compile time DI
- Play Version 2.5.0-RC2
- API: Scala
- Module: cache

In play/api/cache/Cache.scala there is EhCacheComponents trait that is supposed to provide cache components for compile time DI. However, there is no general CacheComponents trait that can be used to define a dependency on cache without requiring a concrete implementation (EH Cache). There should be a CacheComponents trait.

I'm creating this issue toghether with proposing a PR.

### PR DESCRIPTION
**Pull request by povder**
Fixes #5761

### CODE REVIEW

**Comment by wsargent** [comment]
Hi @povder -- can you provide a test for this?

**Comment by povder** [comment]
Hi @wsargent. I'd be happy to provide a test for this, but I'm not sure how to do this. I'm not familiar with play's test framework but I can see, that there is `WithApplication` trait that can be used to execute tests within a context of a fake application. This application uses Guice application builder by default, I couldn't find other tests that test compile time DI components. Of course I can come up with something by myself, but any guidance by somebody familiar with testing play would be great. Is there any existing approach for testing compile-time DI components provided by Play?

**Comment by gmethvin** [comment]
@povder You would just create and build your components the same way you do normally. You might want to use `WithApplicationLoader` (you can subclass it for your custom loader).

A few more traits you could add along the same lines:
* `ConnectionPoolComponents` (`BoneCPComponents` and `HikariCPComponents`)
* `WSComponents` (`NingWSComponents` and `AhcWSComponents`).

We should go though the existing `*Components` classes and add the self types as well.

**Comment by povder** [comment]
@wsargent @gmethvin I implemented a test for my change. I had to create some utility class that can be used like WithApplication but for compile time DI - please verify if I went in the correct direction with it.

@gmethvin I'll look through other *Component traits and make analogous changes, either as part of this PR or I'll submit another.

**Comment by povder** [comment]
@gmethvin I went through the existing *Components traits and made appropriate changes

**Comment by mkurz** [comment]
@povder Tests fail, see here:
https://travis-ci.org/playframework/playframework/jobs/113261584#L573-L578

**Comment by povder** [comment]
@mkurz, yes, documentation failed to build, will fix this very soon

**Comment by povder** [comment]
@mkurz: fixed

**Comment by gmethvin** [comment]
Hi @povder,

After some discussion I think we've decided we don't need the self types for our built in traits, and there's no need for the `Default*` traits either. This way self types will still work as expected for people who want to use them, but we wont break anything (or slow down compilation time) for everyone else.

**Comment by povder** [comment]
Closing this, see the discussion here: https://groups.google.com/forum/#!topic/play-framework-dev/87vSkU9Foz0/discussion

**Pull request closed without merging**
