### PR TITLE
Reads.IsoDateReads pattern with milliseconds

### PR DESCRIPTION
**Pull request by infm**
This is the fix for #3764

### CODE REVIEW

**Comment by infm** [comment]
There's one issue though - tests don't work on CI platform..

**Comment by jroper** [comment]
Rather than appending millis before formatting, I think it would be nicer to run a heuristic on it to work out whether millis are there or not, and then parse using a format that contains millis or not.

**Comment by cchantep** [comment]
Let's try with a fallback strategy: https://github.com/cchantep/playframework/commit/aac0068cef78268544102cb34a44dcc9c0dad4b5

Validated @ https://travis-ci.org/cchantep/playframework/builds/49495344#L300

**Comment by jroper** [comment]
I wonder how that performs.

**Comment by cchantep** [comment]
?

**Comment by jroper** [comment]
Well, you're passing potentially 4 times, with potentially 3 exceptions thrown - that's not very fast.  In contrast, running the following regexes would over the date would be very fast, and would tell you what sort of date it is:

    ^.*\.\d\d\d$
    ^.*\.\d\d\d.*$
    ^.*:\d\d$

**Comment by cchantep** [comment]
@jroper Updated: https://github.com/cchantep/playframework/compare/fix-3764?expand=1#diff-9ea77db53c6fab35be2599c362a8d529R270

**Comment by cchantep** [comment]
See original PR #3764

**Pull request closed without merging**
