### PR TITLE
Remove deprecated CacheApi usages (#7805)

### LINKED ISSUE #7805: CacheApi and CacheApi hacks should be removed
There are several places in the `EhCacheApi` impl that use `SyncCacheApi with CacheApi` to implement both. We should remove these hacks and simplify the code for 2.7.0, since we can then remove the deprecated `CacheApi`.

### PR DESCRIPTION
**Pull request by srirachapills**
## Fixes

Fixes #7805

## Purpose

Remove deprecated `CacheApi` usages in `EhCacheApi`.

### CODE REVIEW

**Comment by gmethvin** [comment]
Shouldn't we also remove the actual `CacheApi` interfaces then?

**Comment by srirachapills** [comment]
Should we remove `DefaultSyncCacheApi#getOrElse`?

**Comment by srirachapills** [comment]
Documentation for 2.4 migration (`Migration24.md`) still references `CacheApi`, so I'm not sure I should deal with this.

**Comment by gmethvin** [comment]
Migration guides should not be updated. They document migration to that version.

**Comment by gmethvin** [comment]
You can just make it regular text rather than a link in the migration guide so the docs will compile.

**Pull request merged**
