### PR TITLE
Make the JacksonJson module public so that it can be reused. 

### LINKED ISSUE #3880: Allow for custom jackson dataformats in play-json
There are a number of interesting dataformats available for jackson, including:
- [MsgPack](https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson)
- [Yaml](https://github.com/FasterXML/jackson-dataformat-yaml)
- [Smile](https://github.com/FasterXML/jackson-dataformat-smile)

This probably involves transforming `JacksonJson` into a class that accepts a custom json factory.

### PR DESCRIPTION
**Pull request by kanuku**
Fixes #3880.

### CODE REVIEW

**Comment by gmethvin** [comment]
I'm not sure how this fixes #3880. `JacksonJson` has no public API to allow you to set or modify the `ObjectMapper`.

**Comment by kanuku** [comment]
The `ObjectMapper` can now be passed as an implicit parameter, when using `JacksonJson`.

**Comment by gmethvin** [comment]
Hi @kanuku,

I think the goal should be to allow you to configure the ObjectMapper in a way that allows for custom formats, etc., but makes also sure `JsValue` and related types are supported. I think that will ultimately mean using dependency injection in some way instead of statics, but the dependency should probably be on a component with configuration specific to play-json instead of just `ObjectMapper`.

Having a direct dependency on `ObjectMapper` is bad since the `ObjectMapper` needs to be configured in particular way for it to work with `JsValue`. If you call `parseJsValue("{}")(new ObjectMapper())` it won't work as expected.

Anyway, this is something that I think requires much more thought to get right. Perhaps we should discuss on the mailing list?

**Comment by mkurz** [comment]
Can this be closed?

**Pull request closed without merging**
