### PR TITLE
Fix many scaladoc and javadoc warnings in apiDocs task.

### PR DESCRIPTION
**Pull request by eboto**
Also:
  * Add autoAPIMappings to SBT build so we can link into the scala standard library
  * Get inter-project external refs working in apiDocs
  * Remove javadoc links in scaladoc, and hardcode them as web links instead

Addresses #4995 

Also, sorry for this grossly large PR. Made my best stab on some of this documentation but would definitely appreciate any fixes on accuracy.

### CODE REVIEW

**Comment by eboto** [comment]
@jroper you may also want to examine my pr against your code generator here https://github.com/jroper/play-source-generator/pull/1

**Comment by eboto** [comment]
I don't really understand this build failure. It appears that javadoc warnings are now being reported as Errors. I assume this must be due to my change, but the issue continues even if I back off all of my changes to `project/*.scala`

Any ideas?

**Comment by eboto** [comment]
@jroper Any plan to review these changes? I don't want them to become stale.

**Comment by eboto** [comment]
@jroper what is the status of this PR? If it's OK to merge then can we merge it? If it's not OK then I can  clean it up to meet standards.

**Comment by richdougherty** [comment]
@eboto I think you deserve some sort of prize for fixing all those warnings! :cake: Great work, thanks a lot.

Sorry about the late review, some of the Play team have been a bit distracted with other tasks recently.

**Comment by jroper** [comment]
:star: awesome!

**Pull request merged**
