### PR TITLE
Enable evolutions lock using Mysql InnoDB.

### PR DESCRIPTION
**Pull request by brightgenerous**
Evolutions lock is enabled even Mysql InnoDB not only PostgreSQL and Oracle.
were divided script String according to the jdbc url.

### CODE REVIEW

**Comment by marcospereira** [comment]
@brightgenerous, 

Could you please also change the docs to reflect this change? Search for `useLocks ` at file manual/detailedTopics/evolutions/Evolutions.md.

**Comment by brightgenerous** [comment]
just now. changed the docs about useLocks.

**Comment by marcospereira** [comment]
@brightgenerous thank you very much. Could you please squash the two commits?

**Comment by brightgenerous** [comment]
squashed the two commits. sorry, I had forgotten it.

**Pull request merged**
