### PR TITLE
Deprecate rc4 in master

### PR DESCRIPTION
**Pull request by wsargent**
Forward port of https://github.com/playframework/playframework/pull/4246

### CODE REVIEW

**Comment by jroper** [comment]
scalariform check failed

**Comment by benmccann** [comment]
@wsargent can you take a look at fixing the scalariform errors?

>--- a/framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Ciphers.scala
+++ b/framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Ciphers.scala
@@ -134,7 +134,6 @@ object Ciphers {
                      |TLS_KRB5_EXPORT_WITH_RC4_40_MD5
                    """.stripMargin.split("\n").toSet
 
-
   val rc4Ciphers = """SSL_DH_anon_EXPORT_WITH_RC4_40_MD5
                      |SSL_DH_anon_WITH_RC4_128_MD5
                      |SSL_RSA_EXPORT_WITH_RC4_40_MD5
ERROR: Scalariform check failed, see differences above.
To fix, format your sources using ./build scalariformFormat test:scalariformFormat before submitting a pull request.

**Comment by wsargent** [comment]
@benmccann will do.

**Comment by wsargent** [comment]
@play-pull-request-validator please run again.

**Comment by marcospereira** [comment]
@play-pull-request-validator build failed with:

```
[error] Error: Total 416, Failed 12, Errors 143, Passed 260, Skipped 1, Pending 26
[error] Error during tests:
[error] 	play.it.http.NettyFormFieldOrderSpec
[error] 	play.it.mvc.AkkaDefaultHttpFiltersSpec
[error] 	play.it.http.AkkaHttpScalaResultsHandlingSpec
[error] 	play.it.action.NettyHeadActionSpec
[error] 	play.it.http.websocket.NettyWebSocketSpec
[error] 	play.it.http.AkkaHttpFormFieldOrderSpec
[error] 	play.it.http.NettyJavaResultsHandlingSpec
[error] 	play.it.AkkaHttpServerIntegrationSpecificationSpec
[error] 	play.it.libs.NettyWSSpec
[error] 	play.it.http.assets.AkkaHttpAssetsSpec
[error] 	play.it.http.AkkaHttpJavaResultsHandlingSpec
[error] 	play.it.mvc.NettyGlobalFiltersSpec
[error] 	play.it.http.NettyScalaResultsHandlingSpec
[error] 	play.it.http.assets.NettyAssetsSpec
[error] 	play.it.libs.AkkaHttpWSSpec
[error] 	play.it.http.NettyFlashCookieSpec
[error] 	play.it.NettyServerIntegrationSpecificationSpec
[error] 	play.it.action.AkkaHttpHeadActionSpec
[error] 	play.it.http.AkkaHttpFlashCookieSpec
[error] 	play.it.mvc.NettyDefaultFiltersSpec
[error] (Play-Integration-Test/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (Play-Akka-Http-Server-Experimental/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (Play-Java-WS/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (Filters-Helpers/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (Play-WS/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 321 s, completed May 7, 2015 11:50:26 PM
```

**Comment by wsargent** [comment]
@marcospereira Thx -- added a filter on recommendedCiphers to removed deprecated.

**Pull request merged**
