### PR TITLE
Migrate from Hamcrest/FEST-Assert to AssertJ (test sources)

### PR DESCRIPTION
**Pull request by ihostage**
It's a first small step for
- #11839

I'm still thinking we should migrate to AssertJ firstly instead of rewrite assertion expressions twice (Hamcrest -> JUnit5 -> AssertJ).

In this part I remove using Hamcrest in sources. The second part will be related to documentation.

### CODE REVIEW

**Comment by ihostage** [comment]
@Mergifyio rebase

**Comment by mkurz** [comment]
@ihostage Looking at this very soon.

**Comment by mkurz** [comment]
@Mergifyio rebase

**Review by mkurz — APPROVED** [review]
OK, after reading through
- #11839

I get it.

Hamcrest is dead more or less:
- https://github.com/hamcrest/JavaHamcrest/commits/master/
- https://github.com/hamcrest/JavaHamcrest/tags (almost 5 years no release)
- https://groups.google.com/g/hamcrest-dev/c/lYcF3lz8JDQ
- https://github.com/hamcrest/JavaHamcrest/issues/405

And I don't know how we still use a 13 year old outdated library :wink: 
- https://repo1.maven.org/maven2/org/easytesting/fest-assert/1.4/
- https://github.com/easytesting/fest-assert-core

Seems like assertj is the way to got now.

**Pull request merged**
