### PR TITLE
Update SecureFlagSpec to test HTTP/2

### PR DESCRIPTION
**Pull request by richdougherty**
We can remove lots of the custom SSL test code since that's now part of our integration testing code.

### CODE REVIEW

**Comment by richdougherty** [comment]
This was previously part of #7941 but I was having trouble getting that PR to pass on Travis so I've cherry-picked it into a new PR.

**Comment by richdougherty** [comment]
OK, so this integration test somehow interacts with `play.it.JavaServerIntegrationTest` causing it to fail. This was a [source of mystery on #7941](https://github.com/playframework/playframework/pull/7941#issuecomment-338002554).

**Comment by mkurz** [comment]
@richdougherty Can you resolve the conflict?

**Comment by mkurz** [comment]
@marcospereira CI fails, formatting issue.

**Comment by marcospereira** [comment]
Format issue fixed.

**Pull request merged**
