### PR TITLE
[2.6.x] Use error.invalid when form binding fails and messages are empty

### LINKED ISSUE #8318: errorsAsJson with mocked MessagesApi throws java.util.NoSuchElementException (TestCase provided)
### Play Version (2.5.x / etc)
2.6.11

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
JDK 9.0.4

### Library Dependencies
N/A

### Expected Behavior
No exception is thrown

### Actual Behavior
I want my tests to be language independent, thus I want `form.errorsAsJson()` to return error keys instead of translations.
In order to do that I mocked MessagesApi as documentation specifies:
```
public class MyTest extends WithApplication {

  private MessagesApi emptyMessagesApi() {
    return new play.i18n.MessagesApi(new play.api.i18n.DefaultMessagesApi(
        Collections.singletonMap(Lang.defaultLang().code(), Collections.emptyMap()),
        new play.api.i18n.DefaultLangs().asJava()));
  }

  @Override
  protected Application provideApplication() {
    GuiceApplicationBuilder builder = new GuiceApplicationBuilder()
        .in(Environment.simple())
        .overrides(bindings.add(Bindings.bind(MessagesApi.class).toInstance(emptyMessagesApi())));

    Guice.createInjector(builder.applicationModule()).injectMembers(this);
    Application application = builder.build();
    return application;
  }

  public Application getApplication() {
    return app;
  }

//here test making call to controller
}
```

While calls to `messages.at("someKey")` work fine, trying to call `form.errorsAsJson()` throws:
```
[error] Test controllers.MyControllerTest.shouldValidateRequiredFields failed: java.util.NoSuchElementException: null, took 0.881 sec
[error]     at java.util.ArrayList$Itr.next(ArrayList.java:896)
[error]     at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:40)
[error]     at scala.collection.IterableLike.head(IterableLike.scala:106)
[error]     at scala.collection.IterableLike.head$(IterableLike.scala:105)
[error]     at scala.collection.AbstractIterable.head(Iterable.scala:54)
[error]     at scala.collection.TraversableLike.last(TraversableLike.scala:431)
[error]     at scala.collection.TraversableLike.last$(TraversableLike.scala:430)
[error]     at scala.collection.AbstractTraversable.last(Traversable.scala:104)
[error]     at play.api.i18n.DefaultMessagesApi.$anonfun$apply$3(Messages.scala:473)
[error]     at scala.Option.getOrElse(Option.scala:121)
[error]     at play.api.i18n.DefaultMessagesApi.apply(Messages.scala:473)
[error]     at play.i18n.MessagesApi.get(MessagesApi.java:106)
[error]     at play.data.Form.lambda$errorsAsJson$14(Form.java:750)
[error]     at java.util.ArrayList.forEach(ArrayList.java:1380)
[error]     at play.data.Form.errorsAsJson(Form.java:744)
[error]     at play.data.Form.errorsAsJson(Form.java:734)
[error]     at controllers.common.MyController.bindForm(MyController:20)
```

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #8318 for the 2.6.x branch.

See https://github.com/playframework/playframework/issues/8318#issuecomment-455814157 for explanation.

### CODE REVIEW

**Comment by mkurz** [comment]
@dwijnand Same here :wink:

**Comment by dwijnand** [comment]
Could you forward port please?

**Comment by mkurz** [comment]
Sure (however I have to open a pull request, I don't have direct push access to a branch if you mean that.)

**Comment by dwijnand** [comment]
All done.  I just didn't want either one of us to forget.

**Pull request merged**
