### PR TITLE
Create NewApplication.md

### PR DESCRIPTION
**Pull request by borromeotlhs**
Giving a little more hints to sbt newbies so they don't search the world to figure out why sbt run off the bat will complain about no main.  Also, included a little tidbit about running sbt server off a non-standard port to save the carbon footprint that results from the inevitable google search for "sbt run port x". . .

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @borromeotlhs,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by borromeotlhs** [comment]
I won't sign a contribution as I'm updating documentation.  Please place your documentation under a license other than the code, and possibly host them separately such that I am not subject to onerous terms/contracts.   Also, a simple recognized oss license is the extent I'd be willing to agree to, implicitly, as I work for a living and don't want to create a covenant with anyone who isn't paying me.

**Comment by gmethvin** [comment]
@borromeotlhs Unfortunately signing the CLA is a requirement to make any contribution to this project, including documentation.

By contributing to this project you already are agreeing to license your code under the same license Play Framework uses, the Apache 2 license. The CLA does not change this. The CLA transfers the copyright and patent rights for your contributions to a single legal entity, Lightbend Inc. This allows us to enforce the license without getting every contributor involved, and allows us to relicense or dual-license the project if we need to in the future. It also protects you as a contributor from being liable in a copyright infringement suit.

If you're not comfortable with the CLA requirement, you can go ahead and close the pull request.

**Comment by gmethvin** [comment]
This change should also be on master: https://github.com/playframework/playframework/blob/master/documentation/manual/gettingStarted/NewApplication.md

**Comment by borromeotlhs** [comment]
Agreed that I'd like to dislcaim the contributions, but for documentation,
I'd think you'd want a CC0 v1.0 license for it to do exactly that.
Especially in light of the gpl being found a contract, I think that the
right license, with US and international recognition for documentation,
would be much clearer and better for everyone.

Regards,
TJ Borromeo
www.linkedin.com/in/tjborromeo

**Comment by gmethvin** [comment]
If you have concerns about the licensing overall, a good forum for that would probably be [the dev mailing list](https://groups.google.com/forum/#!forum/play-framework-dev) rather than on this issue. We have already applied CC0 to seed/example projects, for example: https://github.com/playframework/play-scala-seed.g8/blob/2.5.x/LICENSE

The great thing about having a CLA, though, is we can change licenses much more easily, since we already have the copyright. But again, the CLA is a separate agreement from the actual open source license the code is released under.

**Comment by richdougherty** [comment]
@borromeotlhs, I appreciate the effort to contribute, but it looks like we're stalled on a legal point now. Shall we close this PR?

**Comment by borromeotlhs** [comment]
yes.  I won't be signing any contracts.  thanks.

**Comment by richdougherty** [comment]
OK, I'll close this one now.

**Pull request closed without merging**
