### PR TITLE
Rename URL to URI. Allow URI to be relative. Fix flash/session copy paste error

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
@jroper @dotta thanks for the review on the last PR. this one fixes the issues you identified that I left for later

**Comment by benmccann** [comment]
@play-pull-request-validator try to get past the flakiness

**Comment by jroper** [comment]
@benmccann our CI server really doesn't like you - I haven't seen any of this flakiness over the past week for my PRs.

**Comment by jroper** [comment]
Do we have a `.path` method as well?

**Comment by benmccann** [comment]
Hmm, weird. I figured everyone was seeing a failure here or there

I hadn't added a path method, but we certainly could. I'm pretty sure `FakeRequest` didn't either, so I figured we didn't need it to reach parity, but have no problem adding it. My only question was for getting the path if we'd want to return the raw path, encoded path, or options of both. We could add a `path()` and a `rawPath()` to match the underlying `URI`

**Comment by jroper** [comment]
I'd say path should just manipulate the raw path, since it's only path segments that get encoded/decoded, if you encode/decode the whole path, you end up losing the difference between `/` and `%2F`.

**Comment by benmccann** [comment]
Sounds good. path added

**Pull request merged**
