### PR TITLE
Post binary data 'as is' with play-ws client.

### PR DESCRIPTION
**Pull request by andreyk0**
Only apply HttpHeaders.Values.APPLICATION_X_WWW_FORM_URLENCODED work
around when needed.

### CODE REVIEW

**Comment by marcospereira** [comment]
LGTM.

@wsargent, what do you think?

**Comment by jroper** [comment]
lgtm

**Comment by andreyk0** [comment]
Hey, guys!
Thanks for reviews, do I need to do anything else to get it merged?

**Comment by marcospereira** [comment]
Backport here: fc284ab

**Comment by wsargent** [comment]
@marcospereira LGTM

**Pull request merged**
