### PR TITLE
Update template build parameters to latest

### PR DESCRIPTION
**Pull request by corruptmemory**
* sbt: 0.13.8
* Scala: 2.11.6

### CODE REVIEW

**Comment by marcospereira** [comment]
@corruptmemory thank you!

Could you also check the versions of these template parameters:

https://github.com/playframework/playframework/blob/master/templates/build.sbt#L33-L48

If you don't have the time right now to do these updates, please let me know.

**Comment by corruptmemory** [comment]
That's kinda interesting, so on master they aren't taking the versions as properties will fallbacks.

For my purposes the only I can comment on is the sbt version, which is correct (for now :-))

**Comment by pvlugter** [comment]
I don't see an update to the scala version?

https://github.com/corruptmemory/Play20/blob/update-latest-template-stuff/templates/build.sbt#L39

**Comment by jroper** [comment]
I've done this change directly here: a3741dc

**Pull request closed without merging**
