### PR TITLE
[2.5.x]: Fix empty query string parse

### LINKED ISSUE #7028: [2.5.x]: FakeRequest has a query-string of at least size 1
Regardless the `FakeRequest` object I am creating, its query-string has always a query-string of size 1, which is `Map( -> ArrayBuffer())`.
I would have thought the query-string to be empty.

### Expected Behavior
When I create a `FakeRequest` object without parameters in the `uri`, I expect the query-string to be an empty map.

### Actual Behavior
The `FakeRequest` object without parameters in the `uri` has instead this query-string:
`Map( -> ArrayBuffer())`

### Reproducible Test Case
```
      val params = Map(
        "client_id" -> Seq("cid"),
        "client_secret" -> Seq("secret")
      )

      val fakeReq1 = new FakeRequest (
        method = "POST",
        uri = "/",
        headers = FakeHeaders(),
        body = AnyContentAsFormUrlEncoded(params))

      println ("query-string: " + fakeReq1.queryString)
      // query-string: Map( -> ArrayBuffer())
      println ("query-string size: " + fakeReq1.queryString.size)
      // query-string size: 1


      val fakeReq2 = new FakeRequest (
        method = "POST",
        uri = "/",
        headers = FakeHeaders(),
        body = AnyContentAsFormUrlEncoded(params)
      ) {
        // this is the workaround I used to make it working
        override lazy val queryString: Map[String, Seq[String]] = Map.empty
      }

      println ("query-string: " + fakeReq2.queryString)
      // query-string: Map()
      println ("query-string size: " + fakeReq2.queryString.size)
      // query-string size: 0
```

### PR DESCRIPTION
**Pull request by marcospereira**
## Purpose

Returns an empty Map when parsing URIs with empty query string.

## Fixes

Fixes #7028.

### CODE REVIEW

**Comment by benmccann** [comment]
Typically we merge code to master first and then backport. Is this already in master?

**Comment by marcospereira** [comment]
@benmccann see #7061.

**Comment by JanRudert** [comment]
:+1: would be great to have this soon. Thank you guys!

**Comment by benmccann** [comment]
Thanks for the pointer to master @marcospereira

**Pull request merged**
