### PR TITLE
[2.7] Fix formatting

### PR DESCRIPTION
**Pull request by mkurz**
Fixes the `2.7.x` branch, see #9118

### CODE REVIEW

**Comment by mkurz** [comment]
#9103 takes care of this already.

**Comment by marcospereira** [comment]
There is a compilation problem for Scala 2.11 though (see the build).

**Comment by marcospereira** [comment]
Anyway, we can fix both in #9103.

**Comment by mkurz** [comment]
@marcospereira Done already, see #9103

**Pull request closed without merging**
