### PR TITLE
Don't allow SSLv3 by overwriting the default.

### PR DESCRIPTION
**Pull request by Xarno**
http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#DisabledAlgorithms

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @Xarno,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by Xarno** [comment]
Come on 3 pages CLA for 6 added characters, be reasonable.

**Comment by Xarno** [comment]
@wsargent, I could, but the ssllabs test shows this is not necessary.
https://www.ssllabs.com/ssltest/analyze.html?d=logs.aws.corussoft.de

**Comment by wsargent** [comment]
@Xarno the cipher suites containing RC4 are all excluded in Play WS already, which is why you don't see them.  They could still show up in global SSLContext, which is what the documentation you are changing addresses.  RC4 is already gone per IETF: https://tools.ietf.org/html/rfc7465

**Comment by typesafehub-validator** [comment]
Hi @Xarno,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by richdougherty** [comment]
@Xarno, just wondering if you're willing to sign the CLA for this contribution?

**Comment by Xarno** [comment]
Not really, i can not see any Intellectual Property in <10 Character edits.
This would be like saying: „Oh you have a typo there this is the correct spelling: …“ and then wanting a citation note. That's just ridiculous.

**Pull request closed without merging**
