### PR TITLE
Update ModuleDirectory.md

### PR DESCRIPTION
**Pull request by jbloemendal**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* [x] Have you added copyright headers to new files? **_I didn't add new files._**
* [x] Have you checked that both Scala and Java APIs are updated? **_Just documentation._**
* [x] Have you updated the documentation for both Scala and Java sections? **_It is a java module_**
* [x] Have you added tests for any changed functionality? **_I didn't change codes_**

## Fixes

I didn't change code.

## Purpose

What does this PR do?

Adding a module reference (documentation), which is hosted on github (https://github.com/jbloemendal/play-hippo). 

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @jbloemendal,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by mkurz** [comment]
I am not entirely sure if this should go below the "Datastore" section.

**Comment by jbloemendal** [comment]
You could create a section "CMS".

**Comment by jbloemendal** [comment]
Thanks!

**Pull request merged**
