### PR TITLE
Documentation: Websockets support in Apache 2.4

### PR DESCRIPTION
**Pull request by Wlanez**

### CODE REVIEW

**Comment by dotta** [comment]
@Wlanez Hey, looks like something went wrong with your commits :-) Here my suggestion for cleaning things up 

```terminal
git checkout master
git fetch <playframework-git-remote-name>
git merge origin/master
git checkout -b patch-3-second-try
git cherry-pick <commit-hash-from-this-pr-you-need>
(if you need to cherry-pick more than one commit, repeat the above step for all the needed commits)
git push <your-playframework-fork-git-remote-name> patch-3-second-try 
```
Then, open a new PR for the branch you just pushed to your remote (i.e., `patch-3-second-try` if you used the above steps), and close this PR.

**Comment by dotta** [comment]
Or, if you are fluent with git, rebasing your PR should be sufficient.

**Comment by dotta** [comment]
@Wlanez Ping.

**Comment by Wlanez** [comment]
@dotta thank you, I just update my branch and send a third try PR

**Comment by dotta** [comment]
@Wlanez I don't seem to be able to find your other PR (it's not in here https://github.com/playframework/playframework/pulls/Wlanez).

**Comment by benmccann** [comment]
Since this PR can't be merged I added the note manually myself in https://github.com/playframework/playframework/commit/dd23c29b8a5a3c1f981e938eed5b1a3b49828c4f and am going to close this one

**Pull request closed without merging**
