### PR TITLE
Prefer immutable seq's

### PR DESCRIPTION
**Pull request by ignasi35**
This is a rewrite of https://github.com/playframework/playframework/pull/9412 for `master`.

### CODE REVIEW

**Comment by dwijnand** [comment]
```
[error]  * method apply(java.util.List)scala.collection.mutable.Buffer in object views.html.helper.options has a different result type in current version, where it is scala.collection.Seq rather than scala.collection.mutable.Buffer
[error]    filter with: ProblemFilters.exclude[IncompatibleResultTypeProblem]("views.html.helper.options.apply")
```

**Comment by ignasi35** [comment]
I had Marco's https://github.com/playframework/playframework/pull/9412#discussion_r296496125 in mind and remove the MiMa without putting it back in the right place. 🤦🏼‍♂️

**Comment by ignasi35** [comment]
Three of the Java 11 jobs in Travis failed with:

```
[info] Loading project definition from /home/travis/build/playframework/playframework/project
[warn] 	module not found: com.typesafe.play#twirl-compiler_2.12;1.5.0-M2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/twirl-compiler_2.12/1.5.0-M2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/twirl-compiler_2.12/1.5.0-M2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/travis/.ivy2/local/com.typesafe.play/twirl-compiler_2.12/1.5.0-M2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/twirl-compiler_2.12/1.5.0-M2/twirl-compiler_2.12-1.5.0-M2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/travis/.sbt/preloaded/com.typesafe.play/twirl-compiler_2.12/1.5.0-M2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/travis/.sbt/preloaded/com/typesafe/play/twirl-compiler_2.12/1.5.0-M2/twirl-compiler_2.12-1.5.0-M2.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/play/twirl-compiler_2.12/1.5.0-M2/twirl-compiler_2.12-1.5.0-M2.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#twirl-compiler_2.12;1.5.0-M2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.play:twirl-compiler_2.12:1.5.0-M2
[warn] 		  +- com.typesafe.sbt:sbt-twirl:1.5.0-M2 (scalaVersion=2.12, sbtVersion=1.0) (/home/travis/build/playframework/playframework/project/plugins.sbt#L31-32)
[warn] 		  +- default:playframework-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
```

All Java 8 worked fine. This is weird because the dependency exists. Maybe those 3 Java11 jobs run on a machine with a dirty http proxy-cache in front of it?

**Comment by ignasi35** [comment]
travis is having some issues downloading deps (after deleting the PR cache, jackson-core and webjars fail too)

**Comment by ignasi35** [comment]
Travis' caches have been acting up like I can't remember when... Over 16h of retried jobs to get this merged because Travis was failing to download artifacts. 😡

**Pull request merged**
