### PR TITLE
Upgrade to SBT Native Packager 1.0.0-M5

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by muuki88** [comment]
LGTM

**Comment by jroper** [comment]
@muuki88 When do you anticipate a 1.0.0 release?  There's no rush, we're not planning on releasing Play 2.4 until April, but we'll definitely need a 1.0.0 release before then for this to go in.

**Comment by muuki88** [comment]
There is no exacte date. @jsuereth and I thought it would be a good idea to release it with SBT 1.0.0.
However if 1.0.0-M4 works fine with play we can release it earlier.

**Comment by benmccann** [comment]
What do you guys think of this one then? I believe the thought was that it would be helpful for testing native packager and getting it to the 1.0 release

**Comment by jroper** [comment]
I don't want to upgrade if there's not going to be a final release before April.  But if @muuki88 is happy to make a final release for Play whether SBT 1.0.0 is ready or not, then I'm ok with it.  @jsuereth what do you think about that?

**Comment by muuki88** [comment]
Actually there are only two issues before `1.0.0` can be released

1. The docker refactoring. I want this done before a final release, so we don't have to make (binary) incompatible changes
2. Integration with play works smooth

The first point will hopefully be done in february. We could keep this PR open
and adjust on a `RC` release of sbt-np

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by benmccann** [comment]
@muuki88 it looks like the Docker refactoring is done, so I've upgraded this PR to M5

Should we merge this now?

**Comment by benmccann** [comment]
@play-pull-request-validator try again

> [error] Error: Total 381, Failed 0, Errors 1, Passed 254, Skipped 126
[error] Error during tests:
[error] 	play.it.http.assets.NettyAssetsSpec
[error] (Play-Integration-Test/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1814 s, completed Feb 21, 2015 10:14:58 PM

**Comment by benmccann** [comment]
@play-pull-request-validator  try again

>[error] Failed: Total 329, Failed 1, Errors 0, Passed 328
[error] Failed tests:
[error] 	javaguide.cache.JavaCache
[error] (Play-Documentation/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 90 s, completed Feb 22, 2015 1:49:15 AM

**Comment by huntc** [comment]
On the release date, we have an Typesafe commercial project that is to be released at the end of March. There's a dependency on the native packager so it'd be great to have it go 1.0.0 before then.

@muuki88 Is there anything we can do to expedite a release for you? We're pretty snowed under right now, but I'm hoping that they'll be a few cycles spare during March.

**Comment by huntc** [comment]
Nice work btw @benmccann . We've also made some notes re. using the native-packager for Play 2.3:

https://github.com/sbt/sbt-bundle#usage

You might also need to check the Play doco/samples to see if there's any of the following sort of thing going on in sbt files (it is no longer required):

```scala
import com.typesafe.sbt.SbtNativePackager._
import NativePackagerKeys._
```

**Comment by muuki88** [comment]
@benmccann , yep the docker refactoring is done and we haven't had negative feedbacks so far. In the next days I'll cut of a release candidate and hopefully the release very soon after.

@huntc Only the windows part is tricky (messy). There are only one or two tickets that are really a blocker, but should be easily solvable.

**Comment by benmccann** [comment]
@play-pull-request-validator try again

>[error] Error: Total 381, Failed 0, Errors 1, Passed 254, Skipped 126
[error] Error during tests:
[error] 	play.it.http.assets.NettyAssetsSpec
[error] (Play-Integration-Test/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1585 s, completed Feb 22, 2015 8:30:22 PM

**Comment by benmccann** [comment]
@huntc I've updated the docs

**Pull request merged**
