### PR TITLE
Fix typo on JavaDatabase.md (DB -> db)

### PR DESCRIPTION
**Pull request by Uxio0**
# Pull Request Checklist

* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @Uxio0,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by mkurz** [comment]
@Uxio0 Could you please sign the CLA? It's just a few clicks.

**Comment by marcospereira** [comment]
I don't think this is a typo but, instead, it looks like a use of the [deprecated DB api](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-java-jdbc/src/main/java/play/db/DB.java#L14-L19) to [get a database connection](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-java-jdbc/src/main/java/play/db/DB.java#L39-L47). A better alternative here is to externalize this code snippet with and update it to use the new `play.db.Database` API.

**Comment by Uxio0** [comment]
I thought it was refering the previous example:

`class JavaNamedDatabase extends Controller {
    @Inject @NamedDatabase("orders") Database db;
    // do whatever you need with the db
}`

And then:

> You can retrieve a JDBC connection the same way:

https://www.playframework.com/documentation/2.5.x/JavaDatabase#Accessing-the-JDBC-datasource

**Comment by marcospereira** [comment]
@Uxio0 got it. So, could you instead move the example code to an external .java file? Both `JavaApplicationDatabase.java` and `JavaNamedDatabase.java` are goods places.

**Comment by Uxio0** [comment]
Ok, I think that was what you wanted, I created a new pull request, maybe you can close this:

https://github.com/playframework/playframework/pull/5885

**Pull request closed without merging**
