### PR TITLE
change uri parse path error from warn to debug

### PR DESCRIPTION
**Pull request by fusuiyi123**
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes https://github.com/playframework/playframework/issues/10072

## Purpose

change uri parse path error from warn to debug

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by ertra** [comment]
Please can I ask, 

was this fixed in version 2.7.9 ? I still get the error there as a warning
2021-07-06 21:19:09,127 [WARN] from play.core.server.akkahttp.AkkaModelConversion in application-akka.actor.default-dispatcher-1033 - Failed to parse path; returning empty string.
java.net.URISyntaxException: Expected authority at index 2: //
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.failExpecting(URI.java:2854)
	at java.net.URI$Parser.parseHierarchical(URI.java:3102)
	at java.net.URI$Parser.parse(URI.java:3063)



regards
tomas

**Comment by mkurz** [comment]
@ertra No, it seems this change made it into 2.8.x only.

**Comment by jtjeferreira** [comment]
@mkurz I dont think this even made it to 2.8.x. Is the backport worth it? Or is 2.9.0 imminent?

**Comment by mkurz** [comment]
@jtjeferreira You are right, never made it into 2.8.x
@Mergifyio backport 2.8.x

**Pull request merged**
