### PR TITLE
Use slf4j parameters for logging instead of string concatenation

### PR DESCRIPTION
**Pull request by Chklang**

### CODE REVIEW

**Comment by benmccann** [comment]
We really prefer that you submit pull requests against the master branch first, so that the changes persist for all future versions of Play that are released. We can always backport the changes once they are merged to master

**Comment by jroper** [comment]
In addition, the changes you made don't actually compile:

```
[error] /home/travis/build/playframework/playframework/documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/Application.java:41: cannot find symbol
[error]   symbol:   variable method
[error]   location: variable request of type play.mvc.Http.Request
[error] request.method
```

Also, when you fix, please squash your commits, for information on how/why, read [here](https://playframework.com/documentation/2.4.x/WorkingWithGit).

**Comment by dotta** [comment]
@jroper @benmccann I guess I'm missing something. Are the changes in this PR really the only places where we shouldn't use string concatenation?

**Comment by benmccann** [comment]
Here' s a list of all the places I see that we're doing string concatenation in logging in the documentation:

./manual/working/scalaGuide/main/ws/code/ScalaOpenIdSpec.scala:      Logger.info("bad request " + error.toString)
./manual/working/scalaGuide/advanced/http/code/FiltersRouting.scala:      Logger.info(s"${action} took ${requestTime}ms" +
./manual/working/scalaGuide/advanced/http/code/ScalaHttpFilters.scala:      Logger.info(s"${requestHeader.method} ${requestHeader.uri} " +
./manual/working/scalaGuide/advanced/http/code/EssentialFilter.scala:        Logger.info(s"${requestHeader.method} ${requestHeader.uri}" +
./manual/working/javaGuide/main/logging/code/javaguide/logging/Application.java:    accessLogger.info("method=" + request.method() + " uri=" + request.uri() + " remote-address=" + request.remoteAddress());
./manual/working/javaGuide/main/logging/code/javaguide/logging/Global.java:    accessLogger.info("method=" + request.method() + " uri=" + request.uri() + " remote-address=" + request.remoteAddress());
./manual/working/javaGuide/main/logging/code/javaguide/logging/JavaLogging.java:      Logger.debug("Result=" + result);
./manual/working/javaGuide/main/http/code/javaguide/http/JavaActionsComposition.java:            Logger.info("Calling action for " + ctx);
./manual/working/javaGuide/main/http/code/javaguide/http/JavaActionsComposition.java:                Logger.info("Calling action for " + ctx);

**Comment by dotta** [comment]
@benmccann Right, so I'm not missing things :-) I guess then this PR should attempt to fix the issue once and for all, and ideally we should also make this a code style rule.

**Comment by benmccann** [comment]
I'm going to close this PR since it seems to have been abandoned. Please feel free to re-open if you've addressed the comments here

A few other things to note that will help you get it merged is that we generally accept changes only to the master branch first and then after they're in master we can merge those changes to older branches. Also, we generally ask people to squash their commits, so that will help as well

Thanks for the PR and please feel free to send again with the changes discussed above

**Comment by mkurz** [comment]
There is a newer PR which also includes these fixes now anyway: #5406

**Pull request closed without merging**
