### PR TITLE
[3.0.x] Fix jjwt 0.12 compatibility for `setExpiration` method

### LINKED ISSUE #12817: Using jjwt 0.12.6 with Play 3.0.5 throws NoSuchMethodError
### Play Version

3.0.5

### API

Scala

### Operating System

macOS

### JDK

17

### Library Dependencies

```scala
val jjwtVersion = "0.12.6"

val jjwts = Seq(
  "io.jsonwebtoken" % "jjwt-api",
  "io.jsonwebtoken" % "jjwt-impl"
).map(_ % jjwtVersion) ++ Seq(
  ("io.jsonwebtoken" % "jjwt-jackson" % jjwtVersion).excludeAll(
    ExclusionRule("com.fasterxml.jackson.core")
  )
)
```

### Expected Behavior

Since #12474 you allow using jjwt 0.12 which is great, however it does not work when setting `play.http.session.maxAge`.

### Actual Behavior

I have read #12474 and this is likely related, when the config value `play.http.session.maxAge` is set, Play will crash with a `java.lang.NoSuchMethodError: 'io.jsonwebtoken.JwtBuilder io.jsonwebtoken.JwtBuilder.setExpiration(java.util.Date)'`  (if `play.http.session.maxAge` is not set, there is no crash).

Here is the stack trace:

```
Uncaught error from thread [application-pekko.actor.default-dispatcher-15]: 'io.jsonwebtoken.JwtBuilder io.jsonwebtoken.JwtBuilder.setExpiration(java.util.Date)', shutting down JVM since 'pekko.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: 'io.jsonwebtoken.JwtBuilder io.jsonwebtoken.JwtBuilder.setExpiration(java.util.Date)'
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.$anonfun$format$2(Cookie.scala:794)
	at scala.Option.map(Option.scala:242)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:792)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:643)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:641)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:859)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:841)
	at play.api.mvc.FallbackCookieDataCodec.encode$(Cookie.scala:841)
	at play.api.mvc.DefaultSessionCookieBaker.encode(Session.scala:120)
	at play.api.mvc.CookieBaker.encodeAsCookie(Cookie.scala:478)
	at play.api.mvc.CookieBaker.encodeAsCookie$(Cookie.scala:477)
	at play.api.mvc.DefaultSessionCookieBaker.encodeAsCookie(Session.scala:120)
	at play.api.mvc.Result.$anonfun$bakeCookies$2(Results.scala:359)
	at scala.Option.map(Option.scala:242)
	at play.api.mvc.Result.bakeCookies(Results.scala:358)
	at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:312)
	at play.core.server.PekkoHttpServer.$anonfun$runAction$6(PekkoHttpServer.scala:494)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
	at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
	at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### PR DESCRIPTION
**Pull request by PromanSEW**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #12817

## Purpose

Fix for `JwtBuilder.setExpiration` method which become `expiration` in 0.12+

## References

#12817, #12624, #12626

### CODE REVIEW

**Comment by PromanSEW** [comment]
I don't know how to correctly test the fix, except adding config setting. Are any other checks neeeded?

**Comment by mkurz** [comment]
> Are any other checks needed?

@PromanSEW actually not. However can you do the following?

  1. First push your second commit, where you add the config to tests. Let all the tests run, we should then see the error.
  2. After that push the fix and we will then see the commit fixes the problem.

**Comment by PromanSEW** [comment]
@mkurz #12819 confirmed that my fix worked

**Comment by mkurz** [comment]
Thanks! Actually I meant to rebase this PR and first push the test commit, wait for the tests, and then push the second commit. Anyway, LGTM!

**Comment by mkurz** [comment]
@Mergifyio backport 2.9.x

**Pull request merged**
