### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by sf17490**
As a Play user
I want the links in the Play documentation to take me to the correct webpage
So that I am not frustrated by a 404 error

### CODE REVIEW

**Review by mkurz — APPROVED** [review]
Thanks!

**Comment by mkurz** [comment]
@Mergifyio backport main 3.0.x 2.9.x

**Comment by mkurz** [comment]
@sf17490 Actually - do you still use Play 2.8?

**Comment by sf17490** [comment]
I don't really use Play 2.8, I was just looking for a general tutorial and it took me to this page

**Pull request merged**
