### PR TITLE
[2.7.x] Remove autoApply handling from EvolutionsWebCommands (DEV mode)

### PR DESCRIPTION
**Pull request by mkurz**
Backport of #10030 to 2.7.x

### CODE REVIEW

**Comment by gmethvin** [comment]
looks like there are still some bincompat issues with this one 🙁

**Comment by mkurz** [comment]
Works in Scala 2.12, does not compile in 2.11...

**Comment by mkurz** [comment]
@gmethvin I fixed the Scala 2.11 problem. Looking forward to your review / approval.

**Comment by mkurz** [comment]
@gmethvin This is green finally.

**Pull request merged**
