### PR TITLE
Split Http.scala file into multiple files

### PR DESCRIPTION
**Pull request by richdougherty**
Finally `RequestHeader` and `Request` are in their own files! No code was changed, except I removed `GlobalStateHttpConfiguration` after inlining its `httpConfiguration` method.

This change will affect git history, but I think it's worth doing to make our codebase a bit easier to understand.

### CODE REVIEW

**Comment by marcospereira** [comment]
@richdougherty should the same be done to the Java API?

**Comment by richdougherty** [comment]
It would be nice to make the same change to the `Http.java` file, but the Java classes are all inside a `class Http { ... }` declaration, and it would change the Java API if we split them out. The changes I've made to `Http.scala` don't affect the API at all.

I guess we could replace the Java `HTTP` class with a *package* called `play.mvc.HTTP`, but that seems a bit ugly!

**Comment by schmitch** [comment]
LGTM!

**Comment by schmitch** [comment]
Misclicked. LGTM

**Pull request merged**
