### PR TITLE
Enable Websocket compression for Netty

### LINKED ISSUE #10863: Enabling Compression to Websocket
### Play Version

2.8.8

### API

Java

### Operating System

Windows and Linux

### JDK

```
~/ java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

### Actual Behavior

I am currently implementing a websocket server in Play. As part of doing that I noted that the server does not support the `permessage-deflate` Websocket Extension.

Netty had added this as part of their [4.1 release](https://github.com/netty/netty/commit/282d6e73b82ec943a739201f7be1985c45ef032b) . An example of a server implementation is [here](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/websocketx/server/WebSocketServerInitializer.java#L47) . 

### Possible Solution

I went over the codebase, and found that using the `ChannelPipeline` object during the handshake here, [HttpStreamsServerHandler.java#L187](https://github.com/playframework/netty-reactive-streams/blob/master/netty-reactive-streams-http/src/main/java/com/typesafe/netty/http/HttpStreamsServerHandler.java#L187) to add the `WebSocketServerCompressionHandler` could work.

Although, I cannot be certain if this would work or be the right way to achieve it, I could surely raise a PR, if someone pointed me in the right direction.

### PR DESCRIPTION
**Pull request by TheAntimist**
# Pull Request Checklist

* [X] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [X] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [X] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [X] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [X] Have you added copyright headers to new files?
* [X] Have you checked that both Scala and Java APIs are updated?
* [X] Have you updated the documentation for both Scala and Java sections?
* [X] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #10863 and #4186

## Purpose

Enable WebSocket Compression for Netty, using the `WebSocketServerCompressionHandler`. Adds the Netty 4.x `WebSocketServerCompressionHandler` to the chain of Netty's codecs.

Tests have been added to the `netty-reactive-streams` repository, as that seemed the correct place to add them. Let me know in case there's any concerns over this.

## Tests

Added here: https://github.com/playframework/netty-reactive-streams/pull/126

## Background Context

This had to be added here, because if I added it to `HttpStreamsServerHandler` it would be too late for processing, and Compression would not get enabled. This is because it requires detecting of the Websocket Upgrade requests to enable Websocket Extension Headers.

## References

From the Netty Websocket examples: https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/websocketx/server/WebSocketServerInitializer.java#L47

### CODE REVIEW

**Comment by TheAntimist** [comment]
@mkurz Hopefully this looks good, let me know in case of any changes or questions.

**Comment by mkurz** [comment]
Thanks! The test in the netty-reactive-streams repo is broken.
Adding tests in the netty-reactive-streams repo however does not test this change here. I mean, it shows nicely which effect adding `WebSocketServerCompressionHandler` has, however not sure if it's worth also adding a scripted test here too, like [`http-backend-netty`](https://github.com/playframework/playframework/tree/main/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty) or [`http-backend-netty-channel-options`](https://github.com/playframework/playframework/tree/main/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options).

**Comment by TheAntimist** [comment]
FYI, got caught up in some work but the integration test is a WIP and should be done by this weekend.

**Comment by mkurz** [comment]
No hurry, I am busy with other stuff this week as well :wink:

**Comment by mkurz** [comment]
@TheAntimist are you still willing to work on this pull request?

**Comment by TheAntimist** [comment]
@mkurz Apologies I got busy with some other personal things and also an internship in between. I cannot find the work that I had completed on it for some reason.

I can continue working on it now. I have a question on the IntegrationTest, would you want me to modify the controllers for the `http-netty-backend` [here](https://github.com/playframework/playframework/blob/919b5bda99b03a8ebeca956a6f6c0c6361ce9df5/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/test/scala/controllers/IntegrationTest.scala) or do you want me to create one seperate integration test for just this?

**Comment by mkurz** [comment]
You can make use of that existing scripted test. E.g. you can add new routes [here](https://github.com/playframework/playframework/blob/919b5bda99b03a8ebeca956a6f6c0c6361ce9df5/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/resources/routes#L1) and new action methods [here](https://github.com/playframework/playframework/blob/main/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/scala/controllers/HomeController.scala), then you should be able to write the test(s) needed. Be aware that here we talk about scripted tests, so you need to run `publishLocal` before running them with `scripted play-sbt-plugin/http-backend-netty`. I also highly recommend to set `(ThisBuild / version) := "2.9.0-SNAPSHOT"` within the `build.sbt` file of your play repo clone (before running sbt). This way you makes sure each time you restart sbt and start running `scripted ...` again the locally publish artifact will be found (because right now the local published artifacts contain the date and time, like `2.8.1+1835-919b5bda+20220912-1743-SNAPSHOT`, which of course would change as soon as you reload sbt).

Actually... As an alternative to the scripted test you could add a test here as well if you prefer that:
https://github.com/playframework/playframework/blob/main/core/play-integration-test/src/it/scala/play/it/http/websocket/WebSocketSpec.scala

**Comment by mkurz** [comment]
Could not re-open this pull request, so I had to create a new one:
- #12477

**Comment by mkurz** [comment]
- Merged via #12477

**Pull request closed without merging**
