### PR TITLE
[2.4.x] Added failing testcases for onDoneEnumerating

### PR DESCRIPTION
**Pull request by bbarkley**

### CODE REVIEW

**Comment by bbarkley** [comment]
For #6098

**Comment by bbarkley** [comment]
If there is a more comprehensive way to test this it would be great, but this covers the known cases in ServerResultUtils currently

**Comment by gmethvin** [comment]
Thanks @bbarkley this is helpful.

Basically the issue is that we need some way to know when the request is finished. Previously we recommended using onDoneEnumerating to know when the body was completely sent to the client. This does not work, however, if any exceptions happen before the body is sent out.

This problem is especially problematic if the exception happens in the Netty server ([this code](https://github.com/playframework/playframework/blob/master/framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala#L220)), since then your application can not be made aware of the error.

So the solution is one of the following:
 1. Always run out the Enumerator/Source so any callbacks are executed.
 2. Provide an alternative hook for when the request is finished.

Given that a range of errors might occur that could prevent us from running out the enumerator, I'm thinking option 2 might be the better solution.

**Comment by bbarkley** [comment]
Well option 2 was what we had back in 2.2 with GlobalSettings.onRequestCompletion - I'm not sure why that was removed, but the suggested replacement was to use onDoneEnumerating. The problem is that onRequestCompletion didn't have access to the result - if it was passed the request and result (which may be the 500 Play is returning) that would be great.

**Comment by wsargent** [comment]
This PR is 8 months old and against 2.4.x -- unless it's going to be rebased against 2.6.x (assuming that's even an option) I suggest we close it

**Comment by mjrussell** [comment]
@gmethvin 
Sorry to revive a dead thread, but what is the recommended way now to ensure that a callback gets fired from a possible empty enumerator of a `Result`?

After upgrading from play 2.4.6 to 2.4.8 I've seen a regression for this behavior with the changes in place from #6098. I'm trying to run the content through an enumeratee and fallback in the cases where there is no input (`NoContent` or `Accepted`) but now the `onDoneEnumerating` is never called for those types of Results.

**Comment by mjrussell** [comment]
Quick update, this only happens for `NoContent`. It works for `Accepted` even without passing it a new content

**Comment by FranklinYinanDing** [comment]
@mjrussell Caught this when checking old issues. :) It should be fixed in #7004

**Comment by mjrussell** [comment]
Thanks @FranklinYinanDing !

**Pull request closed without merging**
