### PR TITLE
Netty 4.1.35

### PR DESCRIPTION
**Pull request by mkurz**
https://netty.io/news/2019/04/17/4-1-35-Final.html

### CODE REVIEW

**Comment by renatocaval** [comment]
Now that mergify is enabled for backports, I'm wondering if it will pick this one.

**Comment by mkurz** [comment]
> Now that mergify is enabled for backports, I'm wondering if it will pick this one.

No, it does not :cry:

**Comment by renatocaval** [comment]
The question now is if we want to backport library updates. We have been discussing it and the decision was to only backport when there is a bug fix that is impacting the stable branch. 

This all for the sake of reducing the overhead. A user of Play 2.7.x can update the library if they want, for instance. Of course, when we know that there is a bug that can be fixed by updating a lib, we should do it.

WDYT?

**Comment by mkurz** [comment]
What about if we don't immediately backport every lib upgrades, but do it only once at all just before we release a new 2.7.x version, in just one single pull request, to not overload the CI pipeline all the time?
I like the idea of including the latest library bugfix releases with each new Play release, because they fix bugs.

**Comment by renatocaval** [comment]
The problem with mass updates is that when one lib breaks it, it's hard to find. And it blocks the release. 

We have a similar situation recently with play-ws. 

Each backport is a potential distraction for us. If it backports cleanly, I have no problem, but if it fails, we need to check why. Sometimes it is a flakky tests, sometimes is a real issue. 

I understand that it's nice to have lib updates on each new bug fix release, but users can also update themselves. We are not blocking people in upgrading. 

Maybe we should open an issue in play-meta and have a broader discussion about this strategy.

**Comment by renatocaval** [comment]
Removed the backport label. This is old and we didn't make it for 2.7.3. 
Let's backport if there is a real need for it (like security issue or major bug)

**Comment by renatocaval** [comment]
For clarity, I mean let's backport future dependencies update when there is a pressing need.

**Pull request merged**
