### PR TITLE
Fix versioned assets on Windows

### PR DESCRIPTION
**Pull request by tg44**
This commit succesfully merged to 2.4.x anno:
https://github.com/playframework/playframework/commit/9cd744f7171de2682e93a533a18c672f43a898e1

I can't test it on local, I had problems in local publish, and its not a really well documented area in this version, but we want to use it in the next release.

### CODE REVIEW

**Comment by benmccann** [comment]
@tg44 can you please squash the commits?

**Comment by typesafehub-validator** [comment]
Hi @tg44,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by tg44** [comment]
So I tried to squash the commits, in my branch they are merged, but I think I need to open a new pullreq for this.
I do the cla agreemant too. A minor bug with that: you cant use your language specific characters in that form like "ö" "á" "ő".

**Comment by tg44** [comment]
Ohh I see, github is updated itself I will not need to creat new pullreq :)

**Pull request merged**
