### PR TITLE
Fix the error of config sample in ExternalAssets's comments.

### PR DESCRIPTION
**Pull request by joymufeng**
Remove character '\uFEFF' and change c:\ to c:\\.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @joymufeng,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by marcospereira** [comment]
@joymufeng `\uFEFF` was intended to be a [zero width, no break space](http://www.fileformat.info/info/unicode/char/feff/index.htm) character and was added here to avoid problems with documentation syntax. But, I saw that it is not working as expected for the [published docs](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#controllers.Assets$) and it is rendering `/assets/￯ﾻ﾿*file` instead.

I can't reproduce the problem locally.

@jroper and @richdougherty, any ideas?

**Comment by richdougherty** [comment]
What about using XML entities? http://stackoverflow.com/questions/23959902/how-to-escape-in-scaladoc

**Comment by benmccann** [comment]
What if you change it to:

    {@literal *}

**Comment by benmccann** [comment]
Or if you follow @richdougherty 's link it says you can change `/*` to `&#47;*`

**Comment by benmccann** [comment]
@joymufeng can you update this PR per the comments?

**Comment by mkurz** [comment]
Ping @joymufeng

**Comment by marcospereira** [comment]
2.5.x docs are ok:

https://www.playframework.com/documentation/2.5.x/api/scala/index.html#controllers.Assets%24
https://www.playframework.com/documentation/2.5.x/api/scala/index.html#controllers.ExternalAssets

Should we close this?

**Comment by mkurz** [comment]
I can confirm as well that the 2.5.x docs look ok now.
Closing. We can re-open in case someone experiences this behaviour again.

**Pull request closed without merging**
