### PR TITLE
Update to netty 4.0.33

### PR DESCRIPTION
**Pull request by mchv**
* Update to netty `4.0.33` - [Changelog](http://netty.io/news/2015/11/04/4-0-33-Final.html)
* Add documentation about configuring netty 
* Add [native socket transport feature](https://github.com/playframework/playframework/pull/5273) in `2.5` highlights

### CODE REVIEW

**Comment by richdougherty** [comment]
LGTM, you just need to fix up a syntax error in the docs:
```
[error] Could not find link Netty configuration at /home/travis/build/playframework/playframework/documentation/manual/releases/Highlights25.md:13
[error] See more information about it in [[|Netty configuration|NettyConfiguration]]
```

**Comment by mchv** [comment]
@richdougherty fixed now

**Comment by jroper** [comment]
By the way, I released netty-reactive-streams 1.0.1 yesterday, there was a bug in it that I've now fixed. This particular bug fix won't have much impact on Play though.

**Comment by richdougherty** [comment]
@jroper, I created an issue so we remember to update: https://github.com/playframework/playframework/issues/5331

**Pull request merged**
