### PR TITLE
Improve the case of when to display the logger configuration deprecat…

### PR DESCRIPTION
**Pull request by rethab**
As requested / proposed here:
https://github.com/playframework/playframework/pull/5451

### CODE REVIEW

**Comment by mkurz** [comment]
Weird... I can not force the failed tests to restart.
Travis tells me `"The job was successfully restarted"` but nothing happens... Even closing/re-opening this PR doesn' work here. I already tried like 10 hours ago and thought maybe Travis is under high load but it's the same now as well. However tests for other PR's run fine...
Does someone have an idea what's wrong?

**Comment by mkurz** [comment]
OK now it runs... Took a while it seems.

**Comment by benmccann** [comment]
@rethab looks like this broke one of the tests:

>play.api.libs.ws.ssl.AlgorithmChecker$$anonfun$checkKeyAlgorithms$1$$anonfun$apply$2.apply(AlgorithmChecker.scala:102)
[error]       x log a warning if sslConfig.default is passed in with an weak certificate
[error]        0 is equal to 0 (NingConfigSpec.scala:269)

**Comment by marcospereira** [comment]
@benmccann the build is unstable for branch 2.4. @mkurz has already [reported it here](https://gitter.im/playframework/contributors?at=56d711b706ba9a282a288bdb).

**Pull request merged**
