### PR TITLE
Support * when configuring play.filters.cors.allowedOrigins 

### LINKED ISSUE #9880: Support ["*"] when configuring play.filters.cors.allowedOrigins
### Play Version

Play 2.7+.

### API

Java and Scala APIs.

### Description

`Access-Control-Allow-Origin` header uses `*`wildcard to tell browsers to allow any origin to access the resource. Play, on the other hand, uses `null` to indicate that all origins are allowed. It would be better for developer experience if the configuration in Play supported wildcard too, making it closer to the specifications for the header.

Due to compatibility reasons, we need to support both, meaning both configurations below should be equivalent:

```hocon
play.filters.cors.allowedOrigins = null
```

```hocon
play.filters.cors.allowedOrigins = ["*"]
```

### PR DESCRIPTION
**Pull request by uname-yang**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #9880

## Purpose

What does this PR do?
To support both `null` and `*` in `play.filters.cors.allowedOrigins` to allow any origin to access the resource.
```
play.filters.cors.allowedOrigins = null
OR
play.filters.cors.allowedOrigins = ["*"]
```

## Background Context

This is yy first commit to Play, be happy to hear your advices.

## References

NO

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by uname-yang** [comment]
I will create a new pull request, sorry for the mess commit history.

**Pull request closed without merging**
