### PR TITLE
fix Play does not support alpha-3/ISO 639-2 language codes #4014 (master branch)

### PR DESCRIPTION
**Pull request by intracer**

### CODE REVIEW

**Comment by benmccann** [comment]
Thanks for resubmitting against master.FYI, iIt looks like there's some compilation problem

**Comment by intracer** [comment]
Commited compilation error fix

**Comment by cchantep** [comment]
Hi @intracer , please squash commits (`git rebase -i HEAD~3`) so that this PR could be merge as a single commit. Thanks

**Comment by benmccann** [comment]
Change looks good to me. @intracer we can merge after you squash as @cchantep suggested

**Comment by jroper** [comment]
See [here](https://www.playframework.com/documentation/2.3.x/WorkingWithGit) if unsure about how to squash commits.

**Comment by jroper** [comment]
Hi @intracer,

I would like to merge this, are you able to squash your commits, or are you happy for me to do that for you?

Cheers,

James

**Comment by intracer** [comment]
one commit - https://github.com/playframework/playframework/pull/4151

**Comment by benmccann** [comment]
Thanks @intracer. Just for future reference, you don't have to make a new PR. You can do this:

    git rebase -i HEAD~2
    git push -f

**Pull request closed without merging**
