### PR TITLE
Upgrade to Config 1.3.0-M1

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
@havocp thanks for all the recent config changes!! I'd love to get Config 1.3.0 into Play 2.4 if possible. We're just about to release another milestone release of Play, so I thought I'd upgrade Play to the most recent Config to get extra eyes on it. Do you think that 1.3.0 final will be released within the next month in time for Play 2.4 in April?

**Comment by havocp** [comment]
Yes,1.3.0 will be released for the next akka and play (whichever of those comes out first just needs to ask for the 1.3.0 final build). We should upgrade to M1 in the meantime for testing.

**Comment by benmccann** [comment]
Thanks @havocp !

It seems like most of the builds are failing right now, so I'll rerun the PR validator after https://github.com/playframework/playframework/pull/4030 is checked in.

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by jroper** [comment]
@benmccann looks like a legit failure caused by the upgrade

**Comment by havocp** [comment]
Not sure I'm looking at the right thing, but it looks like the wildcard case here throws an exception with no message in it at https://github.com/playframework/playframework/blob/ee31842d29cfd7133ba9024ee63ec59b09cb716b/framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala#L159

```
[error] p.c.s.n.NettyResultStreamer$ - Error while sending response.
java.lang.Exception: null
	at play.it.libs.WSSpec$$anonfun$3$$anonfun$apply$82$$anonfun$apply$83$$anonfun$apply$84.apply(WSSpec.scala:159) ~[test-classes/:na]
	at play.it.libs.WSSpec$$anonfun$3$$anonfun$apply$82$$anonfun$apply$83$$anonfun$apply$84.apply(WSSpec.scala:157) ~[test-classes/:na]
	at play.api.libs.iteratee.Enumerator$$anon$12$$anonfun$apply$24.apply(Enumerator.scala:396) ~[classes/:na]
	at play.api.libs.iteratee.Enumerator$$anon$12$$anonfun$apply$24.apply(Enumerator.scala:396) ~[classes/:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.5.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.5.jar:na]
```

**Comment by havocp** [comment]
Doesn't look directly config related, though I suppose if the config isn't loaded in the same way or something it could affect almost anything.

**Comment by jroper** [comment]
The failure is:

```
[info] Configuration should
[info] x be accessible as an entry set
[error]    Set(blah2.blah3.blah4, blah.1, blah.0, foo.bar2, foo.bar1, blah.4, blah.2, blah.3) does not contain blah."0", blah."1", blah."2", blah."3", blah."4" but contains blah.3, blah.0, blah.2, blah.1, blah.4 (ConfigurationSpec.scala:31)
[info] 
[info] x make all paths accessible
[error]    Set(blah2.blah3.blah4, blah.1, blah.0, foo.bar2, foo.bar1, blah.4, blah.2, blah.3) does not contain blah."0", blah."1", blah."2", blah."3", blah."4" but contains blah.3, blah.0, blah.2, blah.1, blah.4 (ConfigurationSpec.scala:35)
```

It's probably an issue with our tests, not Typesafe config.

**Comment by havocp** [comment]
where can I see this failure? I clicked on "details" on the jenkins-pr-validator

I think the failure is due to the sixth bullet point under "most likely to break something" at https://github.com/typesafehub/config/blob/master/NEWS.md, that paths with digits no longer quote the digits unless there's some other reason to quote that path (like another special char)

**Comment by jroper** [comment]
@havocp Play generates a lot of garbage in its test logs - something we haven't got around to fixing.  I go to the full console log, and then search for `[error]`, until I come to a test failure.

**Comment by havocp** [comment]
@benmccann fwiw I think the right fix is to change the expected result in these two tests so the numbers aren't quoted.

The history of this change is to first allow paths with unquoted digits (pre-1.2.0 it looks like):
https://github.com/typesafehub/config/pull/116
then a couple weeks ago I fixed rendering to avoid quoting paths starting with a number:
https://github.com/typesafehub/config/pull/258

The quoted paths were also valid, just ugly. Old versions (1.2.0 anyway) should be able to parse the new unquoted rendering though, if that arises somehow.

**Comment by benmccann** [comment]
@jroper this passes now with @havocp 's suggested change. thanks guys!

**Pull request merged**
