### PR TITLE
Added compile time dependency injection notes

### PR DESCRIPTION
**Pull request by asdcdow**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @asdcdow,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by asdcdow** [comment]
I believe I signed the CLA under my other github account `cdow`

**Comment by gmethvin** [comment]
@asdcdow You can sign the CLA under the account you're using here or you can submit a PR from your other account.

**Comment by gmethvin** [comment]
The example is actually incomplete because you also need an `ExecutionContext` and `Materializer`. It's probably better to just tell people to use [`AhcWSComponents`](https://playframework.com/documentation/2.6.x/api/scala/index.html#play.api.libs.ws.ahc.AhcWSComponents). It's easy to see what it does by looking at the code.

Also, I see no reason not to also correct this in master, so it would be better to submit your PR to master and backport from there.

**Comment by asdcdow** [comment]
D'oh.  I thought I was sending this to master.  I guess I should have looked more closely.  I will do a new pull request with my other account.

You are right, `AhcWSComponents` does look a lot nicer.  However, I didn't realize that existed.  I will just point people to that in the pull request.

Thanks for your feedback

**Comment by asdcdow** [comment]
Replaced by #7828

**Pull request closed without merging**
