### PR TITLE
fix for issue #4939 (add ../conf/ instead of ../conf to the classpath when externalizeResources=true)

### PR DESCRIPTION
**Pull request by katzelad**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @katzelad,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by cchantep** [comment]
Hi @katzelad, please remove the merge commit from this PR (rather use rebase). Best regards

**Comment by katzelad** [comment]
Done @cchantep

**Comment by jroper** [comment]
Closing/reopening to retrigger travis build.

**Comment by jroper** [comment]
Thanks!

**Comment by jroper** [comment]
Backported to 2.4.x: 73debe8

**Pull request merged**
