### PR TITLE
Sunset bintray. Always publish to Sonatype

### PR DESCRIPTION
**Pull request by ignasi35**

### CODE REVIEW

**Review by marcospereira — APPROVED** [review]
LGTM!

I wonder if we can do a snapshot release on this branch to validate the changes, though.

WDYT?

**Comment by ignasi35** [comment]
> LGTM!
> 
> I wonder if we can do a snapshot release on this branch to validate the changes, though.
> 
> WDYT?

Well, that would validate snapshot settings not production settings. Maybe we can do an `M1` release?

**Comment by ignasi35** [comment]
For the record: the [last commit before merging this PR](https://github.com/playframework/playframework/commits/master) was successfully published to OSS snapshots:

https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/sbt-plugin_2.12_1.0/2.8.1+1094-12c20cea-SNAPSHOT/

Let's wait until tomorrow.

**Comment by marcospereira** [comment]
> Both of those releases produced all necessary artifacts to Sonatype.

Hooray! 🍾 🎉

**Pull request merged**
