### PR TITLE
Missing imports in doc

### PR DESCRIPTION
**Pull request by csongnguyen**
I just included two import packages that were necessary for compilation problems that occurred when those two packages were not included. 
> Don't forget to do "import com.avaje.ebean.*; import play.libs.*;"

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @csongnguyen,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by benmccann** [comment]
@csongnguyen just a reminder that you'll need to sign the CLA still

**Comment by marcospereira** [comment]
The page changed does not exists anymore.

**Comment by marcospereira** [comment]
Ooops! Just saw that this PR is for branch 2.2.x. Sorry.

**Comment by benmccann** [comment]
@csongnguyen a reminder to please sign the CLA if you'd like to get this change in. thanks!

**Comment by benmccann** [comment]
Closing due to inactivity. Please feel free to reopen with the necessary changes

**Pull request closed without merging**
