### PR TITLE
Bump Jackson to 2.11.x

### PR DESCRIPTION
**Pull request by ignasi35**
refs https://github.com/playframework/play-json/pull/588

### CODE REVIEW

**Review by mkurz — APPROVED** [review]

**Comment by mkurz** [comment]
@ignasi35 backporting?

**Comment by ignasi35** [comment]
@mergifyio backport 2.8.x

**Comment by mkurz** [comment]
:boom: 

https://travis-ci.com/github/playframework/playframework/jobs/493325846#L1906

```
Suppressed: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:819)
	at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4(JacksonObjectMapperProvider.scala:242)
	at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4$adapted(JacksonObjectMapperProvider.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at akka.serialization.jackson.JacksonObjectMapperProvider$.configureObjectMapperModules(JacksonObjectMapperProvider.scala:241)
	at akka.serialization.jackson.JacksonObjectMapperProvider$.createObjectMapper(JacksonObjectMapperProvider.scala:265)
	at akka.serialization.jackson.JacksonObjectMapperProvider.create(JacksonObjectMapperProvider.scala:359)
	at akka.serialization.jackson.JacksonObjectMapperProvider.$anonfun$getOrCreate$1(JacksonObjectMapperProvider.scala:317)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at akka.serialization.jackson.JacksonObjectMapperProvider.getOrCreate(JacksonObjectMapperProvider.scala:317)
	at akka.serialization.jackson.JacksonJsonSerializer.<init>(JacksonSerializer.scala:141)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
	at scala.util.Success.flatMap(Try.scala:258)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:396)
	at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:392)
	at scala.util.Failure.recoverWith(Try.scala:240)
	at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:392)
	at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:390)
	at scala.util.Failure.recoverWith(Try.scala:240)
	at akka.serialization.Serialization.serializerOf(Serialization.scala:390)
	at akka.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:424)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
	at scala.collection.immutable.HashMapBuilder.addAll(HashMap.scala:2338)
	at scala.collection.immutable.HashMap$.from(HashMap.scala:2162)
	at scala.collection.immutable.HashMap$.from(HashMap.scala:2138)
	at scala.collection.MapOps$WithFilter.map(Map.scala:353)
	at akka.serialization.Serialization.<init>(Serialization.scala:424)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:14)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
	at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1201)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1195)
	at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1214)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1035)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1022)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1022)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1045)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
	at play.api.libs.concurrent.ActorSystemProvider$.start(Akka.scala:246)
	at play.api.libs.concurrent.ActorSystemProvider.get$lzycompute(Akka.scala:131)
	at play.api.libs.concurrent.ActorSystemProvider.get(Akka.scala:131)
	at play.api.libs.concurrent.AkkaComponents.actorSystem(Akka.scala:104)
	at play.api.libs.concurrent.AkkaComponents.actorSystem$(Akka.scala:104)
	at play.api.BuiltInComponentsFromContext.actorSystem$lzycompute(ApplicationLoader.scala:228)
	at play.api.BuiltInComponentsFromContext.actorSystem(ApplicationLoader.scala:228)
	at play.api.BuiltInComponents.tempFileReaper(Application.scala:337)
	at play.api.BuiltInComponents.tempFileReaper$(Application.scala:336)
	at play.api.BuiltInComponentsFromContext.tempFileReaper$lzycompute(ApplicationLoader.scala:228)
	at play.api.BuiltInComponentsFromContext.tempFileReaper(ApplicationLoader.scala:228)
	at play.api.BuiltInComponents.tempFileCreator(Application.scala:339)
	at play.api.BuiltInComponents.tempFileCreator$(Application.scala:338)
	at play.api.BuiltInComponentsFromContext.tempFileCreator$lzycompute(ApplicationLoader.scala:228)
	at play.api.BuiltInComponentsFromContext.tempFileCreator(ApplicationLoader.scala:228)
	at play.api.BuiltInComponents.injector(Application.scala:260)
	at play.api.BuiltInComponents.injector$(Application.scala:256)
	at play.api.BuiltInComponentsFromContext.injector$lzycompute(ApplicationLoader.scala:228)
	at play.api.BuiltInComponentsFromContext.injector(ApplicationLoader.scala:228)
	at play.api.BuiltInComponents.application(Application.scala:322)
	at play.api.BuiltInComponents.application$(Application.scala:319)
	at play.api.BuiltInComponentsFromContext.application$lzycompute(ApplicationLoader.scala:228)
	at play.api.BuiltInComponentsFromContext.application(ApplicationLoader.scala:228)
	at play.api.test.ApplicationFactories$$anon$2.create(ApplicationFactory.scala:32)
	at play.api.test.ServerEndpointRecipe$.startEndpoint(ServerEndpointRecipe.scala:185)
	at play.microbenchmark.it.HelloWorldBenchmark.setup(HelloWorldBenchmark.scala:58)
	at play.microbenchmark.it.jmh_generated.HelloWorldBenchmark_helloWorld_jmhTest._jmh_tryInit_f_helloworldbenchmark0_G(HelloWorldBenchmark_helloWorld_jmhTest.java:458)
	at play.microbenchmark.it.jmh_generated.HelloWorldBenchmark_helloWorld_jmhTest.helloWorld_Throughput(HelloWorldBenchmark_helloWorld_jmhTest.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mkurz** [comment]
I guess that will fix itself when upgrading to akka 2.6.14:
https://github.com/akka/akka/blob/master/project/Dependencies.scala#L127

**Comment by ignasi35** [comment]
> I guess that will fix itself when upgrading to akka 2.6.14:
> [https://github.com/akka/akka/blob/master/project/Dependencies.scala#L127](https://github.com/akka/akka/blob/master/project/Dependencies.scala?rgh-link-date=2021-03-24T10%3A37%3A32Z#L127)

Yeah. But we workaround and have the tests complete. I'll declare the explicit dependency on that artifact instead of relying on transitive deps.

**Review by marcospereira — APPROVED** [review]

**Comment by ignasi35** [comment]
@mergifyio backport 2.8.x

**Pull request merged**
