### PR TITLE
Remove the request and context id

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
@play-pull-request-validator try again. NettyAssetsSpec is being super flaky

>[error] Error: Total 381, Failed 0, Errors 1, Passed 254, Skipped 126
[error] Error during tests:
[error] 	play.it.http.assets.NettyAssetsSpec
[error] (Play-Integration-Test/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1568 s, completed Feb 23, 2015 1:56:10 AM

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
This is passing now after some test flakiness

**Comment by jroper** [comment]
I think there are people out there that rely on this.

**Comment by benmccann** [comment]
I'm not sure what exactly it would be used for. I would think the vast majority of uses could be replaced by the hashcode just as I'm doing here. Maybe I could just also update the migration guide

Another alternative would be to get rid of the `AtomicLong` and just use `SecureRandom.nextInt(Integer.MAX_VALUE)` though that would be an `int` instead of a `Long`

**Comment by jroper** [comment]
I think some monitoring solutions may depend on it - perhaps.

**Comment by benmccann** [comment]
Well I won't push for it too hard. Seems like the solution we came up with on the other thread will work well enough

**Pull request closed without merging**
