### PR TITLE
[2.8] Prep for 2.8.1 release

### LINKED ISSUE #9999: JNA error running ~run
### Play Version

A build off of the 2.8.x branch, current HEAD is da4a19d69e8c45a0163fe34df1e6528e52d6eed9.

### Operating System

macOS

### JDK

```
java version "1.8.0_202-ea"
Java(TM) SE Runtime Environment (build 1.8.0_202-ea-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b03, mixed mode)
```

### Library Dependencies

sbt 1.3.6

### Expected Behavior

1. Running `~run`
2. the server is started
3. the code is compiled
4. file watching is started

### Actual Behavior

The execution of the `Compile / run` task fails with:

```
[error] java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
[error] 	at io.methvin.watchservice.jna.CarbonAPI.<clinit>(CarbonAPI.java:19)
[error] 	at io.methvin.watchservice.jna.CFStringRef.toCFString(CFStringRef.java:23)
[error] 	at io.methvin.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:128)
[error] 	at io.methvin.watchservice.WatchablePath.register(WatchablePath.java:50)
[error] 	at io.methvin.watcher.DirectoryWatcher.register(DirectoryWatcher.java:341)
[error] 	at io.methvin.watcher.DirectoryWatcher.registerAll(DirectoryWatcher.java:315)
[error] 	at io.methvin.watcher.DirectoryWatcher.<init>(DirectoryWatcher.java:176)
[error] 	at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:117)
[error] 	at play.dev.filewatch.DefaultFileWatchService.watch(DefaultFileWatchService.scala:38)
[error] 	at play.dev.filewatch.FileWatchService$$anon$1.watch(FileWatchService.scala:87)
[error] 	at play.runsupport.Reloader.<init>(Reloader.scala:443)
[error] 	at play.runsupport.Reloader$.reloader$lzycompute$1(Reloader.scala:283)
[error] 	at play.runsupport.Reloader$.play$runsupport$Reloader$$reloader$1(Reloader.scala:275)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
```

### Reproducible Test Case

1. `publishLocal` Play 2.8.x
2. Take https://github.com/playframework/play-samples/tree/2.8.x/play-scala-hello-world-tutorial (current HEAD https://github.com/playframework/play-samples/commit/da4a19d69e8c45a0163fe34df1e6528e52d6eed9)
3. Update Play to the published version
4. Optional: Update sbt from 1.3.4 to 1.3.6
5. start `sbt`
6. run `~run`

### PR DESCRIPTION
**Pull request by dwijnand**
With the upgrade of play-file-watch this...
Fixes #9999

### CODE REVIEW

**Comment by dwijnand** [comment]
Upgrading play-file-watch has stalled with this:

```
[info] [error] java.lang.ExceptionInInitializerError
[info] [error] 	at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.<init>(Unknown Source)
[info] [error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info] [error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info] [error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info] [error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info] [error] 	at java.lang.Class.newInstance(Class.java:442)
[info] [error] 	at net.contentobjects.jnotify.JNotify.<clinit>(Unknown Source)
[info] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] [error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] [error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$JNotifyDelegate.ensureLoaded(JNotifyFileWatchService.scala:62)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$.$anonfun$apply$1(JNotifyFileWatchService.scala:122)
[info] [error] 	at scala.util.control.Exception$Catch.$anonfun$withTry$1(Exception.scala:253)
[info] [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[info] [error] 	at scala.util.control.Exception$Catch.withTry(Exception.scala:253)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$.apply(JNotifyFileWatchService.scala:73)
[info] [error] 	at play.dev.filewatch.FileWatchService$.jnotify(FileWatchService.scala:92)
[info] [error] 	at play.sbt.scriptedtools.ScriptedTools$.$anonfun$jnotifyWatchService$1(ScriptedTools.scala:57)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[info] [error] Caused by: java.lang.NullPointerException
[info] [error] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
[info] [error] 	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
[info] [error] 	at java.lang.System.loadLibrary(System.java:1124)
[info] [error] 	at net.contentobjects.jnotify.linux.JNotify_linux.<clinit>(Unknown Source)
[info] [error] 	at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.<init>(Unknown Source)
[info] [error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info] [error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info] [error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info] [error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info] [error] 	at java.lang.Class.newInstance(Class.java:442)
[info] [error] 	at net.contentobjects.jnotify.JNotify.<clinit>(Unknown Source)
[info] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] [error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] [error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$JNotifyDelegate.ensureLoaded(JNotifyFileWatchService.scala:62)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$.$anonfun$apply$1(JNotifyFileWatchService.scala:122)
[info] [error] 	at scala.util.control.Exception$Catch.$anonfun$withTry$1(Exception.scala:253)
[info] [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[info] [error] 	at scala.util.control.Exception$Catch.withTry(Exception.scala:253)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$.apply(JNotifyFileWatchService.scala:73)
[info] [error] 	at play.dev.filewatch.FileWatchService$.jnotify(FileWatchService.scala:92)
```

**Comment by dwijnand** [comment]
The upgrade is:
* play-file-watch 1.1.9 -> 1.1.11, which, in turn, is
* directory-watcher 0.9.6 -> 0.9.9, which is
* jna 5.3.1 -> 5.5.0, which I'd already tried to mitigate (https://github.com/gmethvin/directory-watcher/pull/48)

My guess is that JNA upgrade is the cause here, and needs investigating.

**Comment by dwijnand** [comment]
OK, dropped the upgrade to play-file-watch 1.1.11 and added a comment.

**Comment by dwijnand** [comment]
Actually need to downgrade to play-file-watch 1.1.10 in order to resolve #9999 (by downgrading directory-watcher back to JNA 5.3.1).

**Comment by dwijnand** [comment]
WAT!  Exact same stack, when _downgrading_ to play-file-watch 1.1.9!

How I suspect it's the sbt 1.3.7 upgrade.  So let's try no sbt upgrade, and update play-file-watch.

If that fails then no sbt upgrade and downgrade play-file-watch.

**Comment by dwijnand** [comment]
Let's try the noop diff... Still gonna fail, `JNotify_linux`?

**Comment by dwijnand** [comment]
OK, at least sanity restored, but expectations blown out of the water and huge amount of my time wasted: 2.8.x HEAD is broken on Travis CI.................

**Comment by dwijnand** [comment]
Riddle me this:

How does a CRON build of 2.8.x HEAD 4 days ago pass: https://travis-ci.com/playframework/playframework/builds/146191697

But a PR build on 2d910dbb7a398b9c7eaba7a16c5955a40574afec with no(!) diff (https://github.com/playframework/playframework/compare/02159497b3b503169d4693f666012488f3ea157a...2d910dbb7a398b9c7eaba7a16c5955a40574afec) fail on JNotify_linux: https://travis-ci.com/playframework/playframework/jobs/282117956 ???

Possible causes:
* running different things and/or in different ways in PR than CRON
* changes in underlying Travis CI
* differences in caches???

The CRON job from yesterday (21 hours ago) failed on Jnotify (and I'm not sure if to be happy or sad about it) https://travis-ci.com/playframework/playframework/jobs/281828070

Which biases me to underlying Travis CI changes?

**Comment by dwijnand** [comment]
Spotted a difference:

```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```

```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

**Comment by mkurz** [comment]
> Spotted a difference:

That's it! I can reproduce!

```
[info] [error] java.lang.ExceptionInInitializerError
[info] [error]  at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.<init>(Unknown Source)
[info] [error]  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info] [error]  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info] [error]  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info] [error]  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info] [error]  at java.lang.Class.newInstance(Class.java:442)
[info] [error] iat net.contentobjects.jnotify.JNotify.<clinit>(Unknown Source)
[info] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] [error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] [error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$JNotifyDelegate.ensureLoaded(JNotifyFileWatchService.scala:62)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$.$anonfun$apply$1(JNotifyFileWatchService.scala:122)
[info] [error] 	at scala.util.control.Exception$Catch.$anonfun$withTry$1(Exception.scala:253)
[info] [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[info] [error] 	at scala.util.control.Exception$Catch.withTry(Exception.scala:253)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$.apply(JNotifyFileWatchService.scala:73)
[info] [error] 	at play.dev.filewatch.FileWatchService$.jnotify(FileWatchService.scala:92)
[info] [error] 	at play.sbt.scriptedtools.ScriptedTools$.$anonfun$jnotifyWatchService$1(ScriptedTools.scala:53)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[info] [error] Caused by: java.lang.NullPointerException
[info] [error] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
[info] [error] 	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
[info] [error] 	at java.lang.System.loadLibrary(System.java:1124)
[info] [error] 	at net.contentobjects.jnotify.linux.JNotify_linux.<clinit>(Unknown Source)
[info] [error] 	at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.<init>(Unknown Source)
[info] [error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info] [error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info] [error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info] [error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info] [error] 	at java.lang.Class.newInstance(Class.java:442)
[info] [error] 	at net.contentobjects.jnotify.JNotify.<clinit>(Unknown Source)
[info] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] [error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] [error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$JNotifyDelegate.ensureLoaded(JNotifyFileWatchService.scala:62)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$.$anonfun$apply$1(JNotifyFileWatchService.scala:122)
[info] [error] 	at scala.util.control.Exception$Catch.$anonfun$withTry$1(Exception.scala:253)
[info] [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[info] [error] 	at scala.util.control.Exception$Catch.withTry(Exception.scala:253)
[info] [error] 	at play.dev.filewatch.JNotifyFileWatchService$.apply(JNotifyFileWatchService.scala:73)
[info] [error] 	at play.dev.filewatch.FileWatchService$.jnotify(FileWatchService.scala:92)
[info] [error] 	at play.sbt.scriptedtools.ScriptedTools$.$anonfun$jnotifyWatchService$1(ScriptedTools.scala:53)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[info] [error] (Compile / run) java.lang.ExceptionInInitializerError
[info] [error] Total time: 1 s, completed Jan 31, 2020 4:19:14 PM
[error] x play-sbt-plugin / dev-mode 
[error]  Cause of test exception: {line 106}  Command failed: run failed
[error] stack trace is suppressed; run last scripted for the full output
[error] (scripted) Failed tests:
[error]         play-sbt-plugin / dev-mode
[error] Total time: 63 s (01:03), completed Jan 31, 2020 4:19:14 PM
```

Worked before with `1.8.0_232`

**Pull request merged**
