### PR TITLE
Enable default samesite

### PR DESCRIPTION
**Pull request by wsargent**
## Fixes

Fixes https://github.com/playframework/playframework/issues/7316

## Purpose

Enables SameSite.Lax on cookies by default and add more documentation.

### CODE REVIEW

**Comment by gmethvin** [comment]
This does mean that if you happen to have a cookie that you want to be cross site, your existing code will compile but actually works slightly differently. I don't know if this is a real problem, though. It could be argued that typically cookies are intended to be same-site.

**Comment by wsargent** [comment]
@gmethvin I think it's fair that most cookies can be assumed as SameSite unless explicitly defined otherwise.  The failure mode could be obscure though for those rare instances where it is intended to be cross-site, because suddenly the site would just stop working, and the browser would not receive the cookies.

The other option is to not provide a default option for SameSite at all, and force developers to choose up front...

**Comment by gmethvin** [comment]
> The failure mode could be obscure though for those rare instances where it is intended to be cross-site, because suddenly the site would just stop working, and the browser would not receive the cookies.

The other problem is that SameSite only works in some browsers, so if you develop using Firefox you won't notice that the failure will happen in Chrome.

**Comment by wsargent** [comment]
> The other problem is that SameSite only works in some browsers, so if you develop using Firefox you won't notice that the failure will happen in Chrome.

Ugh, yes.  Okay, this is a bad idea until there's full support then.

**Pull request closed without merging**
