### PR TITLE
Kuzminki added to ModuleDirectory.md

### PR DESCRIPTION
**Pull request by karimagnusson**
I added links to the documentation and demo pages for my project Kuzminki.

# Pull Request Checklist

* [x ] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [ x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x ] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [ x] Have you added copyright headers to new files?
* [ x] Have you checked that both Scala and Java APIs are updated?
* [x ] Have you updated the documentation for both Scala and Java sections?
* [x ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by mkurz** [comment]
@karimagnusson Do these modules also support Play 2.9?

**Comment by mkurz** [comment]
> As I understand it, most users have switched to version 3. I can of course update the versions for 2.9 if there is interest.

I would just wait for user feedback :wink:

**Comment by karimagnusson** [comment]
Do you know when these changes will appear on playframework.com?

**Comment by mkurz** [comment]
> Do you know when these changes will appear on playframework.com?

With the next patch release.

**Pull request merged**
