### PR TITLE
Migrate PushPullStage based implementations to GraphStage

### PR DESCRIPTION
**Pull request by naferx**
PushPullStage based implementations are deprecated and must be migrated to GraphStage.

* [x]  GzipFlow
* [x]  play.core.parsers.Multipart
* [x]  AkkaStreams
* [x]  Probes
* [x]  play.core.formatters.Multipart

## References

Related to PR https://github.com/playframework/playframework/pull/6022

### CODE REVIEW

**Comment by naferx** [comment]
Thanks @gmethvin !

There are still others old Akka Streams API usages in
```
CSRFActions.scala
WebSocketClient.scala
RangeResult.scala
```
I will submit a new PR with the remaining migration.

**Comment by gmethvin** [comment]
Thanks @naferx

**Comment by naferx** [comment]
Your help and collaboration motivates me to continue to contribute in this project.

**Comment by gmethvin** [comment]
Thanks. We really appreciate your help (and the help of all the members of the community) in making Play better.

**Pull request merged**
