### PR TITLE
Add missing import block in documentation abt Forms

### PR DESCRIPTION
**Pull request by diamondo25**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @diamondo25,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by diamondo25** [comment]
This should be pushed to the other branches too, as it's missing there too.

**Comment by jroper** [comment]
Once #5017 is merged, the tests can be rerun to verify that this is ok (we're in the middle of switching CI servers).  In the meantime, are you able to sign the Typesafe CLA?

**Comment by jroper** [comment]
Closing/reopening to trigger travis.

**Comment by jroper** [comment]
CI is passing, @diamondo25 are you able to sign our CLA?

**Comment by marcospereira** [comment]
This should be manually forward ported to our master (and maybe 2.4.x).

**Comment by mkurz** [comment]
This never got ported to the `2.4.x`, `2.5.x`, `2.6.x` and `master` branches.

**Comment by marcospereira** [comment]
Thank you, @mkurz. I will take a look at forward-porting it to 2.5.x, 2.6.x and master. Not sure if it is useful to port it to 2.4.x though.

**Pull request merged**
