### PR TITLE
Bumped sbt-native-packager version to 1.0.6

### PR DESCRIPTION
**Pull request by dotta**

### CODE REVIEW

**Comment by benmccann** [comment]
> [error] (Play-Documentation/*:generateMarkdownRefReport) Error creating extended parser class: null

**Comment by dotta** [comment]
@benmccann Yeah, not sure what happened there :-/

**Comment by benmccann** [comment]
Hmm, doesn't seem to be a flake as we got the same error again

**Comment by dotta** [comment]
Sorry for the delay. I'm closing this pr until I get time to investigate the reason for the failure.

**Pull request closed without merging**
