### PR TITLE
Updating documentation for RC2

### PR DESCRIPTION
**Pull request by muuki88**
I will release `RC2` today and this is the upgraded documentation.

### CODE REVIEW

**Comment by jroper** [comment]
Ok, could you include the upgrade to RC2 in this PR then?

**Comment by benmccann** [comment]
@play-pull-request-validator try again

>[info] [error] (*:checkStartScript) Start script is adding conf directory to the classpath when it shouldn't be
[info] [error] Total time: 0 s, completed Mar 30, 2015 10:14:38 AM
[error] x play-sbt-plugin / distribution
[error]    {line 27}  Command failed: check-start-script failed

**Comment by jroper** [comment]
Ok, looks like the upgrade broke our tests for packaging.

**Comment by muuki88** [comment]
My guess is that the `etc-default` to `application.ini` change broke the test. I take a look if I can fix  the test.

**Comment by muuki88** [comment]
Okay, I found the line in the test and adjusted the test by making it more explicit.

The [distribution test](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt#L23-L26) failed due to this line

> [info] declare -r script_conf_file="${app_home}/../conf/application.ini"

As it only checks for `../conf` in order to determine if `conf` was added to the classpath. So now we find the `app_classpath` line and check only this line if `../conf` was added.

**Comment by jroper** [comment]
Thanks @muuki88 for following that up and fixing.

**Pull request merged**
