### PR TITLE
Use play-file-watch library

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by wsargent** [comment]
I'm running into problems using a project running against 2.6.0-SNAPSHOT:

```
java.lang.NoClassDefFoundError: play/dev/filewatch/FileWatchService
	at play.sbt.PlayImport$PlayKeys$.<init>(PlayImport.scala:128)
	at play.sbt.PlayImport$PlayKeys$.<clinit>(PlayImport.scala)
```

**Comment by wsargent** [comment]
so if I put the following in `project/plugins.sbt` then it gets past that:

```
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.0-SNAPSHOT")

libraryDependencies += "com.lightbend.play" %% "play-file-watch" % "1.0.0"
```

but then I run into ` java.lang.ClassNotFoundException: play.runsupport.Reloader$GeneratedSourceMapping`

I think this is because run-support is not published -- there is https://mvnrepository.com/artifact/com.typesafe.play/run-support_2.11/2.6.0-M2 but there is no https://mvnrepository.com/artifact/com.typesafe.play/run-support_2.11/2.6.0-M3

```
Caused by: java.lang.ClassNotFoundException: play.runsupport.Reloader$GeneratedSourceMapping
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.sbt.run.PlayRun$.<init>(PlayRun.scala:47)
	at play.sbt.run.PlayRun$.<clinit>(PlayRun.scala)
	at play.sbt.PlaySettings$.defaultSettings$lzycompute(PlaySettings.scala:81)
	at play.sbt.PlaySettings$.defaultSettings(PlaySettings.scala:56)
	at play.sbt.Play$.projectSettings(Play.scala:25)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1$$anonfun$apply$34.apply(Load.scala:721)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1$$anonfun$apply$34.apply(Load.scala:721)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
```

**Comment by benmccann** [comment]
Hmm. It looks like there were two SBT projects setup for the same directory before. I don't understand how that would have worked exactly. Perhaps some settings from the removed one need to be applied to the remaining one?

    lazy val RunSupportProject = PlayDevelopmentProject("Run-Support", "run-support")
    lazy val SbtRunSupportProject = PlaySbtProject("SBT-Run-Support", "run-support")

**Comment by gmethvin** [comment]
@benmccann This really should have been commented in the build to make it clear, but `PlaySbtProject` was intended for use with SBT, so it's built for Scala 2.10, but `PlayDevelopmentProject` is a regular Play library for use in dev mode, and is built for 2.11/2.12.

**Comment by benmccann** [comment]
I left a comment on your PR as well, but I intended the library to be built for only Scala 2.10 since the only usage is by the SBT plugin. I'm not sure why there's anything that's trying to consume a 2.11/2.12 version

**Comment by gmethvin** [comment]
Actually, the latest snapshot works fine for me.

@benmccann You're right. I don't believe having runsupport for other scala versions is needed for Play itself at all. I was thinking there must be something that is using it, but the only thing I believe it was used for is Activator, which is no longer supported for Play 2.6.

**Comment by wsargent** [comment]
@benmccann looks like the problem was a corrupted ivy2 cache on my end -- deleted and rebuilt everything from scratch and it all worked. 👍

**Pull request merged**
