### PR TITLE
Fix performance issues creating JsObject

### PR DESCRIPTION
**Pull request by gmethvin**
Opening this so we can continue discussion from #3865.

Currently my proposed solution is to just use `mutable.LinkedHashMap` and make sure `value` always returns an immutable map.

### CODE REVIEW

**Comment by richdougherty** [comment]
LGTM

**Comment by richdougherty** [comment]
@xuwei-k, do you want to check the performance of JsObject again?

**Comment by xuwei-k** [comment]
:+1:

**Comment by richdougherty** [comment]
:smile:

**Pull request merged**
