### PR TITLE
Add 402 status result.

### PR DESCRIPTION
**Pull request by kappezoro**
I will add the case HTTP status return 402. 
Please check it.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @kappezoro,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by cchantep** [comment]
Hi @kappezoro . Thanks for this PR. Would you mind to update `src/play/src/test/scala/play/api/mvc/ResultsSpec.scala` consequently?

**Comment by kappezoro** [comment]
Hi @cchantep , Thank you for your comment. I added the test for the status on ResultsSpec.scala. Please check it.

**Comment by cchantep** [comment]
Thanks @kappezoro . It would be nice to add tests for `paymentRequired` with some content (e.g. `File`) as for tests about `Unauthorised`. Could you update this PR in this way before it can get merged?

**Comment by kappezoro** [comment]
Thank you @cchantep. I updated test as for Unauthorized has.

**Comment by cchantep** [comment]
Thanks @kappezoro

**Pull request merged**
