### PR TITLE
Update JavaCsrf.md

### PR DESCRIPTION
**Pull request by sant0s**
Fixed typos.

### CODE REVIEW

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by benmccann** [comment]
Thanks for the cleanup. Can you send us a PR for this update against the master branch first? Typically we always start there and then backport changes

https://github.com/playframework/playframework/blob/master/documentation/manual/working/javaGuide/main/forms/JavaCsrf.md

**Comment by sant0s** [comment]
You're welcome. I don't have a PR for merging against the master branch. All documentation related PRs I've been submitting (e.g. merged today: https://github.com/playframework/playframework/pull/4130) refer to merges against the 2.3.x branch, as described at the end of each documentation page. Has this now changed?

**Comment by jroper** [comment]
I'm happy to forward port to master.

**Comment by jroper** [comment]
Forward ported: 9921452

**Comment by sant0s** [comment]
Ok, so the procedure for documentation contributions is to merge to both the current version branch (e.g. 2.3.x) and the master branch?

**Comment by jroper** [comment]
The master branch is the more important one, since if you just update a stable branch, future versions won't include the change.  But generally we'll forward port/back port where necessary.

**Comment by sant0s** [comment]
Ok, thanks for clarifying.

**Pull request merged**
