### PR TITLE
Upgrade SBT native packager to 0.8.0

### PR DESCRIPTION
**Pull request by benmccann**
@muuki88 does this seem like a good idea to you?

### CODE REVIEW

**Comment by muuki88** [comment]
`0.8.0` added some new settings, changed some behaviors and reworked the bash-template generation stuff. I wouldn't recommend for the `2.3.x` line. Instead putting `1.0.0-M4` into the `master` (or `2.4.x`) line would be a better way to go IMHO.

**Comment by benmccann** [comment]
Cool. Exactly what I was thinking (and what this PR does)

**Comment by benmccann** [comment]
How far out do you think the sbt-native-packager 1.0 final release is? It'd be weird if we ended up releasing Play 2.4 and it was still depending on a milestone or RC release of native packager

**Comment by muuki88** [comment]
All the autoplugins are working fine. Actually I wanted to provide a pr like this as
we only wanted to release `1.0.0` when it works with play and if possible with sbt 1.0.0

There are more things to change in play if we move to 1.0.x. There is currently one
issue ( sbt/sbt-native-packager/407 ), which IMHO has to be fixed on the play side,
but I didn't had the time to investigate.

cc @jsuereth

**Comment by benmccann** [comment]
@muuki88 I filed a bug to track the Play side of it https://github.com/playframework/playframework/issues/3801

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Pull request merged**
