### PR TITLE
Fix Akka migration link

### LINKED ISSUE #7481: [doc] Akka migration link from 2.4.x to 2.5.x is broken
### Play Version (2.5.x / etc)

2.6.0

### Expected Behavior

I read this chapter:
https://www.playframework.com/documentation/2.6.x/Migration26#akka-migration
Here I found this link:
http://doc.akka.io/docs/akka/2.5/project/migration-guide-2.4.x-2.5.x.html

### Actual Behavior

This link displays 404 Not Found page
Link must be
http://doc.akka.io/docs/akka/current/scala/project/migration-guide-2.4.x-2.5.x.html

### Reproducible Test Case

Go to this link :)

### PR DESCRIPTION
**Pull request by PromanSEW**
# Pull Request Checklist

* [X] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [X] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [X] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [ ] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [X] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #7481

## Purpose

Fix Akka migration link in Play Framework 2.6 migration guide

### CODE REVIEW

**Comment by PromanSEW** [comment]
@marcospereira please review

**Comment by mkurz** [comment]
I can't push this change to the 2.6.x branch because it is protected.
/cc @marcospereira @gmethvin

**Comment by PromanSEW** [comment]
@mkurz I see you fixed this link in your fork, but you did not open PR for 2.6.x branch yet

**Comment by marcospereira** [comment]
Backport to 2.6.x here: aa479107e

**Pull request merged**
