### PR TITLE
Added few seed projects

### PR DESCRIPTION
**Pull request by gjorgiev**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @gjorgiev,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by richdougherty** [comment]
Hi @gjorgiev I'm going to ask @marcospereira to review this since he's doing some work on making it easier to get started with Play.

**Comment by marcospereira** [comment]
Hey @gjorgiev, sorry for the long time to give you a proper reply here. Are you still interested in adding those? If so, could you please resolve the conflicts and also sign the CLA?

Best.

**Comment by marcospereira** [comment]
Hi @gjorgiev,

I'm closing this but, please let me know if you want to move this forward later.

Thank you.

**Pull request closed without merging**
