### PR TITLE
Append fragment (use Call.path instead of Call.url) when redirecting

### PR DESCRIPTION
**Pull request by rvangsgaard**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @rvangsgaard,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by rvangsgaard** [comment]
What is the process for backporting?

**Comment by schmitch** [comment]
For 2.5.x its already backported. Of you Need a backport for 2.4 you can either create a PR with the cherry picked commit or tell us what you need

**Comment by rvangsgaard** [comment]
I would very much like this to be backported to 2.4, as we have not yet planned for upgrading to 2.5.

**Pull request merged**
