### PR TITLE
TemporaryFile() throws InstantiationException when using compile time…

### PR DESCRIPTION
**Pull request by phleemac**
… dependency injection (https://github.com/playframework/playframework/issues/4909)

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @ph88lee,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by phleemac** [comment]
Hi there, I've followed step 2 in https://www.typesafe.com/contribute/cla to confirm CLA.  But the typesafe-cla-validator still fails.  Should I also confirm the Scala CLA?

**Comment by marcospereira** [comment]
@phleemac apparently the problem is that you are using two users here:

1. @ph88lee is the commiter
2. @phleemac is the pull requester

I've seen other users with the same problem, but if you hadn't sign the CLA with both users, this could be the problem here.

**Comment by phleemac** [comment]
Yeah, I just sign again using my other account.  Do I need to do anything to refresh the validator status?  It's still showing error.

**Comment by phleemac** [comment]
Replaced with https://github.com/playframework/playframework/pull/4925 to workaround the typesafe-cla-validator error

**Pull request closed without merging**
