### PR TITLE
replace specs2-mockito with vanilla mockito

### PR DESCRIPTION
**Pull request by jtjeferreira**
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Purpose

Replace specs2-mockito with vanilla mockito in preparation for scala 3. 

## Background Context

author of specs2 [recommends switching to ScalaMock](https://github.com/etorreborre/specs2/issues/1079#issuecomment-1092863601), but that doesn't have Scala 3 artifacts yet as well: https://github.com/paulbutcher/ScalaMock/issues/429

## References

https://github.com/playframework/playframework/pull/11266
https://github.com/playframework/playframework/pull/11550

### CODE REVIEW

**Comment by mkurz** [comment]
Please run `formatCode` (inside the the documentation folder)

**Comment by jtjeferreira** [comment]
> Please run `formatCode` (inside the the documentation folder)

I wasn't able to launch sbt on the documentation, because I had `addDependencyTreePlugin` in `~/.sbt/1.0/plugins/plugins.sbt ` 🤷 

<details>
<summary>Details</summary>

```
$ sbt
[info] welcome to sbt 1.7.2 (Homebrew Java 11.0.17)
[info] loading settings for project global-plugins from plugins.sbt ...
[info] loading global plugins from /Users/joao/.sbt/1.0/plugins
[info] loading settings for project plugins from plugins.sbt ...
[info] loading settings for project playframework-build-build from buildinfo.sbt ...
[info] loading project definition from /Users/joao/git/OSS/playframework/project/project
[info] loading settings for project plugins from plugins.sbt ...
[info] loading project definition from /Users/joao/git/OSS/playframework/project
[info] loading settings for project Play-Framework from build.sbt,common.sbt ...
[info] resolving key references (48920 settings) ...
[info] loading project definition from /Users/joao/git/OSS/playframework/documentation/project
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.3.0, 1.2.0, 1.0.6}
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.6.0-M7          (depends on 2.1.0)
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- org.scala-sbt:testing_2.12:1.7.2                   (depends on 1.3.0)
[error] 	    +- org.scala-sbt:sbinary_2.12:0.5.1                   (depends on 1.0.6)
[error] 	    +- org.scala-sbt:main_2.12:1.7.2                      (depends on 1.3.0)
[error] 	    +- org.scala-sbt:librarymanagement-core_2.12:1.7.1    (depends on 1.2.0)
[error] 	    +- io.get-coursier:lm-coursier-shaded_2.12:2.0.10     (depends on 1.3.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.3.0, 1.2.0, 1.0.6}
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- org.scala-sbt:testing_2.12:1.7.2                   (depends on 1.3.0)
[error] 	    +- org.scala-sbt:sbinary_2.12:0.5.1                   (depends on 1.0.6)
[error] 	    +- org.scala-sbt:main_2.12:1.7.2                      (depends on 1.3.0)
[error] 	    +- org.scala-sbt:librarymanagement-core_2.12:1.7.1    (depends on 1.2.0)
[error] 	    +- io.get-coursier:lm-coursier-shaded_2.12:2.0.10     (depends on 1.3.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (ProjectRef(uri("file:///Users/joao/git/OSS/playframework/"), "Sbt-Routes-Compiler") / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.3.0, 1.2.0, 1.0.6}
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.6.0-M7          (depends on 2.1.0)
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- org.scala-sbt:testing_2.12:1.7.2                   (depends on 1.3.0)
[error] 	    +- org.scala-sbt:sbinary_2.12:0.5.1                   (depends on 1.0.6)
[error] 	    +- org.scala-sbt:main_2.12:1.7.2                      (depends on 1.3.0)
[error] 	    +- org.scala-sbt:librarymanagement-core_2.12:1.7.1    (depends on 1.2.0)
[error] 	    +- io.get-coursier:lm-coursier-shaded_2.12:2.0.10     (depends on 1.3.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] (ProjectRef(uri("file:///Users/joao/git/OSS/playframework/"), "Run-Support") / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.3.0, 1.2.0, 1.0.6}
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- org.scala-sbt:testing_2.12:1.7.2                   (depends on 1.3.0)
[error] 	    +- org.scala-sbt:sbinary_2.12:0.5.1                   (depends on 1.0.6)
[error] 	    +- org.scala-sbt:main_2.12:1.7.2                      (depends on 1.3.0)
[error] 	    +- org.scala-sbt:librarymanagement-core_2.12:1.7.1    (depends on 1.2.0)
[error] 	    +- io.get-coursier:lm-coursier-shaded_2.12:2.0.10     (depends on 1.3.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```
</details>

**Comment by mkurz** [comment]
@jtjeferreira I pushed a small fix.

I think we should mention the fact the Play 2.9 does not ship with specs2-mockito any longer in the Migration guide: https://github.com/playframework/playframework/blob/main/documentation/manual/releases/release29/migration29/Migration29.md
Not sure, but what about giving small codes snippets, like your changes as examples for how to migrate?

**Comment by jtjeferreira** [comment]
> I think we should mention the fact the Play 2.9 does not ship with specs2-mockito any longer in the Migration guide: [main/documentation/manual/releases/release29/migration29/Migration29.md](https://github.com/playframework/playframework/blob/main/documentation/manual/releases/release29/migration29/Migration29.md?rgh-link-date=2023-02-02T16%3A17%3A53Z)
Not sure, but what about giving small codes snippets, like your changes as examples for how to migrate?

Should I add in the "Updated libraries" section?

**Comment by jtjeferreira** [comment]
> Should I add in the "Updated libraries" section?

Or even a new section "Dependency graph changes" like in https://www.playframework.com/documentation/2.8.x/Migration28#Dependency-graph-changes

**Comment by mkurz** [comment]
I wouldn't put it into Updated libraries, because ususally here we just list noteworthy deps that bumped their versions.

So either a complete new section, but actually also the "API-changes" section would fit, or what do you think? Because the api kind of changed since it's not available anymore.
What sounds better for you?

**Comment by jtjeferreira** [comment]
@mkurz anything missing here?

**Comment by mkurz** [comment]
I will be there in the next 2 hours. I have an idea for a smoother upgrade experience for users that stay on Scala 2.

**Comment by jtjeferreira** [comment]
> I will be there in the next 2 hours. I have an idea for a smoother upgrade experience for users that stay on Scala 2.

Keeping specs2-mock as dependency when scala version is 2.x? I thought of that, but I was imagining a play contributor writing tests with specs2-mock only to realize those tests don't work with scala3...

**Comment by mkurz** [comment]
@jtjeferreira I was thinking about this as well. And I think it's a better solution IMHO. Please see the commit I pushed.

People will first start to migrate to Play 2.9 but may not want to migrate to Scala 3 immediately, because for big applications that might is a lot of work - but still they want to migrate to 2.9 for new features, new libs/security upgrades, etc. So there is no need to immediately migrate away from specs2-mock for those people. So if we keep specs2-mock by default for Scala 2 the upgrade will be very smooth and things just keep working.

Only when migrating to Scala 3 there will be code to adjust regarding specs2 (in additation to the Scala 3 code changes needed in applications anyway)

Currently we have only a Migration Guide from Play 2.8 to Play 2.9. Maybe there will be more cases where we need to have a distinct Scala 2 to Scala 3 migration guide also (I will go over the Migration guide before the final release anyway to adjust things, so things might change in the end)

I know this last commit can be thought of from different perspectives, like to just make people switch away from specs2-mocks immediately or just tell them to add the dependency themselves, however the past showed that people were a bit unsatisfied with breaking changes between Play major releases, so I want to keep the experience as smooth as possible. On the other hand people will expect to adjust code when migrating to Scala 3 anyway, so then this is not Play's fault, but Scala 3 fault, if you know what I mean :wink:

**Comment by mkurz** [comment]
Here is the docs for now, so this is more a Scala 3 migration guide then (like said maybe this changes until the final release anyway):

<kbd></kbd>

**Comment by mkurz** [comment]
@jtjeferreira Let me now what you think, if I overlooked something. If you are ok with that, I will merge that PR.

**Review by jtjeferreira — COMMENTED** [review]
LGTM

**Pull request merged**
