### PR TITLE
Misc backports to 2.6.x

### PR DESCRIPTION
**Pull request by richdougherty**
Contains several backports from master to 2.6.x - see list of commits. *This PR should be rebased, but not squashed.*

### CODE REVIEW

**Comment by richdougherty** [comment]
Also getting the following errors directly on the original 2.6.x branch HEAD (29765e39ee834603ff4bac0ef4c625934e67d889), so maybe not caused by this change:

```
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	play.api.http.HttpErrorHandlerSpec
[error] (Play-Guice/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by richdougherty** [comment]
Works on aa66958fa46b573bbf7cd8b92a92568c64c15cd4 so probably caused by the binding change backport: the https://github.com/playframework/playframework/pull/8398#issuecomment-388272038 (cc @gmethvin).

FYI here's some more of the test failure (cc @jroper):
```
[error] Uncaught exception when running play.api.http.HttpErrorHandlerSpec: org.specs2.specification.dsl.mutable.SpecificationCreationException: 
[error] An exception was raised during the creation of the specification: Unable to create injector, see the following errors:
[error] 
[error] 1) No implementation for play.core.j.JavaContextComponents was bound.
[error]   while locating play.core.j.JavaContextComponents
[error]     for the 2nd parameter of play.core.j.JavaHttpErrorHandlerAdapter.<init>(JavaHttpErrorHandlerAdapter.scala:15)
[error]   at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:64):
[error] Binding(class play.core.j.JavaHttpErrorHandlerAdapter to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

...

[error] com.google.inject.CreationException: Unable to create injector, see the following errors:
[error] 
[error] 1) No implementation for play.core.j.JavaContextComponents was bound.
[error]   while locating play.core.j.JavaContextComponents
[error]     for the 2nd parameter of play.core.j.JavaHttpErrorHandlerAdapter.<init>(JavaHttpErrorHandlerAdapter.scala:15)
[error]   at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:64):
[error] Binding(class play.core.j.JavaHttpErrorHandlerAdapter to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
```

I will take a look at that backport later unless someone else has any suggestions.

**Comment by pettyjamesm** [comment]
Thanks for falling on the backport sword, Rich. Looking forward to the new release so that we don't have to carry around the specific netty overrides in our build.

**Comment by schmitch** [comment]
should we also try to backport https://github.com/playframework/playframework/commit/e6ed774086368eb7e70fba2b7019494b28dc74b8 ? it breaks binary compatibility, however only when running in dev mode since runsupport interface is the only one that is changed.

**Comment by pettyjamesm** [comment]
Since we're doing a bunch of backports to prepare for the next milestone, can a `play-ws` update make the cut too? Here's a PR https://github.com/playframework/playframework/pull/8418, but since it targets 2.6.x which is currently broken the specs are failing.

**Comment by richdougherty** [comment]
Restarting build now that #8419 is merged.

**Comment by richdougherty** [comment]
@schmitch - sounds good, I've tagged as _needs-backport_ so I'll remember to backport.

@pettyjamesm - I've restarted the Travis build and tagged as _2.6.14_ so I remember to merge it.

**Comment by schmitch** [comment]
Well I created the [backport](#8420) myself, I just tought that you want to release 2.6.14 really soon and i wasn't at home ;)

**Pull request merged**
