### PR TITLE
add Char binding to forms

### PR DESCRIPTION
**Pull request by godenji**
complements prior [accepted pull request](https://github.com/playframework/playframework/commit/e6cec6bc003fb3612f4337cf943da96a3f533c5a) that added Char binding to routes.

### CODE REVIEW

**Comment by marcospereira** [comment]
@godenji, 

Could you please add some tests for this mapping and also format:

1. FormSpec: https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/api/data/FormSpec.scala
2. FormatSpec: https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/api/data/format/FormatSpec.scala

Thanks!

**Comment by godenji** [comment]
@marcospereira added the tests and made a small change to binding (now prevent " " string from being converted to empty char).

Not sure if this will go through now though; rebased on my end to squash commits into one, and see that in the interum a few commits were made today...

**Comment by godenji** [comment]
Can someone take a look at this? Have another PR to make but waiting for this one to get merged first.

Thanks.

**Comment by gmethvin** [comment]
@godenji would you mind rebasing on top of master without the merge commit (or otherwise making this just one commit on top of master)?

It looks fine otherwise.

**Comment by godenji** [comment]
@gmethvin done

**Pull request merged**
