### PR TITLE
Remove empty ebean.properties from main project as it causes deprecat… Fixes #10141

### LINKED ISSUE #10141: Remove ebean.properties from main project
First of all, I think this file is not belong to this project, as ebean is a different plugin and not necessary to use it anyway, also I see the file is already empty:

https://github.com/playframework/playframework/tree/master/core/play-java/src/main/resources

The second point that this file making a log warning about deprecated file:
```console
2020-03-22 18:09:32 +0200 5401  WARN  io.avaje.config.load.Loader - Loading properties from ebean.properties is deprecated. Please migrate to use application.yaml or application.properties instead.
```

This warning started since the latest version of ebean 12.2.x

### Play Version
```hocon
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.1")
addSbtPlugin("com.payintech" % "sbt-play-ebean" % "20.02")
```

### API
Java

### Operating System
Windows 10 64bit Pro

### JDK
```console
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
```

### Library Dependencies
Build.sbt:

```hocon
lazy val root = (project in file(".")).enablePlugins(PlayJava, PlayEbean, LauncherJarPlugin)

scalaVersion := "2.13.1"

val javaVersion = settingKey[String]("The version of Java used for building.")

javaVersion := System.getProperty("java.version")
val java9AndSupLibraryDependencies: Seq[sbt.ModuleID] =
  if (!javaVersion.toString.startsWith("1.8")) {
    Seq(
      "com.sun.activation" % "javax.activation" % "1.2.0",
      "com.sun.xml.bind" % "jaxb-core" % "2.3.0.1",
      "com.sun.xml.bind" % "jaxb-impl" % "2.3.1",
      "javax.jws" % "javax.jws-api" % "1.1",
      "javax.xml.bind" % "jaxb-api" % "2.3.1",
      "javax.xml.ws" % "jaxws-api" % "2.3.1"
    )
  } else {
    Seq.empty
  }

val ebeanDependencies: Seq[sbt.ModuleID] =
  Seq(
    "io.ebean" % "ebean" % "12.2.1",
    "io.ebean" % "ebean-agent" % "12.2.2",
    "io.ebean" % "ebean-migration" % "12.1.4"
  )

libraryDependencies ++= Seq(
  guice,
  javaJdbc,
  javaWs,
  caffeine,
  filters,
  evolutions,
  "org.postgresql" % "postgresql" % "42.2.9",
  "com.microsoft.sqlserver" % "mssql-jdbc" % "7.4.1.jre11",
  "com.typesafe.play" %% "play-json" % "2.8.1",
  "com.typesafe.play" %% "play-mailer" % "7.0.1",
  "com.typesafe.play" %% "play-mailer-guice" % "7.0.1",
) ++ java9AndSupLibraryDependencies ++ ebeanDependencies

```

### Reproducible Test Case

Having any project with ebean enabled and used, as the previous `build.sbt` and `plugins.sbt` above.

You can refer to https://github.com/ebean-orm/ebean/issues/1975 for more details.

### PR DESCRIPTION
**Pull request by almothafar**
Remove empty ebean.properties from main project as it causes deprecation warning since ebean v12.2.x

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #10141

## Purpose

Removing empty ebean.properties 

## Background Context

ebean.properties file as it does not belong to this project anymore since version 2.4 and it should be in separated plugin. also, the new version of bean (12.2.x) introduces some changes that causing to have a warning message in the console when the app startup.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @almothafar,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Comment by mkurz** [comment]
Mergify does not create the correct backport....

**Comment by raboof** [comment]
That's weird, it had already created that one a while ago (https://github.com/playframework/playframework/pull/10083#issuecomment-601713321)

**Comment by mkurz** [comment]
@Mergifyio backport 2.8.x

**Comment by ignasi35** [comment]
This is really weird and it looks like a mergify bug. The reason why #10083 is used is that it's the tip of `2.8.x`, I think.

**Comment by ignasi35** [comment]
Raised https://github.com/Mergifyio/mergify-engine/issues/849

**Comment by ignasi35** [comment]
The mergify issue was fixed... I'll try again.

**Comment by ignasi35** [comment]
@Mergifyio backport 2.8.x

**Pull request merged**
