### PR TITLE
Remove unnecessary modifiers from interfaces in play-jdbc-api

### LINKED ISSUE #10552: Remove unnecessary modifiers from interfaces in play-jdbc-api
There are some interfaces in the module play-jdbc-api with public-modifiers for methods. Example:
`public interface DBApi {

  **public** List<Database> getDatabases();
...`

These modifiers can be removed. I'm going to fix it.

### PR DESCRIPTION
**Pull request by Captain1653**
Hi!
It's my first PR in your project. I tried to follow your guide lines. Your help will be appreciate.  I signed Lightbend CLA

The PR fixes #10552 

Kind regards

### CODE REVIEW

**Comment by Captain1653** [comment]
My build failed, but I don't know why. My changes are so simple .

**Comment by raboof** [comment]
> My build failed, but I don't know why. My changes are so simple .

Seems like an infrastructure failure:

```
[error] scala.reflect.internal.FatalError: Error accessing /home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport/4.1.54.Final/netty-transport-4.1.54.Final.jar
```

I'll rerun the build

**Comment by mkurz** [comment]
Thanks for taking the time contributing to Play @Captain1653.
However I am against this change. What is the rationale behind these changes? Just because they are interfaces doesn't mean they should not contain any public modifiers. Actually I am using some of these methods in my own projects and making them non-public will break my code.

**Comment by raboof** [comment]
> However I am against this change. What is the rationale behind these changes? Just because they are interfaces doesn't mean they should not contain any public modifiers. Actually I am using some of these methods in my own projects and making them non-public will break my code.

Methods on interfaces are (unlike on regular classes) implicitly public unless otherwise specified (e.g. https://docs.oracle.com/javase/tutorial/java/IandI/interfaceDef.html), so the modifier does seem redundant in this case.

**Review by ignasi35 — APPROVED** [review]
LGTM

**Pull request merged**
