### PR TITLE
[2.5.x] Fix binary compatibility issues in MessagesApi

### PR DESCRIPTION
**Pull request by gmethvin**
Removes the extra methods added to `MessagesApi` and uses an alternative strategy to achieve the same result.

Also enables MiMa on the 2.5.x branch (closes #5900).

### CODE REVIEW

**Comment by mkurz** [comment]
LGTM

**Comment by mkurz** [comment]
@gmethvin Would you prefer having this solution in the master branch as well?

**Comment by gmethvin** [comment]
Probably yes, unless you can think of a good reason you need those extra methods. It's just for the Java context, right? If you agree you can forward-port it :smile:

**Comment by mkurz** [comment]
@gmethvin Here we go: #5917

**Pull request merged**
