### PR TITLE
HTTP/2 integration tests; update to Akka HTTP 10.0.10 (backport)

### PR DESCRIPTION
**Pull request by richdougherty**
Backports two commits from _master_ to _2.6.x_. These PRs add tests for HTTP/2 query string decoding and then update Akka HTTP to fix it.

You might want to not squash these commits to preserve their lovely commit messages. :)

### CODE REVIEW

**Comment by richdougherty** [comment]
A _Rebase and merge_ would be the nicest way to add these commits to _2.6.x_.

**Comment by gmethvin** [comment]
@richdougherty Note that there are some compilation errors on travis

**Comment by richdougherty** [comment]
> could not find implicit value for evidence parameter of type org.specs2.execute.AsResult[org.specs2.specification.core.Fragment]

Probably needs some work to get it going on the older version of specs2. I'll take a look.

**Comment by richdougherty** [comment]
Fixed compile error. Now fails locally but I'm pushing an update to see how it goes on Travis.

```
[info] AkkaIdleTimeoutSpec
[info] 
[info] Play's idle timeout support should
[info]   + support sub-second timeouts
[error]   x support a separate timeout for https
[error]    Expected: java.net.SocketException. Got: java.io.IOException: No response 2: EOF reached instead 
```

**Comment by richdougherty** [comment]
The 2.12 build passed, but the 2.11 build failed with lots of environment-related errors. Restarting.

```
java.lang.IllegalStateException: Closed (NettyRequestSender.java:91)
```

**Comment by mkurz** [comment]
I restarted again and it's green now :+1:

**Pull request merged**
