### PR TITLE
bump: Interplay 2.1.9 (Scala versions)

### PR DESCRIPTION
**Pull request by ennru**
See https://github.com/playframework/interplay/releases/tag/2.1.9

### CODE REVIEW

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
The artifacts weren't published because the build in the 2.1.x branch is not configured for that. And I'm not really willing to jump into that and fix just to get Scala 2.12.15 and 2.13.7. 

We should stop that madness. Let's release Play 2.8.9 as is and next time let's have interplay out of the picture.

**Comment by octonato** [comment]
I'm closing this PR, we are going nowhere with this.

**Comment by mkurz** [comment]
Agree.

**Pull request closed without merging**
