### PR TITLE
Expose a method for getting the Guice Module for the application for use in testing

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
Hmm. Seems like Jenkins got stuck. @play-pull-request-validator try again

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by benmccann** [comment]
Hmm. @jroper it looks like Jenkins has 2 builds going right now for this PR and they both look stuck in the same place  https://playframework2.ci.cloudbees.com/job/play-master-PRs/

**Comment by benmccann** [comment]
@play-pull-request-validator try again please

**Comment by benmccann** [comment]
Hmm, that didn't help at all. Now there's a third build pending

**Comment by benmccann** [comment]
One of them just timed out after a couple hours

>Build timed out (after 84 minutes). Marking the build as aborted.

**Comment by marcospereira** [comment]
@benmccann maybe you could do a rebase to get #4332 and see if it will help with this PR.

**Comment by benmccann** [comment]
@marcospereira i just did that. though i'm afraid it caused yet another build to get kicked off in the already jammed up build queue

**Comment by marcospereira** [comment]
Looks like the other builds are stuck at the same point.

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by benmccann** [comment]
Yay. Tests finally passed!

**Comment by benmccann** [comment]
Yay, it's passing now!

**Pull request merged**
