### PR TITLE
+akk update to 2.5 RC1 of Akka to get new materializer

### PR DESCRIPTION
**Pull request by ktoso**
This should be fine for this since the final Play should be on 2.5 in any case.
It is binary compatible btw.

### CODE REVIEW

**Comment by ktoso** [comment]
I'll PR more of the performnce work in the coming days

**Comment by mkurz** [comment]
Isn't there akka-http 10.0.5 already?

**Comment by marcospereira** [comment]
The build is failing:

https://travis-ci.org/playframework/playframework/jobs/212927165#L1198

This is probably related to #7094.

**Comment by ktoso** [comment]
Oh weird, it passed locally for me... Yeah, Stages are gone they're ancient :) Will look at Will's PR.
Yeah, 10.0.5 you're right, I released it so should have remembered that, was early morning... 😉

**Comment by mkurz** [comment]
@ktoso There is a merge conflict now because #7096 also upgraded akka-http

**Comment by ktoso** [comment]
I'll PR again in a bit, addressing the other PRs

**Pull request closed without merging**
