### PR TITLE
Fix simple typo

### PR DESCRIPTION
**Pull request by Abrasha**
- What does this PR do?
_Fixes simple typo in documentation_

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Abrasha,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by Abrasha** [comment]
@lightbend-cla-validator I signed the CLA

**Comment by marcospereira** [comment]
Thank you very much, @Abrasha!

**Comment by marcospereira** [comment]
By the way, we usually send pull requests to master branch and then backport them to a specific branch if necessary. :-)

**Comment by Abrasha** [comment]
@marcospereira Thank you. Sorry for that. The reason why I did this: it was a quick fix from documentation, something like [this](https://github.com/playframework/playframework/edit/2.5.x/documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md)

So this was GitHub's default branch.

**Pull request merged**
