### PR TITLE
[WIP] Move controllers to play.controllers

### PR DESCRIPTION
**Pull request by gmethvin**
This moves the `controllers` package to `play.controllers`, fixing #6555. This is helpful for two reasons:
 1. Now all logic for assets can be under the `play` package. This allows us to access things that are `private[play]`
 2. I don't think it makes sense for us to use any namespace other than `play`, and doing so makes clear that these controllers are provided by Play, not by the end user of the application.

### CODE REVIEW

**Comment by gmethvin** [comment]
Note that I haven't had time to investigate why the docs are failing and figure out if this is a problem. Seems like a local `play` package is being created somehow.

**Comment by gmethvin** [comment]
Looks like the docs are failing because a local `play.controllers` package is being created instead of using the global package (e.g. it uses `com.example.play.controllers.routes` instead of `play.controllers.routes`). This seems like it could be a bug in the routes compiler, but I haven't investigated how to work around or fix yet.

**Comment by wsargent** [comment]
I've usually used `_root_.play.controllers` in cases like that.

**Comment by gmethvin** [comment]
@wsargent Right, the main issue is that I'm worried that since we're creating a `play.controllers` package for the reverse routes, it will be ugly if you're in that package and want to refer to `play`

**Comment by marcospereira** [comment]
Should we have something like:

```scala
package controllers {

  import javax.inject.Inject

  import play.api.http.HttpErrorHandler
  import play.controllers.AssetsMetadata

  @deprecated("Use [[play.controllers.Assets] instead.", "2.6.0")
  class Assets @Inject()(errorHandler: HttpErrorHandler, meta: AssetsMetadata) extends play.controllers.AssetsBuilder(errorHandler, meta)

}
```
Of course, I thinking here about code compatibility, since these controllers are widely used. We could then create deprecated versions of `play.controllers` inside package `controllers` to enable a soft transition.

What do you think?

**Comment by gmethvin** [comment]
We could move the assets controllers to `play.controllers.assets` (not sure what to do with `Default`), and then import `assets` in the router by default, so it looks like `assets.Assets` instead of `controllers.Assets`

**Comment by gmethvin** [comment]
Actually, I guess we're always going to have a problem with routes files not at the root. Will have to add new hacks to the documentation build.

**Comment by gmethvin** [comment]
Closing since I plan to take a different approach here.

**Pull request closed without merging**
