### PR TITLE
Update IDE.md

### PR DESCRIPTION
**Pull request by rpridemore**
Clarify where to place suggested configuration changes when using the eclipse plugin.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @rpridemore,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by rpridemore** [comment]
I'd be happy to, but adobe reader isn't available for my Linux system and
my pdf viewer can't fill forms.

Russ

**Comment by benmccann** [comment]
@rpridemore you just click a button. no need to fill out a pdf form. go back and look at the link again. step 2 is the one that really matters

**Comment by marcospereira** [comment]
@play-pull-request-validator run again.

**Comment by gmethvin** [comment]
@play-pull-request-validator again?

**Comment by rpridemore** [comment]
Huh?  Sending me a link that appears to do nothing is unproductive.  Either
explain what you need or go away.

Russ

**Comment by benmccann** [comment]
@rpridemore if you agree with the terms of the CLA, then you simply need to click "Authorize" on the page http://www.typesafe.com/contribute/cla/verify. No need to return a pdf to us

**Comment by rpridemore** [comment]
Yes, I did that already.  What else is required?

**Comment by rpridemore** [comment]
Looks like you have a build problem here:
https://playframework2.ci.cloudbees.com/job/play-master-PRs/5053/console

**Comment by benmccann** [comment]
@rpridemore ok, thanks for signing

**Comment by cchantep** [comment]
@play-pull-request-validator

**Comment by marcospereira** [comment]
@cchantep the problem with the build is that we have a binary incompatibility:

```

[info] Play-Java-JPA: found 0 potential binary incompatibilities
java.lang.RuntimeException: Play-Test: Binary compatibility check failed!
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.tools.mima.plugin.SbtMima$.reportErrors(SbtMima.scala:64)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$3.apply(MimaPlugin.scala:26)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$3.apply(MimaPlugin.scala:26)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (Play-Test/*:mimaReportBinaryIssues) Play-Test: Binary compatibility check failed!
[error] Total time: 16 s, completed Jul 28, 2015 7:46:16 AM
```
It was introduced here by 5978b273f3c53c15b33a24e20266aafad8fea87d and it is also impacting other PRs submitted agains branch 2.4.x. @jroper, what do you think?

About this PR, I think it should be submitted to `master` and then we can backport it to `2.4.x` branch.

**Comment by marcospereira** [comment]
@play-pull-request-validator try again.

**Pull request merged**
