### PR TITLE
fix DefaultTemporaryFileCreator leak

### PR DESCRIPTION
**Pull request by jtjeferreira**
# Pull Request Checklist

# Helpful things

## Fixes

Fixes one of the memory leak issues reported in #9935

## Purpose

What does this PR do?

## Background Context

Took the fix from the gist in https://github.com/playframework/playframework/issues/9935#issuecomment-585495107

## References

#9935

### CODE REVIEW

**Comment by jtjeferreira** [comment]
What do I need to do to backport this to 2.8.x and 2.7.x?

**Comment by ignasi35** [comment]
> What do I need to do to backport this to 2.8.x and 2.7.x?

We can ask mergify to do the backport. It is usually flawless backporting to `2.8.x` but it sometimes needs some human intervention when backporting to `2.7.x`.

**Comment by ignasi35** [comment]
@mergifyio backport 2.8.x 2.7.x

**Comment by ignasi35** [comment]
> @Merg... backport 2.8.x 2.7.x

@jtjeferreira now mergify will watch this PR and, as soon as it's merged, it'll create two new PRs on the requested branches.

**Comment by marcospereira** [comment]
@jtjeferreira thanks. I wonder if we should also `clear` the `Reference` objects in `references`:

```scala
...
frq.close()
references.asScala.foreach(_.clear())
```

I don't have the time to investigate it right now, but I want to point it out if you do.

**Comment by jtjeferreira** [comment]
> @jtjeferreira thanks. I wonder if we should also `clear` the `Reference` objects in `references`:
> 
> ```scala
> ...
> frq.close()
> references.asScala.foreach(_.clear())
> ```
> 
> I don't have the time to investigate it right now, but I want to point it out if you do.

I dont think that is necessary, as `close` will do the finalization...

**Comment by jtjeferreira** [comment]
anything preventing this to be merged?

**Comment by mkurz** [comment]
> > @jtjeferreira thanks. I wonder if we should also `clear` the `Reference` objects in `references`:
> > ```scala
> > ...
> > frq.close()
> > references.asScala.foreach(_.clear())
> > ```
> > 
> > 
> > I don't have the time to investigate it right now, but I want to point it out if you do.
> 
> I dont think that is necessary, as `close` will do the finalization, and `references.remove` will be called...

I just checked that and I think that should be alright :+1:

**Review by mkurz — APPROVED** [review]

**Comment by gurshafriri** [comment]
@jtjeferreira do you see this as a DoS attack vector? 
If you do, we (at (Snyk)[https://snyk.io]) would like to add it to our vulnerability DB and assign a CVE for it.

**Comment by jtjeferreira** [comment]
> @jtjeferreira do you see this as a DoS attack vector?
> If you do, we (at (Snyk)[https://snyk.io]) would like to add it to our vulnerability DB and assign a CVE for it.

No. This was only a problem in devmode

**Pull request merged**
