### PR TITLE
Remove using deprecated constructor Http.RequestImpl

### LINKED ISSUE #10607: Remove using deprecated constructor Http.RequestImpl(RequestHeader header)
There is deprecated constuctor Http.RequestImpl(RequestHeader header). It is still using. It can be replaced on normal constructor RequestImpl(Request<RequestBody> request) .

### PR DESCRIPTION
**Pull request by Captain1653**
Fixes #10607 

Kind regards

### CODE REVIEW

**Comment by mkurz** [comment]
Why did you not also _remove_ the deprecated constructor with this pull request?

**Comment by Captain1653** [comment]
@mkurz  Oh, sorry. My mistake . Should I use amend commit and for push or add another commit?

**Comment by mkurz** [comment]
> Should I use amend commit and for push or add another commit?

Either is OK, you choose :wink:

**Review by mkurz — APPROVED** [review]

**Comment by mkurz** [comment]
@Captain1653 The build failed, see https://travis-ci.com/github/playframework/playframework/jobs/463686604#L916-L918

To fix the binary compatibility problem you need to add 
```
ProblemFilters.exclude[DirectMissingMethodProblem]("play.mvc.Http#RequestImpl.this")
```
to this list:
https://github.com/playframework/playframework/blob/291fa78db4efac4dc18bc737188021caebcc280c/project/BuildSettings.scala#L211
This tells MiMa ("Migration Manager") to not report this binary incompatibility anymore.

**Comment by Captain1653** [comment]
Thank you @mkurz  . I'll fix it today.

**Pull request merged**
