### PR TITLE
Updating guide to starting an application in the console

### PR DESCRIPTION
**Pull request by kamatsuoka**
Following the recipe in https://github.com/playframework/playframework/issues/4593

### CODE REVIEW

**Comment by marcospereira** [comment]
@kamatsuoka, thank you very much. Some things that can make this PR even better:

1. Use a [code sample](https://www.playframework.com/documentation/2.4.x/Documentation#Code-samples) instead of directly embed the code in markdown.
2. Squash all commits into a single one.

Thanks.

**Comment by jroper** [comment]
@marcosinigaglia actually as is, code samples won't work, because it includes the `scala>` prompt from the console. but... that raises a second concern, you can't copy/paste this snippet (which most people will want to do) because of the `scala>` prompt, so that should be removed, and then, the snippet will be extractable to a Scala file, where the build will fail if it breaks again.

**Comment by marcospereira** [comment]
Hi @jroper, I think you referenced the wrong "marcos" here. :-)

Anyway, I'm aware the `scala>` prompt need to be removed. Just thought that this would be clear enough to not be worth mentioning it.

**Comment by jroper** [comment]
Are you telling me there's more than one Marcos?

**Comment by marcospereira** [comment]
Unfortunately. :stuck_out_tongue_winking_eye:

**Comment by marcospereira** [comment]
Hello @kamatsuoka.

Could you please:

1. Use a [code sample](https://www.playframework.com/documentation/2.4.x/Documentation#Code-samples) instead of directly embed the code in markdown.
2. Squash all commits into a single one.

When extracting the code sample, please pay attention to the comment made by @jroper:

https://github.com/playframework/playframework/pull/4854#issuecomment-121486200

After that, I think this PR will be ready to be merged. :-)

**Comment by kamatsuoka** [comment]
Code sample extracted, commits squashed.

**Comment by marcospereira** [comment]
Thank you very much, @kamatsuoka.

**Comment by kamatsuoka** [comment]
Nada!

**Pull request merged**
