### PR TITLE
fix jmh Microbenchmarks

### PR DESCRIPTION
**Pull request by jtjeferreira**
# Pull Request Checklist

* [X] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [X] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [X] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [X] Have you added copyright headers to new files?
* [X] Have you checked that both Scala and Java APIs are updated?
* [X] Have you updated the documentation for both Scala and Java sections?
* [X] Have you added tests for any changed functionality?

# Helpful things

## Purpose

Fixes `p.microbenchmark.it.HelloWorldBenchmark` when using akka-http-2 (ak-20-enc) and akka http1.1 encrypted (ak-11-enc)

## Background Context

`ak-20-enc` was failing with a `java.lang.ClassNotFoundException: akka.http.scaladsl.Http2` exception because of missing akka-http2-support jar.
`ak-11-enc` was failing with a `javax.net.ssl.SSLPeerUnverifiedException: Hostname localhost not verified:` which was solved by setting the a dumb `hostnameVerifier` in the OkHttp client

### CODE REVIEW

**Comment by marcospereira** [comment]
Thank you, @jtjeferreira. Is it possible to configure our script to get these problems?

https://github.com/playframework/playframework/blob/master/framework/bin/validate-microbenchmarks

**Comment by jtjeferreira** [comment]
> Thank you, @jtjeferreira. Is it possible to configure our script to get these problems?
> 
> [/framework/bin/validate-microbenchmarks@`master`](https://github.com/playframework/playframework/blob/master/framework/bin/validate-microbenchmarks)

I dont have a lot of experience with sbt-jmh, so we should investigate how to make the "test" fail instead of being a success... If that is not possible we would have to parse the console output?

**Comment by jtjeferreira** [comment]
hey @marcospereira, found a solution! see 80ed1fc (that should fail)

**Comment by jtjeferreira** [comment]
and now I pushed the fix to the tests... 82e1972

**Comment by dwijnand** [comment]
2.7.x 985ee6ada

**Pull request merged**
