### PR TITLE
2.4.x Backport to fix issue #6272

### PR DESCRIPTION
**Pull request by MarkPaxton**
# Pull Request Checklist
- [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
- [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
- [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
- [ ] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
- [ ] Have you added copyright headers to new files?
- [ ] Have you checked that both Scala and Java APIs are updated?
- [ ] Have you updated the documentation for both Scala and Java sections?
- [ ] Have you added tests for any changed functionality?
# Helpful things
## Fixes

Fixes #6272
## Purpose

This is a backport of the change in the 2.5.x branch to fix the issue as above
## Background Context

This was suggested as part of issue #6592 
## References
#6592

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @MarkPaxton,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by MarkPaxton** [comment]
@gmethvin I'm not actually sure why the test suite fails as it doesn't appear to be against anything I changed - does the current test expect the 2.5.x branch only?

**Comment by gmethvin** [comment]
It looks like we just added tests that used `play.api.test.WithApplication` in 2.5.x, so we added a dependency on  play-specs2 (only in test): https://github.com/playframework/playframework/blob/2.5.x/framework/project/Build.scala#L373

If you add the play-specs2 dependency and import WithApplication it should work fine.

**Comment by MarkPaxton** [comment]
@gmethvin It looks like the backport of the fix hasn't worked as now the new tests are failing

**Pull request merged**
