### PR TITLE
fix external link to Scalatest

### PR DESCRIPTION
**Pull request by arnostv**
# Pull Request Checklist

* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* [x] Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

## Fixes

Fix external URL in documentation.

## Purpose

Fix external URL in documentation.

---

Current external link http://scalatest.org/release_notes/3.0.0 seems to
go to some Spotify-styled error page.

Updated link http://www.scalatest.org/release_notes/3.0.0 seems to
be the right one.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @arnostv,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by marcospereira** [comment]
Hum, looks like Play 2.5.0 is **not** using Scalatest 3.0.0 yet:

https://github.com/playframework/scalatestplus-play/blob/1.5.0/build.sbt#L33

Probably because, as the linked page says, 3.0.0 final version was not released yet:

> Note: Eventually this will be the home for the 3.0.0 final release notes. These release notes are written from the perspective of the final release, but with 3.0.0 replaced with **3.0.0-M15, the current milestone version**.

**Comment by gmethvin** [comment]
@marcospereira Yes the docs are actually incorrect here, so we should update it to reflect that we are still using 2.x. It would be nice if we can ensure a clean migration path to ScalaTest 3.0 for Play 2.5 users, though.

**Comment by marcospereira** [comment]
@gmethvin I clean migration will probably happens only at 2.6 or later, right? Since this PR is changing the highlights for 2.5.x, I suppose we can complete remove this section.

Actually, #5938 is doing exactly this. :-)

**Comment by marcospereira** [comment]
#5938 fixed this by removing this paragraph.

**Pull request closed without merging**
