### PR TITLE
Make it a bit easier to read a JSON body

### PR DESCRIPTION
**Pull request by benmccann**
See https://github.com/playframework/playframework/issues/5275

### CODE REVIEW

**Comment by benmccann** [comment]
The error seems unrelated to my change:

>[error] error while loading <root>, Error accessing /home/travis/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.1.2.jar
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

**Comment by marcospereira** [comment]
Hey @benmccann, can we have a test/spec here?

**Comment by benmccann** [comment]
If there is a positive reaction to https://github.com/playframework/playframework/issues/5317 then I will probably abandon this PR and focus there instead.

**Comment by wsargent** [comment]
Closing in favor of #5317 -- we do need a nicer body parser and better mapping to internal objects.

**Pull request closed without merging**
