### PR TITLE
Suggestion: validating bin compatibility with all the patch versions in 2.5 series

### PR DESCRIPTION
**Pull request by seratch**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

## Purpose

This pull request is just a suggestion on migration manager usage.

Currently, the `master` branch checks bin-compatibility with only 2.5.0. But the current setting may miss bin-incompatibility in some cases. For instance, it cannot detect unexpected deletion of new methods introduced 2.5.{1,2,3,4}.

### CODE REVIEW

**Comment by gmethvin** [comment]
@seratch If we do this, we it would be nice to use the version specified in version.sbt, which is automatically updated by `sbt release`.

**Comment by seratch** [comment]
I agree maintaining the versions by hand is not a proper way. 

Referring `version.sbt` would be fine after releasing 2.6.0. But, at the current moment, the previous version is 2.5.4. I'm not sure how we should determine the previous version of the build yet.

**Comment by xuwei-k** [comment]
> automatically updated by sbt release.

in scalaz

- https://github.com/scalaz/scalaz/blob/v7.2.3/project/build.scala#L53-L58
- https://github.com/scalaz/scalaz/blob/v7.2.3/project/build.scala#L187
- https://github.com/scalaz/scalaz/blob/v7.2.3/project/build.scala#L238-L252

**Comment by gmethvin** [comment]
A slightly nicer thing than this suggestion would be to add a setting for `previousVersions` and then set
```scala
previousVersions := {
  val VersionPattern = """^(\d+).(\d+).(\d+)(-SNAPSHOT)?""".r
  version.value match {
    case VersionPattern(epoch, major, minor, rest) => (0 until minor.toInt).map(v => s"$epoch.$major.$v")
    case _ => sys.error(s"Cannot find latest version for ${version.value}")
  }
}
```

**Comment by seratch** [comment]
@gmethvin Your solution looks nice! We should go with your solution after releasing 2.6.0.

**Comment by gmethvin** [comment]
@seratch Why is it a problem to do it now? For the master branch, previousVersions should be computed to be an empty list. For 2.5.x, it should be 2.5.0...2.5.4.

**Comment by seratch** [comment]
@gmethvin This pull request is made for `master` branch. Since the `version.value` is `"2.6.0-SNAPSHOT"` in `master` branch, I'm afraid that it's a bit early to apply your solution.

**Comment by seratch** [comment]
@gmethvin Ah, understood. `(0 until minor.toInt)` is empty now.

**Comment by seratch** [comment]
@gmethvin Updated.

**Pull request merged**
