### PR TITLE
Don't assume developers are male

### PR DESCRIPTION
**Pull request by treppo**
## Purpose

One simple technique to normalize the thought of women being developers is to use he for some examples and she for others. When reading this part of the documentation, I stumbled upon the example where both developers are assumed to be male.

An alternative, that is not assuming any gender at all (going beyond binary gender identification), would be to use completely gender neutral language.

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

### CODE REVIEW

**Comment by shkhln** [comment]
Let's stick to the singular _they_, it is already used on CoC text and elsewhere in the documentation.

**Comment by schmitch** [comment]
actually I the **he** doesn't mean "the developer" is female or male. it's just the word that has a male context.
they would be wrong. because it assumes that both developers do the task. while it actually only means that either of them do the task.

**Comment by treppo** [comment]
@schmitch It's a complicated matter, basically he is _not_ gender-neutral language: https://en.wikipedia.org/wiki/Gender-neutral_language#Gender_indication

**Comment by gmethvin** [comment]
Actually, in an example with multiple people, it would be more clear to use names like Alice and Bob instead of Developer A and Developer B.

If we're making a general statement, there are usually tricks we can use to reword things to avoid having to use gendered pronouns, e.g. using plurals or passive voice. I also don't have a problem with using "they" as a gender-neutral singular pronoun but I suppose some non-native speakers might be confused by it.

Note that the PR should be submitted to master so it applies to future versions documentation as well.

**Comment by treppo** [comment]
@gmethvin While Alice and Bob might be an improvement over the current state of the documentation – normalizing women as developers – it sticks to gender binary instead of gender neutral language ("they" instead of "she"/"he"). As the Code of Conduct says "[…]we explicitly honor diversity in […]gender identity[…]", therefore I would argue that we should go beyond the gender binary.

**Comment by treppo** [comment]
Maybe by using [Unisex Names](https://en.wikipedia.org/wiki/Unisex_name#English)

**Comment by schmitch** [comment]
I think using one of the unisex names is fine.

**Comment by gmethvin** [comment]
Maybe something about this should be added to https://www.playframework.com/documentation/2.6.x/Documentation. At the moment that page not provide much guidance about non-technical aspects of writing the documentation, but it probably should.

**Comment by marcospereira** [comment]
Thanks for that, @treppo. Do you mind also submit a new PR to improve the documentation guidelines, as suggested by @gmethvin?

Thank you.

**Comment by marcospereira** [comment]
Forwardport to master: 028d989154635e967a3e1d64c4e510cc9d741093

**Comment by treppo** [comment]
@marcospereira I will try to add some guidelines next week.
Thank you all for the support with this pull request!

**Pull request merged**
