### PR TITLE
Don't log when Akka is started

### PR DESCRIPTION
**Pull request by warchildmd**
Don't log when Akka is started #4554

### CODE REVIEW

**Comment by gmethvin** [comment]
Might be better to just change to `debug` instead of `info`. Same for shutting down the actor system in the stop hook.

**Comment by marcospereira** [comment]
+1 to just change it to `debug`.

**Comment by marcospereira** [comment]
Hey @warchildmd, do you mind take a look at the log level at `stopHook` also? After that, we can merge this PR. :wink:

**Comment by wsargent** [comment]
+1 for debug.

**Comment by marcospereira** [comment]
Fixed in #4743.

**Pull request closed without merging**
