### PR TITLE
Improve 2.5 migration guide

### PR DESCRIPTION
**Pull request by ninneko**
## Purpose

Fix migration doxuments to use Tink instead of Keyczar.

## Background Context

Keyczar is deplecated and all jars are removed from repository[https://github.com/google/keyczar/commit/0f0727dbc2ee02467f9c927bbf35898aa3be4c45].
Keyczar developers are recommended to use Tink.

### CODE REVIEW

**Comment by ignasi35** [comment]
hi @ninneko, the title of the PR mentions "improve 2.7 migration guide" but the edited files are on the `release25/migration25` folder. Is that correct? Should we rename the PR?

**Comment by dwijnand** [comment]
Thanks!

**Comment by dwijnand** [comment]
The documentation tests errored due to an unrelated failure in installing jabba (or using jabba, I forget).  Restarted.

**Comment by ignasi35** [comment]
Thanks @ninneko

**Pull request merged**
