### PR TITLE
Do not throw exception when trying to get a cookie that doesnt exist …

### PR DESCRIPTION
**Pull request by adelorme82**
…for a Result

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Purpose

In our tests, we use the router to generate Results and then check for the existence of cookies. We know that cookies should only be set in some instances, so our tests generate the Result then check if the cookie is present or not. Currently though if the cookie is missing it throws an exception instead of returning null

### CODE REVIEW

**Comment by marcospereira** [comment]
Hi @adelorme82,

I would prefer to move this API to be more like the Scala one:

https://github.com/playframework/playframework/blob/f7f4727add26a689e0667eda278c9f20bda70f02/framework/src/play/src/main/scala/play/api/mvc/Cookie.scala#L117-L131

In other words, have an API that:

1. Returns an `Optional<Cookie>` instead of null.
2. Have a method that fails if the cookie is not present.

Also, it would be necessary to add tests.

**Comment by gmethvin** [comment]
Well, there is still a bug in that the method is currently documented to return null if the cookie doesn't exist, so it still probably makes sense to have a change like this for 2.6.

I think it'd be nice to go through all the other Java APIs and change them all at once, just to make sure we don't have inconsistencies.

**Comment by marcospereira** [comment]
> Well, there is still a bug in that the method is currently documented to return null if the cookie doesn't exist, so it still probably makes sense to have a change like this for 2.6.

Hi @gmethvin, which method documentation? [This one](https://github.com/playframework/playframework/blob/ed67d87498d3f0f5a81749c95b21a8e02aaf4651/framework/src/play/src/main/java/play/mvc/Http.java#L2455-L2458)?

> I think it'd be nice to go through all the other Java APIs and change them all at once, just to make sure we don't have inconsistencies.

Yes! Although I would favor having them based on `Optional`, just like the Scala APIs are based on `Option`.

**Comment by gmethvin** [comment]
Actually it looks like the documentation changed at some point to not mention the null. It used to be https://playframework.com/documentation/2.4.x/api/java/play/mvc/Http.Cookies.html

It seems strange for the behavior to just change like that.

**Comment by gmethvin** [comment]
Also in other parts of the code we do return `null` if the cookie does not exist: https://github.com/playframework/playframework/blob/2.6.11/framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala#L40

**Comment by marcospereira** [comment]
> Actually it looks like the documentation changed at some point to not mention the null. It used to be https://playframework.com/documentation/2.4.x/api/java/play/mvc/Http.Cookies.html

I see. It makes sense to me then to return `null` in the current API and later evolve to use `Optional`.

**Comment by mkurz** [comment]
@adelorme82 Can you please add test(s) for this change? I think a good place would be [ResultSpec.scala](https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/mvc/ResultSpec.scala) or [CookieBuilderTest.java](https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/java/play/mvc/CookieBuilderTest.java)

**Comment by mkurz** [comment]
Fixed by #8650. `get(...)` is deprecated now in favor of `getCookie(...)` which returns `Optional`.

**Pull request closed without merging**
