### PR TITLE
Upgrade to Guice 4.0

### PR DESCRIPTION
**Pull request by benmccann**
Woohoo!!

### CODE REVIEW

**Comment by wsargent** [comment]
Final for 2 whole hours, that must be a record. :-)

**Comment by jroper** [comment]
I'm actually disappointed. I'm pretty sure @benmccann has been sitting at his computer for the past few weeks constantly refreshing http://repo1.maven.org/maven2/com/google/inject/guice/4.0/ until it stops 404ing.  The fact that it took 2 hours for him to submit this PR shows he must have had a lapse in concentration.

**Comment by benmccann** [comment]
I probably should have scripted it instead of doing it manually :-)

**Comment by richdougherty** [comment]
Yeah, pretty slow [considering](https://github.com/playframework/playframework/issues/3634#issuecomment-64500720).

**Comment by benmccann** [comment]
@play-pull-request-validator try again

>java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

**Comment by benmccann** [comment]
wtf. @play-pull-request-validator try again

>sbt.ResolveException: unresolved dependency: com.typesafe.sbtrc#client-2-10;0.3.1: not found

**Comment by benmccann** [comment]
Hmm still failing to find sbtrc. Going to try making it fetch 0.3.4 instead to see if that helps?

**Comment by jroper** [comment]
#4315 fixes the resolve errors.

**Comment by benmccann** [comment]
Yay! Jenkins passed now :-)

**Pull request merged**
