### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### playframework/playframework now has a Chat Room on Gitter

@jroper has just created a chat room. You can visit it here: [https://gitter.im/playframework/playframework](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @gitter-badger,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by jroper** [comment]
Let's not merge this until we find out whether the community finds it useful or not.

**Comment by benmccann** [comment]
It's a cool idea. Personally I prefer the mailing lists. I feel like it's nice to have all discussion happen in once place rather than be split between mailing list and chat. Though this is lower latency if two people are on at once and want to discuss some feature

**Comment by heat** [comment]
Mailing lists, Irc, Github. We already have a wide way to communication. If it'll become a empty room do not make sense have it.

**Comment by jroper** [comment]
The problem with IRC is:

    13:00 cybermonkey joined #playframework
    13:01 <cybermonkey> I'm trying to foo but it's not working for me.
    13:05 cybermonkey left #playframework

so by the time I see the message and think "oh! I know how to foo! I can help that person!" it's too late.  Whereas gitter channels are persistent, so if I answer it 5 hours later, that person can go back and see the answer if they're not around when I answer it.

**Comment by benmccann** [comment]
I didn't even know we had an IRC channel. I like this way more than IRC though because it's web-based and takes you right to the room you want to be in instead of having to figure out how to configure some weird desktop app I never use.

**Comment by jroper** [comment]
"We" as in the Play community has an IRC channel, I don't know who first created it.  I linger in there, but only because I already use IRC for other things have been in the habit of running irssi in a screen session on a server for over 10 years.

**Pull request closed without merging**
