### PR TITLE
Fix misleading deprecation message

### PR DESCRIPTION
**Pull request by psttf**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @psttf,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by jroper** [comment]
@play-pull-request-validator again please

@psttf Are you able to sign our CLA?

**Comment by psttf** [comment]
Yes, I will sign it today, sorry for delay!

**Comment by psttf** [comment]
the CLA is signed and the TypeSafe app authorised!

**Comment by gmethvin** [comment]
Backported to 2.4.x: d1ca952

**Pull request merged**
