### PR TITLE
Update SerializableResultSpec.scala

### PR DESCRIPTION
**Pull request by garhirunrat**
Correct typo

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @garhirunrat,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by garhirunrat** [comment]
I did sign the CLA.

**Comment by gmethvin** [comment]
[statūs](https://en.wiktionary.org/wiki/stat%C5%ABs) was likely intended as the plural of "status". Normally in English it's "statuses" though. I think @richdougherty was just trying to be clever.

**Comment by garhirunrat** [comment]
And I thought something was wrong with my font. LOL

**Comment by richdougherty** [comment]
Actually I thought I was clever when I wrote "statii" but someone even cleverer corrected me.

**Pull request closed without merging**
