### PR TITLE
Test with Akka HTTP 10.1.9+136-f05f0267

### PR DESCRIPTION
**Pull request by raboof**
Which is intended to become 10.1.10

Only for CI, not necessarily for merge

### CODE REVIEW

**Comment by ignasi35** [comment]
Why did this build pass?

I thought we only allowed using Akka (and Akka HTTP) snapshots in `CRON` builds (not PRs).

**Comment by marcospereira** [comment]
@raboof I think we can close this since the validation is done, right? scala-steward will then do the update when 10.1.10 is released. 😄

**Comment by raboof** [comment]
sounds good to me

**Comment by ignasi35** [comment]
> Why did this build pass?

@marcospereira found out about a hardcoded `resolvers +=` adding visibilty over Akka snaphosts. Removed in https://github.com/playframework/playframework/pull/9656

**Pull request closed without merging**
