### PR TITLE
Update assembly.sbt

### PR DESCRIPTION
**Pull request by Dinduks**
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Purpose

These lines are no longer needed in recent versions of sbt-assembly, as explained here: https://github.com/sbt/sbt-assembly/blob/master/Migration.md#upgrading-with-bare-buildsbt

### CODE REVIEW

**Comment by marcospereira** [comment]
Build is failing here:

https://travis-ci.org/playframework/playframework/builds/191584887#L2577

**Comment by marcospereira** [comment]
Hello @Dinduks, as you can see at my comment above, the build is failing for this PR.

Are you still interested? What was exactly the purpose of this change?

**Comment by Dinduks** [comment]
Hi Marcos,

As mentioned in my PR's description, the lines I removed are no longer needed in newer versions of SBT and thus are misleading.

I ran `compile` on this PR's branch but I had no error. I didn't have the time to look into it further. How can I reproduce Travis' test?

Thanks!

**Comment by marcospereira** [comment]
Hey @Dinduks, to reproduce the problem locally, run `./framework/bin/testDocumentation`.

**Comment by marcospereira** [comment]
So, the problem here is that you also need to update sbt-assembly plugin to the version that does not requires the removed configuration. See:

https://github.com/playframework/playframework/blob/master/documentation/project/plugins.sbt#L11

And:

https://github.com/sbt/sbt-assembly#using-published-plugin

Finally, I recommend that you rebase against the current master (which has a stable build).

**Comment by Dinduks** [comment]
Will do that, thanks Marcos.

**Pull request merged**
