### PR TITLE
NO-ISSUE: small refactoring to handle better null values in Scala code for core Play module

### PR DESCRIPTION
**Pull request by cleliofs**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

This is a small refactoring to handle better null values in Scala code for core Play module

## Fixes

N/A

## Purpose

What does this PR do?

Better handling for null values in Scala code for core Play module.

## Background Context

Why did you take this approach?

This is my first PR and I want to start getting involved in the Community and understanding better the code base and PR process itself.

## References

Are there any relevant issues / PRs / mailing lists discussions? N/A

### CODE REVIEW

**Comment by gmethvin** [comment]
Are there any instances where this fixes something with the existing code?

IMO the explicit null checks are clearer in a lot of these situations, e.g., `Option(x).isEmpty` means the exact same thing as `x == null` but it takes slightly more time to read and involves an extra allocation of an `Option`.

**Comment by cleliofs** [comment]
Hi @gmethvin no, there isn't any particular bug itself related to this. This is just to avoid relying on Java-like null comparison in Scala code bases. A bit of favour Option instead of Null. In situations where the comparison involves collections, and empty collection will compare properly, in case of the raw null comparison it would result in a false negative. 

In terms of `Option` allocation I believe the underlining bytecode resulted of the Scala compiler won't be much different from the previous null comparison. 

Anyway, I will leave you to decide whether this PR is worth merging it. I decided to do that as my first PR to get a bit of hands-on in the code itself :)

**Comment by mkurz** [comment]
@cleliofs Can you please rebase to solve the conflicts? Thanks!

**Comment by mkurz** [comment]
I was looking again at this PR (finally) and have to agree with Greg that I can not see the benefit of this changes. Thanks anyway, but IMHO it's better to keep things like they are.

**Pull request closed without merging**
