### PR TITLE
The file should be named conf/logger.xml to be picked up automatically

### PR DESCRIPTION
**Pull request by jeroenr**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

## Fixes

N/A

## Purpose

Fixes a mistake in the documentation regarding logger configuration

## Background Context

If you create conf/logback.xml, as the docs suggest, that logback configuration won't be picked up by default. However, if you create conf/logger.xml it will be picked up by default. Hence, I propose to update the docs.

## References

N/A

### CODE REVIEW

**Comment by wsargent** [comment]
@jeroenr Can you explain this PR with some more background context?

**Comment by jeroenr** [comment]
@wsargent I've updated the background context section. Is it more clear now?

**Comment by marcospereira** [comment]
Looks like the current docs are ok with the code:

https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala#L44-L55

Am I missing something here?

**Comment by gmethvin** [comment]
As @marcospereira said, the current code uses `logback.xml` so the documentation is correct. Perhaps you are using an older version of Play?

**Comment by jeroenr** [comment]
My mistake, I was using version 2.3.x and didn't realize it was renamed. Should have double checked this. Sorry for wasting your time.

**Pull request closed without merging**
