### PR TITLE
HTTP caching for WS

### PR DESCRIPTION
**Pull request by wsargent**
First pass of HTTP caching for Ning WS client.

Needs tests.  And documentation.  But if you use CachingNingWSClient() and turn up the debugging, you'll see it work out of the box.

### CODE REVIEW

**Comment by jroper** [comment]
A few questions:

* Is the Guava cache asynchronous?  Ie, does it return futures?
* In your opinion, how hard would it be to build this on top of the existing `WSClient` API?  Ie, with something like this:

```scala
client.url(...).withFilter(wsCache).get()
```

Such that `wsCache` would use a `WSClient` filter api to implement the caching?

**Comment by gmethvin** [comment]
@jroper All the Guava caches are synchronous. `LoadingCache` can asynchronously refresh values, but `get` will still block if there is nothing in the cache. There is discussion of an `AsyncLoadingCache` though: google/guava/issues/1350

**Comment by wsargent** [comment]
@jroper The guava caches are all local and synchronous.  The logic to pull data out of cache is in the CacheAsyncHttpProvider, which uses a AsyncCacheableConnection / ListenableFuture to return a result.  I was lazy and used Await.result internally (since gcache is sync) but it would not be difficult to tie a cache result to a promise and hook it to a ListenableFuture.

https://github.com/playframework/playframework/pull/4357/files#diff-c9e4a8945e2caa5326c3cd62719813e7R28

The difficulty with a withFilter().get() is that the underlying AsyncHttpClient needs a provider which is passed in on instantiation.  So it's possible to set up two different clients and defer which client is selected until the get(), but each client has its own internal thread pool so you would be paying for that even if you only used the filter once.

**Comment by jroper** [comment]
Do we need to use a separate provider?  What about async-http-clients Filter interface:

https://github.com/AsyncHttpClient/async-http-client/blob/master/api/src/main/java/org/asynchttpclient/filter/RequestFilter.java

**Comment by wsargent** [comment]
@jroper The problem with the request filter is that it applies to all requests, and doesn't allow you to swap out the source -- you can replay the request, but you can't swap out the listenable future and repoint it to complete with a response from cache instead of from netty, because the provider has already kicked off the future and then executed the filter.

**Comment by wsargent** [comment]
Maybe @slandelle knows how you'd work a filter in?

**Comment by slandelle** [comment]
I have to admit I never use the RequestFilter API, but I agree with @wsargent, it only let you enrich the request, or throw an Exception (the sole implementation provided with AHC does that for throttling), but not bypass sending over the wire and pass a cached response.

Regarding guava, please note that @ben-manes now works on [caffeine](https://github.com/ben-manes/caffeine).

**Comment by ben-manes** [comment]
Note that storing futures in Guava's cache is easy and works great in a limited form, but there are many limitations that can be surprising. Proper support is provided in the Java 8 rewrite, which returns a [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html). If using Guava with future values, take not of...

- Failures will not be automatically removed (must be triggered as completion listener)
- Weights, refresh, and weak/soft values are incompatible
- Expiration times are screwy
- Stats are inaccurate
- Cannot intelligently batch computations (`loadAll`)
- Eviction will occur eagerly, before the entry materializes
- Removal listener may receive an incomplete future value
- Recursive computations (always wrong) are harder to detect prior and will deadlock

As long as your usages are careful to not abuse any of the above, and double checks that I didn't miss another gotcha, it should be okay to store future values. If you use Java 8, then [AsyncLoadingCache](http://static.javadoc.io/com.github.ben-manes.caffeine/caffeine/1.1.0/com/github/benmanes/caffeine/cache/AsyncLoadingCache.html) provides a proper implementation. You can use the [scala-java8-compat](https://github.com/scala/scala-java8-compat) [FutureConverters](https://github.com/scala/scala-java8-compat/blob/master/src/main/scala/scala/compat/java8/FutureConverters.scala) for interop.

**Comment by wsargent** [comment]
Closing this, as we now have https://github.com/playframework/cachecontrol and https://github.com/playframework/play-ws-cache projects.

**Pull request closed without merging**
