### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by marcospereira**
## Purpose

Probably the last round of dependencies updates before 2.6.0.

- specs2 to version 3.9.1
- spring to version 4.3.9
- commons-lang to version 3.6
- caffeine to version 2.5.2
- htmlunit-driver to version 2.27

### CODE REVIEW

**Comment by mkurz** [comment]
@marcospereira Tests fail.

**Comment by marcospereira** [comment]
Thanks, @mkurz. Will take a look now. :-)

**Comment by mkurz** [comment]
Still fails.

**Comment by marcospereira** [comment]
Closing after ##7465 and #7471.

**Pull request closed without merging**
