### PR TITLE
Fixes #4944: Evolutions support for Derby DB

### LINKED ISSUE #4944: Evolutions support for Derby DB
Play Evolutions currently doesn't support Apache Derby DB[1]. As discussed in the mailing list [2], adding support for Derby boils down to having a specific Derby SQL statement for creating the `play_evolutions` table, just like we have for other databases [3].

A possible workaround until a fix is available is to manually create the `play_evolutions table`, so play won't try to create it. You can try with the following SQL:

```
create table play_evolutions (
    id int not null primary key,
    hash varchar(255) not null,
    applied_at timestamp not null,
    apply_script clob,
    revert_script clob,
    state varchar(255),
    last_problem clob
)
```

[1] http://db.apache.org/derby/
[2] https://groups.google.com/forum/#!topic/play-framework/Z8olAtkQLhY
[3] https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L328-L366

### PR DESCRIPTION
**Pull request by fehmicansaglam**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @fehmicansaglam,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by cchantep** [comment]
Hi, it would be nice to include some tests, as Derby can be embedded for. Best regards.

**Comment by marcospereira** [comment]
Close/reopen to trigger a travis build.

**Comment by marcospereira** [comment]
@fehmicansaglam as suggested by @cchantep, please add some tests here. :-)

**Comment by fehmicansaglam** [comment]
I will.

**Comment by dotta** [comment]
@fehmicansaglam Did you find time for adding tests? If not, and you think you won't find time in the next few days, it might be better to close this PR until it's ready.

**Comment by fehmicansaglam** [comment]
Sorry about that. I am going to add tests tonight.

**Comment by dotta** [comment]
@fehmicansaglam No worries! And thanks a lot for donating your code and time!

**Comment by fehmicansaglam** [comment]
@dotta @marcospereira I have updated the tests.

**Comment by dotta** [comment]
LGTM. Thanks!

**Pull request merged**
