### PR TITLE
return to using HTML5 regex for email verification. Fixes #4022

### LINKED ISSUE #4022: [Scala-2.3.8] Validation.emailRegex doesn't allow single-letter domains
[Validation.emailRegex](https://github.com/playframework/playframework/blob/a0a8bd5796c746334dac1d88f65cda66975cb6a8/framework/src/play/src/main/scala/play/api/data/validation/Validation.scala#L76) doesn't allow email addresses with single-letter domains such as example@x.com.

### PR DESCRIPTION
**Pull request by felixmulder**
To quote @jroper:
> "At the end of the day, if you want to validate an email address, the
> only real way to do it is to send an email to it with a secret token.
> For this reason, false positives are not a big problem, what is a big
> problem is false negatives, ie issues like this very bug."

### CODE REVIEW

**Comment by jroper** [comment]
PR validation failed due to JVM crash?  @play-pull-request-validator again.

**Comment by jroper** [comment]
@play-pull-request-validator

**Comment by felixmulder** [comment]
Hmm, second run was successful. Should I be worried?

**Comment by jroper** [comment]
No. Our CI is just a little unstable.

**Pull request merged**
