### PR TITLE
Add section on Plugin API to Migration25.md

### PR DESCRIPTION
**Pull request by wsargent**
Fixes https://github.com/playframework/playframework/issues/5371

### CODE REVIEW

**Comment by wsargent** [comment]
play.it.http.websocket.AkkaHttpWebSocketSpec failed at "close the websocket when the wrong type of frame is received"

https://travis-ci.org/playframework/playframework/jobs/96837527#L4180

https://github.com/playframework/playframework/blob/master/framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala#L246

**Comment by wsargent** [comment]
https://travis-ci.org/playframework/playframework/jobs/96868315#L2158

**Comment by wsargent** [comment]
https://travis-ci.org/playframework/playframework/jobs/97060027#L6132

```
[error]   ! use queryString in url
[error]    play.libs.F$PromiseTimeoutException: null (F.java:279)
[error] play.libs.F$Promise.get(F.java:279)
[error] play.libs.F$Promise.get(F.java:303)
[error] play.it.libs.WSSpec$$anonfun$2$$anonfun$apply$23$$anonfun$apply$24.apply(WSSpec.scala:93)
[error] play.it.libs.WSSpec$$anonfun$2$$anonfun$apply$23$$anonfun$apply$24.apply(WSSpec.scala:92)
[error] play.it.libs.WSSpec$$anonfun$2.play$it$libs$WSSpec$class$$anonfun$$withClient$1(WSSpec.scala:76)
[error] play.it.libs.WSSpec$$anonfun$2$$anonfun$play$it$libs$WSSpec$class$$anonfun$$withServer$1$1.apply(WSSpec.scala:44)
[error] play.it.libs.WSSpec$$anonfun$2$$anonfun$play$it$libs$WSSpec$class$$anonfun$$withServer$1$1.apply(WSSpec.scala:43)
[error] play.core.server.Server$.withApplication(Server.scala:120)
```

**Comment by benmccann** [comment]
>[error]   ! not overflow the stack when called recursively
[error]    java.util.concurrent.TimeoutException: Futures timed out after [5 seconds] (IterateeSpecification.scala:18)
[error] play.api.libs.iteratee.IterateeSpecification$class.await(IterateeSpecification.scala:18)
[error] play.api.libs.iteratee.IterateesSpec$.await(IterateesSpec.scala:10)
[error] play.api.libs.iteratee.IterateesSpec$$anonfun$28$$anonfun$apply$158$$anonfun$apply$160.apply(IterateesSpec.scala:229)
[error] play.api.libs.iteratee.IterateesSpec$$anonfun$28$$anonfun$apply$158$$anonfun$apply$160.apply(IterateesSpec.scala:229)
[error] play.api.libs.iteratee.IterateesSpec$$anonfun$28$$anonfun$apply$158.apply(IterateesSpec.scala:229)
[error] play.api.libs.iteratee.IterateesSpec$$anonfun$28$$anonfun$apply$158.apply(IterateesSpec.scala:208)
java.lang.RuntimeException
java.lang.RuntimeException
[error] Error: Total 200, Failed 0, Errors 1, Passed 199
[error] Error during tests:
[error] 	play.api.libs.iteratee.IterateesSpec

**Comment by benmccann** [comment]
>[error]     x aggregate text frames
[error]      List(second, third) is not equal to List(first, second, third) (WebSocketSpec.scala:202)
[error] Missing (1)
[error] first

**Pull request merged**
