### PR TITLE
FileWatchService is in different package in 2.4

### PR DESCRIPTION
**Pull request by domdorn**
The FileWatchService moved from 
play.sbtplugin.run to play.runsupport

### CODE REVIEW

**Comment by benmccann** [comment]
How about if instead of starting a new paragraph, you just combined the two sentences like this?

> renamed to `fileWatchService` and the corresponding

**Comment by domdorn** [comment]
thx I'll try to reformat it. not sure why the build fails, thought..

**Comment by benmccann** [comment]
the build's been flaky lately. if you push a change, it'll kick the build off again. or you can mention @play-pull-request-validator to kick it off as well

**Comment by benmccann** [comment]
@play-pull-request-validator try again

**Pull request merged**
