### PR TITLE
fix warnings with Scala 3.4. avoid `private[this]`

### PR DESCRIPTION
**Pull request by xuwei-k**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Purpose

fix warnings. use `private` instead of `private[this]` in routes-compiler generate code.

## Background Context

- https://github.com/lampepfl/dotty/pull/18819
- https://docs.scala-lang.org/scala3/reference/dropped-features/this-qualifier.html

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@mkurz Can this be merged?

**Review by mkurz — APPROVED** [review]
Since all tests pass it seems this doesn't do any harm (and we have quite a lot of tests regarding routing, specially also scripted tests). Probably a leftover from old days.

**Comment by mkurz** [comment]
@Mergifyio backport 2.9.x

**Comment by ahjohannessen** [comment]
@mkurz Would be nice with a minor release with this :)

**Pull request merged**
