### PR TITLE
TemporaryFile() throws InstantiationException when using compile time…

### PR DESCRIPTION
**Pull request by phleemac**
… dependency injection (https://github.com/playframework/playframework/issues/4909)

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @ph88lee,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by phleemac** [comment]
I downloaded and signed the CLA.  How should I return it to you?

**Comment by marcospereira** [comment]
@phleemac to sign the CLA, just follow the link at the step 2:

http://www.typesafe.com/contribute/cla

Also, could you please submit this PR to master branch instead. We can then backport it to branch 2.4.x if it pass the binary compatibility check. I'm closing this PR so that you can submit it again targeting our master branch.

Thanks.

**Comment by marcospereira** [comment]
Also, keep in mind that you should sign the CLA with the commiter user (@ph88lee).

**Comment by phleemac** [comment]
But I've already follow step 2 to confirm the CLA twice.  Anyway, just done it again the third times.

Will re-submit the PR.  Thanks.

**Pull request closed without merging**
