### PR TITLE
[2.7.x] Support sbt 1.4 virtual files when displaying error source

### PR DESCRIPTION
**Pull request by mkurz**
Backport of #10648 (only slightly modified to make it work for 2.7.x)

### CODE REVIEW

**Comment by mkurz** [comment]
2.7 is EOL, no more backports

**Comment by jtjeferreira** [comment]
I understand that 2.7 is EOL, but since 2.7.10 still has to be released why not also merge and include this?

**Comment by mkurz** [comment]
@jtjeferreira It's not my decision, it was decided by Lightbend. You can talk to @octonato about that.

**Comment by mkurz** [comment]
@gmethvin Do we want to re-open this PR to bring support for sbt 1.4+ in Play 2.7? Back in February I closed the PR because Renato said 2.7 is EOL. However if we plan to release (a) new 2.7 version(s), we could get this one in as well.
However, this pr is only half the story, we would also need to backport #10712, #10442 and probably #10723 and as a bonus #10707.
What do you think?

**Comment by gmethvin** [comment]
@mkurz Since it seems there are users who want it, I think it might make sense, as long as we don't see anything specific about the 2.7.x code that makes it more risky. Now I also realize the built-in thin client was added in sbt 1.4, so I guess we've already committed to supporting at least one sbt 1.4 feature...

**Comment by jtjeferreira** [comment]
I am already in 2.8 so no need for this backport

**Comment by mkurz** [comment]
@linux-root I highly recommend to upgrade to Play 2.8.x, 2.7.x does not receive security updates anymore.

**Comment by linux-root** [comment]
> @linux-root I highly recommend to upgrade to Play 2.8.x, 2.7.x does not receive security updates anymore.

@mkurz Thank you for warning me!

**Pull request closed without merging**
