### PR TITLE
Update PlayConsole.md

### PR DESCRIPTION
**Pull request by SMcClelland**
Due to #4203, play.core.StaticApplication(new java.io.File(".")) no longer exists. Proposing documentation change to play.core.server.ProdServerStart.main(Array()) which I believe should be pretty much the current equivalent.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @SMcClelland,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by wsargent** [comment]
Thanks!

**Comment by wsargent** [comment]
@SMcClelland The changes Rich made on #4203 are on the 2.5.x branch, but your patch is against the 2.4.x branch.

**Comment by SMcClelland** [comment]
@wsargent Hi Will you are absolutely right and sorry it's been a month or so since I did this push so I am foggy on the details. If I remember correctly, at least part of that commit was backported into 2.4. Tonight I will see if I can find the exact commit trail again. 

Anyway, the easiest thing to do is just set up a Play 2.4 environment and try to run the command that is documented in: https://www.playframework.com/documentation/2.4.x/PlayConsole

scala>  new play.core.StaticApplication(new java.io.File("."))
<console>:11: error: type StaticApplication is not a member of package play.core
        new play.core.StaticApplication(new java.io.File("."))

In my case I was using 2.4.3 and as you can see it's not working. This commit might need to be ported to master as well but I haven't personally tried running it on master.

**Pull request merged**
