### PR TITLE
[doc] Add SIRD routing documentation

### PR DESCRIPTION
**Pull request by wsargent**
Fixes https://github.com/playframework/playframework/issues/4586

Describes SIRD routing in context of a conf/routes file and by extending SimpleRouter.

### CODE REVIEW

**Comment by schmitch** [comment]
Shouldn't we also add a @Inject parameter to it and describe that? That the Main Router will Inject stuff into the SIRD router?

**Comment by wsargent** [comment]
@schmitch there's nothing to inject though...

**Comment by schmitch** [comment]
yeah not here but it's possible but not documented.

**Comment by wsargent** [comment]
@schmitch something like this?

class HomeRouter @Inject()(controller: HomeController)
  extends SimpleRouter
{
  override def routes: Routes = {
    case GET(p"/") =>
      val f = controller.index _
      f()
  }
}

**Comment by schmitch** [comment]
yeah exactly

**Comment by wsargent** [comment]
@schmitch okay done

**Comment by wsargent** [comment]
also added a note addressing https://github.com/playframework/playframework/issues/6107

**Comment by schmitch** [comment]
yeah actually it not really addresses it.
it's still not easy to especially group multiple routers so that you can just skip the routes file.
we have like 20 subrouters and the syntax would really ugly with orElse, but I didn't found a good way how to handle it (yet).

**Pull request merged**
