### PR TITLE
Add csrfCheck and csrfAddToken to the components

### PR DESCRIPTION
**Pull request by alexduf**
## Fixes

Fixes the absence of `CSRFCheck` and `CSRFAddToken` in the `CSRFComponents` trait

## Purpose

This will help users trying to use CSRF per endpoint when they use compile time dependency injection as these two components are currently missing.

If this PR is accepted I'll create the same onto master.

### CODE REVIEW

**Comment by wsargent** [comment]
Hi @alexduf thanks for the contribution!  

The PR looks good -- can you add tests to verify the presence of check and token, and have you checked to see if there's any documentation that needs to be updated?

Also, generally we take PRs on master and then cherrypick the backport to 2.5.x, but in this case it's small enough to be done either way.

**Comment by julienrf** [comment]
Looks good! Can you please also update the "compile-time" DI documentation section to mention it?

**Comment by gmethvin** [comment]
The CSRF docs should ideally have a section about compile-time DI.

**Comment by alexduf** [comment]
Thanks for your feedback everyone,
If I close this PR to create a new one on master that is squashed and modify `ScalaCompileTimeDependencyInjection.md` and `ScalaCsrf.md` does that work for everyone?
@wsargent how does one go about testing the presence of an attribute in such a case and would you have an example of such a test?

**Pull request closed without merging**
