### PR TITLE
Cross-build support for routes compiler

### PR DESCRIPTION
**Pull request by richdougherty**
Backport of #5343.

### CODE REVIEW

**Comment by benmccann** [comment]
Looks like it's not backporting cleanly. Maybe we need to include some other dependency as well?

>[error] /home/travis/build/playframework/playframework/framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesFileParser.scala:10: object parsing is not a member of package util
[error] import scala.util.parsing.combinator._
[error]                   ^

**Comment by richdougherty** [comment]
OK I can add that in by re-cherry-picking the backport. I thought the parser combinator stuff wasn't needed.

**Comment by richdougherty** [comment]
Test failure seems to be unrelated. I'll record the failure here for posterity:
```
[error]       x log a warning if sslConfig.default is passed in with an weak certificate
[error]        0 is equal to 0 (NingConfigSpec.scala:269)
```

**Comment by richdougherty** [comment]
Tests froze for 10 mins. Probably related to test box flakiness.
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

**Pull request merged**
