### PR TITLE
Updates swagger list

### PR DESCRIPTION
**Pull request by ignasi35**
Removes deprecated module `zalando` and promotes `iheartradio` at the top of the list (since it's the most well-maintained).

### CODE REVIEW

**Comment by gmethvin** [comment]
Also https://github.com/swagger-api/swagger-play has not been updated to Play 2.6, seems to be mostly unmaintained, and only supports Swagger 2. So I think it makes sense to remove that module from the list as well, at least for the Play 2.7 docs.

My company maintains a fork https://github.com/iterable/swagger-play that incorporates some of the unmerged PRs and updates to Play 2.7, but only because it would be a significant amount of work for us to migrate off that library. I would generally not recommend it for new projects.

**Comment by ignasi35** [comment]
Removed! Thanks for the update @gmethvin

**Comment by renatocaval** [comment]
What!!!

```
[error] Test javaguide.ehcache.JavaEhCache.http failed: 
[error] Expected: "something else"
[error]      but: was "Hello world", took 0.129 sec
```

**Comment by ignasi35** [comment]
@renatocaval why is mergify blocking this TR?

**Comment by dwijnand** [comment]
image

scheduled a re-run

**Comment by renatocaval** [comment]
> @renatocaval why is mergify blocking this PR?

No idea. Maybe a bug in Mergify.

**Comment by renatocaval** [comment]
Backported to 2.7.x (f2900009b)

**Comment by dwijnand** [comment]
I think Mergify's re-run functionality doesn't work.  It's not the first time I've seen it not act.

**Pull request merged**
