### PR TITLE
Don’t use global to route requests in test helpers

### PR DESCRIPTION
**Pull request by julienrf**
See [this message](https://groups.google.com/d/msg/play-framework-dev/9IZOhzQ8e9Y/rgR5_L0c79IJ) for details about the problem to solve.

### CODE REVIEW

**Comment by jroper** [comment]
This has broken FakeApplicationSpec.  That particular spec is possibly either broken or invalid now - or maybe it's a legitimate failure, perhaps the way routes are added in FakeApplication now needs to changed.

**Comment by julienrf** [comment]
I think the spec is still valid. If I understand correctly the problem comes from the way the `Router.Routes` module is injected in the `HttpRequestHandler`.

**Comment by julienrf** [comment]
I was wrong, everything was correctly wired. The problem actually came from the fact that the `HttpRequestHandler` always returns a handler, even when the `Router` does not return a handler for a given request.

BTW, I’d like to avoid the pattern matching on the returned handler because I really don’t know on what I should match! The `Handler` type tells nothing.

**Comment by julienrf** [comment]
I see.

I was finally able to fix all the tests that failed due to my changes. Tell me if you think that my changes go to the right direction :)

**Comment by jroper** [comment]
Looks good to me.

**Pull request merged**
