### PR TITLE
Wip/making scala ide happy

### PR DESCRIPTION
**Pull request by dotta**
* Updated `Execution` package delcaration to match its filesystem location
* Working around Eclipse Java compiler bug

### CODE REVIEW

**Comment by jroper** [comment]
Could we move `Execution.scala` into the core directory instead of changing its package?  I know it's private play, but I wouldn't be surprised if some of our other libraries (play-slick/play-ebean) use it.

**Comment by mkurz** [comment]
@dotta Just a thought: Maybe it would be useful to update https://www.playframework.com/documentation/2.4.x/BuildingFromSource and describe how to import the Play source into ScalaIDE?

**Comment by dotta** [comment]
@jroper Absolutely. I'll make the change and force push. Also, I'll exclude the other commit for the moment.
@mkurz Of course, as soon as I can get it to work :-)

**Comment by benmccann** [comment]
I merged to master. I'll leave it to you to decide if it's something to backport to 2.4

I'll be very curious to see how to import the Play sources into Eclipse. I've always been too chicken to try it :-)

**Comment by mkurz** [comment]
+1 for backporting to `2.4.x`

**Comment by dotta** [comment]
@benmccann Thanks. Not far from being able to do that by just typing `eclipse` in sbt. I just need a few more tweaks in sbteclipse, and possibly a couple of changes in Play to workaround what seem to be bugs in the Eclipse java compiler. I'll keep you guys posted.

**Comment by jroper** [comment]
Backported to 2.4.x: 57a8695

**Pull request merged**
