### PR TITLE
Added ',' to fix json syntax of given example.

### PR DESCRIPTION
**Pull request by vinsy**
I was copy pasting and getting error, later I figured out this syntax error.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @vinsy,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by benmccann** [comment]
@vinsy thanks for the fix! i'd be happy to merge if you don't mind online signing the CLA first

**Comment by benmccann** [comment]
@vinsy just a quick reminder. can you sign the CLA?

**Comment by benmccann** [comment]
@vinsy would you be able to sign the CLA? you can do it online and it's super easy

**Comment by benmccann** [comment]
I'm going to close this one since the CLA hasn't been signed

**Pull request closed without merging**
