### PR TITLE
Add a helper method for calling a controller with a context in a test

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
@play-pull-request-validator try again

> [error] (Play-WS/test:test) sbt.TestsFailedException: Tests unsuccessful

**Comment by benmccann** [comment]
Hmmm. @play-pull-request-validator try again please

>[info] [error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#play-server_2.10;2.4.0-SNAPSHOT: not found
[info] [error] unresolved dependency: com.typesafe.play#play-netty-server_2.10;2.4.0-SNAPSHOT: not found
[info] [error] unresolved dependency: com.typesafe.play#play-test_2.10;2.4.0-SNAPSHOT: not found
[info] [error] unresolved dependency: com.typesafe.play#play-docs_2.10;2.4.0-SNAPSHOT: not found
[info] [error] Total time: 1 s, completed Mar 5, 2015 10:07:06 PM
[error] x fork-run / dev-mode
[error]    {line 15}  Command failed: backgroundRun failed
Running akka-http / system-property
Running akka-http / play-akka-http-plugin
java.lang.RuntimeException: Failed tests:
	fork-run / dev-mode

	at scala.sys.package$.error(package.scala:27)
	at sbt.test.ScriptedTests$.runAll(ScriptedTests.scala:128)
	at sbt.test.ScriptedTests$.run(ScriptedTests.scala:122)
	at sbt.test.ScriptedTests$.run(ScriptedTests.scala:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.ScriptedPlugin$$anonfun$scriptedTask$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScriptedPlugin.scala:44)
	at sbt.ScriptedPlugin$$anonfun$scriptedTask$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScriptedPlugin.scala:40)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Failed tests:
	routes-compiler-plugin / injected-routes-compilation
	routes-compiler-plugin / source-mapping
	routes-compiler-plugin / routes-compilation
	play-sbt-plugin / dev-mode
	play-sbt-plugin / distribution
	play-sbt-plugin / multiproject-assets
	play-sbt-plugin / play-position-mapper

	at scala.sys.package$.error(package.scala:27)
	at sbt.test.ScriptedTests$.runAll(ScriptedTests.scala:128)
	at sbt.test.ScriptedTests$.run(ScriptedTests.scala:122)
	at sbt.test.ScriptedTests$.run(ScriptedTests.scala:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.ScriptedPlugin$$anonfun$scriptedTask$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScriptedPlugin.scala:44)
	at sbt.ScriptedPlugin$$anonfun$scriptedTask$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScriptedPlugin.scala:40)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (SBT-Fork-Run-Plugin/*:scripted) Failed tests:
[error] 	fork-run / dev-mode
[error] (SBT-Plugin/*:scripted) Failed tests:
[error] 	routes-compiler-plugin / injected-routes-compilation
[error] 	routes-compiler-plugin / source-mapping
[error] 	routes-compiler-plugin / routes-compilation
[error] 	play-sbt-plugin / dev-mode
[error] 	play-sbt-plugin / distribution
[error] 	play-sbt-plugin / multiproject-assets
[error] 	play-sbt-plugin / play-position-mapper
[error] Total time: 311 s, completed Mar 5, 2015 10:08:33 PM

**Comment by jroper** [comment]
I just merged a PR from Peter that I think fixes this.

**Comment by jroper** [comment]
@play-pull-request-validator should be fixed now

**Comment by benmccann** [comment]
@jroper which PR of @pvlugter 's are you referring to?

**Comment by benmccann** [comment]
oh, sorry. i misunderstood. i thought you were saying this PR was a duplicate of peter's, but now i think i understand you were saying his PR fixed the build

**Comment by benmccann** [comment]
@play-pull-request-validator doesn't look fixed yet :-(

>[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#play-ws_2.10;2.4.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.play:play-ws_2.10:2.4.0-SNAPSHOT
[warn] 		  +- plugins:plugins:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-ws_2.10;2.4.0-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Using$.withResource(Using.scala:11)
	at xsbt.boot.Using$.apply(Using.scala:10)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
	at sbt.IvySbt.withIvy(Ivy.scala:123)
	at sbt.IvySbt.withIvy(Ivy.scala:120)
	at sbt.IvySbt$Module.withModule(Ivy.scala:151)
	at sbt.IvyActions$.updateEither(IvyActions.scala:157)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (plugins/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#play-ws_2.10;2.4.0-SNAPSHOT: not found

**Comment by benmccann** [comment]
@play-pull-request-validator still broken :-/

**Comment by pvlugter** [comment]
I fixed the first problem, in the scripted tests. The next one is in the templates.

The earlier builds must have had cross published artefacts already in the ivy local and cache.

I'll make a quick fix now.

**Comment by pvlugter** [comment]
Actually, it's a bit more awkward to fix. I was just going to use a fixed version of play-ws, but the use of PlayVersion.current in the templates build makes it more difficult. And the project reference from the templates build needing 2.10 but the main build using 2.11 by default now doesn't work.

**Comment by pvlugter** [comment]
I've made the simplest fix to get things working again for now: https://github.com/playframework/playframework/pull/4030

**Comment by pvlugter** [comment]
This has passed now. Maybe the last build ended up on an instance with the cross built artefacts.

**Pull request merged**
